/*
 Highcharts Gantt JS v8.0.0 (2020-02-16)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(t){"object"===typeof module&&module.exports?(t["default"]=t,module.exports=t):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(E){t(E);t.Highcharts=E;return t}):t("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(t){function E(e,a,q,v){e.hasOwnProperty(a)||(e[a]=v.apply(null,q))}t=t?t._modules:{};E(t,"parts-gantt/CurrentDateIndicator.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.addEvent,v=a.merge;a=
a.wrap;var x=e.PlotLineOrBand,D={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(a,q){return e.dateFormat(q,a)},rotation:0,style:{fontSize:"10px"}}};q(e.Axis,"afterSetOptions",function(){var a=this.options,e=a.currentDateIndicator;e&&(e="object"===typeof e?v(D,e):v(D),e.value=new Date,a.plotLines||(a.plotLines=[]),a.plotLines.push(e))});q(x,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});a(x.prototype,
"getLabelText",function(a,e){var y=this.options;return y.currentDateIndicator&&y.label&&"function"===typeof y.label.formatter?(y.value=new Date,y.label.formatter.call(this,y.value,y.label.format)):a.call(this,e)})});E(t,"parts-gantt/GridAxis.js",[t["parts/Globals.js"],t["parts/Tick.js"],t["parts/Utilities.js"]],function(e,a,q){var v=q.addEvent,x=q.defined,D=q.erase,t=q.find,A=q.isArray,y=q.isNumber,u=q.merge,h=q.pick,m=q.timeUnits,w=q.wrap,I=e.dateFormat,p=function(c){return q.isObject(c,!0)},f=e.Chart,
d=e.Axis,k=function(c){var b=c.options;b.labels||(b.labels={});b.labels.align=h(b.labels.align,"center");c.categories||(b.showLastLabel=!1);c.labelRotation=0;b.labels.rotation=0},C={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};d.prototype.isOuterAxis=function(){var c=this,b=c.columnIndex,d=c.linkedParent&&c.linkedParent.columns||c.columns,k=b?c.linkedParent:c,G=-1,f=0;c.chart[c.coll].forEach(function(g,n){g.side!==c.side||g.options.isInternal||(f=n,g===k&&(G=n))});return f===
G&&(y(b)?d.length===b:!0)};d.prototype.getMaxLabelDimensions=function(c,b){var l={width:0,height:0};b.forEach(function(b){b=c[b];if(p(b)){var d=p(b.label)?b.label:{};b=d.getBBox?d.getBBox().height:0;d.textStr&&!y(d.textPxLength)&&(d.textPxLength=d.getBBox().width);d=y(d.textPxLength)?Math.round(d.textPxLength):0;l.height=Math.max(b,l.height);l.width=Math.max(d,l.width)}});return l};e.dateFormats.W=function(c){c=new Date(c);c.setHours(0,0,0,0);c.setDate(c.getDate()-(c.getDay()||7));var b=new Date(c.getFullYear(),
0,1);return Math.ceil(((c-b)/864E5+1)/7)};e.dateFormats.E=function(c){return I("%a",c,!0).charAt(0)};v(a,"afterGetLabelPosition",function(c){var b=this.label,d=this.axis,k=d.reversed,G=d.chart,f=d.options,g=f&&p(f.grid)?f.grid:{};f=d.options.labels;var n=f.align,r=C[d.side],B=c.tickmarkOffset,F=d.tickPositions,L=this.pos-B;F=y(F[c.index+1])?F[c.index+1]-B:d.max+B;var J=d.tickSize("tick",!0);B=A(J)?J[0]:0;J=J&&J[1]/2;if(!0===g.enabled){if("top"===r){g=d.top+d.offset;var h=g-B}else"bottom"===r?(h=G.chartHeight-
d.bottom+d.offset,g=h+B):(g=d.top+d.len-d.translate(k?F:L),h=d.top+d.len-d.translate(k?L:F));"right"===r?(r=G.chartWidth-d.right+d.offset,k=r+B):"left"===r?(k=d.left+d.offset,r=k-B):(r=Math.round(d.left+d.translate(k?F:L))-J,k=Math.round(d.left+d.translate(k?L:F))-J);this.slotWidth=k-r;c.pos.x="left"===n?r:"right"===n?k:r+(k-r)/2;c.pos.y=h+(g-h)/2;G=G.renderer.fontMetrics(f.style.fontSize,b.element);b=b.getBBox().height;f.useHTML?c.pos.y+=G.b+-(b/2):(b=Math.round(b/G.h),c.pos.y+=(G.b-(G.h-G.f))/2+
-((b-1)*G.h/2));c.pos.x+=d.horiz&&f.x||0}});v(d,"afterTickSize",function(c){var b=this.defaultLeftAxisOptions,d=this.horiz,k=this.options.grid;k=void 0===k?{}:k;var f=this.maxLabelDimensions;k.enabled&&(b=2*Math.abs(b.labels.x),d=d?k.cellHeight||b+f.height:b+f.width,A(c.tickSize)?c.tickSize[0]=d:c.tickSize=[d])});v(d,"afterGetTitlePosition",function(c){var b=this.options;if(!0===(b&&p(b.grid)?b.grid:{}).enabled){var d=this.axisTitle,k=d&&d.getBBox().width,f=this.horiz,m=this.left,g=this.top,n=this.width,
r=this.height,B=b.title;b=this.opposite;var F=this.offset,L=this.tickSize()||[0],J=B.x||0,K=B.y||0,a=h(B.margin,f?5:10);d=this.chart.renderer.fontMetrics(B.style&&B.style.fontSize,d).f;L=(f?g+r:m)+L[0]/2*(b?-1:1)*(f?1:-1)+(this.side===C.bottom?d:0);c.titlePosition.x=f?m-k/2-a+J:L+(b?n:0)+F+J;c.titlePosition.y=f?L-(b?r:0)+(b?d:-d)/2+F+K:g-a+K}});w(d.prototype,"unsquish",function(c){var b=this.options;return!0===(b&&p(b.grid)?b.grid:{}).enabled&&this.categories?this.tickInterval:c.apply(this,Array.prototype.slice.call(arguments,
1))});v(d,"afterSetOptions",function(c){var b=this.options;c=c.userOptions;var d=b&&p(b.grid)?b.grid:{};if(!0===d.enabled){var k=u(!0,{className:"highcharts-grid-axis "+(c.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",
[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},c);"xAxis"===this.coll&&(x(c.linkedTo)&&!x(c.tickPixelInterval)&&(k.tickPixelInterval=350),x(c.tickPixelInterval)||!x(c.linkedTo)||x(c.tickPositioner)||x(c.tickInterval)||(k.tickPositioner=function(c,b){var g=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(g){var n,d=k.units;for(n=0;n<d.length;n++)if(d[n][0]===g.unitName){var l=n;break}if(d[l+1]){var z=d[l+
1][0];var f=(d[l+1][1]||[1])[0]}else"year"===g.unitName&&(z="year",f=10*g.count);g=m[z];this.tickInterval=g*f;return this.getTimeTicks({unitRange:g,count:f,unitName:z},c,b,this.options.startOfWeek)}}));u(!0,this.options,k);this.horiz&&(b.minPadding=h(c.minPadding,0),b.maxPadding=h(c.maxPadding,0));y(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=d.borderWidth)}});v(d,"afterSetAxisTranslation",function(){var c=this.options,b=c&&p(c.grid)?c.grid:{},d=this.tickPositions&&this.tickPositions.info,k=this.userOptions.labels||
{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(c){c.options.pointRange=0}),d&&(!1===c.dateTimeLabelFormats[d.unitName].range||1<d.count)&&!x(k.align)&&(c.labels.align="left",x(k.x)||(c.labels.x=3)))});v(d,"trimTicks",function(){var c=this.options,b=c&&p(c.grid)?c.grid:{},d=this.categories,k=this.tickPositions,f=k[0],h=k[k.length-1],g=this.linkedParent&&this.linkedParent.min||this.min,n=this.linkedParent&&this.linkedParent.max||this.max,r=this.tickInterval;!0!==b.enabled||d||!this.horiz&&
!this.isLinked||(f<g&&f+r>g&&!c.startOnTick&&(k[0]=g),h>n&&h-r<n&&!c.endOnTick&&(k[k.length-1]=n))});v(d,"afterRender",function(){var b=this.options,d=b&&p(b.grid)?b.grid:{},k=this.chart.renderer;if(!0===d.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var f=b.lineWidth;if(f){var h=this.getLinePath(f);var m=h.indexOf("M")+1;var g=h.indexOf("L")+1;d=h.indexOf("M")+2;var n=h.indexOf("L")+
2;var r=(this.tickSize("tick")[0]-1)*(this.side===C.top||this.side===C.left?-1:1);this.horiz?(h[d]+=r,h[n]+=r):(h[m]+=r,h[g]+=r);this.axisLineExtra?this.axisLineExtra.animate({d:h}):(this.axisLineExtra=k.path(h).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),k.styledMode||this.axisLineExtra.attr({stroke:b.lineColor,"stroke-width":f}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(g){g.render()})}});var b={afterGetOffset:function(){(this.columns||
[]).forEach(function(b){b.getOffset()})},afterInit:function(){var b=this.chart,l=this.userOptions,z=this.options;z=z&&p(z.grid)?z.grid:{};z.enabled&&(k(this),w(this,"labelFormatter",function(g){var b=this.axis,c=b.tickPositions,d=this.value,l=(b.isLinked?b.linkedParent:b).series[0],k=d===c[0];c=d===c[c.length-1];l=l&&t(l.options.data,function(g){return g[b.isXAxis?"x":"y"]===d});this.isFirst=k;this.isLast=c;this.point=l;return g.call(this)}));if(z.columns)for(var f=this.columns=[],h=this.columnIndex=
0;++h<z.columns.length;){var C=u(l,z.columns[z.columns.length-h-1],{linkedTo:0,type:"category"});delete C.grid.columns;C=new d(this.chart,C,!0);C.isColumn=!0;C.columnIndex=h;D(b.axes,C);D(b[this.coll],C);f.push(C)}},afterSetOptions:function(b){b=(b=b.userOptions)&&p(b.grid)?b.grid:{};var c=b.columns;b.enabled&&c&&u(!0,this.options,c[c.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(b){b.setScale()})},destroy:function(b){(this.columns||[]).forEach(function(c){c.destroy(b.keepEvents)})},
init:function(b){var c=(b=b.userOptions)&&p(b.grid)?b.grid:{};c.enabled&&x(c.borderColor)&&(b.tickColor=b.lineColor=c.borderColor)}};Object.keys(b).forEach(function(c){v(d,c,b[c])});v(f,"afterSetChartSize",function(){this.axes.forEach(function(b){(b.columns||[]).forEach(function(b){b.setAxisSize();b.setAxisTranslation()})})})});E(t,"modules/static-scale.src.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.addEvent,v=a.defined,x=a.isNumber,D=a.pick;a=e.Chart;q(e.Axis,"afterSetOptions",
function(){var a=this.chart.options&&this.chart.options.chart;!this.horiz&&x(this.options.staticScale)&&(!a.height||a.scrollablePlotArea&&a.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});a.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(a){var e=a.chart,y=!!e.initiatedScale&&e.options.animation,u=a.options.staticScale;if(a.staticScale&&v(a.min)){var h=D(a.unitLength,a.max+a.tickInterval-a.min)*u;h=Math.max(h,u);
u=h-e.plotHeight;1<=Math.abs(u)&&(e.plotHeight=h,e.redrawTrigger="adjustHeight",e.setSize(void 0,e.chartHeight+u,y));a.series.forEach(function(h){(h=h.sharedClipKey&&e[h.sharedClipKey])&&h.attr({height:e.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};q(a,"render",a.prototype.adjustHeight)});E(t,"mixins/tree-series.js",[t["parts/Color.js"],t["parts/Utilities.js"]],function(e,a){var q=a.extend,v=a.isArray,x=a.isNumber,D=a.isObject,t=a.merge,A=a.pick;return{getColor:function(a,u){var h=
u.index,m=u.mapOptionsToLevel,w=u.parentColor,q=u.parentColorIndex,p=u.series,f=u.colors,d=u.siblings,k=p.points,C=p.chart.options.chart,b;if(a){k=k[a.i];a=m[a.level]||{};if(m=k&&a.colorByPoint){var c=k.index%(f?f.length:C.colorCount);var l=f&&f[c]}if(!p.chart.styledMode){f=k&&k.options.color;C=a&&a.color;if(b=w)b=(b=a&&a.colorVariation)&&"brightness"===b.key?e.parse(w).brighten(h/d*b.to).get():w;b=A(f,C,l,b,p.color)}var z=A(k&&k.options.colorIndex,a&&a.colorIndex,c,q,u.colorIndex)}return{color:b,
colorIndex:z}},getLevelOptions:function(a){var u=null;if(D(a)){u={};var h=x(a.from)?a.from:1;var m=a.levels;var w={};var e=D(a.defaults)?a.defaults:{};v(m)&&(w=m.reduce(function(a,f){if(D(f)&&x(f.level)){var d=t({},f);var k="boolean"===typeof d.levelIsConstant?d.levelIsConstant:e.levelIsConstant;delete d.levelIsConstant;delete d.level;f=f.level+(k?0:h-1);D(a[f])?q(a[f],d):a[f]=d}return a},{}));m=x(a.to)?a.to:1;for(a=0;a<=m;a++)u[a]=t({},e,D(w[a])?w[a]:{})}return u},setTreeValues:function m(a,h){var w=
h.before,u=h.idRoot,p=h.mapIdToNode[u],f=h.points[a.i],d=f&&f.options||{},k=0,C=[];q(a,{levelDynamic:a.level-(("boolean"===typeof h.levelIsConstant?h.levelIsConstant:1)?0:p.level),name:A(f&&f.name,""),visible:u===a.id||("boolean"===typeof h.visible?h.visible:!1)});"function"===typeof w&&(a=w(a,h));a.children.forEach(function(b,c){var d=q({},h);q(d,{index:c,siblings:a.children.length,visible:a.visible});b=m(b,d);C.push(b);b.visible&&(k+=b.val)});a.visible=0<k||a.visible;w=A(d.value,k);q(a,{children:C,
childrenTotal:k,isLeaf:a.visible&&!k,val:w});return a},updateRootId:function(a){if(D(a)){var h=D(a.options)?a.options:{};h=A(a.rootNode,h.rootId,"");D(a.userOptions)&&(a.userOptions.rootId=h);a.rootNode=h}return h}}});E(t,"parts-gantt/Tree.js",[t["parts/Utilities.js"]],function(e){var a=e.extend,q=e.isNumber,v=e.pick,x=function(a,e){var q=a.reduce(function(a,h){var m=v(h.parent,"");"undefined"===typeof a[m]&&(a[m]=[]);a[m].push(h);return a},{});Object.keys(q).forEach(function(a,h){var m=q[a];""!==
a&&-1===e.indexOf(a)&&(m.forEach(function(a){h[""].push(a)}),delete h[a])});return q},D=function(e,x,y,u,h,m){var w=0,I=0,p=m&&m.after,f=m&&m.before;x={data:u,depth:y-1,id:e,level:y,parent:x};var d,k;"function"===typeof f&&f(x,m);f=(h[e]||[]).map(function(a){var b=D(a.id,e,y+1,a,h,m),c=a.start;a=!0===a.milestone?c:a.end;d=!q(d)||c<d?c:d;k=!q(k)||a>k?a:k;w=w+1+b.descendants;I=Math.max(b.height+1,I);return b});u&&(u.start=v(u.start,d),u.end=v(u.end,k));a(x,{children:f,descendants:w,height:I});"function"===
typeof p&&p(x,m);return x};return{getListOfParents:x,getNode:D,getTree:function(a,e){var q=a.map(function(a){return a.id});a=x(a,q);return D("",null,1,null,a,e)}}});E(t,"modules/broken-axis.src.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.addEvent,v=a.extend,x=a.find,D=a.fireEvent,t=a.isArray,A=a.pick,y=e.Axis;a=e.Series;var u=function(a,m){return x(m,function(h){return h.from<a&&a<h.to})};v(y.prototype,{isInBreak:function(a,m){var h=a.repeat||Infinity,e=a.from,p=a.to-
a.from;m=m>=e?(m-e)%h:h-(e-m)%h;return a.inclusive?m<=p:m<p&&0!==m},isInAnyBreak:function(a,m){var h=this.options.breaks,e=h&&h.length,p;if(e){for(;e--;)if(this.isInBreak(h[e],a)){var f=!0;p||(p=A(h[e].showPoints,!this.isXAxis))}var d=f&&m?f&&!p:f}return d}});q(y,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});q(y,"afterSetTickPositions",function(){if(this.isBroken){var a=this.tickPositions,m=this.tickPositions.info,e=[],u;for(u=0;u<a.length;u++)this.isInAnyBreak(a[u])||
e.push(a[u]);this.tickPositions=e;this.tickPositions.info=m}});q(y,"afterSetOptions",function(){this.isBroken&&(this.options.ordinal=!1)});y.prototype.setBreaks=function(a,m){function h(d){var a=d,f;for(f=0;f<p.breakArray.length;f++){var b=p.breakArray[f];if(b.to<=d)a-=b.len;else if(b.from>=d)break;else if(p.isInBreak(b,d)){a-=d-b.from;break}}return a}function e(d){var a;for(a=0;a<p.breakArray.length;a++){var f=p.breakArray[a];if(f.from>=d)break;else f.to<d?d+=f.len:p.isInBreak(f,d)&&(d+=f.len)}return d}
var p=this,f=t(a)&&!!a.length;p.isDirty=p.isBroken!==f;p.isBroken=f;p.options.breaks=p.userOptions.breaks=a;p.forceRedraw=!0;p.series.forEach(function(d){d.isDirty=!0});f||p.val2lin!==h||(delete p.val2lin,delete p.lin2val);f&&(p.userOptions.ordinal=!1,p.val2lin=h,p.lin2val=e,p.setExtremes=function(d,a,f,b,c){if(this.isBroken){for(var l,k=this.options.breaks;l=u(d,k);)d=l.to;for(;l=u(a,k);)a=l.from;a<d&&(a=d)}y.prototype.setExtremes.call(this,d,a,f,b,c)},p.setAxisTranslation=function(d){y.prototype.setAxisTranslation.call(this,
d);this.unitLength=null;if(this.isBroken){d=p.options.breaks;var a=[],f=[],b=0,c,l=p.userMin||p.min,z=p.userMax||p.max,h=A(p.pointRangePadding,0),m;d.forEach(function(b){c=b.repeat||Infinity;p.isInBreak(b,l)&&(l+=b.to%c-l%c);p.isInBreak(b,z)&&(z-=z%c-b.from%c)});d.forEach(function(b){g=b.from;for(c=b.repeat||Infinity;g-c>l;)g-=c;for(;g<l;)g+=c;for(m=g;m<z;m+=c)a.push({value:m,move:"in"}),a.push({value:m+(b.to-b.from),move:"out",size:b.breakSize})});a.sort(function(b,g){return b.value===g.value?("in"===
b.move?0:1)-("in"===g.move?0:1):b.value-g.value});var e=0;var g=l;a.forEach(function(c){e+="in"===c.move?1:-1;1===e&&"in"===c.move&&(g=c.value);0===e&&(f.push({from:g,to:c.value,len:c.value-g-(c.size||0)}),b+=c.value-g-(c.size||0))});p.breakArray=f;p.unitLength=z-l-b+h;D(p,"afterBreaks");p.staticScale?p.transA=p.staticScale:p.unitLength&&(p.transA*=(z-p.min+h)/p.unitLength);h&&(p.minPixelPadding=p.transA*p.minPointOffset);p.min=l;p.max=z}});A(m,!0)&&this.chart.redraw()};q(a,"afterGeneratePoints",
function(){var a=this.options.connectNulls,m=this.points,e=this.xAxis,u=this.yAxis;if(this.isDirty)for(var p=m.length;p--;){var f=m[p],d=!(null===f.y&&!1===a)&&(e&&e.isInAnyBreak(f.x,!0)||u&&u.isInAnyBreak(f.y,!0));f.visible=d?!1:!1!==f.options.visible}});q(a,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))});e.Series.prototype.drawBreaks=function(a,m){var h=this,e=h.points,p,f,d,k;a&&m.forEach(function(m){p=a.breakArray||[];f=a.isXAxis?
a.min:A(h.options.threshold,a.min);e.forEach(function(b){k=A(b["stack"+m.toUpperCase()],b[m]);p.forEach(function(c){d=!1;if(f<c.from&&k>c.to||f>c.from&&k<c.from)d="pointBreak";else if(f<c.from&&k>c.from&&k<c.to||f>c.from&&k>c.to&&k<c.from)d="pointInBreak";d&&D(a,d,{point:b,brk:c})})})})};e.Series.prototype.gappedPath=function(){var a=this.currentDataGrouping,m=a&&a.gapSize;a=this.options.gapSize;var u=this.points.slice(),q=u.length-1,p=this.yAxis,f;if(a&&0<q)for("value"!==this.options.gapUnit&&(a*=
this.basePointRange),m&&m>a&&m>=this.basePointRange&&(a=m),f=void 0;q--;)f&&!1!==f.visible||(f=u[q+1]),m=u[q],!1!==f.visible&&!1!==m.visible&&(f.x-m.x>a&&(f=(m.x+f.x)/2,u.splice(q+1,0,{isNull:!0,x:f}),this.options.stacking&&(f=p.stacks[this.stackKey][f]=new e.StackItem(p,p.options.stackLabels,!1,f,this.stack),f.total=0)),f=m);return this.getGraphPath(u)}});E(t,"parts-gantt/TreeGrid.js",[t["parts/Globals.js"],t["mixins/tree-series.js"],t["parts/Tick.js"],t["parts-gantt/Tree.js"],t["parts/Utilities.js"]],
function(e,a,q,v,x){var D=x.addEvent,t=x.defined,A=x.fireEvent,y=x.extend,u=x.isNumber,h=x.isString,m=x.merge,w=x.pick,I=x.wrap,p=function(b){return Array.prototype.slice.call(b,1)},f=x.find,d=a.getLevelOptions,k=function(b){return x.isObject(b,!0)};e=e.Axis;a=function(b,c){var g;for(g in c)if(Object.hasOwnProperty.call(c,g)){var n=c[g];I(b,g,n)}};var C=function(b,c){var g=b.collapseStart;b=b.collapseEnd;b>=c&&(g-=.5);return{from:g,to:b,showPoints:!1}},b=function(b){return Object.keys(b.mapOfPosToGridNode).reduce(function(g,
c){c=+c;b.min<=c&&b.max>=c&&!b.isInAnyBreak(c)&&g.push(c);return g},[])},c=function(b,c){var g=b.options.breaks||[],n=C(c,b.max);return g.some(function(b){return b.from===n.from&&b.to===n.to})},l=function(b,c){var g=b.options.breaks||[];b=C(c,b.max);g.push(b);return g},z=function(b,c){var g=b.options.breaks||[],n=C(c,b.max);return g.reduce(function(b,g){g.to===n.to&&g.from===n.from||b.push(g);return b},[])},P=function(b,c){var g=b.labelIcon,d=!g,n=c.renderer,a=c.xy,l=c.options,k=l.width,f=l.height,
z=a.x-k/2-l.padding;a=a.y-f/2;var h=c.collapsed?90:180,m=c.show&&u(a);d&&(b.labelIcon=g=n.path(n.symbols[l.type](l.x,l.y,k,f)).addClass("highcharts-label-icon").add(c.group));m||g.attr({y:-9999});n.styledMode||g.attr({"stroke-width":1,fill:w(c.color,"#666666")}).css({cursor:"pointer",stroke:l.lineColor,strokeWidth:l.lineWidth});g[d?"attr":"animate"]({translateX:z,translateY:a,rotation:h})},G=function(b,c,d){var g=[],n=[],a={},l={},r=-1,z="boolean"===typeof c?c:!1;b=v.getTree(b,{after:function(b){b=
l[b.pos];var c=0,g=0;b.children.forEach(function(b){g+=b.descendants+1;c=Math.max(b.height+1,c)});b.descendants=g;b.height=c;b.collapsed&&n.push(b)},before:function(b){var c=k(b.data)?b.data:{},d=h(c.name)?c.name:"",n=a[b.parent];n=k(n)?l[n.pos]:null;var B=function(b){return b.name===d},F;z&&k(n)&&(F=f(n.children,B))?(B=F.pos,F.nodes.push(b)):B=r++;l[B]||(l[B]=F={depth:n?n.depth+1:0,name:d,nodes:[b],children:[],pos:B},-1!==B&&g.push(d),k(n)&&n.children.push(F));h(b.id)&&(a[b.id]=b);!0===c.collapsed&&
(F.collapsed=!0);b.pos=B}});l=function(b,c){var g=function(b,n,d){var a=n+(-1===n?0:c-1),l=(a-n)/2,r=n+l;b.nodes.forEach(function(b){var c=b.data;k(c)&&(c.y=n+c.seriesIndex,delete c.seriesIndex);b.pos=r});d[r]=b;b.pos=r;b.tickmarkOffset=l+.5;b.collapseStart=a+.5;b.children.forEach(function(b){g(b,a+1,d);a=b.collapseEnd-.5});b.collapseEnd=a+.5;return d};return g(b["-1"],-1,{})}(l,d);return{categories:g,mapOfIdToNode:a,mapOfPosToGridNode:l,collapsedNodes:n,tree:b}},Q=function(b){b.target.axes.filter(function(b){return"treegrid"===
b.options.type}).forEach(function(c){var g=c.options||{},n=g.labels,a,f=g.uniqueNames,z=0;if(!c.mapOfPosToGridNode||c.series.some(function(b){return!b.hasRendered||b.isDirtyData||b.isDirty})){g=c.series.reduce(function(b,c){c.visible&&(c.options.data.forEach(function(c){k(c)&&(c.seriesIndex=z,b.push(c))}),!0===f&&z++);return b},[]);var h=G(g,f,!0===f?z:1);c.categories=h.categories;c.mapOfPosToGridNode=h.mapOfPosToGridNode;c.hasNames=!0;c.tree=h.tree;c.series.forEach(function(b){var c=b.options.data.map(function(b){return k(b)?
m(b):b});b.visible&&b.setData(c,!1)});c.mapOptionsToLevel=d({defaults:n,from:1,levels:n.levels,to:c.tree.height});"beforeRender"===b.type&&(a=D(c,"foundExtremes",function(){h.collapsedNodes.forEach(function(b){b=l(c,b);c.setBreaks(b,!1)});a()}))}})};a(e.prototype,{init:function(b,c,d){var g="treegrid"===d.type;g&&(D(c,"beforeRender",Q),D(c,"beforeRedraw",Q),d=m({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,
width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[c,d]);g&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var c=this.options,g=c&&c.labels;c=g&&u(g.indentation)?c.labels.indentation:0;g=b.apply(this,p(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var d=this.mapOfPosToGridNode[-1].height;g.width+=c*(d-1)}return g},generateTick:function(b,c){var g=k(this.mapOptionsToLevel)?this.mapOptionsToLevel:
{},d=this.ticks,n=d[c],a;if("treegrid"===this.options.type){var l=this.mapOfPosToGridNode[c];(g=g[l.depth])&&(a={labels:g});n?(n.parameters.category=l.name,n.options=a,n.addLabel()):d[c]=new q(this,c,null,void 0,{category:l.name,tickmarkOffset:l.tickmarkOffset,options:a})}else b.apply(this,p(arguments))},setTickInterval:function(c){var g=this.options;"treegrid"===g.type?(this.min=w(this.userMin,g.min,this.dataMin),this.max=w(this.userMax,g.max,this.dataMax),A(this,"foundExtremes"),this.setAxisTranslation(!0),
this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?b(this):[]):c.apply(this,p(arguments))}});a(q.prototype,{getLabelPosition:function(b,c,d,a,l,f,z,h,m){var g=w(this.options&&this.options.labels,f);f=this.pos;var n=this.axis,r="treegrid"===n.options.type;b=b.apply(this,[c,d,a,l,g,z,h,m]);r&&(c=g&&k(g.symbol)?g.symbol:{},g=g&&u(g.indentation)?g.indentation:0,f=(f=(n=n.mapOfPosToGridNode)&&n[f])&&f.depth||1,b.x+=c.width+2*c.padding+(f-1)*g);return b},renderLabel:function(b){var g=
this,d=g.pos,a=g.axis,l=g.label,f=a.mapOfPosToGridNode,z=a.options,h=w(g.options&&g.options.labels,z&&z.labels),m=h&&k(h.symbol)?h.symbol:{},e=(f=f&&f[d])&&f.depth;z="treegrid"===z.type;var C=!(!l||!l.element),G=-1<a.tickPositions.indexOf(d);d=a.chart.styledMode;z&&f&&C&&l.addClass("highcharts-treegrid-node-level-"+e);b.apply(g,p(arguments));z&&f&&C&&0<f.descendants&&(a=c(a,f),P(g,{color:!d&&l.styles.color,collapsed:a,group:l.parentGroup,options:m,renderer:l.renderer,show:G,xy:l.xy}),m="highcharts-treegrid-node-"+
(a?"expanded":"collapsed"),l.addClass("highcharts-treegrid-node-"+(a?"collapsed":"expanded")).removeClass(m),d||l.css({cursor:"pointer"}),[l,g.labelIcon].forEach(function(b){b.attachedTreeGridEvents||(D(b.element,"mouseover",function(){l.addClass("highcharts-treegrid-node-active");l.renderer.styledMode||l.css({textDecoration:"underline"})}),D(b.element,"mouseout",function(){var b=t(h.style)?h.style:{};l.removeClass("highcharts-treegrid-node-active");l.renderer.styledMode||l.css({textDecoration:b.textDecoration})}),
D(b.element,"click",function(){g.toggleCollapse()}),b.attachedTreeGridEvents=!0)}))}});y(q.prototype,{collapse:function(b){var c=this.axis,g=l(c,c.mapOfPosToGridNode[this.pos]);c.setBreaks(g,w(b,!0))},expand:function(b){var c=this.axis,g=z(c,c.mapOfPosToGridNode[this.pos]);c.setBreaks(g,w(b,!0))},toggleCollapse:function(b){var g=this.axis;var d=g.mapOfPosToGridNode[this.pos];d=c(g,d)?z(g,d):l(g,d);g.setBreaks(d,w(b,!0))}});e.prototype.utils={getNode:v.getNode}});E(t,"parts-gantt/PathfinderAlgorithms.js",
[t["parts/Utilities.js"]],function(e){function a(a,m,e){e=e||0;var h=a.length-1;m-=1e-7;for(var p,f;e<=h;)if(p=h+e>>1,f=m-a[p].xMin,0<f)e=p+1;else if(0>f)h=p-1;else return p;return 0<e?e-1:0}function q(h,m){for(var e=a(h,m.x+1)+1;e--;){var u;if(u=h[e].xMax>=m.x)u=h[e],u=m.x<=u.xMax&&m.x>=u.xMin&&m.y<=u.yMax&&m.y>=u.yMin;if(u)return e}return-1}function v(a){var h=[];if(a.length){h.push("M",a[0].start.x,a[0].start.y);for(var e=0;e<a.length;++e)h.push("L",a[e].end.x,a[e].end.y)}return h}function x(a,
e){a.yMin=y(a.yMin,e.yMin);a.yMax=A(a.yMax,e.yMax);a.xMin=y(a.xMin,e.xMin);a.xMax=A(a.xMax,e.xMax)}var t=e.extend,H=e.pick,A=Math.min,y=Math.max,u=Math.abs;return{straight:function(a,e){return{path:["M",a.x,a.y,"L",e.x,e.y],obstacles:[{start:a,end:e}]}},simpleConnect:t(function(a,e,w){function h(b,c,d,a,f){b={x:b.x,y:b.y};b[c]=d[a||c]+(f||0);return b}function m(b,c,d){var a=u(c[d]-b[d+"Min"])>u(c[d]-b[d+"Max"]);return h(c,d,b,d+(a?"Max":"Min"),a?1:-1)}var f=[],d=H(w.startDirectionX,u(e.x-a.x)>u(e.y-
a.y))?"x":"y",k=w.chartObstacles,C=q(k,a);w=q(k,e);if(-1<w){var b=k[w];w=m(b,e,d);b={start:w,end:e};var c=w}else c=e;-1<C&&(k=k[C],w=m(k,a,d),f.push({start:a,end:w}),w[d]>=a[d]===w[d]>=c[d]&&(d="y"===d?"x":"y",e=a[d]<e[d],f.push({start:w,end:h(w,d,k,d+(e?"Max":"Min"),e?1:-1)}),d="y"===d?"x":"y"));a=f.length?f[f.length-1].end:a;w=h(a,d,c);f.push({start:a,end:w});d=h(w,"y"===d?"x":"y",c);f.push({start:w,end:d});f.push(b);return{path:v(f),obstacles:f}},{requiresObstacles:!0}),fastAvoid:t(function(e,
m,w){function h(b,c,d){var n,l=b.x<c.x?1:-1;if(b.x<c.x){var r=b;var f=c}else r=c,f=b;if(b.y<c.y){var k=b;var z=c}else k=c,z=b;for(n=0>l?A(a(g,f.x),g.length-1):0;g[n]&&(0<l&&g[n].xMin<=f.x||0>l&&g[n].xMax>=r.x);){if(g[n].xMin<=f.x&&g[n].xMax>=r.x&&g[n].yMin<=z.y&&g[n].yMax>=k.y)return d?{y:b.y,x:b.x<c.x?g[n].xMin-1:g[n].xMax+1,obstacle:g[n]}:{x:b.x,y:b.y<c.y?g[n].yMin-1:g[n].yMax+1,obstacle:g[n]};n+=l}return c}function p(b,c,g,d,a){var n=a.soft,l=a.hard,r=d?"x":"y",f={x:c.x,y:c.y},k={x:c.x,y:c.y};
a=b[r+"Max"]>=n[r+"Max"];n=b[r+"Min"]<=n[r+"Min"];var z=b[r+"Max"]>=l[r+"Max"];l=b[r+"Min"]<=l[r+"Min"];var e=u(b[r+"Min"]-c[r]),B=u(b[r+"Max"]-c[r]);g=10>u(e-B)?c[r]<g[r]:B<e;k[r]=b[r+"Min"];f[r]=b[r+"Max"];b=h(c,k,d)[r]!==k[r];c=h(c,f,d)[r]!==f[r];g=b?c?g:!0:c?!1:g;g=n?a?g:!0:a?!1:g;return l?z?g:!0:z?!1:g}function f(b,d,a){if(b.x===d.x&&b.y===d.y)return[];var n=a?"x":"y",l=w.obstacleOptions.margin;var r={soft:{xMin:z,xMax:P,yMin:G,yMax:Q},hard:w.hardBounds};var k=q(g,b);if(-1<k){k=g[k];r=p(k,b,
d,a,r);x(k,w.hardBounds);var e=a?{y:b.y,x:k[r?"xMax":"xMin"]+(r?1:-1)}:{x:b.x,y:k[r?"yMax":"yMin"]+(r?1:-1)};var B=q(g,e);-1<B&&(B=g[B],x(B,w.hardBounds),e[n]=r?y(k[n+"Max"]-l+1,(B[n+"Min"]+k[n+"Max"])/2):A(k[n+"Min"]+l-1,(B[n+"Max"]+k[n+"Min"])/2),b.x===e.x&&b.y===e.y?(c&&(e[n]=r?y(k[n+"Max"],B[n+"Max"])+1:A(k[n+"Min"],B[n+"Min"])-1),c=!c):c=!1);b=[{start:b,end:e}]}else n=h(b,{x:a?d.x:b.x,y:a?b.y:d.y},a),b=[{start:b,end:{x:n.x,y:n.y}}],n[a?"x":"y"]!==d[a?"x":"y"]&&(r=p(n.obstacle,n,d,!a,r),x(n.obstacle,
w.hardBounds),r={x:a?n.x:n.obstacle[r?"xMax":"xMin"]+(r?1:-1),y:a?n.obstacle[r?"yMax":"yMin"]+(r?1:-1):n.y},a=!a,b=b.concat(f({x:n.x,y:n.y},r,a)));return b=b.concat(f(b[b.length-1].end,d,!a))}function d(b,c,g){var d=A(b.xMax-c.x,c.x-b.xMin)<A(b.yMax-c.y,c.y-b.yMin);g=p(b,c,g,d,{soft:w.hardBounds,hard:w.hardBounds});return d?{y:c.y,x:b[g?"xMax":"xMin"]+(g?1:-1)}:{x:c.x,y:b[g?"yMax":"yMin"]+(g?1:-1)}}var k=H(w.startDirectionX,u(m.x-e.x)>u(m.y-e.y)),C=k?"x":"y",b=[],c=!1,l=w.obstacleMetrics,z=A(e.x,
m.x)-l.maxWidth-10,P=y(e.x,m.x)+l.maxWidth+10,G=A(e.y,m.y)-l.maxHeight-10,Q=y(e.y,m.y)+l.maxHeight+10,g=w.chartObstacles;var n=a(g,z);l=a(g,P);g=g.slice(n,l+1);if(-1<(l=q(g,m))){var r=d(g[l],m,e);b.push({end:m,start:r});m=r}for(;-1<(l=q(g,m));)n=0>m[C]-e[C],r={x:m.x,y:m.y},r[C]=g[l][n?C+"Max":C+"Min"]+(n?1:-1),b.push({end:m,start:r}),m=r;e=f(e,m,k);e=e.concat(b.reverse());return{path:v(e),obstacles:e}},{requiresObstacles:!0})}});E(t,"parts-gantt/ArrowSymbols.js",[t["parts/Globals.js"]],function(e){e.SVGRenderer.prototype.symbols.arrow=
function(a,e,v,x){return["M",a,e+x/2,"L",a+v,e,"L",a,e+x/2,"L",a+v,e+x]};e.SVGRenderer.prototype.symbols["arrow-half"]=function(a,q,v,x){return e.SVGRenderer.prototype.symbols.arrow(a,q,v/2,x)};e.SVGRenderer.prototype.symbols["triangle-left"]=function(a,e,v,x){return["M",a+v,e,"L",a,e+x/2,"L",a+v,e+x,"Z"]};e.SVGRenderer.prototype.symbols["arrow-filled"]=e.SVGRenderer.prototype.symbols["triangle-left"];e.SVGRenderer.prototype.symbols["triangle-left-half"]=function(a,q,v,x){return e.SVGRenderer.prototype.symbols["triangle-left"](a,
q,v/2,x)};e.SVGRenderer.prototype.symbols["arrow-filled-half"]=e.SVGRenderer.prototype.symbols["triangle-left-half"]});E(t,"parts-gantt/Pathfinder.js",[t["parts/Globals.js"],t["parts/Utilities.js"],t["parts-gantt/PathfinderAlgorithms.js"]],function(e,a,q){function v(b){var c=b.shapeArgs;return c?{xMin:c.x,xMax:c.x+c.width,yMin:c.y,yMax:c.y+c.height}:(c=b.graphic&&b.graphic.getBBox())?{xMin:b.plotX-c.width/2,xMax:b.plotX+c.width/2,yMin:b.plotY-c.height/2,yMax:b.plotY+c.height/2}:null}function x(b){for(var c=
b.length,d=0,a,f,e=[],h=function(b,c,d){d=p(d,10);var g=b.yMax+d>c.yMin-d&&b.yMin-d<c.yMax+d,a=b.xMax+d>c.xMin-d&&b.xMin-d<c.xMax+d,n=g?b.xMin>c.xMax?b.xMin-c.xMax:c.xMin-b.xMax:Infinity,l=a?b.yMin>c.yMax?b.yMin-c.yMax:c.yMin-b.yMax:Infinity;return a&&g?d?h(b,c,Math.floor(d/2)):Infinity:C(n,l)};d<c;++d)for(a=d+1;a<c;++a)f=h(b[d],b[a]),80>f&&e.push(f);e.push(80);return k(Math.floor(e.sort(function(b,c){return b-c})[Math.floor(e.length/10)]/2-1),1)}function t(b,c,d){this.init(b,c,d)}function H(b){this.init(b)}
function A(b){if(b.options.pathfinder||b.series.reduce(function(b,d){d.options&&w(!0,d.options.connectors=d.options.connectors||{},d.options.pathfinder);return b||d.options&&d.options.pathfinder},!1))w(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder),h('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}var y=a.addEvent,u=a.defined,h=a.error,m=a.extend,w=a.merge,I=a.objectEach,p=a.pick,f=a.splat,d=e.deg2rad,k=Math.max,C=Math.min;
m(e.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});t.prototype={init:function(b,c,d){this.fromPoint=b;this.toPoint=c;this.options=d;this.chart=b.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(b,c,d){var a=this.chart,l=a.styledMode,f=a.pathfinder,k=!a.options.chart.forExport&&!1!==d,g=this.graphics&&this.graphics.path;
f.group||(f.group=a.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(a.seriesGroup));f.group.translate(a.plotLeft,a.plotTop);g&&g.renderer||(g=a.renderer.path().add(f.group),l||g.attr({opacity:0}));g.attr(c);b={d:b};l||(b.opacity=1);g[k?"animate":"attr"](b,d);this.graphics=this.graphics||{};this.graphics.path=g},addMarker:function(b,c,a){var l=this.fromPoint.series.chart,f=l.pathfinder;l=l.renderer;var k="start"===b?this.fromPoint:this.toPoint,e=k.getPathfinderAnchorPoint(c);
if(c.enabled){a="start"===b?{x:a[4],y:a[5]}:{x:a[a.length-5],y:a[a.length-4]};a=k.getRadiansToVector(a,e);e=k.getMarkerVector(a,c.radius,e);a=-a/d;if(c.width&&c.height){var g=c.width;var n=c.height}else g=n=2*c.radius;this.graphics=this.graphics||{};e={x:e.x-g/2,y:e.y-n/2,width:g,height:n,rotation:a,rotationOriginX:e.x,rotationOriginY:e.y};this.graphics[b]?this.graphics[b].animate(e):(this.graphics[b]=l.symbol(c.symbol).addClass("highcharts-point-connecting-path-"+b+"-marker").attr(e).add(f.group),
l.styledMode||this.graphics[b].attr({fill:c.color||this.fromPoint.color,stroke:c.lineColor,"stroke-width":c.lineWidth,opacity:0}).animate({opacity:1},k.series.options.animation))}},getPath:function(b){var c=this.pathfinder,d=this.chart,a=c.algorithms[b.type],f=c.chartObstacles;if("function"!==typeof a)h('"'+b.type+'" is not a Pathfinder algorithm.');else return a.requiresObstacles&&!f&&(f=c.chartObstacles=c.getChartObstacles(b),d.options.connectors.algorithmMargin=b.algorithmMargin,c.chartObstacleMetrics=
c.getObstacleMetrics(f)),a(this.fromPoint.getPathfinderAnchorPoint(b.startMarker),this.toPoint.getPathfinderAnchorPoint(b.endMarker),w({chartObstacles:f,lineObstacles:c.lineObstacles||[],obstacleMetrics:c.chartObstacleMetrics,hardBounds:{xMin:0,xMax:d.plotWidth,yMin:0,yMax:d.plotHeight},obstacleOptions:{margin:b.algorithmMargin},startDirectionX:c.getAlgorithmStartDirection(b.startMarker)},b))},render:function(){var b=this.fromPoint,c=b.series,d=c.chart,a=d.pathfinder,f=w(d.options.connectors,c.options.connectors,
b.options.connectors,this.options),e={};d.styledMode||(e.stroke=f.lineColor||b.color,e["stroke-width"]=f.lineWidth,f.dashStyle&&(e.dashstyle=f.dashStyle));e["class"]="highcharts-point-connecting-path highcharts-color-"+b.colorIndex;f=w(e,f);u(f.marker.radius)||(f.marker.radius=C(k(Math.ceil((f.algorithmMargin||8)/2)-1,1),5));b=this.getPath(f);d=b.path;b.obstacles&&(a.lineObstacles=a.lineObstacles||[],a.lineObstacles=a.lineObstacles.concat(b.obstacles));this.renderPath(d,e,c.options.animation);this.addMarker("start",
w(f.marker,f.startMarker),d);this.addMarker("end",w(f.marker,f.endMarker),d)},destroy:function(){this.graphics&&(I(this.graphics,function(b){b.destroy()}),delete this.graphics)}};H.prototype={algorithms:q,init:function(b){this.chart=b;this.connections=[];y(b,"redraw",function(){this.pathfinder.update()})},update:function(b){var c=this.chart,d=this,a=d.connections;d.connections=[];c.series.forEach(function(b){b.visible&&!b.options.isInternal&&b.points.forEach(function(b){var g,a=b.options&&b.options.connect&&
f(b.options.connect);b.visible&&!1!==b.isInside&&a&&a.forEach(function(a){g=c.get("string"===typeof a?a:a.to);g instanceof e.Point&&g.series.visible&&g.visible&&!1!==g.isInside&&d.connections.push(new t(b,g,"string"===typeof a?{}:a))})})});for(var k=0,h,m,g=a.length,n=d.connections.length;k<g;++k){m=!1;for(h=0;h<n;++h)if(a[k].fromPoint===d.connections[h].fromPoint&&a[k].toPoint===d.connections[h].toPoint){d.connections[h].graphics=a[k].graphics;m=!0;break}m||a[k].destroy()}delete this.chartObstacles;
delete this.lineObstacles;d.renderConnections(b)},renderConnections:function(b){b?this.chart.series.forEach(function(b){var c=function(){var c=b.chart.pathfinder;(c&&c.connections||[]).forEach(function(c){c.fromPoint&&c.fromPoint.series===b&&c.render()});b.pathfinderRemoveRenderEvent&&(b.pathfinderRemoveRenderEvent(),delete b.pathfinderRemoveRenderEvent)};!1===b.options.animation?c():b.pathfinderRemoveRenderEvent=y(b,"afterAnimate",c)}):this.connections.forEach(function(b){b.render()})},getChartObstacles:function(b){for(var c=
[],d=this.chart.series,a=p(b.algorithmMargin,0),f,k=0,e=d.length;k<e;++k)if(d[k].visible&&!d[k].options.isInternal)for(var g=0,n=d[k].points.length,r;g<n;++g)r=d[k].points[g],r.visible&&(r=v(r))&&c.push({xMin:r.xMin-a,xMax:r.xMax+a,yMin:r.yMin-a,yMax:r.yMax+a});c=c.sort(function(b,c){return b.xMin-c.xMin});u(b.algorithmMargin)||(f=b.algorithmMargin=x(c),c.forEach(function(b){b.xMin-=f;b.xMax+=f;b.yMin-=f;b.yMax+=f}));return c},getObstacleMetrics:function(b){for(var c=0,d=0,a,f,k=b.length;k--;)a=b[k].xMax-
b[k].xMin,f=b[k].yMax-b[k].yMin,c<a&&(c=a),d<f&&(d=f);return{maxHeight:d,maxWidth:c}},getAlgorithmStartDirection:function(b){var c="top"!==b.verticalAlign&&"bottom"!==b.verticalAlign;return"left"!==b.align&&"right"!==b.align?c?void 0:!1:c?!0:void 0}};e.Connection=t;e.Pathfinder=H;m(e.Point.prototype,{getPathfinderAnchorPoint:function(b){var c=v(this);switch(b.align){case "right":var d="xMax";break;case "left":d="xMin"}switch(b.verticalAlign){case "top":var a="yMin";break;case "bottom":a="yMax"}return{x:d?
c[d]:(c.xMin+c.xMax)/2,y:a?c[a]:(c.yMin+c.yMax)/2}},getRadiansToVector:function(b,c){u(c)||(c=v(this),c={x:(c.xMin+c.xMax)/2,y:(c.yMin+c.yMax)/2});return Math.atan2(c.y-b.y,b.x-c.x)},getMarkerVector:function(b,c,d){var a=2*Math.PI,f=v(this),k=f.xMax-f.xMin,l=f.yMax-f.yMin,g=Math.atan2(l,k),n=!1;k/=2;var r=l/2,e=f.xMin+k;f=f.yMin+r;for(var h=e,m=f,C={},p=1,u=1;b<-Math.PI;)b+=a;for(;b>Math.PI;)b-=a;a=Math.tan(b);b>-g&&b<=g?(u=-1,n=!0):b>g&&b<=Math.PI-g?u=-1:b>Math.PI-g||b<=-(Math.PI-g)?(p=-1,n=!0):
p=-1;n?(h+=p*k,m+=u*k*a):(h+=l/(2*a)*p,m+=u*r);d.x!==e&&(h=d.x);d.y!==f&&(m=d.y);C.x=h+c*Math.cos(b);C.y=m-c*Math.sin(b);return C}});e.Chart.prototype.callbacks.push(function(b){!1!==b.options.connectors.enabled&&(A(b),this.pathfinder=new H(this),this.pathfinder.update(!0))})});E(t,"modules/xrange.src.js",[t["parts/Globals.js"],t["parts/Color.js"],t["parts/Utilities.js"]],function(e,a,q){var t=a.parse;a=q.addEvent;var x=q.clamp,D=q.correctFloat,H=q.defined,A=q.find,y=q.isNumber,u=q.isObject,h=q.merge,
m=q.pick;q=q.seriesType;var w=e.seriesTypes.column,I=e.Axis,p=e.Point,f=e.Series;q("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var d=this.point.partialFill;u(d)&&(d=d.amount);if(y(d)&&0<d)return D(100*d)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",
parallelArrays:["x","x2","y"],requireSorting:!1,animate:e.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:e.noop,buildKDTree:e.noop,getColumnMetrics:function(){function d(){a.series.forEach(function(b){var c=b.xAxis;b.xAxis=b.yAxis;b.yAxis=c})}var a=this.chart;d();var f=w.prototype.getColumnMetrics.call(this);d();return f},cropData:function(d,a,e,b){a=f.prototype.cropData.call(this,this.x2Data,a,e,b);a.xData=d.slice(a.start,a.end);return a},findPointIndex:function(d){var a=
this.cropped,f=this.cropStart,b=this.points,c=d.id;if(c)var l=(l=A(b,function(b){return b.id===c}))?l.index:void 0;"undefined"===typeof l&&(l=(l=A(b,function(b){return b.x===d.x&&b.x2===d.x2&&!b.touched}))?l.index:void 0);a&&y(l)&&y(f)&&l>=f&&(l-=f);return l},translatePoint:function(d){var a=this.xAxis,f=this.yAxis,b=this.columnMetrics,c=this.options,l=c.minPointLength||0,e=d.plotX,p=m(d.x2,d.x+(d.len||0)),q=a.translate(p,0,0,0,1);p=Math.abs(q-e);var w=this.chart.inverted,g=m(c.borderWidth,1)%2/2,
n=b.offset,r=Math.round(b.width);l&&(l-=p,0>l&&(l=0),e-=l/2,q+=l/2);e=Math.max(e,-10);q=x(q,-10,a.len+10);H(d.options.pointWidth)&&(n-=(Math.ceil(d.options.pointWidth)-r)/2,r=Math.ceil(d.options.pointWidth));c.pointPlacement&&y(d.plotY)&&f.categories&&(d.plotY=f.translate(d.y,0,1,0,1,c.pointPlacement));d.shapeArgs={x:Math.floor(Math.min(e,q))+g,y:Math.floor(d.plotY+n)+g,width:Math.round(Math.abs(q-e)),height:r,r:this.options.borderRadius};c=d.shapeArgs.x;l=c+d.shapeArgs.width;0>c||l>a.len?(c=x(c,
0,a.len),l=x(l,0,a.len),q=l-c,d.dlBox=h(d.shapeArgs,{x:c,width:l-c,centerX:q?q/2:null})):d.dlBox=null;c=d.tooltipPos;l=w?1:0;q=w?0:1;c[l]=x(c[l]+p/2*(a.reversed?-1:1)*(w?-1:1),0,a.len-1);c[q]=x(c[q]+b.width/2*(w?1:-1),0,f.len-1);if(b=d.partialFill)u(b)&&(b=b.amount),y(b)||(b=0),f=d.shapeArgs,d.partShapeArgs={x:f.x,y:f.y,width:f.width,height:f.height,r:this.options.borderRadius},e=Math.max(Math.round(p*b+d.plotX-e),0),d.clipRectArgs={x:a.reversed?f.x+p-e:f.x,y:f.y,width:e,height:f.height}},translate:function(){w.prototype.translate.apply(this,
arguments);this.points.forEach(function(d){this.translatePoint(d)},this)},drawPoint:function(d,a){var f=this.options,b=this.chart.renderer,c=d.graphic,l=d.shapeType,e=d.shapeArgs,k=d.partShapeArgs,p=d.clipRectArgs,q=d.partialFill,g=f.stacking&&!f.borderRadius,n=d.state,r=f.states[n||"normal"]||{},B="undefined"===typeof n?"attr":a;n=this.pointAttribs(d,n);r=m(this.chart.options.chart.animation,r.animation);if(d.isNull||!1===d.visible)c&&(d.graphic=c.destroy());else{if(c)c.rect[a](e);else d.graphic=
c=b.g("point").addClass(d.getClassName()).add(d.group||this.group),c.rect=b[l](h(e)).addClass(d.getClassName()).addClass("highcharts-partfill-original").add(c);k&&(c.partRect?(c.partRect[a](h(k)),c.partialClipRect[a](h(p))):(c.partialClipRect=b.clipRect(p.x,p.y,p.width,p.height),c.partRect=b[l](k).addClass("highcharts-partfill-overlay").add(c).clip(c.partialClipRect)));this.chart.styledMode||(c.rect[a](n,r).shadow(f.shadow,null,g),k&&(u(q)||(q={}),u(f.partialFill)&&(q=h(q,f.partialFill)),d=q.fill||
t(n.fill).brighten(-.3).get()||t(d.color||this.color).brighten(-.3).get(),n.fill=d,c.partRect[B](n,r).shadow(f.shadow,null,g)))}},drawPoints:function(){var d=this,a=d.getAnimationVerb();d.points.forEach(function(f){d.drawPoint(f,a)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var d=this.series;if(d.options.colorByPoint&&!this.options.color){var a=d.options.colors||d.chart.options.colors;var f=this.y%(a?a.length:
d.chart.options.chart.colorCount);a=a&&a[f];d.chart.styledMode||(this.color=a);this.options.colorIndex||(this.colorIndex=f)}else this.color||(this.color=d.color)},init:function(){p.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){p.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=p.prototype.getLabelConfig.call(this),f=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=
f&&f[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});a(I,"afterGetSeriesExtremes",function(){var a=this.series,f;if(this.isXAxis){var e=m(this.dataMax,-Number.MAX_VALUE);a.forEach(function(b){b.x2Data&&b.x2Data.forEach(function(b){b>e&&(e=b,f=!0)})});f&&(this.dataMax=e)}});""});E(t,"parts-gantt/GanttSeries.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.isNumber,t=a.merge,x=a.pick,D=a.seriesType,
H=a.splat,A=e.dateFormat,y=e.seriesTypes.xrange;D("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var a=this.series,e=a.chart.tooltip,m=a.xAxis,q=a.tooltipOptions.dateTimeLabelFormats,t=m.options.startOfWeek,p=a.tooltipOptions,f=p.xDateFormat;a=this.options.milestone;var d="<b>"+(this.name||this.yCategory)+"</b>";if(p.pointFormat)return this.tooltipFormatter(p.pointFormat);
f||(f=H(e.getDateFormat(m.closestPointRange,this.start,t,q))[0]);e=A(f,this.start);m=A(f,this.end);d+="<br/>";return a?d+(e+"<br/>"):d+("Start: "+e+"<br/>End: ")+(m+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(a){y.prototype.translatePoint.call(this,a);if(a.options.milestone){var e=
a.shapeArgs;var m=e.height;a.shapeArgs={x:e.x-m/2,y:e.y,width:m,height:m}}},drawPoint:function(a,e){var h=this.options,u=this.chart.renderer,t=a.shapeArgs,p=a.plotY,f=a.graphic,d=a.selected&&"select",k=h.stacking&&!h.borderRadius;if(a.options.milestone)if(q(p)&&null!==a.y&&!1!==a.visible){t=u.symbols.diamond(t.x,t.y,t.width,t.height);if(f)f[e]({d:t});else a.graphic=u.path(t).addClass(a.getClassName(),!0).add(a.group||this.group);this.chart.styledMode||a.graphic.attr(this.pointAttribs(a,d)).shadow(h.shadow,
null,k)}else f&&(a.graphic=f.destroy());else y.prototype.drawPoint.call(this,a,e)},setData:e.Series.prototype.setData,setGanttPointAliases:function(a){function e(e,h){"undefined"!==typeof h&&(a[e]=h)}e("x",x(a.start,a.x));e("x2",x(a.end,a.x2));e("partialFill",x(a.completed,a.partialFill));e("connect",x(a.dependency,a.connect))}},t(y.prototype.pointClass.prototype,{applyOptions:function(a,h){a=t(a);e.seriesTypes.gantt.prototype.setGanttPointAliases(a);return a=y.prototype.pointClass.prototype.applyOptions.call(this,
a,h)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});E(t,"parts-gantt/GanttChart.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.isArray,t=a.merge,x=a.splat,D=e.Chart;e.ganttChart=function(a,v,y){var u="string"===typeof a||a.nodeName,h=v.series,m=e.getOptions(),w,A=v;v=arguments[u?1:0];q(v.xAxis)||(v.xAxis=[v.xAxis||{},{}]);v.xAxis=v.xAxis.map(function(a,f){1===
f&&(w=0);return t(m.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:w},a,{type:"datetime"})});v.yAxis=x(v.yAxis||{}).map(function(a){return t(m.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:a.categories?a.type:"treegrid"},a)});v.series=null;v=t(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},v,{isGantt:!0});v.series=A.series=h;v.series.forEach(function(a){a.data.forEach(function(a){e.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});return u?new D(a,v,y):new D(v,v)}});
E(t,"parts/Scrollbar.js",[t["parts/Globals.js"],t["parts/Utilities.js"]],function(e,a){var q=a.addEvent,t=a.correctFloat,x=a.defined,D=a.destroyObjectProperties,H=a.fireEvent,A=a.merge,y=a.pick,u=a.removeEvent;a=e.Axis;var h=e.defaultOptions,m=e.hasTouch,w,E={height:e.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",
buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};h.scrollbar=A(!0,E,h.scrollbar);e.swapXY=w=function(a,d){var f=a.length;if(d)for(d=0;d<f;d+=3){var e=a[d+1];a[d+1]=a[d+2];a[d+2]=e}return a};var p=function(){function a(a,f,e){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=
void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=e;this.options=f;this.renderer=e.renderer;this.init(a,f,e)}a.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,1],f=this.scrollbarButtons,e=this.scrollbarGroup.element,b=this.track.element,c=this.mouseDownHandler.bind(this),l=this.mouseMoveHandler.bind(this),h=this.mouseUpHandler.bind(this);a=[[f[a[0]].element,"click",this.buttonToMinClick.bind(this)],
[f[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[b,"click",this.trackClick.bind(this)],[e,"mousedown",c],[e.ownerDocument,"mousemove",l],[e.ownerDocument,"mouseup",h]];m&&a.push([e,"touchstart",c],[e.ownerDocument,"touchmove",l],[e.ownerDocument,"touchend",h]);a.forEach(function(b){q.apply(null,b)});this._events=a};a.prototype.buttonToMaxClick=function(a){var d=(this.to-this.from)*y(this.options.step,.2);this.updatePosition(this.from+d,this.to+d);H(this,"changed",{from:this.from,to:this.to,
trigger:"scrollbar",DOMEvent:a})};a.prototype.buttonToMinClick=function(a){var d=t(this.to-this.from)*y(this.options.step,.2);this.updatePosition(t(this.from-d),t(this.to-d));H(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.cursorToScrollbarPosition=function(a){var d=this.options;d=d.minWidth>this.calculatedWidth?d.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-d),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-d)}};a.prototype.destroy=
function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,D(a.scrollbarButtons))};a.prototype.drawScrollbarButton=function(a){var d=this.renderer,f=this.scrollbarButtons,b=this.options,c=this.size;var e=d.g().add(this.group);f.push(e);e=d.rect().addClass("highcharts-scrollbar-button").add(e);this.chart.styledMode||
e.attr({stroke:b.buttonBorderColor,"stroke-width":b.buttonBorderWidth,fill:b.buttonBackgroundColor});e.attr(e.crisp({x:-.5,y:-.5,width:c+1,height:c+1,r:b.buttonBorderRadius},e.strokeWidth()));e=d.path(w(["M",c/2+(a?-1:1),c/2-3,"L",c/2+(a?-1:1),c/2+3,"L",c/2+(a?2:-2),c/2],b.vertical)).addClass("highcharts-scrollbar-arrow").add(f[a]);this.chart.styledMode||e.attr({fill:b.buttonArrowColor})};a.prototype.init=function(a,f,e){this.scrollbarButtons=[];this.renderer=a;this.userOptions=f;this.options=A(E,
f);this.chart=e;this.size=y(this.options.size,this.options.height);f.enabled&&(this.render(),this.addEvents())};a.prototype.mouseDownHandler=function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=function(a){var d=this.chart.pointer.normalize(a),f=this.options.vertical?"chartY":"chartX",b=this.initPositions||[];!this.grabbedCenter||a.touches&&
0===a.touches[0][f]||(d=this.cursorToScrollbarPosition(d)[f],f=this[f],f=d-f,this.hasDragged=!0,this.updatePosition(b[0]+f,b[1]+f),this.hasDragged&&H(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};a.prototype.mouseUpHandler=function(a){this.hasDragged&&H(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(a,f,e,b){var c=this.options.vertical,
d=0,k=this.rendered?"animate":"attr";this.x=a;this.y=f+this.trackBorderWidth;this.width=e;this.xOffset=this.height=b;this.yOffset=d;c?(this.width=this.yOffset=e=d=this.size,this.xOffset=f=0,this.barWidth=b-2*e,this.x=a+=this.options.margin):(this.height=this.xOffset=b=f=this.size,this.barWidth=e-2*b,this.y+=this.options.margin);this.group[k]({translateX:a,translateY:this.y});this.track[k]({width:e,height:b});this.scrollbarButtons[1][k]({translateX:c?0:e-f,translateY:c?b-d:0})};a.prototype.removeEvents=
function(){this._events.forEach(function(a){u.apply(null,a)});this._events.length=0};a.prototype.render=function(){var a=this.renderer,f=this.options,e=this.size,b=this.chart.styledMode,c;this.group=c=a.g("scrollbar").attr({zIndex:f.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:f.trackBorderRadius||0,height:e,width:e}).add(c);b||this.track.attr({fill:f.trackBackgroundColor,stroke:f.trackBorderColor,"stroke-width":f.trackBorderWidth});this.trackBorderWidth=
this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(c);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:e,width:e,r:f.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(w(["M",-3,e/4,"L",-3,2*e/3,"M",0,e/4,"L",0,2*e/3,"M",3,e/4,"L",3,2*e/3],f.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);b||(this.scrollbar.attr({fill:f.barBackgroundColor,stroke:f.barBorderColor,"stroke-width":f.barBorderWidth}),
this.scrollbarRifles.attr({stroke:f.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(a,f){var d=this.options,b=d.vertical,c=d.minWidth,e=this.barWidth,k,h=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(x(e)){a=Math.max(a,0);
var m=Math.ceil(e*a);this.calculatedWidth=k=t(e*Math.min(f,1)-m);k<c&&(m=(e-c+k)*a,k=c);c=Math.floor(m+this.xOffset+this.yOffset);e=k/2-.5;this.from=a;this.to=f;b?(this.scrollbarGroup[h]({translateY:c}),this.scrollbar[h]({height:k}),this.scrollbarRifles[h]({translateY:e}),this.scrollbarTop=c,this.scrollbarLeft=0):(this.scrollbarGroup[h]({translateX:c}),this.scrollbar[h]({width:k}),this.scrollbarRifles[h]({translateX:e}),this.scrollbarLeft=c,this.scrollbarTop=0);12>=k?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);
!1===d.showFull&&(0>=a&&1<=f?this.group.hide():this.group.show());this.rendered=!0}};a.prototype.trackClick=function(a){var d=this.chart.pointer.normalize(a),f=this.to-this.from,b=this.y+this.scrollbarTop,c=this.x+this.scrollbarLeft;this.options.vertical&&d.chartY>b||!this.options.vertical&&d.chartX>c?this.updatePosition(this.from+f,this.to+f):this.updatePosition(this.from-f,this.to-f);H(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.update=function(a){this.destroy();
this.init(this.chart.renderer,A(!0,this.options,a),this.chart)};a.prototype.updatePosition=function(a,f){1<f&&(a=t(1-t(f-a)),f=1);0>a&&(f=t(f-a),a=0);this.from=a;this.to=f};return a}();e.Scrollbar||(q(a,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new p(a.chart.renderer,a.options.scrollbar,a.chart),q(a.scrollbar,"changed",function(d){var f=Math.min(y(a.options.min,
a.min),a.min,a.dataMin),h=Math.max(y(a.options.max,a.max),a.max,a.dataMax)-f;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var b=f+h*this.to;f+=h*this.from}else b=f+h*(1-this.from),f+=h*(1-this.to);y(this.options.liveRedraw,e.svg&&!e.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===d.DOMType||!x(d.DOMType)?a.setExtremes(f,b,!0,"mousemove"!==d.DOMType,d):this.setRange(this.from,this.to)}))}),q(a,"afterRender",function(){var a=Math.min(y(this.options.min,this.min),this.min,y(this.dataMin,this.min)),
d=Math.max(y(this.options.max,this.max),this.max,y(this.dataMax,this.max)),e=this.scrollbar,h=this.axisTitleMargin+(this.titleOffset||0),b=this.chart.scrollbarsOffsets,c=this.options.margin||0;e&&(this.horiz?(this.opposite||(b[1]+=h),e.position(this.left,this.top+this.height+2+b[1]-(this.opposite?c:0),this.width,this.height),this.opposite||(b[1]+=c),h=1):(this.opposite&&(b[0]+=h),e.position(this.left+this.width+2+b[0]-(this.opposite?0:c),this.top,this.width,this.height),this.opposite&&(b[0]+=c),h=
0),b[h]+=e.size+e.options.margin,isNaN(a)||isNaN(d)||!x(this.min)||!x(this.max)||this.min===this.max?e.setRange(0,1):(b=(this.min-a)/(d-a),a=(this.max-a)/(d-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?e.setRange(b,a):e.setRange(1-a,1-b)))}),q(a,"afterGetOffset",function(){var a=this.horiz?2:1,d=this.scrollbar;d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=d.size+d.options.margin)}),e.Scrollbar=p);return e.Scrollbar});E(t,"parts/RangeSelector.js",[t["parts/Globals.js"],
t["parts/Utilities.js"]],function(e,a){function q(b){this.init(b)}var t=a.addEvent,x=a.createElement,D=a.css,E=a.defined,A=a.destroyObjectProperties,y=a.discardElement,u=a.extend,h=a.fireEvent,m=a.isNumber,w=a.merge,I=a.objectEach,p=a.pick,f=a.pInt,d=a.splat,k=e.Axis;a=e.Chart;var C=e.defaultOptions;u(C,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},
labelStyle:{color:"#666666"}}});C.lang=w(C.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});q.prototype={clickButton:function(b,a){var c=this.chart,e=this.buttonOptions[b],f=c.xAxis[0],h=c.scroller&&c.scroller.getUnionExtremes()||f||{},q=h.dataMin,g=h.dataMax,n=f&&Math.round(Math.min(f.max,p(g,f.max))),r=e.type;h=e._range;var B,F=e.dataGrouping;if(null!==q&&null!==g){c.fixedRange=h;F&&(this.forcedDataGrouping=!0,k.prototype.setDataGrouping.call(f||{chart:this.chart},
F,!1),this.frozenStates=e.preserveDataGrouping);if("month"===r||"year"===r)if(f){r={range:e,max:n,chart:c,dataMin:q,dataMax:g};var L=f.minFromRange.call(r);m(r.newMax)&&(n=r.newMax)}else h=e;else if(h)L=Math.max(n-h,q),n=Math.min(L+h,g);else if("ytd"===r)if(f)"undefined"===typeof g&&(q=Number.MAX_VALUE,g=Number.MIN_VALUE,c.series.forEach(function(b){b=b.xData;q=Math.min(b[0],q);g=Math.max(b[b.length-1],g)}),a=!1),n=this.getYTDExtremes(g,q,c.time.useUTC),L=B=n.min,n=n.max;else{this.deferredYTDClick=
b;return}else"all"===r&&f&&(L=q,n=g);L+=e._offsetMin;n+=e._offsetMax;this.setSelected(b);if(f)f.setExtremes(L,n,p(a,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:e});else{var J=d(c.options.xAxis)[0];var K=J.range;J.range=h;var u=J.min;J.min=B;t(c,"load",function(){J.range=K;J.min=u})}}},setSelected:function(b){this.selected=this.options.selected=b},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},
{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(b){var a=this,d=b.options.rangeSelector,e=d.buttons||[].concat(a.defaultButtons),f=d.selected,k=function(){var b=a.minInput,c=a.maxInput;b&&b.blur&&h(b,"blur");c&&c.blur&&h(c,"blur")};a.chart=b;a.options=d;a.buttons=[];a.buttonOptions=e;this.unMouseDown=t(b.container,"mousedown",k);this.unResize=t(b,"resize",k);e.forEach(a.computeButtonRange);"undefined"!==typeof f&&e[f]&&this.clickButton(f,!1);t(b,"load",function(){b.xAxis&&b.xAxis[0]&&
t(b.xAxis[0],"setExtremes",function(c){this.max-this.min!==b.fixedRange&&"rangeSelectorButton"!==c.trigger&&"updatedData"!==c.trigger&&a.forcedDataGrouping&&!a.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var b=this,a=this.chart,d=a.xAxis[0],e=Math.round(d.max-d.min),f=!d.hasVisibleSeries,h=a.scroller&&a.scroller.getUnionExtremes()||d,k=h.dataMin,g=h.dataMax;a=b.getYTDExtremes(g,k,a.time.useUTC);var n=a.min,r=a.max,p=b.selected,q=m(p),t=b.options.allButtonsEnabled,
J=b.buttons;b.buttonOptions.forEach(function(a,c){var l=a._range,h=a.type,m=a.count||1,B=J[c],z=0,F=a._offsetMax-a._offsetMin;a=c===p;var K=l>g-k,L=l<d.minRange,u=!1,w=!1;l=l===e;("month"===h||"year"===h)&&e+36E5>=864E5*{month:28,year:365}[h]*m-F&&e-36E5<=864E5*{month:31,year:366}[h]*m+F?l=!0:"ytd"===h?(l=r-n+F===e,u=!a):"all"===h&&(l=d.max-d.min>=g-k,w=!a&&q&&l);h=!t&&(K||L||w||f);m=a&&l||l&&!q&&!u||a&&b.frozenStates;h?z=3:m&&(q=!0,z=2);B.state!==z&&(B.setState(z),0===z&&p===c&&b.setSelected(null))})},
computeButtonRange:function(b){var a=b.type,d=b.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[a])b._range=e[a]*d;else if("month"===a||"year"===a)b._range=864E5*{month:30,year:365}[a]*d;b._offsetMin=p(b.offsetMin,0);b._offsetMax=p(b.offsetMax,0);b._range+=b._offsetMax-b._offsetMin},setInputValue:function(a,c){var b=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];E(c)&&(e.previousValue=e.HCTime,e.HCTime=c);e.value=d.dateFormat(b.inputEditDateFormat||
"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var b=this.inputGroup,d=this[a+"DateBox"];D(this[a+"Input"],{left:b.translateX+d.x+"px",top:b.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})},hideInput:function(a){D(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=r.value,b=(q.inputDateParser||Date.parse)(a),c=h.xAxis[0],
g=h.scroller&&h.scroller.xAxis?h.scroller.xAxis:c,e=g.dataMin;g=g.dataMax;b!==r.previousValue&&(r.previousValue=b,m(b)||(b=a.split("-"),b=Date.UTC(f(b[0]),f(b[1])-1,f(b[2]))),m(b)&&(h.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),n?b>d.maxInput.HCTime?b=void 0:b<e&&(b=e):b<d.minInput.HCTime?b=void 0:b>g&&(b=g),"undefined"!==typeof b&&c.setExtremes(n?b:c.min,n?c.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var d=this,h=d.chart,k=h.renderer.style||{},p=h.renderer,q=h.options.rangeSelector,
g=d.div,n="min"===a,r,B,F=this.inputGroup;this[a+"Label"]=B=p.label(C.lang[n?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(F);F.offset+=B.width+5;this[a+"DateBox"]=p=p.label("",F.offset).addClass("highcharts-range-input").attr({padding:2,width:q.inputBoxWidth||90,height:q.inputBoxHeight||17,"text-align":"center"}).on("click",function(){d.showInput(a);d[a+"Input"].focus()});h.styledMode||p.attr({stroke:q.inputBoxBorderColor||
"#cccccc","stroke-width":1});p.add(F);F.offset+=p.width+(n?10:0);this[a+"Input"]=r=x("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:h.plotTop+"px"},g);h.styledMode||(B.css(w(k,q.labelStyle)),p.css(w({color:"#333333"},k,q.inputStyle)),D(r,u({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:k.fontSize,fontFamily:k.fontFamily,top:"-9999em"},q.inputStyle)));r.onfocus=function(){d.showInput(a)};r.onblur=function(){r===e.doc.activeElement&&
b();d.hideInput(a);r.blur()};r.onchange=b;r.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,d){var b=this.chart.time,e=new b.Date(a),f=b.get("FullYear",e);d=d?b.Date.UTC(f,0,1):+new b.Date(f,0,1);c=Math.max(c||0,d);e=e.getTime();return{max:Math.min(a||e,e),min:c}},render:function(a,c){var b=
this,d=b.chart,e=d.renderer,f=d.container,h=d.options,g=h.exporting&&!1!==h.exporting.enabled&&h.navigation&&h.navigation.buttonOptions,n=C.lang,r=b.div,k=h.rangeSelector,m=p(h.chart.style&&h.chart.style.zIndex,0)+1;h=k.floating;var q=b.buttons;r=b.inputGroup;var t=k.buttonTheme,K=k.buttonPosition,u=k.inputPosition,w=k.inputEnabled,y=t&&t.states,D=d.plotLeft,v=b.buttonGroup;var A=b.rendered;var E=b.options.verticalAlign,H=d.legend,I=H&&H.options,S=K.y,R=u.y,T=A||!1,U=T?"animate":"attr",O=0,M=0,N;
if(!1!==k.enabled){A||(b.group=A=e.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=v=e.g("range-selector-buttons").add(A),b.zoomText=e.text(n.rangeSelectorZoom,0,15).add(v),d.styledMode||(b.zoomText.css(k.labelStyle),t["stroke-width"]=p(t["stroke-width"],0)),b.buttonOptions.forEach(function(a,c){q[c]=e.button(a.text,0,0,function(d){var g=a.events&&a.events.click,e;g&&(e=g.call(a,d));!1!==e&&b.clickButton(c);b.isActive=!0},t,y&&y.hover,y&&y.select,y&&y.disabled).attr({"text-align":"center"}).add(v)}),
!1!==w&&(b.div=r=x("div",null,{position:"relative",height:0,zIndex:m}),f.parentNode.insertBefore(r,f),b.inputGroup=r=e.g("input-group").add(A),r.offset=0,b.drawInput("min"),b.drawInput("max")));b.zoomText[U]({x:p(D+K.x,D)});var V=p(D+K.x,D)+b.zoomText.getBBox().width+5;b.buttonOptions.forEach(function(a,b){q[b][U]({x:V});V+=q[b].width+p(k.buttonSpacing,5)});D=d.plotLeft-d.spacing[3];b.updateButtonStates();g&&this.titleCollision(d)&&"top"===E&&"right"===K.align&&K.y+v.getBBox().height-12<(g.y||0)+
g.height&&(O=-40);"left"===K.align?N=K.x-d.spacing[3]:"right"===K.align&&(N=K.x+O-d.spacing[1]);v.align({y:K.y,width:v.getBBox().width,align:K.align,x:N},!0,d.spacingBox);b.group.placed=T;b.buttonGroup.placed=T;!1!==w&&(O=g&&this.titleCollision(d)&&"top"===E&&"right"===u.align&&u.y-r.getBBox().height-12<(g.y||0)+g.height+d.spacing[0]?-40:0,"left"===u.align?N=D:"right"===u.align&&(N=-Math.max(d.axisOffset[1],-O)),r.align({y:u.y,width:r.getBBox().width,align:u.align,x:u.x+N-2},!0,d.spacingBox),f=r.alignAttr.translateX+
r.alignOptions.x-O+r.getBBox().x+2,g=r.alignOptions.width,n=v.alignAttr.translateX+v.getBBox().x,N=v.getBBox().width+20,(u.align===K.align||n+N>f&&f+g>n&&S<R+r.getBBox().height)&&r.attr({translateX:r.alignAttr.translateX+(d.axisOffset[1]>=-O?0:-O),translateY:r.alignAttr.translateY+v.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=T);b.group.align({verticalAlign:E},!0,d.spacingBox);a=b.group.getBBox().height+20;c=b.group.alignAttr.translateY;"bottom"===E&&
(H=I&&"bottom"===I.verticalAlign&&I.enabled&&!I.floating?H.legendHeight+p(I.margin,10):0,a=a+H-20,M=c-a-(h?0:k.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===E)h&&(M=0),d.titleOffset&&d.titleOffset[0]&&(M=d.titleOffset[0]),M+=d.margin[0]-d.spacing[0]||0;else if("middle"===E)if(R===S)M=0>R?c+void 0:c;else if(R||S)M=0>R||0>S?M-Math.min(R,S):c-a+NaN;b.group.translate(k.x,k.y+Math.floor(M));!1!==w&&(b.minInput.style.marginTop=b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+
"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,d=a.y,e=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;a=c?c.getBBox(!0).height+13+d:0;c=Math.min(f,e);if(0>f&&0>e||0<f&&0<e)a+=Math.abs(c);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;w(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var a=this,c=a.minInput,d=a.maxInput;
a.unMouseDown();a.unResize();A(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);I(a,function(b,c){b&&"chart"!==c&&(b.destroy?b.destroy():b.nodeType&&y(this[c]));b!==q.prototype[c]&&(a[c]=null)},this)}};k.prototype.minFromRange=function(){var a=this.range,c=a.type,d=this.max,e=this.chart.time,f=function(a,b){var d="year"===c?"FullYear":"Month",g=new e.Date(a),f=e.get(d,g);e.set(d,g,f+b);f===e.get(d,g)&&e.set("Date",g,0);return g.getTime()-a};if(m(a)){var h=
d-a;var k=a}else h=d+f(d,-a.count),this.chart&&(this.chart.fixedRange=d-h);var g=p(this.dataMin,Number.MIN_VALUE);m(h)||(h=g);h<=g&&(h=g,"undefined"===typeof k&&(k=f(h,a.count)),this.newMax=Math.min(h+k,this.dataMax));m(d)||(h=void 0);return h};e.RangeSelector||(t(a,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new q(this))}),t(a,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(m(c.deferredYTDClick)&&(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),
a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,c.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),t(a,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!E(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new q(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||
a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==d||this.extraTopMargin!==e)&&(this.isDirtyBox=!0)}),t(a,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),t(a,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=
a),this.extraBottomMargin&&(this.marginBottom+=a))}),a.prototype.callbacks.push(function(a){function b(){d=a.xAxis[0].getExtremes();m(d.min)&&e.render(d.min,d.max)}var d,e=a.rangeSelector;if(e){var f=t(a.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var h=t(a,"redraw",b);b()}t(a,"destroy",function(){e&&(h(),f())})}),e.RangeSelector=q)});E(t,"parts/Navigator.js",[t["parts/Globals.js"],t["parts/Utilities.js"],t["parts/Color.js"],t["parts/Scrollbar.js"]],function(e,a,q,t){function x(a){this.init(a)}
var v=a.addEvent,E=a.clamp,A=a.correctFloat,y=a.defined,u=a.destroyObjectProperties,h=a.erase,m=a.extend,w=a.find,I=a.isArray,p=a.isNumber,f=a.merge,d=a.pick,k=a.removeEvent,C=a.splat;a=q.parse;var b=e.Axis;q=e.Chart;var c=e.defaultOptions,l=e.hasTouch,z=e.isTouchDevice,P=e.Series,G=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,p);if(b.length)return Math[a].apply(0,b)};var Q="undefined"===typeof e.seriesTypes.areaspline?"line":"areaspline";m(c,{navigator:{height:40,
margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:Q,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",
[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",
gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});e.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height;return["M",-a-1,.5,"L",a,.5,"L",a,e+.5,"L",-a-1,e+.5,"L",-a-1,.5,"M",-b,4,"L",-b,e-3,"M",b-1,4,"L",b-1,e-3]};b.prototype.toFixedRange=function(a,b,c,e){var g=this.chart&&this.chart.fixedRange,f=(this.pointRange||0)/2;a=d(c,this.translate(a,
!0,!this.horiz));b=d(e,this.translate(b,!0,!this.horiz));var n=g&&(b-a)/g;y(c)||(a=A(a+f));y(e)||(b=A(b-f));.7<n&&1.3>n&&(e?a=b-g:b=a+g);p(a)&&p(b)||(a=b=void 0);return{min:a,max:b}};x.prototype={drawHandle:function(a,b,c,d){var g=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-g)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-g/2-1)})},drawOutline:function(a,
b,c,d){var g=this.navigatorOptions.maskInside,e=this.outline.strokeWidth(),f=e/2;e=e%2/2;var n=this.outlineHeight,r=this.scrollbarHeight,h=this.size,k=this.left-r,m=this.top;c?(k-=f,c=m+b+e,b=m+a+e,a=["M",k+n,m-r-e,"L",k+n,c,"L",k,c,"L",k,b,"L",k+n,b,"L",k+n,m+h+r].concat(g?["M",k+n,c-f,"L",k+n,b+f]:[])):(a+=k+r-e,b+=k+r-e,m+=f,a=["M",k,m,"L",a,m,"L",a,m+n,"L",b,m+n,"L",b,m,"L",k+h+2*r,m].concat(g?["M",a-f,m,"L",b+f,m]:[]));this.outline[d]({d:a})},drawMasks:function(a,b,c,d){var g=this.left,e=this.top,
f=this.height;if(c){var n=[g,g,g];var r=[e,e+a,e+b];var h=[f,f,f];var k=[a,b-a,this.size-b]}else n=[g,g+a,g+b],r=[e,e,e],h=[a,b-a,this.size-b],k=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:n[b],y:r[b],width:h[b],height:k[b]})})},renderElements:function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,h={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,g){a.shades[g]=
e.rect().addClass("highcharts-navigator-mask"+(1===g?"-inside":"-outside")).add(f);d.styledMode||a.shades[g].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===g&&h)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);
a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var g=b.handles;a.handles[c].attr({fill:g.backgroundColor,stroke:g.borderColor,"stroke-width":g.lineWidth}).css(h)}})},update:function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();f(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)},render:function(a,b,c,e){var g=this.chart,
f=this.scrollbarHeight,n,h=this.xAxis,r=h.pointRange||0;var k=h.fake?g.xAxis[0]:h;var m=this.navigatorEnabled,l,q=this.rendered;var t=g.inverted;var u=g.xAxis[0].minRange,B=g.xAxis[0].options.maxRange;if(!this.hasDragged||y(c)){a=A(a-r/2);b=A(b+r/2);if(!p(a)||!p(b))if(q)c=0,e=d(h.width,k.width);else return;this.left=d(h.left,g.plotLeft+f+(t?g.plotWidth:0));this.size=l=n=d(h.len,(t?g.plotHeight:g.plotWidth)-2*f);g=t?f:n+2*f;c=d(c,h.toPixels(a,!0));e=d(e,h.toPixels(b,!0));p(c)&&Infinity!==Math.abs(c)||
(c=0,e=g);a=h.toValue(c,!0);b=h.toValue(e,!0);var v=Math.abs(A(b-a));v<u?this.grabbedLeft?c=h.toPixels(b-u-r,!0):this.grabbedRight&&(e=h.toPixels(a+u+r,!0)):y(B)&&A(v-r)>B&&(this.grabbedLeft?c=h.toPixels(b-B-r,!0):this.grabbedRight&&(e=h.toPixels(a+B+r,!0)));this.zoomedMax=E(Math.max(c,e),0,l);this.zoomedMin=E(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,e),0,l);this.range=this.zoomedMax-this.zoomedMin;l=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);m&&(this.navigatorGroup.attr({visibility:"visible"}),
q=q&&!this.hasDragged?"animate":"attr",this.drawMasks(c,l,t,q),this.drawOutline(c,l,t,q),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,t,q),this.drawHandle(l,1,t,q)));this.scrollbar&&(t?(t=this.top-f,k=this.left-f+(m||!k.opposite?0:(k.titleOffset||0)+k.axisTitleMargin),f=n+2*f):(t=this.top+(m?this.height:-f),k=this.left-f),this.scrollbar.position(k,t,g,f),this.scrollbar.setRange(this.zoomedMin/(n||1),this.zoomedMax/(n||1)));this.rendered=!0}},addMouseEvents:function(){var a=this,b=a.chart,
c=b.container,d=[],e,f;a.mouseMoveHandler=e=function(b){a.onMouseMove(b)};a.mouseUpHandler=f=function(b){a.onMouseUp(b)};d=a.getPartsEvents("mousedown");d.push(v(b.renderTo,"mousemove",e),v(c.ownerDocument,"mouseup",f));l&&(d.push(v(b.renderTo,"touchmove",e),v(c.ownerDocument,"touchend",f)),d.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=d;a.series&&a.series[0]&&d.push(v(a.series[0].xAxis,"foundExtremes",function(){b.navigator.modifyNavigatorAxisExtremes()}))},getPartsEvents:function(a){var b=
this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(g,e){c.push(v(g.element,a,function(a){b[d+"Mousedown"](a,e)}))})});return c},shadesMousedown:function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,g=this.left,f=this.size,n=this.range,h=a.chartX;c.inverted&&(h=a.chartY,g=this.top);if(1===b)this.grabbedCenter=h,this.fixedWidth=n,this.dragOffset=h-e;else{a=h-g-n/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+n>=f)if(a=f-n,this.reversedExtremes){a-=
n;var k=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;a!==e&&(this.fixedWidth=n,b=d.toFixedRange(a,a+n,k,m),y(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=
this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null},onMouseMove:function(a){var b=this,c=b.chart,g=b.left,f=b.navigatorSize,h=b.range,k=b.dragOffset,m=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,m&&(g=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-g,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-g)):b.grabbedCenter&&(b.hasDragged=!0,c<k?c=k:c>f+k-h&&(c=f+k-h),b.render(0,0,c-k,c-k+h)),b.hasDragged&&
b.scrollbar&&d(b.scrollbar.options.liveRedraw,e.svg&&!z&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))},onMouseUp:function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,g=b.inverted,f=this.rendered&&!this.hasDragged?"animate":"attr",h=Math.round(this.zoomedMax),k=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var m=this.fixedExtreme;
else if(this.zoomedMax===this.otherHandlePos)var l=this.fixedExtreme;this.zoomedMax===this.size&&(l=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(m=this.reversedExtremes?d.dataMax:d.dataMin);c=c.toFixedRange(this.zoomedMin,this.zoomedMax,m,l);y(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=
this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(k,h,g,f),this.outline&&this.drawOutline(k,h,g,f),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(k,0,g,f),this.drawHandle(h,1,g,f)))},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()},
removeBaseSeriesEvents:function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){k(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&k(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(a){var c=a.options,e=c.navigator,g=e.enabled,h=c.scrollbar,k=h.enabled;c=g?e.height:0;var m=k?h.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=c;this.scrollbarHeight=m;
this.scrollbarEnabled=k;this.navigatorEnabled=g;this.navigatorOptions=e;this.scrollbarOptions=h;this.outlineHeight=c+m;this.opposite=d(e.opposite,!(g||!a.inverted));var l=this;g=l.baseSeries;h=a.xAxis.length;k=a.yAxis.length;var p=g&&g[0]&&g[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new b(a,f({breaks:p.options.breaks,ordinal:p.options.ordinal},e.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:h,isInternal:!0,offset:0,keepOrdinalPadding:!0,
startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[m,0,-m,0],width:c}:{offsets:[0,-m,0,m],height:c})),l.yAxis=new b(a,f(e.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:k,isInternal:!0,zoomEnabled:!1},a.inverted?{width:c}:{height:c})),g||e.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&(l.unbindRedraw=v(a,"beforeRedraw",function(){0<a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||
!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):l.xAxis={translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*m,g=G("min",d.options.min,e.dataMin);d=G("max",d.options.max,e.dataMax)-g;return c?b*d/f+g:f*(b-g)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)},toFixedRange:b.prototype.toFixedRange,fake:!0};a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new t(a.renderer,f(a.options.scrollbar,{margin:l.navigatorEnabled?
0:10,vertical:a.inverted}),a),v(l.scrollbar,"changed",function(b){var c=l.size,d=c*this.to;c*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){l.onMouseUp(b)})}));l.addBaseSeriesEvents();l.addChartEvents()},getUnionExtremes:function(a){var b=this.chart.xAxis[0],c=this.xAxis,e=c.options,f=b.options,g;a&&null===b.dataMin||(g={dataMin:d(e&&e.min,G("min",f.min,b.dataMin,c.dataMin,c.min)),
dataMax:d(e&&e.max,G("max",f.max,b.dataMax,c.dataMax,c.max))});return g},setBaseSeries:function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?w(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.fake&&this.updateNavigatorSeries(!0,b)},updateNavigatorSeries:function(a,
b){var e=this,g=e.chart,h=e.baseSeries,n,l,p=e.navigatorOptions.series,q,t={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},u=e.series=(e.series||[]).filter(function(a){var b=a.baseSeries;return 0>h.indexOf(b)?(b&&(k(b,"updatedData",e.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});h&&h.length&&h.forEach(function(a){var k=a.navigatorSeries,
r=m({color:a.color,visible:a.visible},I(p)?c.navigator.series:p);k&&!1===e.navigatorOptions.adaptToUpdatedData||(t.name="Navigator "+h.length,n=a.options||{},q=n.navigatorOptions||{},l=f(n,t,r,q),l.pointRange=d(r.pointRange,q.pointRange,c.plotOptions[l.type||"line"].pointRange),r=q.data||r.data,e.hasNavigatorData=e.hasNavigatorData||!!r,l.data=r||n.data&&n.data.slice(0),k&&k.options?k.update(l,b):(a.navigatorSeries=g.initSeries(l),a.navigatorSeries.baseSeries=a,u.push(a.navigatorSeries)))});if(p.data&&
(!h||!h.length)||I(p))e.hasNavigatorData=!1,p=C(p),p.forEach(function(a,b){t.name="Navigator "+(u.length+1);l=f(c.navigator.series,{color:g.series[b]&&!g.series[b].options.isInternal&&g.series[b].color||g.options.colors[b]||g.options.colors[0]},t,a);l.data=a.data;l.data&&(e.hasNavigatorData=!0,u.push(g.initSeries(l)))});a&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&v(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){v(b,
"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&v(b,"updatedData",this.updatedDataHandler);v(b,"remove",function(){this.navigatorSeries&&(h(a.series,this.navigatorSeries),y(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)},getBaseSeriesMin:function(a){return this.baseSeries.reduce(function(a,
b){return Math.min(a,b.xData?b.xData[0]:a)},a)},modifyNavigatorAxisExtremes:function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))},modifyBaseAxisExtremes:function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,e=b.dataMax;b=b.max-b.min;var f=a.stickToMin,h=a.stickToMax,k=d(this.options.overscroll,0),l=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==
this.eventArgs.trigger){if(f){var q=c;var t=q+b}h&&(t=e+k,f||(q=Math.max(t-b,a.getBaseSeriesMin(l&&l.xData?l.xData[0]:-Number.MAX_VALUE))));m&&(f||h)&&p(q)&&(this.min=this.userMin=q,this.max=this.userMax=t)}a.stickToMin=a.stickToMax=null},updatedDataHandler:function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=p(this.xAxis.min)&&this.xAxis.min<=
c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(v(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||a.scrollbar&&this.xAxis[0]);b&&a.render(b.min,b.max)}),v(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";
this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(h(this.chart.xAxis,this.xAxis),h(this.chart.axes,this.xAxis));this.yAxis&&(h(this.chart.yAxis,this.yAxis),h(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&
this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){u(a)},this)}};e.Navigator||(e.Navigator=x,v(b,"zoom",function(a){var b=this.chart.options,c=b.chart.zoomType,d=b.chart.pinchType,e=b.navigator;b=b.rangeSelector;this.isXAxis&&(e&&e.enabled||b&&b.enabled)&&("y"===c?a.zoomed=!1:(!z&&"xy"===c||z&&"xy"===d)&&this.options.range&&(c=this.previousZoom,y(a.newMin)?this.previousZoom=[this.min,this.max]:c&&(a.newMin=c[0],a.newMax=c[1],delete this.previousZoom)));"undefined"!==
typeof a.zoomed&&a.preventDefault()}),v(q,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!z&&"x"===a.chart.zoomType||z&&"x"===a.chart.pinchType))return!1}),v(q,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new x(this)}),v(q,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var e=b.xAxis;var f=b.yAxis;var h=b.scrollbarHeight;
this.inverted?(b.left=b.opposite?this.chartWidth-h-b.height:this.spacing[3]+h,b.top=this.plotTop+h):(b.left=this.plotLeft+h,b.top=b.navigatorOptions.top||this.chartHeight-b.height-h-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+d(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));e&&f&&(this.inverted?e.options.left=f.options.left=b.left:e.options.top=f.options.top=b.top,e.setAxisSize(),
f.setAxisSize())}}),v(q,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(f(!0,this.options.navigator,b),f(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),v(q,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new x(this),d(a.redraw,!0)&&this.redraw(a.animation))}),v(q,"afterAddSeries",
function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),v(P,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),q.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}))});E(t,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map