/*
 Highmaps JS v8.0.0 (2020-02-16)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(z){f(z);f.Highcharts=z;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function z(c,a,f,n){c.hasOwnProperty(a)||(c[a]=n.apply(null,f))}f=f?f._modules:{};z(f,"parts-map/MapAxis.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.addEvent,n=a.pick;c=c.Axis;f(c,"getSeriesExtremes",
function(){var a=[];this.isXAxis&&(this.series.forEach(function(c,p){c.useMapGeometry&&(a[p]=c.xData,c.xData=[])}),this.seriesXData=a)});f(c,"afterGetSeriesExtremes",function(){var a=this.seriesXData,c;if(this.isXAxis){var f=n(this.dataMin,Number.MAX_VALUE);var A=n(this.dataMax,-Number.MAX_VALUE);this.series.forEach(function(p,t){p.useMapGeometry&&(f=Math.min(f,n(p.minX,f)),A=Math.max(A,n(p.maxX,A)),p.xData=a[t],c=!0)});c&&(this.dataMin=f,this.dataMax=A);delete this.seriesXData}});f(c,"afterSetAxisTranslation",
function(){var a=this.chart;var c=a.plotWidth/a.plotHeight;a=a.xAxis[0];var f;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(a){a.preserveAspectRatio&&(f=!0)});if(f&&(this.transA=a.transA=Math.min(this.transA,a.transA),c/=(a.max-a.min)/(this.max-this.min),c=1>c?this:a,a=(c.max-c.min)*c.transA,c.pixelPadding=c.len-a,c.minPixelPadding=c.pixelPadding/2,a=c.fixTo)){a=a[1]-c.toValue(a[0],!0);a*=c.transA;if(Math.abs(a)>c.minPixelPadding||c.min===c.dataMin&&c.max===c.dataMax)a=
0;c.minPixelPadding-=a}});f(c,"render",function(){this.fixTo=null})});z(f,"parts-map/ColorSeriesMixin.js",[f["parts/Globals.js"]],function(c){c.colorPointMixin={setVisible:function(a){var c=this,f=a?"show":"hide";c.visible=c.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(c[a])c[a][f]()})}};c.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,c=this.options.nullColor,f=this.colorAxis,p=this.colorKey;(this.data.length?this.data:this.points).forEach(function(t){var A=
t.getNestedProperty(p);if(A=t.options.color||(t.isNull?c:f&&"undefined"!==typeof A?f.toColor(A,t):t.color||a.color))t.color=A})}}});z(f,"parts-map/ColorAxis.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){"";var f=a.addEvent,n=a.erase,p=a.extend,t=a.isNumber,x=a.merge,y=a.pick,q=a.splat,h=c.Axis;a=c.Chart;var d=c.Series,g=c.Point,k=c.color,v=c.Legend,u=c.LegendSymbolMixin,l=c.colorPointMixin,r=c.noop;p(d.prototype,c.colorSeriesMixin);p(g.prototype,l);a.prototype.collectionsWithUpdate.push("colorAxis");
a.prototype.collectionsWithInit.colorAxis=[a.prototype.addColorAxis];var b=c.ColorAxis=function(){this.init.apply(this,arguments)};p(b.prototype,h.prototype);p(b.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup",
"legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(h.prototype.keepProps),init:function(e,b){this.coll="colorAxis";var m=this.buildOptions.call(e,this.defaultColorAxisOptions,b);h.prototype.init.call(this,e,m);b.dataClasses&&this.initDataClasses(b);this.initStops();this.horiz=!m.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(e){var b=this.chart,w,d=0,c=b.options.chart.colorCount,a=this.options,g=e.dataClasses.length;this.dataClasses=w=[];
this.legendItems=[];e.dataClasses.forEach(function(e,m){e=x(e);w.push(e);if(b.styledMode||!e.color)"category"===a.dataClassColor?(b.styledMode||(m=b.options.colors,c=m.length,e.color=m[d]),e.colorIndex=d,d++,d===c&&(d=0)):e.color=k(a.minColor).tweenTo(k(a.maxColor),2>g?.5:m/(g-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return h.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||
[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(e){e.color=k(e[1])})},buildOptions:function(e,b){var m=this.options.legend,d=b.layout?"vertical"!==b.layout:"vertical"!==m.layout;return x(e,{side:d?2:1,reversed:!d},b,{opposite:!d,showEmpty:!1,title:null,visible:m.enabled&&(b?!1!==b.visible:!0)})},setOptions:function(e){h.prototype.setOptions.call(this,e);this.options.crosshair=this.options.marker},setAxisSize:function(){var e=this.legendSymbol,b=this.chart,d=b.options.legend||
{},B,c;e?(this.left=d=e.attr("x"),this.top=B=e.attr("y"),this.width=c=e.attr("width"),this.height=e=e.attr("height"),this.right=b.chartWidth-d-c,this.bottom=b.chartHeight-B-e,this.len=this.horiz?c:e,this.pos=this.horiz?d:B):this.len=(this.horiz?d.symbolWidth:d.symbolHeight)||this.defaultLegendLength},normalizedValue:function(e){this.isLog&&(e=this.val2lin(e));return 1-(this.max-e)/(this.max-this.min||1)},toColor:function(e,b){var m=this.stops,d=this.dataClasses,c;if(d)for(c=d.length;c--;){var a=d[c];
var g=a.from;m=a.to;if(("undefined"===typeof g||e>=g)&&("undefined"===typeof m||e<=m)){var k=a.color;b&&(b.dataClass=c,b.colorIndex=a.colorIndex);break}}else{e=this.normalizedValue(e);for(c=m.length;c--&&!(e>m[c][0]););g=m[c]||m[c+1];m=m[c+1]||g;e=1-(m[0]-e)/(m[0]-g[0]||1);k=g.color.tweenTo(m.color,e)}return k},getOffset:function(){var e=this.legendGroup,b=this.chart.axisOffset[this.side];e&&(this.axisParent=e,h.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=
this.width),this.chart.axisOffset[this.side]=b)},setLegendColor:function(){var e=this.reversed;var b=e?1:0;e=e?0:1;b=this.horiz?[b,0,e,0]:[0,e,0,b];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}},drawLegendSymbol:function(e,b){var m=e.padding,d=e.options,c=this.horiz,a=y(d.symbolWidth,c?this.defaultLegendLength:12),g=y(d.symbolHeight,c?12:this.defaultLegendLength),k=y(d.labelPadding,c?16:30);d=y(d.itemDistance,10);this.setLegendColor();b.legendSymbol=this.chart.renderer.rect(0,
e.baseline-11,a,g).attr({zIndex:1}).add(b.legendGroup);this.legendItemWidth=a+m+(c?d:k);this.legendItemHeight=g+m+(c?k:0)},setState:function(e){this.series.forEach(function(b){b.setState(e)})},visible:!0,setVisible:r,getSeriesExtremes:function(){var e=this.series,b=e.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;b--;){var a=e[b];var g=a.colorKey=y(a.options.colorKey,a.colorKey,a.pointValKey,a.zoneAxis,"y");var k=a.pointArrayMap;var D=a[g+"Min"]&&a[g+"Max"];if(a[g+"Data"])var l=a[g+"Data"];
else if(k){l=[];k=k.indexOf(g);var p=a.yData;if(0<=k&&p)for(c=0;c<p.length;c++)l.push(y(p[c][k],p[c]))}else l=a.yData;D?(a.minColorValue=a[g+"Min"],a.maxColorValue=a[g+"Max"]):(d.prototype.getExtremes.call(a,l),a.minColorValue=a.dataMin,a.maxColorValue=a.dataMax);"undefined"!==typeof a.minColorValue&&(this.dataMin=Math.min(this.dataMin,a.minColorValue),this.dataMax=Math.max(this.dataMax,a.maxColorValue));D||d.prototype.getExtremes.call(a)}},drawCrosshair:function(e,b){var d=b&&b.plotX,m=b&&b.plotY,
a=this.pos,c=this.len;if(b){var g=this.toPixels(b.getNestedProperty(b.series.colorKey));g<a?g=a-2:g>a+c&&(g=a+c+2);b.plotX=g;b.plotY=this.len-g;h.prototype.drawCrosshair.call(this,e,b);b.plotX=d;b.plotY=m;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(b){var e=b.translatedValue;return t(e)?
this.horiz?["M",e-4,this.top-6,"L",e+4,this.top-6,e,this.top,"Z"]:["M",this.left,e,"L",this.left-6,e+6,this.left-6,e-6,"Z"]:h.prototype.getPlotLinePath.apply(this,arguments)},update:function(b,d){var e=this.chart,m=e.legend,a=this.buildOptions.call(e,{},b);this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&m.allItems||this.dataClasses)&&this.destroyItems();e.options[this.coll]=x(this.userOptions,a);h.prototype.update.call(this,a,d);this.legendItem&&(this.setLegendColor(),m.colorizeItem(this,
!0))},destroyItems:function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(e){b.legend.destroyItem(e)});b.isDirtyLegend=!0},remove:function(b){this.destroyItems();h.prototype.remove.call(this,b)},getDataClassLegendSymbols:function(){var b=this,d=this.chart,a=this.legendItems,c=d.options.legend,g=c.valueDecimals,k=c.valueSuffix||"",l;a.length||this.dataClasses.forEach(function(e,m){var c=!0,w=e.from,B=e.to,C=d.numberFormatter;l="";
"undefined"===typeof w?l="< ":"undefined"===typeof B&&(l="> ");"undefined"!==typeof w&&(l+=C(w,g)+k);"undefined"!==typeof w&&"undefined"!==typeof B&&(l+=" - ");"undefined"!==typeof B&&(l+=C(B,g)+k);a.push(p({chart:d,name:l,options:{},drawLegendSymbol:u.drawRectangle,visible:!0,setState:r,isDataClass:!0,setVisible:function(){c=this.visible=!c;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===m&&b.setVisible(c)})});d.legend.colorizeItem(this,c)}},e))});return a},beforePadding:!1,
name:""});["fill","stroke"].forEach(function(b){c.Fx.prototype[b+"Setter"]=function(){this.elem.attr(b,k(this.start).tweenTo(k(this.end),this.pos),null,!0)}});f(a,"afterGetAxes",function(){var e=this,d=e.options;this.colorAxis=[];d.colorAxis&&(d.colorAxis=q(d.colorAxis),d.colorAxis.forEach(function(d,a){d.index=a;new b(e,d)}))});f(d,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});f(v,"afterGetAllItems",function(b){var e=
[],d,a;(this.chart.colorAxis||[]).forEach(function(a){(d=a.options)&&d.showInLegend&&(d.dataClasses&&d.visible?e=e.concat(a.getDataClassLegendSymbols()):d.visible&&e.push(a),a.series.forEach(function(e){if(!e.options.showInLegend||d.dataClasses)"point"===e.options.legendType?e.points.forEach(function(e){n(b.allItems,e)}):n(b.allItems,e)}))});for(a=e.length;a--;)b.allItems.unshift(e[a])});f(v,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});
f(v,"afterUpdate",function(){var b=this.chart.colorAxis;b&&b.forEach(function(b,e,d){b.update({},d)})});f(d,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});z(f,"parts-map/ColorMapSeriesMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.defined;a=c.noop;var n=c.seriesTypes;c.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==
this.value},setState:function(a){c.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})}};c.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:a,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:n.column.prototype.pointAttribs,colorAttribs:function(a){var c={};f(a.color)&&(c[this.colorProp||"fill"]=a.color);return c}}});z(f,"parts-map/MapNavigation.js",
[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){function f(d){d&&(d.preventDefault&&d.preventDefault(),d.stopPropagation&&d.stopPropagation(),d.cancelBubble=!0)}function n(d){this.init(d)}var p=a.addEvent,t=a.extend,x=a.merge,y=a.objectEach,q=a.pick;a=c.Chart;var h=c.doc;n.prototype.init=function(d){this.chart=d;d.mapNavButtons=[]};n.prototype.update=function(d){var a=this.chart,c=a.options.mapNavigation,h,u,l,r,b,e=function(b){this.handler.call(a,b);f(b)},m=a.mapNavButtons;d&&(c=a.options.mapNavigation=
x(a.options.mapNavigation,d));for(;m.length;)m.pop().destroy();q(c.enableButtons,c.enabled)&&!a.renderer.forExport&&y(c.buttons,function(d,g){h=x(c.buttonOptions,d);a.styledMode||(u=h.theme,u.style=x(h.theme.style,h.style),r=(l=u.states)&&l.hover,b=l&&l.select);d=a.renderer.button(h.text,0,0,e,u,r,b,0,"zoomIn"===g?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[g]).attr({width:h.width,height:h.height,title:a.options.lang[g],padding:h.padding,
zIndex:5}).add();d.handler=h.onclick;p(d.element,"dblclick",f);m.push(d);var w=h,k=p(a,"load",function(){d.align(t(w,{width:d.width,height:2*d.height}),null,w.alignTo);k()})});this.updateEvents(c)};n.prototype.updateEvents=function(d){var a=this.chart;q(d.enableDoubleClickZoom,d.enabled)||d.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||p(a.container,"dblclick",function(d){a.pointer.onContainerDblClick(d)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());q(d.enableMouseWheelZoom,
d.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||p(a.container,"undefined"===typeof h.onmousewheel?"DOMMouseScroll":"mousewheel",function(d){a.pointer.onContainerMouseWheel(d);f(d);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};t(a.prototype,{fitToBox:function(d,a){[["x","width"],["y","height"]].forEach(function(c){var g=c[0];c=c[1];d[g]+d[c]>a[g]+a[c]&&(d[c]>a[c]?(d[c]=a[c],d[g]=a[g]):d[g]=a[g]+a[c]-d[c]);d[c]>a[c]&&(d[c]=a[c]);d[g]<a[g]&&(d[g]=a[g])});
return d},mapZoom:function(d,a,c,f,h){var g=this.xAxis[0],k=g.max-g.min,b=q(a,g.min+k/2),e=k*d;k=this.yAxis[0];var m=k.max-k.min,w=q(c,k.min+m/2);m*=d;b=this.fitToBox({x:b-e*(f?(f-g.pos)/g.len:.5),y:w-m*(h?(h-k.pos)/k.len:.5),width:e,height:m},{x:g.dataMin,y:k.dataMin,width:g.dataMax-g.dataMin,height:k.dataMax-k.dataMin});e=b.x<=g.dataMin&&b.width>=g.dataMax-g.dataMin&&b.y<=k.dataMin&&b.height>=k.dataMax-k.dataMin;f&&(g.fixTo=[f-g.pos,a]);h&&(k.fixTo=[h-k.pos,c]);"undefined"===typeof d||e?(g.setExtremes(void 0,
void 0,!1),k.setExtremes(void 0,void 0,!1)):(g.setExtremes(b.x,b.x+b.width,!1),k.setExtremes(b.y,b.y+b.height,!1));this.redraw()}});p(a,"beforeRender",function(){this.mapNavigation=new n(this);this.mapNavigation.update()});c.MapNavigation=n});z(f,"parts-map/MapPointer.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.extend,n=a.pick;a=a.wrap;c=c.Pointer;f(c.prototype,{onContainerDblClick:function(a){var c=this.chart;a=this.normalize(a);c.options.mapNavigation.enableDoubleClickZoomTo?
c.pointer.inClass(a.target,"highcharts-tracker")&&c.hoverPoint&&c.hoverPoint.zoomTo():c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(.5,c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var c=this.chart;a=this.normalize(a);var f=a.detail||-(a.wheelDelta/120);c.isInsidePlot(a.chartX-c.plotLeft,a.chartY-c.plotTop)&&c.mapZoom(Math.pow(c.options.mapNavigation.mouseWheelSensitivity,f),c.xAxis[0].toValue(a.chartX),c.yAxis[0].toValue(a.chartY),
a.chartX,a.chartY)}});a(c.prototype,"zoomOption",function(a){var c=this.chart.options.mapNavigation;n(c.enableTouchZoom,c.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});a(c.prototype,"pinchTranslate",function(a,c,f,n,q,h,d){a.call(this,c,f,n,q,h,d);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=n.scaleX>n.scaleY,this.pinchTranslateDirection(!a,c,f,n,q,h,d,a?n.scaleX:n.scaleY))})});z(f,"parts-map/MapSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],
function(c,a){var f=a.extend,n=a.getNestedProperty,p=a.isArray,t=a.isNumber,x=a.merge,y=a.objectEach,q=a.pick,h=a.seriesType,d=a.splat,g=c.colorMapPointMixin,k=c.noop,v=c.fireEvent,u=c.Point,l=c.Series,r=c.seriesTypes;h("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},turboThreshold:0,
allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},x(c.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:k,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(b){b=l.prototype.setOptions.call(this,b);var e=b.joinBy;null===e&&(e="_i");e=this.joinBy=d(e);e[1]||(e[1]=e[0]);return b},getBox:function(b){var e=
Number.MAX_VALUE,a=-e,d=e,g=-e,k=e,f=e,h=this.xAxis,l=this.yAxis,r;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=c.splitPath(b.path));var m=b.path||[],w=m.length,B=!1,h=-e,l=e,C=-e,E=e,D=b.properties;if(!b._foundBox){for(;w--;)t(m[w])&&(B?(h=Math.max(h,m[w]),l=Math.min(l,m[w])):(C=Math.max(C,m[w]),E=Math.min(E,m[w])),B=!B);b._midX=l+(h-l)*q(b.middleX,D&&D["hc-middle-x"],.5);b._midY=E+(C-E)*q(b.middleY,D&&D["hc-middle-y"],.5);b._maxX=h;b._minX=l;b._maxY=C;b._minY=E;b.labelrank=
q(b.labelrank,(h-l)*(C-E));b._foundBox=!0}a=Math.max(a,b._maxX);d=Math.min(d,b._minX);g=Math.max(g,b._maxY);k=Math.min(k,b._minY);f=Math.min(b._maxX-b._minX,b._maxY-b._minY,f);r=!0}});r&&(this.minY=Math.min(k,q(this.minY,e)),this.maxY=Math.max(g,q(this.maxY,-e)),this.minX=Math.min(d,q(this.minX,e)),this.maxX=Math.max(a,q(this.maxX,-e)),h&&"undefined"===typeof h.options.minRange&&(h.minRange=Math.min(5*f,(this.maxX-this.minX)/5,h.minRange||e)),l&&"undefined"===typeof l.options.minRange&&(l.minRange=
Math.min(5*f,(this.maxY-this.minY)/5,l.minRange||e)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){l.prototype.getExtremes.call(this,this.valueData);this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);this.valueMin=this.dataMin;this.valueMax=this.dataMax;this.dataMin=this.minY;this.dataMax=this.maxY},translatePath:function(b){var e=!1,a=this.xAxis,d=this.yAxis,c=a.min,g=a.transA;a=a.minPixelPadding;var k=d.min,f=d.transA;d=d.minPixelPadding;var h,
l=[];if(b)for(h=b.length;h--;)t(b[h])?(l[h]=e?(b[h]-c)*g+a:(b[h]-k)*f+d,e=!e):l[h]=b[h];return l},setData:function(b,e,a,d){var g=this.options,m=this.chart.options.chart,w=m&&m.map,k=g.mapData,h=this.joinBy,f=g.keys||this.pointArrayMap,r=[],u={},v=this.chart.mapTransforms;!k&&w&&(k="string"===typeof w?c.maps[w]:w);b&&b.forEach(function(e,a){var d=0;if(t(e))b[a]={value:e};else if(p(e)){b[a]={};!g.keys&&e.length>f.length&&"string"===typeof e[0]&&(b[a]["hc-key"]=e[0],++d);for(var m=0;m<f.length;++m,
++d)f[m]&&"undefined"!==typeof e[d]&&(0<f[m].indexOf(".")?c.Point.prototype.setNestedProperty(b[a],e[d],f[m]):b[a][f[m]]=e[d])}h&&"_i"===h[0]&&(b[a]._i=a)});this.getBox(b);(this.chart.mapTransforms=v=m&&m.mapTransforms||k&&k["hc-transform"]||v)&&y(v,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(k){"FeatureCollection"===k.type&&(this.mapTitle=k.title,k=c.geojson(k,this.type,this));this.mapData=k;this.mapMap={};for(v=0;v<k.length;v++)m=k[v],w=m.properties,
m._i=v,h[0]&&w&&w[h[0]]&&(m[h[0]]=w[h[0]]),u[m[h[0]]]=m;this.mapMap=u;if(b&&h[1]){var q=h[1];b.forEach(function(b){b=n(q,b);u[b]&&r.push(u[b])})}if(g.allAreas){this.getBox(k);b=b||[];if(h[1]){var A=h[1];b.forEach(function(b){r.push(n(A,b))})}r="|"+r.map(function(b){return b&&b[h[0]]}).join("|")+"|";k.forEach(function(e){h[0]&&-1!==r.indexOf("|"+e[h[0]]+"|")||(b.push(x(e,{value:null})),d=!1)})}else this.getBox(r)}l.prototype.setData.call(this,b,e,a,d)},drawGraph:k,drawDataLabels:k,doFullTranslate:function(){return this.isDirtyData||
this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var b=this,e=b.xAxis,a=b.yAxis,d=b.doFullTranslate();b.generatePoints();b.data.forEach(function(c){t(c._midX)&&t(c._midY)&&(c.plotX=e.toPixels(c._midX,!0),c.plotY=a.toPixels(c._midY,!0));d&&(c.shapeType="path",c.shapeArgs={d:b.translatePath(c.path)})});v(b,"afterTranslate")},pointAttribs:function(b,e){e=b.series.chart.styledMode?this.colorAttribs(b):r.column.prototype.pointAttribs.call(this,b,e);e["stroke-width"]=
q(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return e},drawPoints:function(){var b=this,e=b.xAxis,a=b.yAxis,d=b.group,c=b.chart,g=c.renderer,k=this.baseTrans;b.transformGroup||(b.transformGroup=g.g().attr({scaleX:1,scaleY:1}).add(d),b.transformGroup.survive=!0);if(b.doFullTranslate())c.hasRendered&&!c.styledMode&&b.points.forEach(function(e){e.shapeArgs&&(e.shapeArgs.fill=b.pointAttribs(e,e.state).fill)}),b.group=b.transformGroup,r.column.prototype.drawPoints.apply(b),
b.group=d,b.points.forEach(function(e){if(e.graphic){var a="";e.name&&(a+="highcharts-name-"+e.name.replace(/ /g,"-").toLowerCase());e.properties&&e.properties["hc-key"]&&(a+=" highcharts-key-"+e.properties["hc-key"].toLowerCase());a&&e.graphic.addClass(a);c.styledMode&&e.graphic.css(b.pointAttribs(e,e.selected&&"select"||void 0))}}),this.baseTrans={originX:e.min-e.minPixelPadding/e.transA,originY:a.min-a.minPixelPadding/a.transA+(a.reversed?0:a.len/a.transA),transAX:e.transA,transAY:a.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var h=e.transA/k.transAX;var f=a.transA/k.transAY;var l=e.toPixels(k.originX,!0);var p=a.toPixels(k.originY,!0);.99<h&&1.01>h&&.99<f&&1.01>f&&(f=h=1,l=Math.round(l),p=Math.round(p));var v=this.transformGroup;if(c.renderer.globalAnimation){var u=v.attr("translateX");var n=v.attr("translateY");var t=v.attr("scaleX");var A=v.attr("scaleY");v.attr({animator:0}).animate({animator:1},{step:function(b,e){v.attr({translateX:u+(l-u)*e.pos,translateY:n+(p-n)*e.pos,scaleX:t+
(h-t)*e.pos,scaleY:A+(f-A)*e.pos})}})}else v.attr({translateX:l,translateY:p,scaleX:h,scaleY:f})}c.styledMode||d.element.setAttribute("stroke-width",q(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(h||1));this.drawMapDataLabels()},drawMapDataLabels:function(){l.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var b=this,e=l.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?
setTimeout(function(){e.call(b)}):e.call(b)},animate:function(b){var e=this.options.animation,a=this.group,d=this.xAxis,c=this.yAxis,g=d.pos,h=c.pos;this.chart.renderer.isSVG&&(!0===e&&(e={duration:1E3}),b?a.attr({translateX:g+d.len/2,translateY:h+c.len/2,scaleX:.001,scaleY:.001}):(a.animate({translateX:g,translateY:h,scaleX:1,scaleY:1},e),this.animate=null))},animateDrilldown:function(b){var e=this.chart.plotBox,a=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],d=a.bBox,c=this.chart.options.drilldown.animation;
b||(b=Math.min(d.width/e.width,d.height/e.height),a.shapeArgs={scaleX:b,scaleY:b,translateX:d.x,translateY:d.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(a.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},c)}),this.animate=null)},drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,animateDrillupFrom:function(b){r.column.prototype.animateDrillupFrom.call(this,b)},animateDrillupTo:function(b){r.column.prototype.animateDrillupTo.call(this,b)}}),f({applyOptions:function(b,
e){var a=this.series;b=u.prototype.applyOptions.call(this,b,e);e=a.joinBy;a.mapData&&a.mapMap&&(e=u.prototype.getNestedProperty.call(b,e[1]),(e="undefined"!==typeof e&&a.mapMap[e])?(a.xyFromShape&&(b.x=e._midX,b.y=e._midY),f(b,e)):b.value=b.value||null);return b},onMouseOver:function(b){a.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)u.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var b=this.series;b.xAxis.setExtremes(this._minX,
this._maxX,!1);b.yAxis.setExtremes(this._minY,this._maxY,!1);b.chart.redraw()}},g));""});z(f,"parts-map/MapLineSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){a=a.seriesType;var f=c.seriesTypes;a("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,c){a=f.map.prototype.pointAttribs.call(this,a,c);a.fill=this.options.fillColor;return a},drawLegendSymbol:f.line.prototype.drawLegendSymbol});
""});z(f,"parts-map/MapPointSeries.js",[f["parts/Globals.js"]],function(c){var a=c.merge,f=c.Point,n=c.Series;c=c.seriesType;c("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){n.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(c,n){c="undefined"!==typeof c.lat&&"undefined"!==
typeof c.lon?a(c,this.series.chart.fromLatLonToPoint(c)):c;return f.prototype.applyOptions.call(this,c,n)}});""});z(f,"parts-more/BubbleLegend.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.addEvent,n=a.arrayMax,p=a.arrayMin,t=a.isNumber,x=a.merge,y=a.objectEach,q=a.pick,h=a.stableSort,d=a.wrap,g=c.Series,k=c.Legend,v=c.Chart,u=c.color,l=c.noop,r=c.setOptions;r({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,
connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});c.BubbleLegend=function(b,e){this.init(b,e)};c.BubbleLegend.prototype={init:function(b,e){this.options=b;this.visible=!0;this.chart=
e.chart;this.legend=e},setState:l,addToLegend:function(b){b.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(b){var e=this.chart,a=this.options,d=q(b.options.itemDistance,20),c=a.ranges;var g=a.connectorDistance;this.fontMetrics=e.renderer.fontMetrics(a.labels.style.fontSize.toString()+"px");c&&c.length&&t(c[0].value)?(h(c,function(b,e){return e.value-b.value}),this.ranges=c,this.setOptions(),this.render(),e=this.getMaxLabelSize(),c=this.ranges[0].radius,b=2*c,g=g-c+e.width,g=0<
g?g:0,this.maxLabel=e,this.movementX="left"===a.labels.align?g:0,this.legendItemWidth=b+g+d,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0},setOptions:function(){var b=this.ranges,e=this.options,a=this.chart.series[e.seriesIndex],c=this.legend.baseline,d={"z-index":e.zIndex,"stroke-width":e.borderWidth},g={"z-index":e.zIndex,"stroke-width":e.connectorWidth},h=this.getLabelStyles(),k=a.options.marker.fillOpacity,f=this.chart.styledMode;b.forEach(function(m,w){f||
(d.stroke=q(m.borderColor,e.borderColor,a.color),d.fill=q(m.color,e.color,1!==k?u(a.color).setOpacity(k).get("rgba"):a.color),g.stroke=q(m.connectorColor,e.connectorColor,a.color));b[w].radius=this.getRangeRadius(m.value);b[w]=x(b[w],{center:b[0].radius-b[w].radius+c});f||x(!0,b[w],{bubbleStyle:x(!1,d),connectorStyle:x(!1,g),labelStyle:h})},this)},getLabelStyles:function(){var b=this.options,e={},a="left"===b.labels.align,d=this.legend.options.rtl;y(b.labels.style,function(b,a){"color"!==a&&"fontSize"!==
a&&"z-index"!==a&&(e[a]=b)});return x(!1,e,{"font-size":b.labels.style.fontSize,fill:q(b.labels.style.color,"#000000"),"z-index":b.zIndex,align:d||a?"right":"left"})},getRangeRadius:function(b){var e=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,e.ranges[e.ranges.length-1].value,e.ranges[0].value,e.minSize,e.maxSize,b)},render:function(){var b=this.chart.renderer,e=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=
b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=e&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(b){var e=this.options,a=e.labels,d=this.chart.renderer,c=this.symbols,g=c.labels,h=b.center,k=Math.abs(b.radius),f=e.connectorDistance,l=a.align,r=a.style.fontSize;f=this.legend.options.rtl||
"left"===l?-f:f;a=e.connectorWidth;var v=this.ranges[0].radius,u=h-k-e.borderWidth/2+a/2;r=r/2-(this.fontMetrics.h-r)/2;var n=d.styledMode;"center"===l&&(f=0,e.connectorDistance=0,b.labelStyle.align="center");l=u+e.labels.y;var p=v+f+e.labels.x;c.bubbleItems.push(d.circle(v,h+((u%1?1:.5)-(a%2?0:.5)),k).attr(n?{}:b.bubbleStyle).addClass((n?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(e.className||"")).add(this.legendSymbol));c.connectors.push(d.path(d.crispLine(["M",
v,u,"L",v+f,u],e.connectorWidth)).attr(n?{}:b.connectorStyle).addClass((n?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(e.connectorClassName||"")).add(this.legendSymbol));b=d.text(this.formatLabel(b),p,l+r).attr(n?{}:b.labelStyle).addClass("highcharts-bubble-legend-labels "+(e.labels.className||"")).add(this.legendSymbol);g.push(b);b.placed=!0;b.alignAttr={x:p,y:l+r}},getMaxLabelSize:function(){var b,a;this.symbols.labels.forEach(function(e){a=e.getBBox(!0);
b=b?a.width>b.width?a:b:a});return b||{}},formatLabel:function(b){var e=this.options,d=e.labels.formatter;e=e.labels.format;var c=this.chart.numberFormatter;return e?a.format(e,b):d?d.call(b):c(b.value,1)},hideOverlappingLabels:function(){var b=this.chart,a=this.symbols;!this.options.labels.allowOverlap&&a&&(b.hideOverlappingLabels(a.labels),a.labels.forEach(function(b,e){b.newOpacity?b.newOpacity!==b.oldOpacity&&a.connectors[e].show():a.connectors[e].hide()}))},getRanges:function(){var b=this.legend.bubbleLegend,
a=b.options.ranges,d,c=Number.MAX_VALUE,g=-Number.MAX_VALUE;b.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(d=b.zData.filter(t),d.length&&(c=q(b.options.zMin,Math.min(c,Math.max(p(d),!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),g=q(b.options.zMax,Math.max(g,n(d)))))});var f=c===g?[{value:g}]:[{value:c},{value:(c+g)/2},{value:g,autoRanges:!0}];a.length&&a[0].radius&&f.reverse();f.forEach(function(b,e){a&&a[e]&&(f[e]=x(!1,a[e],b))});return f},predictBubbleSizes:function(){var b=
this.chart,a=this.fontMetrics,d=b.legend.options,c="horizontal"===d.layout,g=c?b.legend.lastLineHeight:0,f=b.plotSizeX,h=b.plotSizeY,k=b.series[this.options.seriesIndex];b=Math.ceil(k.minPxSize);var l=Math.ceil(k.maxPxSize);k=k.options.maxSize;var r=Math.min(h,f);if(d.floating||!/%$/.test(k))a=l;else if(k=parseFloat(k),a=(r+g-a.h/2)*k/100/(k/100+1),c&&h-a>=f||!c&&f-a>=h)a=l;return[b,Math.ceil(a)]},updateRanges:function(b,a){var e=this.legend.options.bubbleLegend;e.minSize=b;e.maxSize=a;e.ranges=this.getRanges()},
correctSizes:function(){var b=this.legend,a=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(a.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,a.maxPxSize),b.render())}};f(c.Legend,"afterGetAllItems",function(b){var a=this.bubbleLegend,d=this.options,g=d.bubbleLegend,f=this.chart.getVisibleBubbleSeriesIndex();a&&a.ranges&&a.ranges.length&&(g.ranges.length&&(g.autoRanges=!!g.ranges[0].autoRanges),this.destroyItem(a));0<=f&&d.enabled&&g.enabled&&(g.seriesIndex=
f,this.bubbleLegend=new c.BubbleLegend(g,this),this.bubbleLegend.addToLegend(b.allItems))});v.prototype.getVisibleBubbleSeriesIndex=function(){for(var b=this.series,a=0;a<b.length;){if(b[a]&&b[a].isBubble&&b[a].visible&&b[a].zData.length)return a;a++}return-1};k.prototype.getLinesHeights=function(){var b=this.allItems,a=[],d=b.length,c,g=0;for(c=0;c<d;c++)if(b[c].legendItemHeight&&(b[c].itemHeight=b[c].legendItemHeight),b[c]===b[d-1]||b[c+1]&&b[c]._legendItemPos[1]!==b[c+1]._legendItemPos[1]){a.push({height:0});
var f=a[a.length-1];for(g;g<=c;g++)b[g].itemHeight>f.height&&(f.height=b[g].itemHeight);f.step=c}return a};k.prototype.retranslateItems=function(b){var a,c,d,g=this.options.rtl,f=0;this.allItems.forEach(function(e,k){a=e.legendGroup.translateX;c=e._legendItemPos[1];if((d=e.movementX)||g&&e.ranges)d=g?a-e.options.maxSize/2:a+d,e.legendGroup.attr({translateX:d});k>b[f].step&&f++;e.legendGroup.attr({translateY:Math.round(c+b[f].height/2)});e._legendItemPos[1]=c+b[f].height/2})};f(g,"legendItemClick",
function(){var b=this.chart,a=this.visible,c=this.chart.legend;c&&c.bubbleLegend&&(this.visible=!a,this.ignoreSeries=a,b=0<=b.getVisibleBubbleSeriesIndex(),c.bubbleLegend.visible!==b&&(c.update({bubbleLegend:{enabled:b}}),c.bubbleLegend.visible=b),this.visible=a)});d(v.prototype,"drawChartBox",function(b,a,c){var d=this.legend,e=0<=this.getVisibleBubbleSeriesIndex();if(d&&d.options.enabled&&d.bubbleLegend&&d.options.bubbleLegend.autoRanges&&e){var g=d.bubbleLegend.options;e=d.bubbleLegend.predictBubbleSizes();
d.bubbleLegend.updateRanges(e[0],e[1]);g.placed||(d.group.placed=!1,d.allItems.forEach(function(b){b.legendGroup.translateY=null}));d.render();this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();g.placed||(b.setScale(),b.updateNames(),y(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});g.placed=!0;this.getMargins();b.call(this,a,c);d.bubbleLegend.correctSizes();d.retranslateItems(d.getLinesHeights())}else b.call(this,a,c),d&&d.options.enabled&&d.bubbleLegend&&(d.render(),d.retranslateItems(d.getLinesHeights()))})});
z(f,"parts-more/BubbleSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.arrayMax,n=a.arrayMin,p=a.clamp,t=a.extend,x=a.isNumber,y=a.pick,q=a.pInt;a=a.seriesType;var h=c.Axis,d=c.color,g=c.noop,k=c.Point,v=c.Series,u=c.seriesTypes;a("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,
maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(a,c){var b=this.options.marker.fillOpacity;a=v.prototype.pointAttribs.call(this,a,c);1!==b&&(a.fill=d(a.fill).setOpacity(b).get("rgba"));
return a},getRadii:function(a,d,b){var c=this.zData,g=this.yData,f=b.minPxSize,k=b.maxPxSize,h=[];var l=0;for(b=c.length;l<b;l++){var r=c[l];h.push(this.getRadius(a,d,f,k,r,g[l]))}this.radii=h},getRadius:function(a,d,b,c,g,f){var e=this.options,k="width"!==e.sizeBy,h=e.zThreshold,l=d-a,m=.5;if(null===f||null===g)return null;if(x(g)){e.sizeByAbsoluteValue&&(g=Math.abs(g-h),l=Math.max(d-h,Math.abs(a-h)),a=0);if(g<a)return b/2-1;0<l&&(m=(g-a)/l)}k&&0<=m&&(m=Math.sqrt(m));return Math.ceil(b+m*(c-b))/
2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var b=a.graphic;if(b&&b.width){var d={x:b.x,y:b.y,width:b.width,height:b.height};b.attr({x:a.plotX,y:a.plotY,width:1,height:1});b.animate(d,this.options.animation)}},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,d=this.data,b=this.radii;u.scatter.prototype.translate.call(this);for(a=d.length;a--;){var c=d[a];var g=b?b[a]:0;x(g)&&
g>=this.minPxSize/2?(c.marker=t(c.marker,{radius:g,width:2*g,height:2*g}),c.dlBox={x:c.plotX-g,y:c.plotY-g,width:2*g,height:2*g}):c.shapeArgs=c.plotY=c.dlBox=void 0}},alignDataLabel:u.column.prototype.alignDataLabel,buildKDTree:g,applyZones:g},{haloPath:function(a){return k.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});h.prototype.beforePadding=function(){var a=this,d=this.len,b=this.chart,c=0,g=d,k=this.isXAxis,h=k?"xData":"yData",v=this.min,u={},t=Math.min(b.plotWidth,
b.plotHeight),A=Number.MAX_VALUE,z=-Number.MAX_VALUE,G=this.max-v,F=d/G,H=[];this.series.forEach(function(d){var c=d.options;!d.bubblePadding||!d.visible&&b.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,H.push(d),k&&(["minSize","maxSize"].forEach(function(b){var a=c[b],d=/%$/.test(a);a=q(a);u[b]=d?t*a/100:a}),d.minPxSize=u.minSize,d.maxPxSize=Math.max(u.maxSize,u.minSize),d=d.zData.filter(x),d.length&&(A=y(c.zMin,p(n(d),!1===c.displayNegative?c.zThreshold:-Number.MAX_VALUE,A)),z=y(c.zMax,
Math.max(z,f(d))))))});H.forEach(function(b){var d=b[h],e=d.length;k&&b.getRadii(A,z,b);if(0<G)for(;e--;)if(x(d[e])&&a.dataMin<=d[e]&&d[e]<=a.max){var f=b.radii?b.radii[e]:0;c=Math.min((d[e]-v)*F-f,c);g=Math.max((d[e]-v)*F+f,g)}});H.length&&0<G&&!this.isLog&&(g-=d,F*=(d+Math.max(0,c)-Math.min(g,d))/d,[["min","userMin",c],["max","userMax",g]].forEach(function(b){"undefined"===typeof y(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/F)}))};""});z(f,"parts-map/MapBubbleSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],
function(c,a){var f=a.merge;a=a.seriesType;var n=c.Point,p=c.seriesTypes;p.bubble&&a("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:p.map.prototype.getMapData,getBox:p.map.prototype.getBox,setData:p.map.prototype.setData,setOptions:p.map.prototype.setOptions},{applyOptions:function(a,c){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?n.prototype.applyOptions.call(this,f(a,this.series.chart.fromLatLonToPoint(a)),
c):p.map.prototype.pointClass.prototype.applyOptions.call(this,a,c)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});z(f,"parts-map/HeatmapSeries.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){var f=a.clamp,n=a.extend,p=a.merge,t=a.pick;a=a.seriesType;var x=c.colorMapPointMixin,y=c.noop,q=c.fireEvent,h=c.Series,d=c.seriesTypes;a("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,
verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:null,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},p(c.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){d.scatter.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=t(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1},translate:function(){this.generatePoints();
var a=this.options,d=a.colsize,c=a.pointPadding,h=void 0===c?0:c;a=a.rowsize;c=this.points;var l=this.xAxis,r=this.yAxis,b=(void 0===d?1:d)/2,e=(void 0===a?1:a)/2,m=this.pointPlacementToXValue(),n=function(a){return Math.round(f(l.translate(a,!1,!1,!1,!0,m),0,l.len))};c.forEach(function(a){var d=n(a.x-b),c=n(a.x+b),g=Math.round(f(r.translate(a.y-e,!1,!0,!1,!0),0,r.len)),k=Math.round(f(r.translate(a.y+e,!1,!0,!1,!0),0,r.len)),l=t(a.pointPadding,h);a.plotX=a.clientX=(d+c)/2;a.plotY=(g+k)/2;a.shapeType=
"rect";a.shapeArgs={x:Math.min(d,c)+l,y:Math.min(g,k)+l,width:Math.max(Math.abs(c-d)-2*l,0),height:Math.max(Math.abs(k-g)-2*l,0)}});q(this,"afterTranslate")},drawPoints:function(){var a=this.chart.styledMode?"css":"animate";d.column.prototype.drawPoints.call(this);this.points.forEach(function(d){d.graphic[a](this.colorAttribs(d))},this)},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,d){return h.prototype.getValidPoints.call(this,a,d,!0)},animate:y,getBox:y,drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,
alignDataLabel:d.column.prototype.alignDataLabel,getExtremes:function(){h.prototype.getExtremes.call(this,this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;h.prototype.getExtremes.call(this)}}),n({haloPath:function(a){if(!a)return[];var d=this.shapeArgs;return["M",d.x-a,d.y-a,"L",d.x-a,d.y+d.height+a,d.x+d.width+a,d.y+d.height+a,d.x+d.width+a,d.y-a,"Z"]}},x));""});z(f,"parts-map/GeoJSON.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){function f(a,d){var c,f=!1,
h=a.x,u=a.y;a=0;for(c=d.length-1;a<d.length;c=a++){var l=d[a][1]>u;var r=d[c][1]>u;l!==r&&h<(d[c][0]-d[a][0])*(u-d[a][1])/(d[c][1]-d[a][1])+d[a][0]&&(f=!f)}return f}var n=a.error,p=a.extend,t=a.format,x=a.merge;a=a.wrap;var y=c.Chart,q=c.win;y.prototype.transformFromLatLon=function(a,d){var c,f=(null===(c=this.userOptions.chart)||void 0===c?void 0:c.proj4)||q.proj4;if(!f)return n(21,!1,this),{x:0,y:null};a=f(d.crs,[a.lon,a.lat]);c=d.cosAngle||d.rotation&&Math.cos(d.rotation);f=d.sinAngle||d.rotation&&
Math.sin(d.rotation);a=d.rotation?[a[0]*c+a[1]*f,-a[0]*f+a[1]*c]:a;return{x:((a[0]-(d.xoffset||0))*(d.scale||1)+(d.xpan||0))*(d.jsonres||1)+(d.jsonmarginX||0),y:(((d.yoffset||0)-a[1])*(d.scale||1)+(d.ypan||0))*(d.jsonres||1)-(d.jsonmarginY||0)}};y.prototype.transformToLatLon=function(a,d){if("undefined"===typeof q.proj4)n(21,!1,this);else{a={x:((a.x-(d.jsonmarginX||0))/(d.jsonres||1)-(d.xpan||0))/(d.scale||1)+(d.xoffset||0),y:((-a.y-(d.jsonmarginY||0))/(d.jsonres||1)+(d.ypan||0))/(d.scale||1)+(d.yoffset||
0)};var c=d.cosAngle||d.rotation&&Math.cos(d.rotation),f=d.sinAngle||d.rotation&&Math.sin(d.rotation);d=q.proj4(d.crs,"WGS84",d.rotation?{x:a.x*c+a.y*-f,y:a.x*f+a.y*c}:a);return{lat:d.y,lon:d.x}}};y.prototype.fromPointToLatLon=function(a){var d=this.mapTransforms,c;if(d){for(c in d)if(Object.hasOwnProperty.call(d,c)&&d[c].hitZone&&f({x:a.x,y:-a.y},d[c].hitZone.coordinates[0]))return this.transformToLatLon(a,d[c]);return this.transformToLatLon(a,d["default"])}n(22,!1,this)};y.prototype.fromLatLonToPoint=
function(a){var d=this.mapTransforms,c;if(!d)return n(22,!1,this),{x:0,y:null};for(c in d)if(Object.hasOwnProperty.call(d,c)&&d[c].hitZone){var k=this.transformFromLatLon(a,d[c]);if(f({x:k.x,y:-k.y},d[c].hitZone.coordinates[0]))return k}return this.transformFromLatLon(a,d["default"])};c.geojson=function(a,d,c){var f=[],g=[],h=function(a){var c,b=a.length;g.push("M");for(c=0;c<b;c++)1===c&&g.push("L"),g.push(a[c][0],-a[c][1])};d=d||"map";a.features.forEach(function(a){var c=a.geometry,b=c.type;c=c.coordinates;
a=a.properties;var e;g=[];"map"===d||"mapbubble"===d?("Polygon"===b?(c.forEach(h),g.push("Z")):"MultiPolygon"===b&&(c.forEach(function(a){a.forEach(h)}),g.push("Z")),g.length&&(e={path:g})):"mapline"===d?("LineString"===b?h(c):"MultiLineString"===b&&c.forEach(h),g.length&&(e={path:g})):"mappoint"===d&&"Point"===b&&(e={x:c[0],y:-c[1]});e&&f.push(p(e,{name:a.name||a.NAME,properties:a}))});c&&a.copyrightShort&&(c.chart.mapCredits=t(c.chart.options.credits.mapText,{geojson:a}),c.chart.mapCreditsFull=
t(c.chart.options.credits.mapTextFull,{geojson:a}));return f};a(y.prototype,"addCredits",function(a,c){c=x(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});z(f,"parts-map/Map.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(c,a){function f(a,c,f,h,n,l,p,b){return["M",a+n,c,"L",a+f-l,c,"C",a+f-l/2,c,a+f,c+l/2,a+f,c+l,"L",a+f,c+h-p,"C",a+f,c+h-p/2,a+f-p/2,c+h,a+f-p,c+h,"L",a+b,c+
h,"C",a+b/2,c+h,a,c+h-b/2,a,c+h-b,"L",a,c+n,"C",a,c+n/2,a+n/2,c,a+n,c,"Z"]}var n=a.extend,p=a.merge,t=a.pick,x=c.Chart;a=c.defaultOptions;var y=c.Renderer,q=c.SVGRenderer,h=c.VMLRenderer;n(a.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});a.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",
y:0},zoomOut:{onclick:function(){this.mapZoom(2)},text:"-",y:28}},mouseWheelSensitivity:1.1};c.splitPath=function(a){var c;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(c=0;c<a.length;c++)/[a-zA-Z]/.test(a[c])||(a[c]=parseFloat(a[c]));return a};c.maps={};q.prototype.symbols.topbutton=function(a,c,h,n,p){return f(a-1,c-1,h,n,p.r,p.r,0,0)};q.prototype.symbols.bottombutton=function(a,c,h,n,p){return f(a-1,c-1,h,n,0,0,p.r,p.r)};y===h&&["topbutton",
"bottombutton"].forEach(function(a){h.prototype.symbols[a]=q.prototype.symbols[a]});c.Map=c.mapChart=function(a,f,h){var d="string"===typeof a||a.nodeName,g=arguments[d?1:0],k=g,n={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},b=c.getOptions().credits;var e=g.series;g.series=null;g=p({chart:{panning:"xy",type:"map"},credits:{mapText:t(b.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:t(b.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},
xAxis:n,yAxis:p(n,{reversed:!0})},g,{chart:{inverted:!1,alignTicks:!1}});g.series=k.series=e;return d?new x(a,g,h):new x(g,f)}});z(f,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map