/*
 Highcharts Gantt JS v8.0.0 (2020-02-16)

 Pathfinder

 (c) 2016-2019 ystein Moseng

 License: www.highcharts.com/license
*/
(function(g){"object"===typeof module&&module.exports?(g["default"]=g,module.exports=g):"function"===typeof define&&define.amd?define("highcharts/modules/pathfinder",["highcharts"],function(u){g(u);g.Highcharts=u;return g}):g("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(g){function u(m,h,y,g){m.hasOwnProperty(h)||(m[h]=g.apply(null,y))}g=g?g._modules:{};u(g,"parts-gantt/PathfinderAlgorithms.js",[g["parts/Utilities.js"]],function(m){function h(c,d,e){e=e||0;var h=c.length-1;d-=1e-7;
for(var g,m;e<=h;)if(g=h+e>>1,m=d-c[g].xMin,0<m)e=g+1;else if(0>m)h=g-1;else return g;return 0<e?e-1:0}function y(c,d){for(var e=h(c,d.x+1)+1;e--;){var g;if(g=c[e].xMax>=d.x)g=c[e],g=d.x<=g.xMax&&d.x>=g.xMin&&d.y<=g.yMax&&d.y>=g.yMin;if(g)return e}return-1}function g(c){var d=[];if(c.length){d.push("M",c[0].start.x,c[0].start.y);for(var e=0;e<c.length;++e)d.push("L",c[e].end.x,c[e].end.y)}return d}function n(c,d){c.yMin=A(c.yMin,d.yMin);c.yMax=v(c.yMax,d.yMax);c.xMin=A(c.xMin,d.xMin);c.xMax=v(c.xMax,
d.xMax)}var u=m.extend,C=m.pick,v=Math.min,A=Math.max,w=Math.abs;return{straight:function(c,d){return{path:["M",c.x,c.y,"L",d.x,d.y],obstacles:[{start:c,end:d}]}},simpleConnect:u(function(c,d,e){function h(a,b,k,c,e){a={x:a.x,y:a.y};a[b]=k[c||b]+(e||0);return a}function m(a,b,k){var f=w(b[k]-a[k+"Min"])>w(b[k]-a[k+"Max"]);return h(b,k,a,k+(f?"Max":"Min"),f?1:-1)}var n=[],p=C(e.startDirectionX,w(d.x-c.x)>w(d.y-c.y))?"x":"y",r=e.chartObstacles,v=y(r,c);e=y(r,d);if(-1<e){var a=r[e];e=m(a,d,p);a={start:e,
end:d};var b=e}else b=d;-1<v&&(r=r[v],e=m(r,c,p),n.push({start:c,end:e}),e[p]>=c[p]===e[p]>=b[p]&&(p="y"===p?"x":"y",d=c[p]<d[p],n.push({start:e,end:h(e,p,r,p+(d?"Max":"Min"),d?1:-1)}),p="y"===p?"x":"y"));c=n.length?n[n.length-1].end:c;e=h(c,p,b);n.push({start:c,end:e});p=h(e,"y"===p?"x":"y",b);n.push({start:e,end:p});n.push(a);return{path:g(n),obstacles:n}},{requiresObstacles:!0}),fastAvoid:u(function(c,d,e){function m(a,b,f){var k,q=a.x<b.x?1:-1;if(a.x<b.x){var z=a;var c=b}else z=b,c=a;if(a.y<b.y){var e=
a;var d=b}else e=b,d=a;for(k=0>q?v(h(l,c.x),l.length-1):0;l[k]&&(0<q&&l[k].xMin<=c.x||0>q&&l[k].xMax>=z.x);){if(l[k].xMin<=c.x&&l[k].xMax>=z.x&&l[k].yMin<=d.y&&l[k].yMax>=e.y)return f?{y:a.y,x:a.x<b.x?l[k].xMin-1:l[k].xMax+1,obstacle:l[k]}:{x:a.x,y:a.y<b.y?l[k].yMin-1:l[k].yMax+1,obstacle:l[k]};k+=q}return b}function r(a,b,f,k,l){var c=l.soft,z=l.hard,e=k?"x":"y",q={x:b.x,y:b.y},d={x:b.x,y:b.y};l=a[e+"Max"]>=c[e+"Max"];c=a[e+"Min"]<=c[e+"Min"];var E=a[e+"Max"]>=z[e+"Max"];z=a[e+"Min"]<=z[e+"Min"];
var g=w(a[e+"Min"]-b[e]),G=w(a[e+"Max"]-b[e]);f=10>w(g-G)?b[e]<f[e]:G<g;d[e]=a[e+"Min"];q[e]=a[e+"Max"];a=m(b,d,k)[e]!==d[e];b=m(b,q,k)[e]!==q[e];f=a?b?f:!0:b?!1:f;f=c?l?f:!0:l?!1:f;return z?E?f:!0:E?!1:f}function u(a,f,c){if(a.x===f.x&&a.y===f.y)return[];var d=c?"x":"y",g=e.obstacleOptions.margin;var q={soft:{xMin:z,xMax:k,yMin:E,yMax:J},hard:e.hardBounds};var h=y(l,a);if(-1<h){h=l[h];q=r(h,a,f,c,q);n(h,e.hardBounds);var t=c?{y:a.y,x:h[q?"xMax":"xMin"]+(q?1:-1)}:{x:a.x,y:h[q?"yMax":"yMin"]+(q?1:
-1)};var x=y(l,t);-1<x&&(x=l[x],n(x,e.hardBounds),t[d]=q?A(h[d+"Max"]-g+1,(x[d+"Min"]+h[d+"Max"])/2):v(h[d+"Min"]+g-1,(x[d+"Max"]+h[d+"Min"])/2),a.x===t.x&&a.y===t.y?(b&&(t[d]=q?A(h[d+"Max"],x[d+"Max"])+1:v(h[d+"Min"],x[d+"Min"])-1),b=!b):b=!1);a=[{start:a,end:t}]}else d=m(a,{x:c?f.x:a.x,y:c?a.y:f.y},c),a=[{start:a,end:{x:d.x,y:d.y}}],d[c?"x":"y"]!==f[c?"x":"y"]&&(q=r(d.obstacle,d,f,!c,q),n(d.obstacle,e.hardBounds),q={x:c?d.x:d.obstacle[q?"xMax":"xMin"]+(q?1:-1),y:c?d.obstacle[q?"yMax":"yMin"]+(q?
1:-1):d.y},c=!c,a=a.concat(u({x:d.x,y:d.y},q,c)));return a=a.concat(u(a[a.length-1].end,f,!c))}function p(a,b,f){var k=v(a.xMax-b.x,b.x-a.xMin)<v(a.yMax-b.y,b.y-a.yMin);f=r(a,b,f,k,{soft:e.hardBounds,hard:e.hardBounds});return k?{y:b.y,x:a[f?"xMax":"xMin"]+(f?1:-1)}:{x:b.x,y:a[f?"yMax":"yMin"]+(f?1:-1)}}var D=C(e.startDirectionX,w(d.x-c.x)>w(d.y-c.y)),B=D?"x":"y",a=[],b=!1,f=e.obstacleMetrics,z=v(c.x,d.x)-f.maxWidth-10,k=A(c.x,d.x)+f.maxWidth+10,E=v(c.y,d.y)-f.maxHeight-10,J=A(c.y,d.y)+f.maxHeight+
10,l=e.chartObstacles;var x=h(l,z);f=h(l,k);l=l.slice(x,f+1);if(-1<(f=y(l,d))){var t=p(l[f],d,c);a.push({end:d,start:t});d=t}for(;-1<(f=y(l,d));)x=0>d[B]-c[B],t={x:d.x,y:d.y},t[B]=l[f][x?B+"Max":B+"Min"]+(x?1:-1),a.push({end:d,start:t}),d=t;c=u(c,d,D);c=c.concat(a.reverse());return{path:g(c),obstacles:c}},{requiresObstacles:!0})}});u(g,"parts-gantt/ArrowSymbols.js",[g["parts/Globals.js"]],function(g){g.SVGRenderer.prototype.symbols.arrow=function(g,m,r,n){return["M",g,m+n/2,"L",g+r,m,"L",g,m+n/2,
"L",g+r,m+n]};g.SVGRenderer.prototype.symbols["arrow-half"]=function(h,m,r,n){return g.SVGRenderer.prototype.symbols.arrow(h,m,r/2,n)};g.SVGRenderer.prototype.symbols["triangle-left"]=function(g,m,r,n){return["M",g+r,m,"L",g,m+n/2,"L",g+r,m+n,"Z"]};g.SVGRenderer.prototype.symbols["arrow-filled"]=g.SVGRenderer.prototype.symbols["triangle-left"];g.SVGRenderer.prototype.symbols["triangle-left-half"]=function(h,m,r,n){return g.SVGRenderer.prototype.symbols["triangle-left"](h,m,r/2,n)};g.SVGRenderer.prototype.symbols["arrow-filled-half"]=
g.SVGRenderer.prototype.symbols["triangle-left-half"]});u(g,"parts-gantt/Pathfinder.js",[g["parts/Globals.js"],g["parts/Utilities.js"],g["parts-gantt/PathfinderAlgorithms.js"]],function(g,h,u){function m(a){var b=a.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=a.graphic&&a.graphic.getBBox())?{xMin:a.plotX-b.width/2,xMax:a.plotX+b.width/2,yMin:a.plotY-b.height/2,yMax:a.plotY+b.height/2}:null}function n(a){for(var b=a.length,f=0,d,k,c=[],e=function(a,b,f){f=F(f,10);var k=
a.yMax+f>b.yMin-f&&a.yMin-f<b.yMax+f,d=a.xMax+f>b.xMin-f&&a.xMin-f<b.xMax+f,c=k?a.xMin>b.xMax?a.xMin-b.xMax:b.xMin-a.xMax:Infinity,g=d?a.yMin>b.yMax?a.yMin-b.yMax:b.yMin-a.yMax:Infinity;return d&&k?f?e(a,b,Math.floor(f/2)):Infinity:B(c,g)};f<b;++f)for(d=f+1;d<b;++d)k=e(a[f],a[d]),80>k&&c.push(k);c.push(80);return D(Math.floor(c.sort(function(a,b){return a-b})[Math.floor(c.length/10)]/2-1),1)}function y(a,b,f){this.init(a,b,f)}function C(a){this.init(a)}function v(a){if(a.options.pathfinder||a.series.reduce(function(a,
f){f.options&&e(!0,f.options.connectors=f.options.connectors||{},f.options.pathfinder);return a||f.options&&f.options.pathfinder},!1))e(!0,a.options.connectors=a.options.connectors||{},a.options.pathfinder),c('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}var A=h.addEvent,w=h.defined,c=h.error,d=h.extend,e=h.merge,H=h.objectEach,F=h.pick,I=h.splat,p=g.deg2rad,D=Math.max,B=Math.min;d(g.defaultOptions,{connectors:{type:"straight",lineWidth:1,
marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});y.prototype={init:function(a,b,f){this.fromPoint=a;this.toPoint=b;this.options=f;this.chart=a.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(a,b,f){var d=this.chart,k=d.styledMode,c=d.pathfinder,e=!d.options.chart.forExport&&!1!==f,g=this.graphics&&this.graphics.path;c.group||(c.group=d.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(d.seriesGroup));
c.group.translate(d.plotLeft,d.plotTop);g&&g.renderer||(g=d.renderer.path().add(c.group),k||g.attr({opacity:0}));g.attr(b);a={d:a};k||(a.opacity=1);g[e?"animate":"attr"](a,f);this.graphics=this.graphics||{};this.graphics.path=g},addMarker:function(a,b,f){var d=this.fromPoint.series.chart,k=d.pathfinder;d=d.renderer;var c="start"===a?this.fromPoint:this.toPoint,e=c.getPathfinderAnchorPoint(b);if(b.enabled){f="start"===a?{x:f[4],y:f[5]}:{x:f[f.length-5],y:f[f.length-4]};f=c.getRadiansToVector(f,e);
e=c.getMarkerVector(f,b.radius,e);f=-f/p;if(b.width&&b.height){var g=b.width;var h=b.height}else g=h=2*b.radius;this.graphics=this.graphics||{};e={x:e.x-g/2,y:e.y-h/2,width:g,height:h,rotation:f,rotationOriginX:e.x,rotationOriginY:e.y};this.graphics[a]?this.graphics[a].animate(e):(this.graphics[a]=d.symbol(b.symbol).addClass("highcharts-point-connecting-path-"+a+"-marker").attr(e).add(k.group),d.styledMode||this.graphics[a].attr({fill:b.color||this.fromPoint.color,stroke:b.lineColor,"stroke-width":b.lineWidth,
opacity:0}).animate({opacity:1},c.series.options.animation))}},getPath:function(a){var b=this.pathfinder,f=this.chart,d=b.algorithms[a.type],k=b.chartObstacles;if("function"!==typeof d)c('"'+a.type+'" is not a Pathfinder algorithm.');else return d.requiresObstacles&&!k&&(k=b.chartObstacles=b.getChartObstacles(a),f.options.connectors.algorithmMargin=a.algorithmMargin,b.chartObstacleMetrics=b.getObstacleMetrics(k)),d(this.fromPoint.getPathfinderAnchorPoint(a.startMarker),this.toPoint.getPathfinderAnchorPoint(a.endMarker),
e({chartObstacles:k,lineObstacles:b.lineObstacles||[],obstacleMetrics:b.chartObstacleMetrics,hardBounds:{xMin:0,xMax:f.plotWidth,yMin:0,yMax:f.plotHeight},obstacleOptions:{margin:a.algorithmMargin},startDirectionX:b.getAlgorithmStartDirection(a.startMarker)},a))},render:function(){var a=this.fromPoint,b=a.series,f=b.chart,d=f.pathfinder,c=e(f.options.connectors,b.options.connectors,a.options.connectors,this.options),g={};f.styledMode||(g.stroke=c.lineColor||a.color,g["stroke-width"]=c.lineWidth,c.dashStyle&&
(g.dashstyle=c.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+a.colorIndex;c=e(g,c);w(c.marker.radius)||(c.marker.radius=B(D(Math.ceil((c.algorithmMargin||8)/2)-1,1),5));a=this.getPath(c);f=a.path;a.obstacles&&(d.lineObstacles=d.lineObstacles||[],d.lineObstacles=d.lineObstacles.concat(a.obstacles));this.renderPath(f,g,b.options.animation);this.addMarker("start",e(c.marker,c.startMarker),f);this.addMarker("end",e(c.marker,c.endMarker),f)},destroy:function(){this.graphics&&
(H(this.graphics,function(a){a.destroy()}),delete this.graphics)}};C.prototype={algorithms:u,init:function(a){this.chart=a;this.connections=[];A(a,"redraw",function(){this.pathfinder.update()})},update:function(a){var b=this.chart,f=this,d=f.connections;f.connections=[];b.series.forEach(function(a){a.visible&&!a.options.isInternal&&a.points.forEach(function(a){var d,c=a.options&&a.options.connect&&I(a.options.connect);a.visible&&!1!==a.isInside&&c&&c.forEach(function(c){d=b.get("string"===typeof c?
c:c.to);d instanceof g.Point&&d.series.visible&&d.visible&&!1!==d.isInside&&f.connections.push(new y(a,d,"string"===typeof c?{}:c))})})});for(var c=0,e,h,l=d.length,m=f.connections.length;c<l;++c){h=!1;for(e=0;e<m;++e)if(d[c].fromPoint===f.connections[e].fromPoint&&d[c].toPoint===f.connections[e].toPoint){f.connections[e].graphics=d[c].graphics;h=!0;break}h||d[c].destroy()}delete this.chartObstacles;delete this.lineObstacles;f.renderConnections(a)},renderConnections:function(a){a?this.chart.series.forEach(function(a){var b=
function(){var b=a.chart.pathfinder;(b&&b.connections||[]).forEach(function(b){b.fromPoint&&b.fromPoint.series===a&&b.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?b():a.pathfinderRemoveRenderEvent=A(a,"afterAnimate",b)}):this.connections.forEach(function(a){a.render()})},getChartObstacles:function(a){for(var b=[],c=this.chart.series,d=F(a.algorithmMargin,0),e,g=0,h=c.length;g<h;++g)if(c[g].visible&&!c[g].options.isInternal)for(var l=
0,p=c[g].points.length,t;l<p;++l)t=c[g].points[l],t.visible&&(t=m(t))&&b.push({xMin:t.xMin-d,xMax:t.xMax+d,yMin:t.yMin-d,yMax:t.yMax+d});b=b.sort(function(a,b){return a.xMin-b.xMin});w(a.algorithmMargin)||(e=a.algorithmMargin=n(b),b.forEach(function(a){a.xMin-=e;a.xMax+=e;a.yMin-=e;a.yMax+=e}));return b},getObstacleMetrics:function(a){for(var b=0,c=0,d,e,g=a.length;g--;)d=a[g].xMax-a[g].xMin,e=a[g].yMax-a[g].yMin,b<d&&(b=d),c<e&&(c=e);return{maxHeight:c,maxWidth:b}},getAlgorithmStartDirection:function(a){var b=
"top"!==a.verticalAlign&&"bottom"!==a.verticalAlign;return"left"!==a.align&&"right"!==a.align?b?void 0:!1:b?!0:void 0}};g.Connection=y;g.Pathfinder=C;d(g.Point.prototype,{getPathfinderAnchorPoint:function(a){var b=m(this);switch(a.align){case "right":var c="xMax";break;case "left":c="xMin"}switch(a.verticalAlign){case "top":var d="yMin";break;case "bottom":d="yMax"}return{x:c?b[c]:(b.xMin+b.xMax)/2,y:d?b[d]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(a,b){w(b)||(b=m(this),b={x:(b.xMin+b.xMax)/
2,y:(b.yMin+b.yMax)/2});return Math.atan2(b.y-a.y,a.x-b.x)},getMarkerVector:function(a,b,c){var d=2*Math.PI,e=m(this),f=e.xMax-e.xMin,g=e.yMax-e.yMin,h=Math.atan2(g,f),n=!1;f/=2;var t=g/2,q=e.xMin+f;e=e.yMin+t;for(var p=q,r=e,u={},v=1,w=1;a<-Math.PI;)a+=d;for(;a>Math.PI;)a-=d;d=Math.tan(a);a>-h&&a<=h?(w=-1,n=!0):a>h&&a<=Math.PI-h?w=-1:a>Math.PI-h||a<=-(Math.PI-h)?(v=-1,n=!0):v=-1;n?(p+=v*f,r+=w*f*d):(p+=g/(2*d)*v,r+=w*t);c.x!==q&&(p=c.x);c.y!==e&&(r=c.y);u.x=p+b*Math.cos(a);u.y=r-b*Math.sin(a);return u}});
g.Chart.prototype.callbacks.push(function(a){!1!==a.options.connectors.enabled&&(v(a),this.pathfinder=new C(this),this.pathfinder.update(!0))})});u(g,"masters/modules/pathfinder.src.js",[],function(){})});
//# sourceMappingURL=pathfinder.js.map