/*
 Highcharts JS v8.0.0 (2020-02-16)

 Sonification module

 (c) 2012-2019 ystein Moseng

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sonification",["highcharts"],function(n){b(n);b.Highcharts=n;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function n(c,b,e,q){c.hasOwnProperty(b)||(c[b]=q.apply(null,e))}b=b?b._modules:{};n(b,"modules/sonification/Instrument.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(c,b){function e(d){this.init(d)}
var f=b.error,m=b.merge,h=b.pick,l=b.uniqueKey,u={type:"oscillator",playCallbackInterval:20,oscillator:{waveformShape:"sine"}};e.prototype.init=function(d){this.initAudioContext()?(this.options=m(u,d),this.id=this.options.id=d&&d.id||l(),d=c.audioContext,this.gainNode=d.createGain(),this.setGain(0),(this.panNode=d.createStereoPanner&&d.createStereoPanner())?(this.setPan(0),this.gainNode.connect(this.panNode),this.panNode.connect(d.destination)):this.gainNode.connect(d.destination),"oscillator"===
this.options.type&&this.initOscillator(this.options.oscillator),this.playCallbackTimers=[]):f(29)};e.prototype.copy=function(d){return new e(m(this.options,{id:null},d))};e.prototype.initAudioContext=function(){var d=c.win.AudioContext||c.win.webkitAudioContext,a=!!c.audioContext;return d?(c.audioContext=c.audioContext||new d,!a&&c.audioContext&&"running"===c.audioContext.state&&c.audioContext.suspend(),!!(c.audioContext&&c.audioContext.createOscillator&&c.audioContext.createGain)):!1};e.prototype.initOscillator=
function(d){this.oscillator=c.audioContext.createOscillator();this.oscillator.type=d.waveformShape;this.oscillator.connect(this.gainNode);this.oscillatorStarted=!1};e.prototype.setPan=function(d){this.panNode&&this.panNode.pan.setValueAtTime(d,c.audioContext.currentTime)};e.prototype.setGain=function(d,a){this.gainNode&&(1.2<d&&(console.warn("Highcharts sonification warning: Volume of instrument set too high."),d=1.2),a?(this.gainNode.gain.setValueAtTime(this.gainNode.gain.value,c.audioContext.currentTime),
this.gainNode.gain.linearRampToValueAtTime(d,c.audioContext.currentTime+a/1E3)):this.gainNode.gain.setValueAtTime(d,c.audioContext.currentTime))};e.prototype.cancelGainRamp=function(){this.gainNode&&this.gainNode.gain.cancelScheduledValues(0)};e.prototype.getValidFrequency=function(d,a,g){var c=this.options.allowedFrequencies,b=h(g,Infinity),e=h(a,-Infinity);return c&&c.length?c.reduce(function(a,c){return Math.abs(c-d)<Math.abs(a-d)&&c<b&&c>e?c:a},Infinity):d};e.prototype.clearPlayCallbackTimers=
function(){this.playCallbackTimers.forEach(function(d){clearInterval(d)});this.playCallbackTimers=[]};e.prototype.setFrequency=function(d,a){a=a||{};d=this.getValidFrequency(d,a.min,a.max);"oscillator"===this.options.type&&this.oscillatorPlay(d)};e.prototype.oscillatorPlay=function(d){this.oscillatorStarted||(this.oscillator.start(),this.oscillatorStarted=!0);this.oscillator.frequency.setValueAtTime(d,c.audioContext.currentTime)};e.prototype.preparePlay=function(){this.setGain(.001);"suspended"===
c.audioContext.state&&c.audioContext.resume();this.oscillator&&!this.oscillatorStarted&&(this.oscillator.start(),this.oscillatorStarted=!0)};e.prototype.play=function(d){var a=this,g=d.duration||0,k=function(c,g,b){var k=d.duration,e=0,h=a.options.playCallbackInterval;if("function"===typeof c){var l=setInterval(function(){e++;var d=e*h/k;if(1<=d)a[g](c(1),b),clearInterval(l);else a[g](c(d),b)},h);a.playCallbackTimers.push(l)}else a[g](c,b)};if(a.id)if("suspended"===c.audioContext.state||this.oscillator&&
!this.oscillatorStarted)a.preparePlay(),setTimeout(function(){a.play(d)},10);else{a.playCallbackTimers.length&&a.clearPlayCallbackTimers();a.cancelGainRamp();a.stopOscillatorTimeout&&(clearTimeout(a.stopOscillatorTimeout),delete a.stopOscillatorTimeout);a.stopTimeout&&(clearTimeout(a.stopTimeout),delete a.stopTimeout,a.stopCallback&&(a._play=a.play,a.play=function(){},a.stopCallback("cancelled"),a.play=a._play));var b=g<c.sonification.fadeOutDuration+20;a.stopCallback=d.onEnd;var e=function(){delete a.stopTimeout;
a.stop(b)};g?(a.stopTimeout=setTimeout(e,b?g:g-c.sonification.fadeOutDuration),k(d.frequency,"setFrequency",{minFrequency:d.minFrequency,maxFrequency:d.maxFrequency}),k(h(d.volume,1),"setGain",4),k(h(d.pan,0),"setPan")):e()}};e.prototype.mute=function(){this.setGain(.0001,.8*c.sonification.fadeOutDuration)};e.prototype.stop=function(d,a,g){var b=this,e=function(){b.stopOscillatorTimeout&&delete b.stopOscillatorTimeout;try{b.oscillator.stop()}catch(r){}b.oscillator.disconnect(b.gainNode);b.initOscillator(b.options.oscillator);
a&&a(g);b.stopCallback&&b.stopCallback(g)};b.playCallbackTimers.length&&b.clearPlayCallbackTimers();b.stopTimeout&&clearTimeout(b.stopTimeout);d?(b.setGain(0),e()):(b.mute(),b.stopOscillatorTimeout=setTimeout(e,c.sonification.fadeOutDuration+100))};return e});n(b,"modules/sonification/musicalFrequencies.js",[],function(){return[16.351597831287414,17.323914436054505,18.354047994837977,19.445436482630058,20.601722307054366,21.826764464562746,23.12465141947715,24.499714748859326,25.956543598746574,27.5,
29.13523509488062,30.86770632850775,32.70319566257483,34.64782887210901,36.70809598967594,38.890872965260115,41.20344461410875,43.653528929125486,46.2493028389543,48.999429497718666,51.91308719749314,55,58.27047018976124,61.7354126570155,65.40639132514966,69.29565774421802,73.41619197935188,77.78174593052023,82.4068892282175,87.30705785825097,92.4986056779086,97.99885899543733,103.82617439498628,110,116.54094037952248,123.47082531403103,130.8127826502993,138.59131548843604,146.8323839587038,155.56349186104046,
164.81377845643496,174.61411571650194,184.9972113558172,195.99771799087463,207.65234878997256,220,233.08188075904496,246.94165062806206,261.6255653005986,277.1826309768721,293.6647679174076,311.1269837220809,329.6275569128699,349.2282314330039,369.9944227116344,391.99543598174927,415.3046975799451,440,466.1637615180899,493.8833012561241,523.2511306011972,554.3652619537442,587.3295358348151,622.2539674441618,659.2551138257398,698.4564628660078,739.9888454232688,783.9908719634985,830.6093951598903,
880,932.3275230361799,987.7666025122483,1046.5022612023945,1108.7305239074883,1174.6590716696303,1244.5079348883237,1318.5102276514797,1396.9129257320155,1479.9776908465376,1567.981743926997,1661.2187903197805,1760,1864.6550460723597,1975.533205024496,2093.004522404789,2217.4610478149766,2349.31814333926,2489.0158697766474,2637.02045530296,2793.825851464031,2959.955381693075,3135.9634878539946,3322.437580639561,3520,3729.3100921447194,3951.066410048992,4186.009044809578]});n(b,"modules/sonification/utilities.js",
[b["modules/sonification/musicalFrequencies.js"],b["parts/Utilities.js"]],function(b,f){function c(b){this.init(b||[])}var q=f.clamp;c.prototype.init=function(b){this.supportedSignals=b;this.signals={}};c.prototype.registerSignalCallbacks=function(b){var c=this;c.supportedSignals.forEach(function(e){var h=b[e];h&&(c.signals[e]=c.signals[e]||[]).push(h)})};c.prototype.clearSignalCallbacks=function(b){var c=this;b?b.forEach(function(b){c.signals[b]&&delete c.signals[b]}):c.signals={}};c.prototype.emitSignal=
function(b,c){var e;this.signals[b]&&this.signals[b].forEach(function(b){b=b(c);e="undefined"!==typeof b?b:e});return e};return{musicalFrequencies:b,SignalHandler:c,getMusicalScale:function(c){return b.filter(function(b,e){var h=e%12+1;return c.some(function(b){return b===h})})},calculateDataExtremes:function(b,c){return b.series.reduce(function(b,e){e.points.forEach(function(d){d="undefined"!==typeof d[c]?d[c]:d.options[c];b.min=Math.min(b.min,d);b.max=Math.max(b.max,d)});return b},{min:Infinity,
max:-Infinity})},virtualAxisTranslate:function(b,c,e){var h=c.max-c.min;b=e.min+(e.max-e.min)*(b-c.min)/h;return 0<h?q(b,e.min,e.max):e.min}}});n(b,"modules/sonification/instrumentDefinitions.js",[b["modules/sonification/Instrument.js"],b["modules/sonification/utilities.js"]],function(b,f){var c={};["sine","square","triangle","sawtooth"].forEach(function(e){c[e]=new b({oscillator:{waveformShape:e}});c[e+"Musical"]=new b({allowedFrequencies:f.musicalFrequencies,oscillator:{waveformShape:e}});c[e+"Major"]=
new b({allowedFrequencies:f.getMusicalScale([1,3,5,6,8,10,12]),oscillator:{waveformShape:e}})});return c});n(b,"modules/sonification/Earcon.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,f){function c(b){this.init(b||{})}var q=f.error,m=f.merge,h=f.pick,l=f.uniqueKey;c.prototype.init=function(b){this.options=b;this.options.id||(this.options.id=this.id=l());this.instrumentsPlaying={}};c.prototype.sonify=function(c){var d=m(this.options,c),a=h(d.volume,1),g=d.pan,e=this,f=c&&c.onEnd,
r=e.options.onEnd;d.instruments.forEach(function(c){var d="string"===typeof c.instrument?b.sonification.instruments[c.instrument]:c.instrument,k=m(c.playOptions),l="";if(d&&d.play){if(c.playOptions){"function"!==typeof c.playOptions.volume&&(k.volume=h(a,1)*h(c.playOptions.volume,1));k.pan=h(g,k.pan);var p=k.onEnd;k.onEnd=function(){delete e.instrumentsPlaying[l];p&&p.apply(this,arguments);Object.keys(e.instrumentsPlaying).length||(f&&f.apply(this,arguments),r&&r.apply(this,arguments))};c=d.copy();
l=c.id;e.instrumentsPlaying[l]=c;c.play(k)}}else q(30)})};c.prototype.cancelSonify=function(b){var c=this.instrumentsPlaying,a=c&&Object.keys(c);a&&a.length&&(a.forEach(function(a){c[a].stop(!b,null,"cancelled")}),this.instrumentsPlaying={})};return c});n(b,"modules/sonification/pointSonify.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],function(b,f,e){var c=f.error,m=f.merge,h=f.pick,l={minDuration:20,maxDuration:2E3,minVolume:.1,maxVolume:1,minPan:-1,
maxPan:1,minFrequency:220,maxFrequency:2200};return{pointSonify:function(f){var d=this,a=d.series.chart,g=f.dataExtremes||{},k=function(a,b,c){return"function"===typeof a?b?function(b){return a(d,g,b)}:a(d,g):"string"===typeof a?(g[a]=g[a]||e.calculateDataExtremes(d.series.chart,a),e.virtualAxisTranslate(h(d[a],d.options[a]),g[a],c)):a};a.sonification.currentlyPlayingPoint=d;d.sonification=d.sonification||{};d.sonification.instrumentsPlaying=d.sonification.instrumentsPlaying||{};var p=d.sonification.signalHandler=
d.sonification.signalHandler||new e.SignalHandler(["onEnd"]);p.clearSignalCallbacks();p.registerSignalCallbacks({onEnd:f.onEnd});!d.isNull&&d.visible&&d.series.visible?f.instruments.forEach(function(e){var g="string"===typeof e.instrument?b.sonification.instruments[e.instrument]:e.instrument,h=e.instrumentMapping||{},f=m(l,e.instrumentOptions),q=g.id,r=function(b){e.onEnd&&e.onEnd.apply(this,arguments);a.sonification&&a.sonification.currentlyPlayingPoint&&delete a.sonification.currentlyPlayingPoint;
d.sonification&&d.sonification.instrumentsPlaying&&(delete d.sonification.instrumentsPlaying[q],Object.keys(d.sonification.instrumentsPlaying).length||p.emitSignal("onEnd",b))};g&&g.play?(d.sonification.instrumentsPlaying[g.id]=g,g.play({frequency:k(h.frequency,!0,{min:f.minFrequency,max:f.maxFrequency}),duration:k(h.duration,!1,{min:f.minDuration,max:f.maxDuration}),pan:k(h.pan,!0,{min:f.minPan,max:f.maxPan}),volume:k(h.volume,!0,{min:f.minVolume,max:f.maxVolume}),onEnd:r,minFrequency:f.minFrequency,
maxFrequency:f.maxFrequency})):c(30)}):p.emitSignal("onEnd")},pointCancelSonify:function(b){var c=this.sonification&&this.sonification.instrumentsPlaying,a=c&&Object.keys(c);a&&a.length&&(a.forEach(function(a){c[a].stop(!b,null,"cancelled")}),this.sonification.instrumentsPlaying={},this.sonification.signalHandler.emitSignal("onEnd","cancelled"))}}});n(b,"modules/sonification/chartSonify.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],function(b,f,e){function c(b,
a){return"function"===typeof a?a(b):w(b[a],b.options[a])}function m(b,a){return b.points.reduce(function(b,d){d=c(d,a);b.min=Math.min(b.min,d);b.max=Math.max(b.max,d);return b},{min:Infinity,max:-Infinity})}function h(b,a,c){return(a||[]).reduce(function(a,c){Object.keys(c.instrumentMapping||{}).forEach(function(d){d=c.instrumentMapping[d];"string"!==typeof d||a[d]||(a[d]=e.calculateDataExtremes(b,d))});return a},v(c))}function l(a,c){return c.reduce(function(c,d){var e=d.earcon;d.condition?(d=d.condition(a),
d instanceof b.sonification.Earcon?c.push(d):d&&c.push(e)):d.onPoint&&a.id===d.onPoint&&c.push(e);return c},[])}function n(a){return a.map(function(a){var c=a.instrument;c=("string"===typeof c?b.sonification.instruments[c]:c).copy();return v(a,{instrument:c})})}function d(a,d){var g=d.timeExtremes||m(a,d.pointPlayTime,d.dataExtremes),C=h(a.chart,d.instruments,d.dataExtremes),f=n(d.instruments),k=a.points.reduce(function(a,k){var h=l(k,d.earcons||[]),x=e.virtualAxisTranslate(c(k,d.pointPlayTime),g,
{min:0,max:d.duration});return a.concat(new b.sonification.TimelineEvent({eventObject:k,time:x,id:k.id,playOptions:{instruments:f,dataExtremes:C}}),h.map(function(a){return new b.sonification.TimelineEvent({eventObject:a,time:x})}))},[]);return new b.sonification.TimelinePath({events:k,onStart:function(){if(d.onStart)d.onStart(a)},onEventStart:function(a){var c=a.options&&a.options.eventObject;if(c instanceof b.Point){if(!c.series.visible&&!c.series.chart.series.some(function(a){return a.visible}))return a.timelinePath.timeline.pause(),
a.timelinePath.timeline.resetCursor(),!1;if(d.onPointStart)d.onPointStart(a,c)}},onEventEnd:function(a){var c=a.event&&a.event.options&&a.event.options.eventObject;if(c instanceof b.Point&&d.onPointEnd)d.onPointEnd(a.event,c)},onEnd:function(){if(d.onEnd)d.onEnd(a)}})}function a(a,b,c){var d=c.seriesOptions||{};return v({dataExtremes:b,timeExtremes:m(a,c.pointPlayTime),instruments:c.instruments,onStart:c.onSeriesStart,onEnd:c.onSeriesEnd,earcons:c.earcons},B(d)?A(d,function(b){return b.id===w(a.id,
a.options.id)})||{}:d,{pointPlayTime:c.pointPlayTime})}function g(a,c,d){if("sequential"===a||"simultaneous"===a){var e=c.series.reduce(function(a,b){b.visible&&a.push({series:b,seriesOptions:d(b)});return a},[]);"simultaneous"===a&&(e=[e])}else e=a.reduce(function(a,e){e=t(e).reduce(function(a,e){var g;if("string"===typeof e){var k=c.get(e);k.visible&&(g={series:k,seriesOptions:d(k)})}else e instanceof b.sonification.Earcon&&(g=new b.sonification.TimelinePath({events:[new b.sonification.TimelineEvent({eventObject:e})]}));
e.silentWait&&(g=new b.sonification.TimelinePath({silentWait:e.silentWait}));g&&a.push(g);return a},[]);e.length&&a.push(e);return a},[]);return e}function k(a,c){return c?a.reduce(function(d,e,g){e=t(e);d.push(e);g<a.length-1&&e.some(function(a){return a.series})&&d.push(new b.sonification.TimelinePath({silentWait:c}));return d},[]):a}function p(a){return a.reduce(function(a,b){b=t(b);return a+(1===b.length&&b[0].options&&b[0].options.silentWait||0)},0)}function r(a){var c=a.reduce(function(a,b){(b=
b.events)&&b.length&&(a.min=Math.min(b[0].time,a.min),a.max=Math.max(b[b.length-1].time,a.max));return a},{min:Infinity,max:-Infinity});a.forEach(function(a){var d=a.events,e=d&&d.length,g=[];e&&d[0].time<=c.min||g.push(new b.sonification.TimelineEvent({time:c.min}));e&&d[d.length-1].time>=c.max||g.push(new b.sonification.TimelineEvent({time:c.max}));g.length&&a.addTimelineEvents(g)})}function y(a){return a.reduce(function(a,b){return a+t(b).reduce(function(a,b){return(b=b.series&&b.seriesOptions&&
b.seriesOptions.timeExtremes)?Math.max(a,b.max-b.min):a},0)},0)}function z(a,c){var g=Math.max(c-p(a),0),k=y(a);return a.reduce(function(a,c){c=t(c).reduce(function(a,c){c instanceof b.sonification.TimelinePath?a.push(c):c.series&&(c.seriesOptions.duration=c.seriesOptions.duration||e.virtualAxisTranslate(c.seriesOptions.timeExtremes.max-c.seriesOptions.timeExtremes.min,{min:0,max:k},{min:0,max:g}),a.push(d(c.series,c.seriesOptions)));return a},[]);a.push(c);return a},[])}var A=f.find,B=f.isArray,
v=f.merge,w=f.pick,t=f.splat;return{chartSonify:function(c){this.sonification.timeline&&this.sonification.timeline.pause();var d=h(this,c.instruments,c.dataExtremes),e=g(c.order,this,function(b){return a(b,d,c)});e=k(e,c.afterSeriesWait||0);e=z(e,c.duration);e.forEach(function(a){r(a)});this.sonification.timeline=new b.sonification.Timeline({paths:e,onEnd:c.onEnd});this.sonification.timeline.play()},seriesSonify:function(a){a=d(this,a);var c=this.chart.sonification;c.timeline&&c.timeline.pause();
c.timeline=new b.sonification.Timeline({paths:[a]});c.timeline.play()},pause:function(a){this.sonification.timeline?this.sonification.timeline.pause(w(a,!0)):this.sonification.currentlyPlayingPoint&&this.sonification.currentlyPlayingPoint.cancelSonify(a)},resume:function(a){this.sonification.timeline&&this.sonification.timeline.play(a)},rewind:function(a){this.sonification.timeline&&this.sonification.timeline.rewind(a)},cancel:function(a){this.pauseSonify(a);this.resetSonifyCursor()},getCurrentPoints:function(){if(this.sonification.timeline){var a=
this.sonification.timeline.getCursor();return Object.keys(a).map(function(b){return a[b].eventObject}).filter(function(a){return a instanceof b.Point})}return[]},setCursor:function(a){var b=this.sonification.timeline;b&&t(a).forEach(function(a){b.setCursor(a.id)})},resetCursor:function(){this.sonification.timeline&&this.sonification.timeline.resetCursor()},resetCursorEnd:function(){this.sonification.timeline&&this.sonification.timeline.resetCursorEnd()}}});n(b,"modules/sonification/Timeline.js",[b["parts/Globals.js"],
b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],function(b,f,e){function c(a){this.init(a||{})}function m(a){this.init(a)}function h(a){this.init(a||{})}var l=f.merge,n=f.splat,d=f.uniqueKey;c.prototype.init=function(a){this.options=a;this.time=a.time||0;this.id=this.options.id=a.id||d()};c.prototype.play=function(a){var b=this.options.eventObject,c=this.options.onEnd,d=a&&a.onEnd,e=this.options.playOptions&&this.options.playOptions.onEnd;a=l(this.options.playOptions,a);b&&b.sonify?
(a.onEnd=c||d||e?function(){var a=arguments;[c,d,e].forEach(function(b){b&&b.apply(this,a)})}:void 0,b.sonify(a)):(d&&d(),c&&c())};c.prototype.cancel=function(a){this.options.eventObject.cancelSonify(a)};m.prototype.init=function(a){this.options=a;this.id=this.options.id=a.id||d();this.cursor=0;this.eventsPlaying={};this.events=a.silentWait?[new c({time:0}),new c({time:a.silentWait})]:this.options.events;this.sortEvents();this.updateEventIdMap();this.signalHandler=new e.SignalHandler(["playOnEnd",
"masterOnEnd","onStart","onEventStart","onEventEnd"]);this.signalHandler.registerSignalCallbacks(l(a,{masterOnEnd:a.onEnd}))};m.prototype.sortEvents=function(){this.events=this.events.sort(function(a,b){return a.time-b.time})};m.prototype.updateEventIdMap=function(){this.eventIdMap=this.events.reduce(function(a,b,c){a[b.id]=c;return a},{})};m.prototype.addTimelineEvents=function(a){this.events=this.events.concat(a);this.sortEvents();this.updateEventIdMap()};m.prototype.getCursor=function(){return this.events[this.cursor]};
m.prototype.setCursor=function(a){a=this.eventIdMap[a];return"undefined"!==typeof a?(this.cursor=a,!0):!1};m.prototype.play=function(a){this.pause();this.signalHandler.emitSignal("onStart");this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playEvents(1)};m.prototype.rewind=function(a){this.pause();this.signalHandler.emitSignal("onStart");this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});
this.playEvents(-1)};m.prototype.resetCursor=function(){this.cursor=0};m.prototype.resetCursorEnd=function(){this.cursor=this.events.length-1};m.prototype.pause=function(a){var b=this;clearTimeout(b.nextScheduledPlay);Object.keys(b.eventsPlaying).forEach(function(c){b.eventsPlaying[c]&&b.eventsPlaying[c].cancel(a)});b.eventsPlaying={}};m.prototype.playEvents=function(a){var b=this,c=b.events[this.cursor],d=b.events[this.cursor+a],e=function(a){b.signalHandler.emitSignal("masterOnEnd",a);b.signalHandler.emitSignal("playOnEnd",
a)};c.timelinePath=b;if(!1===b.signalHandler.emitSignal("onEventStart",c))e({event:c,cancelled:!0});else if(b.eventsPlaying[c.id]=c,c.play({onEnd:function(a){a={event:c,cancelled:!!a};delete b.eventsPlaying[c.id];b.signalHandler.emitSignal("onEventEnd",a);d||e(a)}}),d){var f=Math.abs(d.time-c.time);1>f?(b.cursor+=a,b.playEvents(a)):this.nextScheduledPlay=setTimeout(function(){b.cursor+=a;b.playEvents(a)},f)}};h.prototype.init=function(a){this.options=a;this.cursor=0;this.paths=a.paths;this.pathsPlaying=
{};this.signalHandler=new e.SignalHandler(["playOnEnd","masterOnEnd","onPathStart","onPathEnd"]);this.signalHandler.registerSignalCallbacks(l(a,{masterOnEnd:a.onEnd}))};h.prototype.play=function(a){this.pause();this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playPaths(1)};h.prototype.rewind=function(a){this.pause();this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playPaths(-1)};
h.prototype.playPaths=function(a){var c=n(this.paths[this.cursor]),d=this.paths[this.cursor+a],e=this,f=this.signalHandler,h=0,l=function(b){f.emitSignal("onPathStart",b);e.pathsPlaying[b.id]=b;b[0<a?"play":"rewind"](function(g){g=g&&g.cancelled;var k={path:b,cancelled:g};delete e.pathsPlaying[b.id];f.emitSignal("onPathEnd",k);h++;h>=c.length&&(d&&!g?(e.cursor+=a,n(d).forEach(function(b){b[0<a?"resetCursor":"resetCursorEnd"]()}),e.playPaths(a)):(f.emitSignal("playOnEnd",k),f.emitSignal("masterOnEnd",
k)))})};c.forEach(function(a){a&&(a.timeline=e,setTimeout(function(){l(a)},b.sonification.fadeOutDuration))})};h.prototype.pause=function(a){var b=this;Object.keys(b.pathsPlaying).forEach(function(c){b.pathsPlaying[c]&&b.pathsPlaying[c].pause(a)});b.pathsPlaying={}};h.prototype.resetCursor=function(){this.paths.forEach(function(a){n(a).forEach(function(a){a.resetCursor()})});this.cursor=0};h.prototype.resetCursorEnd=function(){this.paths.forEach(function(a){n(a).forEach(function(a){a.resetCursorEnd()})});
this.cursor=this.paths.length-1};h.prototype.setCursor=function(a){return this.paths.some(function(b){return n(b).some(function(b){return b.setCursor(a)})})};h.prototype.getCursor=function(){return this.getCurrentPlayingPaths().reduce(function(a,b){a[b.id]=b.getCursor();return a},{})};h.prototype.atStart=function(){return!this.getCurrentPlayingPaths().some(function(a){return a.cursor})};h.prototype.getCurrentPlayingPaths=function(){return n(this.paths[this.cursor])};return{TimelineEvent:c,TimelinePath:m,
Timeline:h}});n(b,"modules/sonification/sonification.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["modules/sonification/Instrument.js"],b["modules/sonification/instrumentDefinitions.js"],b["modules/sonification/Earcon.js"],b["modules/sonification/pointSonify.js"],b["modules/sonification/chartSonify.js"],b["modules/sonification/utilities.js"],b["modules/sonification/Timeline.js"]],function(b,f,e,n,m,h,l,u,d){var a=f.addEvent;f=f.extend;b.sonification={fadeOutDuration:20,utilities:u,Instrument:e,
instruments:n,Earcon:m,TimelineEvent:d.TimelineEvent,TimelinePath:d.TimelinePath,Timeline:d.Timeline};b.Point.prototype.sonify=h.pointSonify;b.Point.prototype.cancelSonify=h.pointCancelSonify;b.Series.prototype.sonify=l.seriesSonify;f(b.Chart.prototype,{sonify:l.chartSonify,pauseSonify:l.pause,resumeSonify:l.resume,rewindSonify:l.rewind,cancelSonify:l.cancel,getCurrentSonifyPoints:l.getCurrentPoints,setSonifyCursor:l.setCursor,resetSonifyCursor:l.resetCursor,resetSonifyCursorEnd:l.resetCursorEnd});
a(b.Chart,"init",function(){this.sonification={}})});n(b,"masters/modules/sonification.src.js",[],function(){})});
//# sourceMappingURL=sonification.js.map