/*
 Highstock JS v8.0.0 (2020-02-16)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?(p["default"]=p,module.exports=p):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(F){p(F);p.Highcharts=F;return p}):p("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(p){function F(r,d,H,p){r.hasOwnProperty(d)||(r[d]=p.apply(null,H))}p=p?p._modules:{};F(p,"parts/Scrollbar.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){var H=d.addEvent,p=d.correctFloat,D=d.defined,
v=d.destroyObjectProperties,G=d.fireEvent,A=d.merge,l=d.pick,J=d.removeEvent;d=r.Axis;var g=r.defaultOptions,t=r.hasTouch,u,x={height:r.isTouchDevice?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",
trackBorderWidth:1};g.scrollbar=A(!0,x,g.scrollbar);r.swapXY=u=function(a,e){var m=a.length;if(e)for(e=0;e<m;e+=3){var I=a[e+1];a[e+1]=a[e+2];a[e+2]=I}return a};var f=function(){function a(e,m,a){this._events=[];this.from=this.chartY=this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions=
{};this.y=this.x=0;this.chart=a;this.options=m;this.renderer=a.renderer;this.init(e,m,a)}a.prototype.addEvents=function(){var e=this.options.inverted?[1,0]:[0,1],m=this.scrollbarButtons,a=this.scrollbarGroup.element,c=this.track.element,k=this.mouseDownHandler.bind(this),n=this.mouseMoveHandler.bind(this),f=this.mouseUpHandler.bind(this);e=[[m[e[0]].element,"click",this.buttonToMinClick.bind(this)],[m[e[1]].element,"click",this.buttonToMaxClick.bind(this)],[c,"click",this.trackClick.bind(this)],[a,
"mousedown",k],[a.ownerDocument,"mousemove",n],[a.ownerDocument,"mouseup",f]];t&&e.push([a,"touchstart",k],[a.ownerDocument,"touchmove",n],[a.ownerDocument,"touchend",f]);e.forEach(function(c){H.apply(null,c)});this._events=e};a.prototype.buttonToMaxClick=function(e){var m=(this.to-this.from)*l(this.options.step,.2);this.updatePosition(this.from+m,this.to+m);G(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};a.prototype.buttonToMinClick=function(e){var m=p(this.to-this.from)*
l(this.options.step,.2);this.updatePosition(p(this.from-m),p(this.to-m));G(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};a.prototype.cursorToScrollbarPosition=function(e){var m=this.options;m=m.minWidth>this.calculatedWidth?m.minWidth:0;return{chartX:(e.chartX-this.x-this.xOffset)/(this.barWidth-m),chartY:(e.chartY-this.y-this.yOffset)/(this.barWidth-m)}};a.prototype.destroy=function(){var e=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar",
"scrollbarGroup","group"].forEach(function(e){this[e]&&this[e].destroy&&(this[e]=this[e].destroy())},this);e&&this===e.scrollbar&&(e.scrollbar=null,v(e.scrollbarButtons))};a.prototype.drawScrollbarButton=function(e){var m=this.renderer,a=this.scrollbarButtons,c=this.options,k=this.size;var n=m.g().add(this.group);a.push(n);n=m.rect().addClass("highcharts-scrollbar-button").add(n);this.chart.styledMode||n.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});
n.attr(n.crisp({x:-.5,y:-.5,width:k+1,height:k+1,r:c.buttonBorderRadius},n.strokeWidth()));n=m.path(u(["M",k/2+(e?-1:1),k/2-3,"L",k/2+(e?-1:1),k/2+3,"L",k/2+(e?2:-2),k/2],c.vertical)).addClass("highcharts-scrollbar-arrow").add(a[e]);this.chart.styledMode||n.attr({fill:c.buttonArrowColor})};a.prototype.init=function(e,m,a){this.scrollbarButtons=[];this.renderer=e;this.userOptions=m;this.options=A(x,m);this.chart=a;this.size=l(this.options.size,this.options.height);m.enabled&&(this.render(),this.addEvents())};
a.prototype.mouseDownHandler=function(e){e=this.chart.pointer.normalize(e);e=this.cursorToScrollbarPosition(e);this.chartX=e.chartX;this.chartY=e.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=function(e){var a=this.chart.pointer.normalize(e),f=this.options.vertical?"chartY":"chartX",c=this.initPositions||[];!this.grabbedCenter||e.touches&&0===e.touches[0][f]||(a=this.cursorToScrollbarPosition(a)[f],f=this[f],f=a-f,this.hasDragged=!0,this.updatePosition(c[0]+
f,c[1]+f),this.hasDragged&&G(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e}))};a.prototype.mouseUpHandler=function(e){this.hasDragged&&G(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(e,a,f,c){var k=this.options.vertical,n=0,m=this.rendered?"animate":"attr";this.x=e;this.y=a+this.trackBorderWidth;this.width=f;this.xOffset=
this.height=c;this.yOffset=n;k?(this.width=this.yOffset=f=n=this.size,this.xOffset=a=0,this.barWidth=c-2*f,this.x=e+=this.options.margin):(this.height=this.xOffset=c=a=this.size,this.barWidth=f-2*c,this.y+=this.options.margin);this.group[m]({translateX:e,translateY:this.y});this.track[m]({width:f,height:c});this.scrollbarButtons[1][m]({translateX:k?0:f-a,translateY:k?c-n:0})};a.prototype.removeEvents=function(){this._events.forEach(function(e){J.apply(null,e)});this._events.length=0};a.prototype.render=
function(){var e=this.renderer,a=this.options,f=this.size,c=this.chart.styledMode,k;this.group=k=e.g("scrollbar").attr({zIndex:a.zIndex,translateY:-99999}).add();this.track=e.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:a.trackBorderRadius||0,height:f,width:f}).add(k);c||this.track.attr({fill:a.trackBackgroundColor,stroke:a.trackBorderColor,"stroke-width":a.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=
e.g().add(k);this.scrollbar=e.rect().addClass("highcharts-scrollbar-thumb").attr({height:f,width:f,r:a.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=e.path(u(["M",-3,f/4,"L",-3,2*f/3,"M",0,f/4,"L",0,2*f/3,"M",3,f/4,"L",3,2*f/3],a.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);c||(this.scrollbar.attr({fill:a.barBackgroundColor,stroke:a.barBorderColor,"stroke-width":a.barBorderWidth}),this.scrollbarRifles.attr({stroke:a.rifleColor,"stroke-width":1}));
this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(e,a){var f=this.options,c=f.vertical,k=f.minWidth,n=this.barWidth,m,g=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(D(n)){e=Math.max(e,0);var t=Math.ceil(n*e);this.calculatedWidth=m=p(n*Math.min(a,1)-t);m<
k&&(t=(n-k+m)*e,m=k);k=Math.floor(t+this.xOffset+this.yOffset);n=m/2-.5;this.from=e;this.to=a;c?(this.scrollbarGroup[g]({translateY:k}),this.scrollbar[g]({height:m}),this.scrollbarRifles[g]({translateY:n}),this.scrollbarTop=k,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:k}),this.scrollbar[g]({width:m}),this.scrollbarRifles[g]({translateX:n}),this.scrollbarLeft=k,this.scrollbarTop=0);12>=m?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===f.showFull&&(0>=e&&1<=a?this.group.hide():
this.group.show());this.rendered=!0}};a.prototype.trackClick=function(e){var a=this.chart.pointer.normalize(e),f=this.to-this.from,c=this.y+this.scrollbarTop,k=this.x+this.scrollbarLeft;this.options.vertical&&a.chartY>c||!this.options.vertical&&a.chartX>k?this.updatePosition(this.from+f,this.to+f):this.updatePosition(this.from-f,this.to-f);G(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};a.prototype.update=function(e){this.destroy();this.init(this.chart.renderer,A(!0,
this.options,e),this.chart)};a.prototype.updatePosition=function(e,a){1<a&&(e=p(1-p(a-e)),a=1);0>e&&(a=p(a-e),e=0);this.from=e;this.to=a};return a}();r.Scrollbar||(H(d,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new f(a.chart.renderer,a.options.scrollbar,a.chart),H(a.scrollbar,"changed",function(e){var f=Math.min(l(a.options.min,a.min),a.min,a.dataMin),
g=Math.max(l(a.options.max,a.max),a.max,a.dataMax)-f;if(a.horiz&&!a.reversed||!a.horiz&&a.reversed){var c=f+g*this.to;f+=g*this.from}else c=f+g*(1-this.from),f+=g*(1-this.to);l(this.options.liveRedraw,r.svg&&!r.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===e.DOMType||!D(e.DOMType)?a.setExtremes(f,c,!0,"mousemove"!==e.DOMType,e):this.setRange(this.from,this.to)}))}),H(d,"afterRender",function(){var a=Math.min(l(this.options.min,this.min),this.min,l(this.dataMin,this.min)),e=Math.max(l(this.options.max,
this.max),this.max,l(this.dataMax,this.max)),f=this.scrollbar,g=this.axisTitleMargin+(this.titleOffset||0),c=this.chart.scrollbarsOffsets,k=this.options.margin||0;f&&(this.horiz?(this.opposite||(c[1]+=g),f.position(this.left,this.top+this.height+2+c[1]-(this.opposite?k:0),this.width,this.height),this.opposite||(c[1]+=k),g=1):(this.opposite&&(c[0]+=g),f.position(this.left+this.width+2+c[0]-(this.opposite?0:k),this.top,this.width,this.height),this.opposite&&(c[0]+=k),g=0),c[g]+=f.size+f.options.margin,
isNaN(a)||isNaN(e)||!D(this.min)||!D(this.max)||this.min===this.max?f.setRange(0,1):(c=(this.min-a)/(e-a),a=(this.max-a)/(e-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?f.setRange(c,a):f.setRange(1-a,1-c)))}),H(d,"afterGetOffset",function(){var a=this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=e.size+e.options.margin)}),r.Scrollbar=f);return r.Scrollbar});F(p,"parts/Navigator.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["parts/Color.js"],
p["parts/Scrollbar.js"]],function(r,d,p,C){function D(b){this.init(b)}var v=d.addEvent,G=d.clamp,A=d.correctFloat,l=d.defined,H=d.destroyObjectProperties,g=d.erase,t=d.extend,u=d.find,x=d.isArray,f=d.isNumber,a=d.merge,e=d.pick,m=d.removeEvent,I=d.splat;d=p.parse;var c=r.Axis;p=r.Chart;var k=r.defaultOptions,n=r.hasTouch,y=r.isTouchDevice,B=r.Series,E=function(b){for(var h=[],w=1;w<arguments.length;w++)h[w-1]=arguments[w];h=[].filter.call(h,f);if(h.length)return Math[b].apply(0,h)};var q="undefined"===
typeof r.seriesTypes.areaspline?"line":"areaspline";t(k,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:d("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:q,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,
50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},
x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});r.Renderer.prototype.symbols["navigator-handle"]=function(b,h,w,c,e){b=e.width/2;h=Math.round(b/3)+.5;e=e.height;return["M",-b-1,.5,"L",b,.5,"L",b,e+.5,"L",-b-1,e+.5,"L",-b-1,.5,"M",-h,4,"L",-h,e-3,"M",h-1,4,"L",h-1,e-3]};c.prototype.toFixedRange=function(b,h,w,c){var a=this.chart&&
this.chart.fixedRange,z=(this.pointRange||0)/2;b=e(w,this.translate(b,!0,!this.horiz));h=e(c,this.translate(h,!0,!this.horiz));var k=a&&(h-b)/a;l(w)||(b=A(b+z));l(c)||(h=A(h-z));.7<k&&1.3>k&&(c?b=h-a:h=b+a);f(b)&&f(h)||(b=h=void 0);return{min:b,max:h}};D.prototype={drawHandle:function(b,h,w,c){var e=this.navigatorOptions.handles.height;this.handles[h][c](w?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(b,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(b,
10)),translateY:Math.round(this.top+this.height/2-e/2-1)})},drawOutline:function(b,h,w,c){var e=this.navigatorOptions.maskInside,a=this.outline.strokeWidth(),z=a/2;a=a%2/2;var k=this.outlineHeight,f=this.scrollbarHeight,n=this.size,g=this.left-f,q=this.top;w?(g-=z,w=q+h+a,h=q+b+a,b=["M",g+k,q-f-a,"L",g+k,w,"L",g,w,"L",g,h,"L",g+k,h,"L",g+k,q+n+f].concat(e?["M",g+k,w-z,"L",g+k,h+z]:[])):(b+=g+f-a,h+=g+f-a,q+=z,b=["M",g,q,"L",b,q,"L",b,q+k,"L",h,q+k,"L",h,q,"L",g+n+2*f,q].concat(e?["M",b-z,q,"L",h+
z,q]:[]));this.outline[c]({d:b})},drawMasks:function(b,h,w,c){var e=this.left,a=this.top,k=this.height;if(w){var z=[e,e,e];var f=[a,a+b,a+h];var n=[k,k,k];var g=[b,h-b,this.size-h]}else z=[e,e+b,e+h],f=[a,a,a],n=[b,h-b,this.size-h],g=[k,k,k];this.shades.forEach(function(b,h){b[c]({x:z[h],y:f[h],width:n[h],height:g[h]})})},renderElements:function(){var b=this,h=b.navigatorOptions,w=h.maskInside,c=b.chart,e=c.renderer,a,k={cursor:c.inverted?"ns-resize":"ew-resize"};b.navigatorGroup=a=e.g("navigator").attr({zIndex:8,
visibility:"hidden"}).add();[!w,w,!w].forEach(function(w,f){b.shades[f]=e.rect().addClass("highcharts-navigator-mask"+(1===f?"-inside":"-outside")).add(a);c.styledMode||b.shades[f].attr({fill:w?h.maskFill:"rgba(0,0,0,0)"}).css(1===f&&k)});b.outline=e.path().addClass("highcharts-navigator-outline").add(a);c.styledMode||b.outline.attr({"stroke-width":h.outlineWidth,stroke:h.outlineColor});h.handles.enabled&&[0,1].forEach(function(w){h.handles.inverted=c.inverted;b.handles[w]=e.symbol(h.handles.symbols[w],
-h.handles.width/2-1,0,h.handles.width,h.handles.height,h.handles);b.handles[w].attr({zIndex:7-w}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][w]).add(a);if(!c.styledMode){var f=h.handles;b.handles[w].attr({fill:f.backgroundColor,stroke:f.borderColor,"stroke-width":f.lineWidth}).css(k)}})},update:function(b){(this.series||[]).forEach(function(b){b.baseSeries&&delete b.baseSeries.navigatorSeries});this.destroy();a(!0,this.chart.options.navigator,this.options,
b);this.init(this.chart)},render:function(b,h,w,c){var a=this.chart,k=this.scrollbarHeight,n,z=this.xAxis,g=z.pointRange||0;var q=z.fake?a.xAxis[0]:z;var m=this.navigatorEnabled,t,y=this.rendered;var d=a.inverted;var u=a.xAxis[0].minRange,B=a.xAxis[0].options.maxRange;if(!this.hasDragged||l(w)){b=A(b-g/2);h=A(h+g/2);if(!f(b)||!f(h))if(y)w=0,c=e(z.width,q.width);else return;this.left=e(z.left,a.plotLeft+k+(d?a.plotWidth:0));this.size=t=n=e(z.len,(d?a.plotHeight:a.plotWidth)-2*k);a=d?k:n+2*k;w=e(w,
z.toPixels(b,!0));c=e(c,z.toPixels(h,!0));f(w)&&Infinity!==Math.abs(w)||(w=0,c=a);b=z.toValue(w,!0);h=z.toValue(c,!0);var x=Math.abs(A(h-b));x<u?this.grabbedLeft?w=z.toPixels(h-u-g,!0):this.grabbedRight&&(c=z.toPixels(b+u+g,!0)):l(B)&&A(x-g)>B&&(this.grabbedLeft?w=z.toPixels(h-B-g,!0):this.grabbedRight&&(c=z.toPixels(b+B+g,!0)));this.zoomedMax=G(Math.max(w,c),0,t);this.zoomedMin=G(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(w,c),0,t);this.range=this.zoomedMax-this.zoomedMin;t=Math.round(this.zoomedMax);
w=Math.round(this.zoomedMin);m&&(this.navigatorGroup.attr({visibility:"visible"}),y=y&&!this.hasDragged?"animate":"attr",this.drawMasks(w,t,d,y),this.drawOutline(w,t,d,y),this.navigatorOptions.handles.enabled&&(this.drawHandle(w,0,d,y),this.drawHandle(t,1,d,y)));this.scrollbar&&(d?(d=this.top-k,q=this.left-k+(m||!q.opposite?0:(q.titleOffset||0)+q.axisTitleMargin),k=n+2*k):(d=this.top+(m?this.height:-k),q=this.left-k),this.scrollbar.position(q,d,a,k),this.scrollbar.setRange(this.zoomedMin/(n||1),this.zoomedMax/
(n||1)));this.rendered=!0}},addMouseEvents:function(){var b=this,h=b.chart,w=h.container,c=[],a,e;b.mouseMoveHandler=a=function(h){b.onMouseMove(h)};b.mouseUpHandler=e=function(h){b.onMouseUp(h)};c=b.getPartsEvents("mousedown");c.push(v(h.renderTo,"mousemove",a),v(w.ownerDocument,"mouseup",e));n&&(c.push(v(h.renderTo,"touchmove",a),v(w.ownerDocument,"touchend",e)),c.concat(b.getPartsEvents("touchstart")));b.eventsToUnbind=c;b.series&&b.series[0]&&c.push(v(b.series[0].xAxis,"foundExtremes",function(){h.navigator.modifyNavigatorAxisExtremes()}))},
getPartsEvents:function(b){var h=this,w=[];["shades","handles"].forEach(function(c){h[c].forEach(function(a,e){w.push(v(a.element,b,function(b){h[c+"Mousedown"](b,e)}))})});return w},shadesMousedown:function(b,h){b=this.chart.pointer.normalize(b);var c=this.chart,a=this.xAxis,e=this.zoomedMin,k=this.left,f=this.size,n=this.range,g=b.chartX;c.inverted&&(g=b.chartY,k=this.top);if(1===h)this.grabbedCenter=g,this.fixedWidth=n,this.dragOffset=g-e;else{b=g-k-n/2;if(0===h)b=Math.max(0,b);else if(2===h&&
b+n>=f)if(b=f-n,this.reversedExtremes){b-=n;var q=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;b!==e&&(this.fixedWidth=n,h=a.toFixedRange(b,b+n,q,m),l(h.min)&&c.xAxis[0].setExtremes(Math.min(h.min,h.max),Math.max(h.min,h.max),!0,null,{trigger:"navigator"}))}},handlesMousedown:function(b,h){this.chart.pointer.normalize(b);b=this.chart;var c=b.xAxis[0],a=this.reversedExtremes;0===h?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=a?c.min:c.max):
(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=a?c.max:c.min);b.fixedRange=null},onMouseMove:function(b){var h=this,c=h.chart,a=h.left,k=h.navigatorSize,f=h.range,n=h.dragOffset,g=c.inverted;b.touches&&0===b.touches[0].pageX||(b=c.pointer.normalize(b),c=b.chartX,g&&(a=h.top,c=b.chartY),h.grabbedLeft?(h.hasDragged=!0,h.render(0,0,c-a,h.otherHandlePos)):h.grabbedRight?(h.hasDragged=!0,h.render(0,0,h.otherHandlePos,c-a)):h.grabbedCenter&&(h.hasDragged=!0,c<n?c=n:c>k+n-f&&
(c=k+n-f),h.render(0,0,c-n,c-n+f)),h.hasDragged&&h.scrollbar&&e(h.scrollbar.options.liveRedraw,r.svg&&!y&&!this.chart.isBoosting)&&(b.DOMType=b.type,setTimeout(function(){h.onMouseUp(b)},0)))},onMouseUp:function(b){var h=this.chart,c=this.xAxis,a=this.scrollbar,e=b.DOMEvent||b,k=h.inverted,f=this.rendered&&!this.hasDragged?"animate":"attr",n=Math.round(this.zoomedMax),g=Math.round(this.zoomedMin);if(this.hasDragged&&(!a||!a.hasDragged)||"scrollbar"===b.trigger){a=this.getUnionExtremes();if(this.zoomedMin===
this.otherHandlePos)var q=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var m=this.fixedExtreme;this.zoomedMax===this.size&&(m=this.reversedExtremes?a.dataMin:a.dataMax);0===this.zoomedMin&&(q=this.reversedExtremes?a.dataMax:a.dataMin);c=c.toFixedRange(this.zoomedMin,this.zoomedMax,q,m);l(c.min)&&h.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==b.DOMType&&"touchmove"!==
b.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(g,n,k,f),this.outline&&this.drawOutline(g,n,k,f),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(g,0,k,f),this.drawHandle(n,1,k,f)))},removeEvents:function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(b){b()}),this.eventsToUnbind=
void 0);this.removeBaseSeriesEvents()},removeBaseSeriesEvents:function(){var b=this.baseSeries||[];this.navigatorEnabled&&b[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&b.forEach(function(b){m(b,"updatedData",this.updatedDataHandler)},this),b[0].xAxis&&m(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))},init:function(b){var h=b.options,w=h.navigator,k=w.enabled,f=h.scrollbar,n=f.enabled;h=k?w.height:0;var g=n?f.height:0;this.handles=[];this.shades=[];this.chart=b;this.setBaseSeries();
this.height=h;this.scrollbarHeight=g;this.scrollbarEnabled=n;this.navigatorEnabled=k;this.navigatorOptions=w;this.scrollbarOptions=f;this.outlineHeight=h+g;this.opposite=e(w.opposite,!(k||!b.inverted));var q=this;k=q.baseSeries;f=b.xAxis.length;n=b.yAxis.length;var m=k&&k[0]&&k[0].xAxis||b.xAxis[0]||{options:{}};b.isDirtyBox=!0;q.navigatorEnabled?(q.xAxis=new c(b,a({breaks:m.options.breaks,ordinal:m.options.ordinal},w.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:f,
isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},b.inverted?{offsets:[g,0,-g,0],width:h}:{offsets:[0,-g,0,g],height:h})),q.yAxis=new c(b,a(w.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:n,isInternal:!0,zoomEnabled:!1},b.inverted?{width:h}:{height:h})),k||w.series.data?q.updateNavigatorSeries(!1):0===b.series.length&&(q.unbindRedraw=v(b,"beforeRedraw",function(){0<b.series.length&&!q.series&&(q.setBaseSeries(),q.unbindRedraw())})),
q.reversedExtremes=b.inverted&&!q.xAxis.reversed||!b.inverted&&q.xAxis.reversed,q.renderElements(),q.addMouseEvents()):q.xAxis={translate:function(h,c){var a=b.xAxis[0],e=a.getExtremes(),w=a.len-2*g,k=E("min",a.options.min,e.dataMin);a=E("max",a.options.max,e.dataMax)-k;return c?h*a/w+k:w*(h-k)/a},toPixels:function(b){return this.translate(b)},toValue:function(b){return this.translate(b,!0)},toFixedRange:c.prototype.toFixedRange,fake:!0};b.options.scrollbar.enabled&&(b.scrollbar=q.scrollbar=new C(b.renderer,
a(b.options.scrollbar,{margin:q.navigatorEnabled?0:10,vertical:b.inverted}),b),v(q.scrollbar,"changed",function(h){var c=q.size,a=c*this.to;c*=this.from;q.hasDragged=q.scrollbar.hasDragged;q.render(0,0,c,a);(b.options.scrollbar.liveRedraw||"mousemove"!==h.DOMType&&"touchmove"!==h.DOMType)&&setTimeout(function(){q.onMouseUp(h)})}));q.addBaseSeriesEvents();q.addChartEvents()},getUnionExtremes:function(b){var h=this.chart.xAxis[0],c=this.xAxis,a=c.options,k=h.options,f;b&&null===h.dataMin||(f={dataMin:e(a&&
a.min,E("min",k.min,h.dataMin,c.dataMin,c.min)),dataMax:e(a&&a.max,E("max",k.max,h.dataMax,c.dataMax,c.max))});return f},setBaseSeries:function(b,h){var c=this.chart,a=this.baseSeries=[];b=b||c.options&&c.options.navigator.baseSeries||(c.series.length?u(c.series,function(b){return!b.options.isInternal}).index:0);(c.series||[]).forEach(function(h,c){h.options.isInternal||!h.options.showInNavigator&&(c!==b&&h.options.id!==b||!1===h.options.showInNavigator)||a.push(h)});this.xAxis&&!this.xAxis.fake&&
this.updateNavigatorSeries(!0,h)},updateNavigatorSeries:function(b,h){var c=this,f=c.chart,n=c.baseSeries,q,g,y=c.navigatorOptions.series,d,u={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:!1,isInternal:!0,states:{inactive:{opacity:1}}},B=c.series=(c.series||[]).filter(function(b){var h=b.baseSeries;return 0>n.indexOf(h)?(h&&(m(h,"updatedData",c.updatedDataHandler),delete h.navigatorSeries),b.chart&&
b.destroy(),!1):!0});n&&n.length&&n.forEach(function(b){var w=b.navigatorSeries,z=t({color:b.color,visible:b.visible},x(y)?k.navigator.series:y);w&&!1===c.navigatorOptions.adaptToUpdatedData||(u.name="Navigator "+n.length,q=b.options||{},d=q.navigatorOptions||{},g=a(q,u,z,d),g.pointRange=e(z.pointRange,d.pointRange,k.plotOptions[g.type||"line"].pointRange),z=d.data||z.data,c.hasNavigatorData=c.hasNavigatorData||!!z,g.data=z||q.data&&q.data.slice(0),w&&w.options?w.update(g,h):(b.navigatorSeries=f.initSeries(g),
b.navigatorSeries.baseSeries=b,B.push(b.navigatorSeries)))});if(y.data&&(!n||!n.length)||x(y))c.hasNavigatorData=!1,y=I(y),y.forEach(function(b,h){u.name="Navigator "+(B.length+1);g=a(k.navigator.series,{color:f.series[h]&&!f.series[h].options.isInternal&&f.series[h].color||f.options.colors[h]||f.options.colors[0]},u,b);g.data=b.data;g.data&&(c.hasNavigatorData=!0,B.push(f.initSeries(g)))});b&&this.addBaseSeriesEvents()},addBaseSeriesEvents:function(){var b=this,h=b.baseSeries||[];h[0]&&h[0].xAxis&&
v(h[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);h.forEach(function(h){v(h,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(h,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&h.xAxis&&v(h,"updatedData",this.updatedDataHandler);v(h,"remove",function(){this.navigatorSeries&&(g(b.series,this.navigatorSeries),l(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},
this)},getBaseSeriesMin:function(b){return this.baseSeries.reduce(function(b,c){return Math.min(b,c.xData?c.xData[0]:b)},b)},modifyNavigatorAxisExtremes:function(){var b=this.xAxis,h;"undefined"!==typeof b.getExtremes&&(!(h=this.getUnionExtremes(!0))||h.dataMin===b.min&&h.dataMax===b.max||(b.min=h.dataMin,b.max=h.dataMax))},modifyBaseAxisExtremes:function(){var b=this.chart.navigator,h=this.getExtremes(),c=h.dataMin,a=h.dataMax;h=h.max-h.min;var k=b.stickToMin,n=b.stickToMax,q=e(this.options.overscroll,
0),g=b.series&&b.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(k){var y=c;var t=y+h}n&&(t=a+q,k||(y=Math.max(t-h,b.getBaseSeriesMin(g&&g.xData?g.xData[0]:-Number.MAX_VALUE))));m&&(k||n)&&f(y)&&(this.min=this.userMin=y,this.max=this.userMax=t)}b.stickToMin=b.stickToMax=null},updatedDataHandler:function(){var b=this.chart.navigator,h=this.navigatorSeries,c=b.getBaseSeriesMin(this.xData[0]);b.stickToMax=b.reversedExtremes?0===Math.round(b.zoomedMin):
Math.round(b.zoomedMax)>=Math.round(b.size);b.stickToMin=f(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!b.stickToMax);h&&!b.hasNavigatorData&&(h.options.pointStart=this.xData[0],h.setData(this.options.data,!1,null,!1))},addChartEvents:function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(v(this.chart,"redraw",function(){var b=this.navigator,h=b&&(b.baseSeries&&b.baseSeries[0]&&b.baseSeries[0].xAxis||b.scrollbar&&this.xAxis[0]);h&&b.render(h.min,h.max)}),
v(this.chart,"getMargins",function(){var b=this.navigator,h=b.opposite?"plotTop":"marginBottom";this.inverted&&(h=b.opposite?"marginRight":"plotLeft");this[h]=(this[h]||0)+(b.navigatorEnabled||!this.inverted?b.outlineHeight:0)+b.navigatorOptions.margin}))},destroy:function(){this.removeEvents();this.xAxis&&(g(this.chart.xAxis,this.xAxis),g(this.chart.axes,this.xAxis));this.yAxis&&(g(this.chart.yAxis,this.yAxis),g(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(b){b.destroy&&b.destroy()});
"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(b){this[b]&&this[b].destroy&&this[b].destroy();this[b]=null},this);[this.handles].forEach(function(b){H(b)},this)}};r.Navigator||(r.Navigator=D,v(c,"zoom",function(b){var h=this.chart.options,c=h.chart.zoomType,a=h.chart.pinchType,k=h.navigator;h=h.rangeSelector;this.isXAxis&&(k&&k.enabled||h&&h.enabled)&&("y"===c?b.zoomed=!1:(!y&&"xy"===c||y&&"xy"===a)&&
this.options.range&&(c=this.previousZoom,l(b.newMin)?this.previousZoom=[this.min,this.max]:c&&(b.newMin=c[0],b.newMax=c[1],delete this.previousZoom)));"undefined"!==typeof b.zoomed&&b.preventDefault()}),v(p,"beforeShowResetZoom",function(){var b=this.options,h=b.navigator,c=b.rangeSelector;if((h&&h.enabled||c&&c.enabled)&&(!y&&"x"===b.chart.zoomType||y&&"x"===b.chart.pinchType))return!1}),v(p,"beforeRender",function(){var b=this.options;if(b.navigator.enabled||b.scrollbar.enabled)this.scroller=this.navigator=
new D(this)}),v(p,"afterSetChartSize",function(){var b=this.legend,h=this.navigator;if(h){var c=b&&b.options;var a=h.xAxis;var k=h.yAxis;var f=h.scrollbarHeight;this.inverted?(h.left=h.opposite?this.chartWidth-f-h.height:this.spacing[3]+f,h.top=this.plotTop+f):(h.left=this.plotLeft+f,h.top=h.navigatorOptions.top||this.chartHeight-h.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?b.legendHeight+
e(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));a&&k&&(this.inverted?a.options.left=k.options.left=h.left:a.options.top=k.options.top=h.top,a.setAxisSize(),k.setAxisSize())}}),v(p,"update",function(b){var h=b.options.navigator||{},c=b.options.scrollbar||{};this.navigator||this.scroller||!h.enabled&&!c.enabled||(a(!0,this.options.navigator,h),a(!0,this.options.scrollbar,c),delete b.options.navigator,delete b.options.scrollbar)}),v(p,"afterUpdate",function(b){this.navigator||this.scroller||
!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new D(this),e(b.redraw,!0)&&this.redraw(b.animation))}),v(p,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),v(B,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),p.prototype.callbacks.push(function(b){var h=b.navigator;h&&b.xAxis[0]&&(b=b.xAxis[0].getExtremes(),h.render(b.min,b.max))}))});F(p,"parts/OrdinalAxis.js",
[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){var p=d.addEvent,C=d.css,D=d.defined,v=d.extend,G=d.pick,A=d.timeUnits,l=r.Axis;d=r.Chart;var J=r.noop;p(r.Series,"updatedData",function(){var g=this.xAxis;g&&g.options.ordinal&&delete g.ordinalIndex});l.prototype.getTimeTicks=function(g,t,d,x,f,a,e){var m=0,u,c,k={},n=[],y=-Number.MAX_VALUE,B=this.options.tickPixelInterval,E=this.chart.time,q=[];if(!this.options.ordinal&&!this.options.breaks||!f||3>f.length||"undefined"===typeof t)return E.getTimeTicks.apply(E,
arguments);var b=f.length;for(u=0;u<b;u++){var h=u&&f[u-1]>d;f[u]<t&&(m=u);if(u===b-1||f[u+1]-f[u]>5*a||h){if(f[u]>y){for(c=E.getTimeTicks(g,f[m],f[u],x);c.length&&c[0]<=y;)c.shift();c.length&&(y=c[c.length-1]);q.push(n.length);n=n.concat(c)}m=u+1}if(h)break}c=c.info;if(e&&c.unitRange<=A.hour){u=n.length-1;for(m=1;m<u;m++)if(E.dateFormat("%d",n[m])!==E.dateFormat("%d",n[m-1])){k[n[m]]="day";var w=!0}w&&(k[n[0]]="day");c.higherRanks=k}c.segmentStarts=q;n.info=c;if(e&&D(B)){m=q=n.length;w=[];var z;
for(E=[];m--;)u=this.translate(n[m]),z&&(E[m]=z-u),w[m]=z=u;E.sort();E=E[Math.floor(E.length/2)];E<.6*B&&(E=null);m=n[q-1]>d?q-1:q;for(z=void 0;m--;)u=w[m],q=Math.abs(z-u),z&&q<.8*B&&(null===E||q<.8*E)?(k[n[m]]&&!k[n[m+1]]?(q=m+1,z=u):q=m,n.splice(q,1)):z=u}return n};v(l.prototype,{beforeSetTickPositions:function(){var g=[],t,d=!1,x=this.getExtremes(),f=x.min,a=x.max,e,m=this.isXAxis&&!!this.options.breaks;x=this.options.ordinal;var l=Number.MAX_VALUE,c=this.chart.options.chart.ignoreHiddenSeries,
k;if(x||m){this.series.forEach(function(a,e){t=[];if(!(c&&!1===a.visible||!1===a.takeOrdinalPosition&&!m)&&(g=g.concat(a.processedXData),n=g.length,g.sort(function(c,b){return c-b}),l=Math.min(l,G(a.closestPointRange,l)),n)){for(e=0;e<n-1;)g[e]!==g[e+1]&&t.push(g[e+1]),e++;t[0]!==g[0]&&t.unshift(g[0]);g=t}a.isSeriesBoosting&&(k=!0)});k&&(g.length=0);var n=g.length;if(2<n){var y=g[1]-g[0];for(e=n-1;e--&&!d;)g[e+1]-g[e]!==y&&(d=!0);!this.options.keepOrdinalPadding&&(g[0]-f>y||a-g[g.length-1]>y)&&(d=
!0)}else this.options.overscroll&&(2===n?l=g[1]-g[0]:1===n?(l=this.options.overscroll,g=[g[0],g[0]+l]):l=this.overscrollPointsRange);d?(this.options.overscroll&&(this.overscrollPointsRange=l,g=g.concat(this.getOverscrollPositions())),this.ordinalPositions=g,y=this.ordinal2lin(Math.max(f,g[0]),!0),e=Math.max(this.ordinal2lin(Math.min(a,g[g.length-1]),!0),1),this.ordinalSlope=a=(a-f)/(e-y),this.ordinalOffset=f-y*a):(this.overscrollPointsRange=G(this.closestPointRange,this.overscrollPointsRange),this.ordinalPositions=
this.ordinalSlope=this.ordinalOffset=void 0)}this.isOrdinal=x&&d;this.groupIntervalFactor=null},val2lin:function(g,d){var t=this.ordinalPositions;if(t){var x=t.length,f;for(f=x;f--;)if(t[f]===g){var a=f;break}for(f=x-1;f--;)if(g>t[f]||0===f){g=(g-t[f])/(t[f+1]-t[f]);a=f+g;break}d=d?a:this.ordinalSlope*(a||0)+this.ordinalOffset}else d=g;return d},lin2val:function(g,d){var t=this.ordinalPositions;if(t){var x=this.ordinalSlope,f=this.ordinalOffset,a=t.length-1;if(d)if(0>g)g=t[0];else if(g>a)g=t[a];else{a=
Math.floor(g);var e=g-a}else for(;a--;)if(d=x*a+f,g>=d){x=x*(a+1)+f;e=(g-d)/(x-d);break}return"undefined"!==typeof e&&"undefined"!==typeof t[a]?t[a]+(e?e*(t[a+1]-t[a]):0):g}return g},getExtendedPositions:function(){var g=this,d=g.chart,u=g.series[0].currentDataGrouping,x=g.ordinalIndex,f=u?u.count+u.unitName:"raw",a=g.options.overscroll,e=g.getExtremes(),m;x||(x=g.ordinalIndex={});if(!x[f]){var A={series:[],chart:d,getExtremes:function(){return{min:e.dataMin,max:e.dataMax+a}},options:{ordinal:!0},
val2lin:l.prototype.val2lin,ordinal2lin:l.prototype.ordinal2lin};g.series.forEach(function(c){m={xAxis:A,xData:c.xData.slice(),chart:d,destroyGroupedData:J};m.xData=m.xData.concat(g.getOverscrollPositions());m.options={dataGrouping:u?{enabled:!0,forced:!0,approximation:"open",units:[[u.unitName,[u.count]]]}:{enabled:!1}};c.processData.apply(m);A.series.push(m)});g.beforeSetTickPositions.apply(A);x[f]=A.ordinalPositions}return x[f]},getOverscrollPositions:function(){var g=this.options.overscroll,d=
this.overscrollPointsRange,u=[],x=this.dataMax;if(D(d))for(u.push(x);x<=this.dataMax+g;)x+=d,u.push(x);return u},getGroupIntervalFactor:function(g,d,u){u=u.processedXData;var t=u.length,f=[];var a=this.groupIntervalFactor;if(!a){for(a=0;a<t-1;a++)f[a]=u[a+1]-u[a];f.sort(function(a,f){return a-f});f=f[Math.floor(t/2)];g=Math.max(g,u[0]);d=Math.min(d,u[t-1]);this.groupIntervalFactor=a=t*f/(d-g)}return a},postProcessTickInterval:function(g){var d=this.ordinalSlope;return d?this.options.breaks?this.closestPointRange||
g:g/(d/this.closestPointRange):g}});l.prototype.ordinal2lin=l.prototype.val2lin;p(d,"pan",function(g){var d=this.xAxis[0],u=d.options.overscroll,x=g.originalEvent.chartX,f=this.options.chart&&this.options.chart.panning,a=!1;if(f&&"y"!==f.type&&d.options.ordinal&&d.series.length){var e=this.mouseDownX,m=d.getExtremes(),l=m.dataMax,c=m.min,k=m.max,n=this.hoverPoints,y=d.closestPointRange||d.overscrollPointsRange;e=(e-x)/(d.translationSlope*(d.ordinalSlope||y));var B={ordinalPositions:d.getExtendedPositions()};
y=d.lin2val;var E=d.val2lin;if(!B.ordinalPositions)a=!0;else if(1<Math.abs(e)){n&&n.forEach(function(b){b.setState()});if(0>e){n=B;var q=d.ordinalPositions?d:B}else n=d.ordinalPositions?d:B,q=B;B=q.ordinalPositions;l>B[B.length-1]&&B.push(l);this.fixedRange=k-c;e=d.toFixedRange(null,null,y.apply(n,[E.apply(n,[c,!0])+e,!0]),y.apply(q,[E.apply(q,[k,!0])+e,!0]));e.min>=Math.min(m.dataMin,c)&&e.max<=Math.max(l,k)+u&&d.setExtremes(e.min,e.max,!0,!1,{trigger:"pan"});this.mouseDownX=x;C(this.container,{cursor:"move"})}}else a=
!0;a||f&&/y/.test(f.type)?u&&(d.max=d.dataMax+u):g.preventDefault()});p(l,"foundExtremes",function(){this.isXAxis&&D(this.options.overscroll)&&this.max===this.dataMax&&(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&D(this.userMin)&&(this.min+=this.options.overscroll))});p(l,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&
!this.chart.navigator.adaptToUpdatedData)})});F(p,"modules/broken-axis.src.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){var p=d.addEvent,C=d.extend,D=d.find,v=d.fireEvent,G=d.isArray,A=d.pick,l=r.Axis;d=r.Series;var J=function(g,d){return D(d,function(d){return d.from<g&&g<d.to})};C(l.prototype,{isInBreak:function(g,d){var u=g.repeat||Infinity,t=g.from,f=g.to-g.from;d=d>=t?(d-t)%u:u-(t-d)%u;return g.inclusive?d<=f:d<f&&0!==d},isInAnyBreak:function(g,d){var t=this.options.breaks,
l=t&&t.length,f;if(l){for(;l--;)if(this.isInBreak(t[l],g)){var a=!0;f||(f=A(t[l].showPoints,!this.isXAxis))}var e=a&&d?a&&!f:a}return e}});p(l,"afterInit",function(){"function"===typeof this.setBreaks&&this.setBreaks(this.options.breaks,!1)});p(l,"afterSetTickPositions",function(){if(this.isBroken){var g=this.tickPositions,d=this.tickPositions.info,u=[],l;for(l=0;l<g.length;l++)this.isInAnyBreak(g[l])||u.push(g[l]);this.tickPositions=u;this.tickPositions.info=d}});p(l,"afterSetOptions",function(){this.isBroken&&
(this.options.ordinal=!1)});l.prototype.setBreaks=function(g,d){function t(a){var e=a,g;for(g=0;g<f.breakArray.length;g++){var c=f.breakArray[g];if(c.to<=a)e-=c.len;else if(c.from>=a)break;else if(f.isInBreak(c,a)){e-=a-c.from;break}}return e}function x(a){var e;for(e=0;e<f.breakArray.length;e++){var g=f.breakArray[e];if(g.from>=a)break;else g.to<a?a+=g.len:f.isInBreak(g,a)&&(a+=g.len)}return a}var f=this,a=G(g)&&!!g.length;f.isDirty=f.isBroken!==a;f.isBroken=a;f.options.breaks=f.userOptions.breaks=
g;f.forceRedraw=!0;f.series.forEach(function(a){a.isDirty=!0});a||f.val2lin!==t||(delete f.val2lin,delete f.lin2val);a&&(f.userOptions.ordinal=!1,f.val2lin=t,f.lin2val=x,f.setExtremes=function(a,f,g,c,k){if(this.isBroken){for(var e,d=this.options.breaks;e=J(a,d);)a=e.to;for(;e=J(f,d);)f=e.from;f<a&&(f=a)}l.prototype.setExtremes.call(this,a,f,g,c,k)},f.setAxisTranslation=function(a){l.prototype.setAxisTranslation.call(this,a);this.unitLength=null;if(this.isBroken){a=f.options.breaks;var e=[],g=[],
c=0,k,n=f.userMin||f.min,d=f.userMax||f.max,t=A(f.pointRangePadding,0),u;a.forEach(function(b){k=b.repeat||Infinity;f.isInBreak(b,n)&&(n+=b.to%k-n%k);f.isInBreak(b,d)&&(d-=d%k-b.from%k)});a.forEach(function(h){b=h.from;for(k=h.repeat||Infinity;b-k>n;)b-=k;for(;b<n;)b+=k;for(u=b;u<d;u+=k)e.push({value:u,move:"in"}),e.push({value:u+(h.to-h.from),move:"out",size:h.breakSize})});e.sort(function(b,c){return b.value===c.value?("in"===b.move?0:1)-("in"===c.move?0:1):b.value-c.value});var q=0;var b=n;e.forEach(function(h){q+=
"in"===h.move?1:-1;1===q&&"in"===h.move&&(b=h.value);0===q&&(g.push({from:b,to:h.value,len:h.value-b-(h.size||0)}),c+=h.value-b-(h.size||0))});f.breakArray=g;f.unitLength=d-n-c+t;v(f,"afterBreaks");f.staticScale?f.transA=f.staticScale:f.unitLength&&(f.transA*=(d-f.min+t)/f.unitLength);t&&(f.minPixelPadding=f.transA*f.minPointOffset);f.min=n;f.max=d}});A(d,!0)&&this.chart.redraw()};p(d,"afterGeneratePoints",function(){var g=this.options.connectNulls,d=this.points,u=this.xAxis,l=this.yAxis;if(this.isDirty)for(var f=
d.length;f--;){var a=d[f],e=!(null===a.y&&!1===g)&&(u&&u.isInAnyBreak(a.x,!0)||l&&l.isInAnyBreak(a.y,!0));a.visible=e?!1:!1!==a.options.visible}});p(d,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,A(this.pointArrayMap,["y"]))});r.Series.prototype.drawBreaks=function(g,d){var t=this,l=t.points,f,a,e,m;g&&d.forEach(function(d){f=g.breakArray||[];a=g.isXAxis?g.min:A(t.options.threshold,g.min);l.forEach(function(c){m=A(c["stack"+d.toUpperCase()],c[d]);f.forEach(function(k){e=
!1;if(a<k.from&&m>k.to||a>k.from&&m<k.from)e="pointBreak";else if(a<k.from&&m>k.from&&m<k.to||a>k.from&&m>k.to&&m<k.from)e="pointInBreak";e&&v(g,e,{point:c,brk:k})})})})};r.Series.prototype.gappedPath=function(){var g=this.currentDataGrouping,d=g&&g.gapSize;g=this.options.gapSize;var l=this.points.slice(),A=l.length-1,f=this.yAxis,a;if(g&&0<A)for("value"!==this.options.gapUnit&&(g*=this.basePointRange),d&&d>g&&d>=this.basePointRange&&(g=d),a=void 0;A--;)a&&!1!==a.visible||(a=l[A+1]),d=l[A],!1!==a.visible&&
!1!==d.visible&&(a.x-d.x>g&&(a=(d.x+a.x)/2,l.splice(A+1,0,{isNull:!0,x:a}),this.options.stacking&&(a=f.stacks[this.stackKey][a]=new r.StackItem(f,f.options.stackLabels,!1,a,this.stack),a.total=0)),a=d);return this.getGraphPath(l)}});F(p,"masters/modules/broken-axis.src.js",[],function(){});F(p,"parts/DataGrouping.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["parts/Tooltip.js"]],function(r,d,p){var C=d.addEvent,D=d.arrayMax,v=d.arrayMin,G=d.correctFloat,A=d.defined,l=d.error,J=d.extend,g=d.format,
t=d.isNumber,u=d.merge,x=d.pick,f=r.Axis,a=r.defaultPlotOptions;d=r.Point;var e=r.Series,m=r.approximations={sum:function(b){var c=b.length;if(!c&&b.hasNulls)var a=null;else if(c)for(a=0;c--;)a+=b[c];return a},average:function(b){var c=b.length;b=m.sum(b);t(b)&&c&&(b=G(b/c));return b},averages:function(){var b=[];[].forEach.call(arguments,function(c){b.push(m.average(c))});return"undefined"===typeof b[0]?void 0:b},open:function(b){return b.length?b[0]:b.hasNulls?null:void 0},high:function(b){return b.length?
D(b):b.hasNulls?null:void 0},low:function(b){return b.length?v(b):b.hasNulls?null:void 0},close:function(b){return b.length?b[b.length-1]:b.hasNulls?null:void 0},ohlc:function(b,c,a,k){b=m.open(b);c=m.high(c);a=m.low(a);k=m.close(k);if(t(b)||t(c)||t(a)||t(k))return[b,c,a,k]},range:function(b,c){b=m.low(b);c=m.high(c);if(t(b)||t(c))return[b,c];if(null===b&&null===c)return null}},I=function(b,c,a,k){var h=this,f=h.data,e=h.options&&h.options.data,n=[],d=[],g=[],q=b.length,w=!!c,z=[],y=h.pointArrayMap,
l=y&&y.length,B=["x"].concat(y||["y"]),E=0,p=0,r;k="function"===typeof k?k:m[k]?m[k]:m[h.getDGApproximation&&h.getDGApproximation()||"average"];l?y.forEach(function(){z.push([])}):z.push([]);var x=l||1;for(r=0;r<=q&&!(b[r]>=a[0]);r++);for(r;r<=q;r++){for(;"undefined"!==typeof a[E+1]&&b[r]>=a[E+1]||r===q;){var v=a[E];h.dataGroupInfo={start:h.cropStart+p,length:z[0].length};var D=k.apply(h,z);h.pointClass&&!A(h.dataGroupInfo.options)&&(h.dataGroupInfo.options=u(h.pointClass.prototype.optionsToObject.call({series:h},
h.options.data[h.cropStart+p])),B.forEach(function(b){delete h.dataGroupInfo.options[b]}));"undefined"!==typeof D&&(n.push(v),d.push(D),g.push(h.dataGroupInfo));p=r;for(v=0;v<x;v++)z[v].length=0,z[v].hasNulls=!1;E+=1;if(r===q)break}if(r===q)break;if(y)for(v=h.cropStart+r,D=f&&f[v]||h.pointClass.prototype.applyOptions.apply({series:h},[e[v]]),v=0;v<l;v++){var G=D[y[v]];t(G)?z[v].push(G):null===G&&(z[v].hasNulls=!0)}else v=w?c[r]:null,t(v)?z[0].push(v):null===v&&(z[0].hasNulls=!0)}return{groupedXData:n,
groupedYData:d,groupMap:g}},c={approximations:m,groupData:I},k=e.prototype,n=k.processData,y=k.generatePoints,B={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e",
"-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},E={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},q=r.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];k.getDGApproximation=function(){return this.is("arearange")?
"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};k.groupData=I;k.processData=function(){var b=this.chart,c=this.options.dataGrouping,a=!1!==this.allowDG&&c&&x(c.enabled,b.options.isStock),f=this.visible||!b.options.chart.ignoreHiddenSeries,e,d=this.currentDataGrouping,g=!1;this.forceCrop=a;this.groupPixelWidth=null;this.hasProcessed=!0;a&&!this.requireSorting&&(this.requireSorting=g=!0);a=!1===n.apply(this,arguments)||!a;g&&(this.requireSorting=!1);if(!a){this.destroyGroupedData();
a=c.groupAll?this.xData:this.processedXData;var m=c.groupAll?this.yData:this.processedYData,y=b.plotSizeX;b=this.xAxis;var l=b.options.ordinal,t=this.groupPixelWidth=b.getGroupPixelWidth&&b.getGroupPixelWidth();if(t){this.isDirty=e=!0;this.points=null;g=b.getExtremes();var B=g.min;g=g.max;l=l&&b.getGroupIntervalFactor(B,g,this)||1;t=t*(g-B)/y*l;y=b.getTimeTicks(b.normalizeTimeTickInterval(t,c.units||q),Math.min(B,a[0]),Math.max(g,a[a.length-1]),b.options.startOfWeek,a,this.closestPointRange);m=k.groupData.apply(this,
[a,m,y,c.approximation]);a=m.groupedXData;l=m.groupedYData;var u=0;if(c.smoothed&&a.length){var v=a.length-1;for(a[v]=Math.min(a[v],g);v--&&0<v;)a[v]+=t/2;a[0]=Math.max(a[0],B)}for(v=1;v<y.length;v++)y.info.segmentStarts&&-1!==y.info.segmentStarts.indexOf(v)||(u=Math.max(y[v]-y[v-1],u));B=y.info;B.gapSize=u;this.closestPointRange=y.info.totalRange;this.groupMap=m.groupMap;if(A(a[0])&&a[0]<b.min&&f){if(!A(b.options.min)&&b.min<=b.dataMin||b.min===b.dataMin)b.min=Math.min(a[0],b.min);b.dataMin=Math.min(a[0],
b.dataMin)}c.groupAll&&(c=this.cropData(a,l,b.min,b.max,1),a=c.xData,l=c.yData);this.processedXData=a;this.processedYData=l}else this.groupMap=null;this.hasGroupedData=e;this.currentDataGrouping=B;this.preventGraphAnimation=(d&&d.totalRange)!==(B&&B.totalRange)}};k.destroyGroupedData=function(){this.groupedData&&(this.groupedData.forEach(function(b,c){b&&(this.groupedData[c]=b.destroy?b.destroy():null)},this),this.groupedData.length=0)};k.generatePoints=function(){y.apply(this);this.destroyGroupedData();
this.groupedData=this.hasGroupedData?this.points:null};C(d,"update",function(){if(this.dataGroup)return l(24,!1,this.series.chart),!1});C(p,"headerFormatter",function(b){var c=this.chart,a=c.time,k=b.labelConfig,f=k.series,e=f.tooltipOptions,n=f.options.dataGrouping,d=e.xDateFormat,q=f.xAxis,y=e[(b.isFooter?"footer":"header")+"Format"];if(q&&"datetime"===q.options.type&&n&&t(k.key)){var m=f.currentDataGrouping;n=n.dateTimeLabelFormats||B.dateTimeLabelFormats;if(m)if(e=n[m.unitName],1===m.count)d=
e[0];else{d=e[1];var l=e[2]}else!d&&n&&(d=this.getXDateFormat(k,e,q));d=a.dateFormat(d,k.key);l&&(d+=a.dateFormat(l,k.key+m.totalRange-1));f.chart.styledMode&&(y=this.styledModeFormat(y));b.text=g(y,{point:J(k.point,{key:d}),series:f},c);b.preventDefault()}});C(e,"destroy",k.destroyGroupedData);C(e,"afterSetOptions",function(b){b=b.options;var c=this.type,k=this.chart.options.plotOptions,f=a[c].dataGrouping,e=this.useCommonDataGrouping&&B;if(E[c]||e)f||(f=u(B,E[c])),b.dataGrouping=u(e,f,k.series&&
k.series.dataGrouping,k[c].dataGrouping,this.userOptions.dataGrouping)});C(f,"afterSetScale",function(){this.series.forEach(function(b){b.hasProcessed=!1})});f.prototype.getGroupPixelWidth=function(){var b=this.series,c=b.length,a,k=0,f=!1,e;for(a=c;a--;)(e=b[a].options.dataGrouping)&&(k=Math.max(k,x(e.groupPixelWidth,B.groupPixelWidth)));for(a=c;a--;)(e=b[a].options.dataGrouping)&&b[a].hasProcessed&&(c=(b[a].processedXData||b[a].data).length,b[a].groupPixelWidth||c>this.chart.plotSizeX/k||c&&e.forced)&&
(f=!0);return f?k:0};f.prototype.setDataGrouping=function(b,c){var a;c=x(c,!0);b||(b={forced:!1,units:null});if(this instanceof f)for(a=this.series.length;a--;)this.series[a].update({dataGrouping:b},!1);else this.chart.options.series.forEach(function(c){c.dataGrouping=b},!1);this.ordinalSlope=null;c&&this.chart.redraw()};r.dataGrouping=c;"";return c});F(p,"parts/OHLCSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){d=d.seriesType;var p=r.Point,C=r.seriesTypes;d("ohlc","column",
{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,pointArrayMap:["open","high","low","close"],toYData:function(d){return[d.open,d.high,d.low,d.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){C.column.prototype.init.apply(this,
arguments);this.options.stacking=!1},pointAttribs:function(d,v){v=C.column.prototype.pointAttribs.call(this,d,v);var r=this.options;delete v.fill;!d.options.color&&r.upColor&&d.open<d.close&&(v.stroke=r.upColor);return v},translate:function(){var d=this,v=d.yAxis,r=!!d.modifyValue,A=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];C.column.prototype.translate.apply(d);d.points.forEach(function(l){[l.open,l.high,l.low,l.close,l.low].forEach(function(p,g){null!==p&&(r&&(p=d.modifyValue(p)),l[A[g]]=
v.toPixels(p,!0))});l.tooltipPos[1]=l.plotHigh+v.pos-d.chart.plotTop})},drawPoints:function(){var d=this,v=d.chart,r=function(d,l,v){d[2]=Math.max(v+l,d[2]);d[5]=Math.min(v-l,d[5])};d.points.forEach(function(p){var l=p.graphic,A=!l;if("undefined"!==typeof p.plotY){l||(p.graphic=l=v.renderer.path().add(d.group));v.styledMode||l.attr(d.pointAttribs(p,p.selected&&"select"));var g=l.strokeWidth();var t=g%2/2;var u=Math.round(p.plotX)-t;var x=Math.round(p.shapeArgs.width/2);var f=["M",u,Math.round(p.yBottom),
"L",u,Math.round(p.plotHigh)];if(null!==p.open){var a=Math.round(p.plotOpen)+t;f.push("M",u,a,"L",u-x,a);r(f,g/2,a)}null!==p.close&&(a=Math.round(p.plotClose)+t,f.push("M",u,a,"L",u+x,a),r(f,g/2,a));l[A?"attr":"animate"]({d:f}).addClass(p.getClassName(),!0)}})},animate:null},{getClassName:function(){return p.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});F(p,"parts/CandlestickSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],
function(p,d){var r=d.merge;d=d.seriesType;var C=p.defaultPlotOptions,D=p.seriesTypes;d("candlestick","ohlc",r(C.column,{states:{hover:{lineWidth:2}},tooltip:C.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(d,p){var r=D.column.prototype.pointAttribs.call(this,d,p),l=this.options,v=d.open<d.close,g=l.lineColor||this.color;r["stroke-width"]=l.lineWidth;r.fill=d.options.color||(v?l.upColor||this.color:this.color);r.stroke=d.options.lineColor||
(v?l.upLineColor||g:g);p&&(d=l.states[p],r.fill=d.color||r.fill,r.stroke=d.lineColor||r.stroke,r["stroke-width"]=d.lineWidth||r["stroke-width"]);return r},drawPoints:function(){var d=this,p=d.chart,r=d.yAxis.reversed;d.points.forEach(function(l){var v=l.graphic,g=!v;if("undefined"!==typeof l.plotY){v||(l.graphic=v=p.renderer.path().add(d.group));d.chart.styledMode||v.attr(d.pointAttribs(l,l.selected&&"select")).shadow(d.options.shadow);var t=v.strokeWidth()%2/2;var u=Math.round(l.plotX)-t;var x=l.plotOpen;
var f=l.plotClose;var a=Math.min(x,f);x=Math.max(x,f);var e=Math.round(l.shapeArgs.width/2);f=r?x!==l.yBottom:Math.round(a)!==Math.round(l.plotHigh);var m=r?Math.round(a)!==Math.round(l.plotHigh):x!==l.yBottom;a=Math.round(a)+t;x=Math.round(x)+t;t=[];t.push("M",u-e,x,"L",u-e,a,"L",u+e,a,"L",u+e,x,"Z","M",u,a,"L",u,f?Math.round(r?l.yBottom:l.plotHigh):a,"M",u,x,"L",u,m?Math.round(r?l.plotHigh:l.yBottom):x);v[g?"attr":"animate"]({d:t}).addClass(l.getClassName(),!0)}})}});""});F(p,"mixins/on-series.js",
[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){var p=d.defined,C=d.stableSort,D=r.seriesTypes;return{getPlotBox:function(){return r.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){D.column.prototype.translate.apply(this);var d=this,r=d.options,A=d.chart,l=d.points,H=l.length-1,g,t=r.onSeries;t=t&&A.get(t);r=r.onKey||"y";var u=t&&t.options.step,x=t&&t.points,f=x&&x.length,a=A.inverted,e=d.xAxis,m=d.yAxis,I=0,
c;if(t&&t.visible&&f){I=(t.pointXOffset||0)+(t.barW||0)/2;A=t.currentDataGrouping;var k=x[f-1].x+(A?A.totalRange:0);C(l,function(c,a){return c.x-a.x});for(r="plot"+r[0].toUpperCase()+r.substr(1);f--&&l[H];){var n=x[f];A=l[H];A.y=n.y;if(n.x<=A.x&&"undefined"!==typeof n[r]){if(A.x<=k&&(A.plotY=n[r],n.x<A.x&&!u&&(c=x[f+1])&&"undefined"!==typeof c[r])){var y=(A.x-n.x)/(c.x-n.x);A.plotY+=y*(c[r]-n[r]);A.y+=y*(c.y-n.y)}H--;f++;if(0>H)break}}}l.forEach(function(c,k){c.plotX+=I;if("undefined"===typeof c.plotY||
a)0<=c.plotX&&c.plotX<=e.len?a?(c.plotY=e.translate(c.x,0,1,0,1),c.plotX=p(c.y)?m.translate(c.y,0,0,0,1):0):c.plotY=(e.opposite?0:d.yAxis.len)+e.offset:c.shapeArgs={};if((g=l[k-1])&&g.plotX===c.plotX){"undefined"===typeof g.stackIndex&&(g.stackIndex=0);var f=g.stackIndex+1}c.stackIndex=f});this.onSeries=t}}});F(p,"parts/FlagsSeries.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["mixins/on-series.js"]],function(r,d,p){function C(d){a[d+"pin"]=function(f,e,c,k,n){var g=n&&n.anchorX;n=n&&n.anchorY;
"circle"===d&&k>c&&(f-=Math.round((k-c)/2),c=k);var m=a[d](f,e,c,k);g&&n&&(m.push("M","circle"===d?f+c/2:m[1]+m[4]/2,e>n?e:e+k,"L",g,n),m=m.concat(a.circle(g-1,n-1,2,2)));return m}}var D=d.addEvent,v=d.defined,H=d.isNumber,A=d.merge,l=d.objectEach,F=d.seriesType,g=d.wrap;d=r.noop;var t=r.Renderer,u=r.Series,x=r.TrackerMixin,f=r.VMLRenderer,a=r.SVGRenderer.prototype.symbols;F("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},
threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:u.prototype.init,pointAttribs:function(a,d){var f=this.options,c=a&&a.color||this.color,k=f.lineColor,e=a&&a.lineWidth;a=a&&a.fillColor||f.fillColor;d&&(a=f.states[d].fillColor,k=f.states[d].lineColor,e=f.states[d].lineWidth);return{fill:a||
c,stroke:k||c,"stroke-width":e||f.lineWidth||0}},translate:p.translate,getPlotBox:p.getPlotBox,drawPoints:function(){var a=this.points,d=this.chart,f=d.renderer,c=d.inverted,k=this.options,n=k.y,y,t=this.yAxis,p={},q=[];for(y=a.length;y--;){var b=a[y];var h=(c?b.plotY:b.plotX)>this.xAxis.len;var w=b.plotX;var z=b.stackIndex;var u=b.options.shape||k.shape;var x=b.plotY;"undefined"!==typeof x&&(x=b.plotY+n-("undefined"!==typeof z&&z*k.stackDistance));b.anchorX=z?void 0:b.plotX;var U=z?void 0:b.plotY;
var R="flag"!==u;z=b.graphic;"undefined"!==typeof x&&0<=w&&!h?(z||(z=b.graphic=f.label("",null,null,u,null,null,k.useHTML),d.styledMode||z.attr(this.pointAttribs(b)).css(A(k.style,b.style)),z.attr({align:R?"center":"left",width:k.width,height:k.height,"text-align":k.textAlign}).addClass("highcharts-point").add(this.markerGroup),b.graphic.div&&(b.graphic.div.point=b),d.styledMode||z.shadow(k.shadow),z.isNew=!0),0<w&&(w-=z.strokeWidth()%2),u={y:x,anchorY:U},k.allowOverlapX&&(u.x=w,u.anchorX=b.anchorX),
z.attr({text:b.options.title||k.title||"A"})[z.isNew?"attr":"animate"](u),k.allowOverlapX||(p[b.plotX]?p[b.plotX].size=Math.max(p[b.plotX].size,z.width):p[b.plotX]={align:R?.5:0,size:z.width,target:w,anchorX:w}),b.tooltipPos=[w,x+t.pos-d.plotTop]):z&&(b.graphic=z.destroy())}k.allowOverlapX||(l(p,function(b){b.plotX=b.anchorX;q.push(b)}),r.distribute(q,c?t.len:this.xAxis.len,100),a.forEach(function(b){var c=b.graphic&&p[b.plotX];c&&(b.graphic[b.graphic.isNew?"attr":"animate"]({x:c.pos+c.align*c.size,
anchorX:b.anchorX}),v(c.pos)?b.graphic.isNew=!1:(b.graphic.attr({x:-9999,anchorX:-9999}),b.graphic.isNew=!0))}));k.useHTML&&g(this.markerGroup,"on",function(b){return r.SVGElement.prototype.on.apply(b.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var a=this.points;x.drawTrackerPoint.apply(this);a.forEach(function(d){var f=d.graphic;f&&D(f.element,"mouseover",function(){0<d.stackIndex&&!d.raised&&(d._y=f.y,f.attr({y:d._y-8}),d.raised=!0);a.forEach(function(c){c!==
d&&c.raised&&c.graphic&&(c.graphic.attr({y:c._y}),c.raised=!1)})})})},animate:function(a){a?this.setClip():this.animate=null},setClip:function(){u.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:d,invertGroups:d},{isValid:function(){return H(this.y)||"undefined"===typeof this.y}});a.flag=function(d,f,g,c,k){var e=k&&k.anchorX||d;k=k&&k.anchorY||f;return a.circle(e-1,k-1,2,2).concat(["M",e,k,"L",
d,f+c,d,f,d+g,f,d+g,f+c,d,f+c,"Z"])};C("circle");C("square");t===f&&["circlepin","flag","squarepin"].forEach(function(d){f.prototype.symbols[d]=a[d]});""});F(p,"parts/RangeSelector.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){function p(c){this.init(c)}var C=d.addEvent,D=d.createElement,v=d.css,G=d.defined,A=d.destroyObjectProperties,l=d.discardElement,F=d.extend,g=d.fireEvent,t=d.isNumber,u=d.merge,x=d.objectEach,f=d.pick,a=d.pInt,e=d.splat,m=r.Axis;d=r.Chart;var I=r.defaultOptions;
F(I,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});I.lang=u(I.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});p.prototype={clickButton:function(c,a){var d=this.chart,k=this.buttonOptions[c],g=d.xAxis[0],l=d.scroller&&d.scroller.getUnionExtremes()||g||{},q=l.dataMin,b=l.dataMax,h=g&&Math.round(Math.min(g.max,
f(b,g.max))),w=k.type;l=k._range;var z,p=k.dataGrouping;if(null!==q&&null!==b){d.fixedRange=l;p&&(this.forcedDataGrouping=!0,m.prototype.setDataGrouping.call(g||{chart:this.chart},p,!1),this.frozenStates=k.preserveDataGrouping);if("month"===w||"year"===w)if(g){w={range:k,max:h,chart:d,dataMin:q,dataMax:b};var r=g.minFromRange.call(w);t(w.newMax)&&(h=w.newMax)}else l=k;else if(l)r=Math.max(h-l,q),h=Math.min(r+l,b);else if("ytd"===w)if(g)"undefined"===typeof b&&(q=Number.MAX_VALUE,b=Number.MIN_VALUE,
d.series.forEach(function(c){c=c.xData;q=Math.min(c[0],q);b=Math.max(c[c.length-1],b)}),a=!1),h=this.getYTDExtremes(b,q,d.time.useUTC),r=z=h.min,h=h.max;else{this.deferredYTDClick=c;return}else"all"===w&&g&&(r=q,h=b);r+=k._offsetMin;h+=k._offsetMax;this.setSelected(c);if(g)g.setExtremes(r,h,f(a,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:k});else{var u=e(d.options.xAxis)[0];var v=u.range;u.range=l;var x=u.min;u.min=z;C(d,"load",function(){u.range=v;u.min=x})}}},setSelected:function(c){this.selected=
this.options.selected=c},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(c){var a=this,d=c.options.rangeSelector,f=d.buttons||[].concat(a.defaultButtons),e=d.selected,l=function(){var c=a.minInput,b=a.maxInput;c&&c.blur&&g(c,"blur");b&&b.blur&&g(b,"blur")};a.chart=c;a.options=d;a.buttons=[];a.buttonOptions=f;this.unMouseDown=C(c.container,
"mousedown",l);this.unResize=C(c,"resize",l);f.forEach(a.computeButtonRange);"undefined"!==typeof e&&f[e]&&this.clickButton(e,!1);C(c,"load",function(){c.xAxis&&c.xAxis[0]&&C(c.xAxis[0],"setExtremes",function(d){this.max-this.min!==c.fixedRange&&"rangeSelectorButton"!==d.trigger&&"updatedData"!==d.trigger&&a.forcedDataGrouping&&!a.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var c=this,a=this.chart,d=a.xAxis[0],f=Math.round(d.max-d.min),g=!d.hasVisibleSeries,e=a.scroller&&
a.scroller.getUnionExtremes()||d,q=e.dataMin,b=e.dataMax;a=c.getYTDExtremes(b,q,a.time.useUTC);var h=a.min,l=a.max,z=c.selected,m=t(z),p=c.options.allButtonsEnabled,r=c.buttons;c.buttonOptions.forEach(function(a,k){var e=a._range,n=a.type,w=a.count||1,y=r[k],u=0,t=a._offsetMax-a._offsetMin;a=k===z;var v=e>b-q,x=e<d.minRange,B=!1,E=!1;e=e===f;("month"===n||"year"===n)&&f+36E5>=864E5*{month:28,year:365}[n]*w-t&&f-36E5<=864E5*{month:31,year:366}[n]*w+t?e=!0:"ytd"===n?(e=l-h+t===f,B=!a):"all"===n&&(e=
d.max-d.min>=b-q,E=!a&&m&&e);n=!p&&(v||x||E||g);w=a&&e||e&&!m&&!B||a&&c.frozenStates;n?u=3:w&&(m=!0,u=2);y.state!==u&&(y.setState(u),0===u&&z===k&&c.setSelected(null))})},computeButtonRange:function(c){var a=c.type,d=c.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[a])c._range=e[a]*d;else if("month"===a||"year"===a)c._range=864E5*{month:30,year:365}[a]*d;c._offsetMin=f(c.offsetMin,0);c._offsetMax=f(c.offsetMax,0);c._range+=c._offsetMax-c._offsetMin},setInputValue:function(c,
a){var d=this.chart.options.rangeSelector,f=this.chart.time,k=this[c+"Input"];G(a)&&(k.previousValue=k.HCTime,k.HCTime=a);k.value=f.dateFormat(d.inputEditDateFormat||"%Y-%m-%d",k.HCTime);this[c+"DateBox"].attr({text:f.dateFormat(d.inputDateFormat||"%b %e, %Y",k.HCTime)})},showInput:function(c){var a=this.inputGroup,d=this[c+"DateBox"];v(this[c+"Input"],{left:a.translateX+d.x+"px",top:a.translateY+"px",width:d.width-2+"px",height:d.height-2+"px",border:"2px solid silver"})},hideInput:function(c){v(this[c+
"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(c)},drawInput:function(c){function d(){var b=w.value,c=(q.inputDateParser||Date.parse)(b),d=e.xAxis[0],k=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:d,g=k.dataMin;k=k.dataMax;c!==w.previousValue&&(w.previousValue=c,t(c)||(c=b.split("-"),c=Date.UTC(a(c[0]),a(c[1])-1,a(c[2]))),t(c)&&(e.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),h?c>f.maxInput.HCTime?c=void 0:c<g&&(c=g):c<f.minInput.HCTime?c=void 0:c>k&&(c=k),"undefined"!==
typeof c&&d.setExtremes(h?c:d.min,h?d.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var f=this,e=f.chart,g=e.renderer.style||{},l=e.renderer,q=e.options.rangeSelector,b=f.div,h="min"===c,w,z,m=this.inputGroup;this[c+"Label"]=z=l.label(I.lang[h?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(m);m.offset+=z.width+5;this[c+"DateBox"]=l=l.label("",m.offset).addClass("highcharts-range-input").attr({padding:2,width:q.inputBoxWidth||
90,height:q.inputBoxHeight||17,"text-align":"center"}).on("click",function(){f.showInput(c);f[c+"Input"].focus()});e.styledMode||l.attr({stroke:q.inputBoxBorderColor||"#cccccc","stroke-width":1});l.add(m);m.offset+=l.width+(h?10:0);this[c+"Input"]=w=D("input",{name:c,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},b);e.styledMode||(z.css(u(g,q.labelStyle)),l.css(u({color:"#333333"},g,q.inputStyle)),v(w,F({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",
fontSize:g.fontSize,fontFamily:g.fontFamily,top:"-9999em"},q.inputStyle)));w.onfocus=function(){f.showInput(c)};w.onblur=function(){w===r.doc.activeElement&&d();f.hideInput(c);w.blur()};w.onchange=d;w.onkeypress=function(b){13===b.keyCode&&d()}},getPosition:function(){var c=this.chart,a=c.options.rangeSelector;c="top"===a.verticalAlign?c.plotTop-c.axisOffset[0]:0;return{buttonTop:c+a.buttonPosition.y,inputTop:c+a.inputPosition.y-10}},getYTDExtremes:function(c,a,d){var f=this.chart.time,e=new f.Date(c),
k=f.get("FullYear",e);d=d?f.Date.UTC(k,0,1):+new f.Date(k,0,1);a=Math.max(a||0,d);e=e.getTime();return{max:Math.min(c||e,e),min:a}},render:function(c,a){var d=this,e=d.chart,k=e.renderer,g=e.container,q=e.options,b=q.exporting&&!1!==q.exporting.enabled&&q.navigation&&q.navigation.buttonOptions,h=I.lang,l=d.div,m=q.rangeSelector,p=f(q.chart.style&&q.chart.style.zIndex,0)+1;q=m.floating;var r=d.buttons;l=d.inputGroup;var u=m.buttonTheme,t=m.buttonPosition,v=m.inputPosition,x=m.inputEnabled,A=u&&u.states,
C=e.plotLeft,H=d.buttonGroup;var G=d.rendered;var F=d.options.verticalAlign,N=e.legend,O=N&&N.options,P=t.y,J=v.y,Q=G||!1,S=Q?"animate":"attr",M=0,L=0,K;if(!1!==m.enabled){G||(d.group=G=k.g("range-selector-group").attr({zIndex:7}).add(),d.buttonGroup=H=k.g("range-selector-buttons").add(G),d.zoomText=k.text(h.rangeSelectorZoom,0,15).add(H),e.styledMode||(d.zoomText.css(m.labelStyle),u["stroke-width"]=f(u["stroke-width"],0)),d.buttonOptions.forEach(function(b,c){r[c]=k.button(b.text,0,0,function(a){var h=
b.events&&b.events.click,f;h&&(f=h.call(b,a));!1!==f&&d.clickButton(c);d.isActive=!0},u,A&&A.hover,A&&A.select,A&&A.disabled).attr({"text-align":"center"}).add(H)}),!1!==x&&(d.div=l=D("div",null,{position:"relative",height:0,zIndex:p}),g.parentNode.insertBefore(l,g),d.inputGroup=l=k.g("input-group").add(G),l.offset=0,d.drawInput("min"),d.drawInput("max")));d.zoomText[S]({x:f(C+t.x,C)});var T=f(C+t.x,C)+d.zoomText.getBBox().width+5;d.buttonOptions.forEach(function(b,c){r[c][S]({x:T});T+=r[c].width+
f(m.buttonSpacing,5)});C=e.plotLeft-e.spacing[3];d.updateButtonStates();b&&this.titleCollision(e)&&"top"===F&&"right"===t.align&&t.y+H.getBBox().height-12<(b.y||0)+b.height&&(M=-40);"left"===t.align?K=t.x-e.spacing[3]:"right"===t.align&&(K=t.x+M-e.spacing[1]);H.align({y:t.y,width:H.getBBox().width,align:t.align,x:K},!0,e.spacingBox);d.group.placed=Q;d.buttonGroup.placed=Q;!1!==x&&(M=b&&this.titleCollision(e)&&"top"===F&&"right"===v.align&&v.y-l.getBBox().height-12<(b.y||0)+b.height+e.spacing[0]?-40:
0,"left"===v.align?K=C:"right"===v.align&&(K=-Math.max(e.axisOffset[1],-M)),l.align({y:v.y,width:l.getBBox().width,align:v.align,x:v.x+K-2},!0,e.spacingBox),g=l.alignAttr.translateX+l.alignOptions.x-M+l.getBBox().x+2,b=l.alignOptions.width,h=H.alignAttr.translateX+H.getBBox().x,K=H.getBBox().width+20,(v.align===t.align||h+K>g&&g+b>h&&P<J+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+(e.axisOffset[1]>=-M?0:-M),translateY:l.alignAttr.translateY+H.getBBox().height+10}),d.setInputValue("min",
c),d.setInputValue("max",a),d.inputGroup.placed=Q);d.group.align({verticalAlign:F},!0,e.spacingBox);c=d.group.getBBox().height+20;a=d.group.alignAttr.translateY;"bottom"===F&&(N=O&&"bottom"===O.verticalAlign&&O.enabled&&!O.floating?N.legendHeight+f(O.margin,10):0,c=c+N-20,L=a-c-(q?0:m.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===F)q&&(L=0),e.titleOffset&&e.titleOffset[0]&&(L=e.titleOffset[0]),L+=e.margin[0]-e.spacing[0]||0;else if("middle"===F)if(J===P)L=0>J?a+void 0:a;else if(J||P)L=0>J||
0>P?L-Math.min(J,P):a-c+NaN;d.group.translate(m.x,m.y+Math.floor(L));!1!==x&&(d.minInput.style.marginTop=d.group.translateY+"px",d.maxInput.style.marginTop=d.group.translateY+"px");d.rendered=!0}},getHeight:function(){var c=this.options,a=this.group,d=c.y,f=c.buttonPosition.y,e=c.inputPosition.y;if(c.height)return c.height;c=a?a.getBBox(!0).height+13+d:0;a=Math.min(e,f);if(0>e&&0>f||0<e&&0<f)c+=Math.abs(a);return c},titleCollision:function(c){return!(c.options.title.text||c.options.subtitle.text)},
update:function(c){var a=this.chart;u(!0,a.options.rangeSelector,c);this.destroy();this.init(a);a.rangeSelector.render()},destroy:function(){var c=this,a=c.minInput,d=c.maxInput;c.unMouseDown();c.unResize();A(c.buttons);a&&(a.onfocus=a.onblur=a.onchange=null);d&&(d.onfocus=d.onblur=d.onchange=null);x(c,function(a,d){a&&"chart"!==d&&(a.destroy?a.destroy():a.nodeType&&l(this[d]));a!==p.prototype[d]&&(c[d]=null)},this)}};m.prototype.minFromRange=function(){var a=this.range,d=a.type,e=this.max,g=this.chart.time,
l=function(b,a){var c="year"===d?"FullYear":"Month",h=new g.Date(b),f=g.get(c,h);g.set(c,h,f+a);f===g.get(c,h)&&g.set("Date",h,0);return h.getTime()-b};if(t(a)){var m=e-a;var q=a}else m=e+l(e,-a.count),this.chart&&(this.chart.fixedRange=e-m);var b=f(this.dataMin,Number.MIN_VALUE);t(m)||(m=b);m<=b&&(m=b,"undefined"===typeof q&&(q=l(m,a.count)),this.newMax=Math.min(m+q,this.dataMax));t(e)||(m=void 0);return m};r.RangeSelector||(C(d,"afterGetContainer",function(){this.options.rangeSelector.enabled&&
(this.rangeSelector=new p(this))}),C(d,"beforeRender",function(){var a=this.axes,d=this.rangeSelector;d&&(t(d.deferredYTDClick)&&(d.clickButton(d.deferredYTDClick),delete d.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),d.render(),a=d.options.verticalAlign,d.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),C(d,"update",function(a){var c=a.options.rangeSelector;a=this.rangeSelector;var d=this.extraBottomMargin,
f=this.extraTopMargin;c&&c.enabled&&!G(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new p(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),c=c&&c.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0)),this.extraBottomMargin!==d||this.extraTopMargin!==f)&&(this.isDirtyBox=!0)}),C(d,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,
"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),C(d,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),d.prototype.callbacks.push(function(a){function c(){d=a.xAxis[0].getExtremes();t(d.min)&&f.render(d.min,d.max)}var d,f=a.rangeSelector;if(f){var e=C(a.xAxis[0],"afterSetExtremes",function(a){f.render(a.min,a.max)});var g=C(a,"redraw",c);c()}C(a,"destroy",function(){f&&
(g(),e())})}),r.RangeSelector=p)});F(p,"parts/StockChart.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(r,d){var p=d.addEvent,C=d.arrayMax,D=d.arrayMin,v=d.clamp,G=d.defined,A=d.extend,l=d.find,F=d.format,g=d.isNumber,t=d.isString,u=d.merge,x=d.pick,f=d.splat;d=r.Axis;var a=r.Chart,e=r.Point,m=r.Renderer,I=r.Series,c=r.SVGRenderer,k=r.VMLRenderer,n=I.prototype,y=n.init,B=n.processData,E=e.prototype.tooltipFormatter;r.StockChart=r.stockChart=function(c,b,d){var h=t(c)||c.nodeName,e=arguments[h?
1:0],g=e,k=e.series,q=r.getOptions(),l,m=e.chart&&e.chart.panning,n=x(e.navigator&&e.navigator.enabled,q.navigator.enabled,!0),p=m&&/y/.test(m.type),v={startOnTick:!1,endOnTick:!1};e.xAxis=f(e.xAxis||{}).map(function(a,b){return u({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},q.xAxis,q.xAxis&&q.xAxis[b],a,{type:"datetime",categories:null},n?v:null)});e.yAxis=f(e.yAxis||{}).map(function(a,b){l=x(a.opposite,!0);return u({labels:{y:-2},
opposite:l,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},q.yAxis,q.yAxis&&q.yAxis[b],a,p?v:null)});e.series=null;e=u({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:n},scrollbar:{enabled:x(q.scrollbar.enabled,!0)},rangeSelector:{enabled:x(q.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:x(q.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},e,{isStock:!0});e.series=g.series=k;return h?new a(c,e,d):new a(e,b)};p(I,"setOptions",function(a){var b;
this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=u(a.plotOptions[this.type],b)))});p(d,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+","+c.height,!b[c]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align=
"right"),b[c]=this,a.align="right",a.preventDefault()))});p(d,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});p(d,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return g(a)?[e[b][a]]:t(a)?[e.get(a)]:d.map(function(a){return a[b]})}var c=this,d=this.isLinked&&!this.series?this.linkedParent.series:this.series,e=c.chart,f=e.renderer,k=c.left,
q=c.top,m,n,p,r,u=[],y=[],A=a.translatedValue,C=a.value,B=a.force;if(e.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){a.preventDefault();y=b(c.coll);var E=c.isXAxis?e.yAxis:e.xAxis;E.forEach(function(a){if(G(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=G(a.options[b])?e[b][a.options[b]]:e[b][0];c===b&&y.push(a)}});var D=y.length?[]:[c.isXAxis?e.yAxis[0]:e.xAxis[0]];y.forEach(function(a){-1!==D.indexOf(a)||l(D,function(b){return b.pos===
a.pos&&b.len===a.len})||D.push(a)});var F=x(A,c.translate(C,null,null,a.old));g(F)&&(c.horiz?D.forEach(function(a){var b;n=a.pos;r=n+a.len;m=p=Math.round(F+c.transB);"pass"!==B&&(m<k||m>k+c.width)&&(B?m=p=v(m,k,k+c.width):b=!0);b||u.push("M",m,n,"L",p,r)}):D.forEach(function(a){var b;m=a.pos;p=m+a.len;n=r=Math.round(q+c.height-F);"pass"!==B&&(n<q||n>q+c.height)&&(B?n=r=v(n,q,q+c.height):b=!0);b||u.push("M",m,n,"L",p,r)}));a.path=0<u.length?f.crispPolyLine(u,a.lineWidth||1):null}});c.prototype.crispPolyLine=
function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};m===k&&(k.prototype.crispPolyLine=c.prototype.crispPolyLine);p(d,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});p(d,"afterDrawCrosshair",function(a){var b,c;if(G(this.crosshair.label)&&this.crosshair.label.enabled&&this.cross){var d=this.chart,e=this.options.crosshair.label,f=this.horiz,
g=this.opposite,k=this.left,q=this.top,l=this.crossLabel,m=e.format,n="",p="inside"===this.options.tickPosition,r=!1!==this.crosshair.snap,u=0,t=a.e||this.cross&&this.cross.e,v=a.point;var y=this.lin2log;if(this.isLog){a=y(this.min);var B=y(this.max)}else a=this.min,B=this.max;y=f?"center":g?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";l||(l=this.crossLabel=d.renderer.label(null,null,null,e.shape||"callout").addClass("highcharts-crosshair-label"+(this.series[0]&&
" highcharts-color-"+this.series[0].colorIndex)).attr({align:e.align||y,padding:x(e.padding,8),r:x(e.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||l.attr({fill:e.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:e.borderColor||"","stroke-width":e.borderWidth||0}).css(A({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},e.style)));f?(y=r?v.plotX+k:t.chartX,q+=g?0:this.height):(y=g?this.width+k:0,q=r?v.plotY+q:t.chartY);m||e.formatter||(this.isDatetimeAxis&&
(n="%b %d, %Y"),m="{value"+(n?":"+n:"")+"}");n=r?v[this.isXAxis?"x":"y"]:this.toValue(f?t.chartX:t.chartY);l.attr({text:m?F(m,{value:n},d):e.formatter.call(this,n),x:y,y:q,visibility:n<a||n>B?"hidden":"visible"});e=l.getBBox();if(f){if(p&&!g||!p&&g)q=l.y-e.height}else q=l.y-e.height/2;f?(b=k-e.x,c=k+this.width-e.x):(b="left"===this.labelAlign?k:0,c="right"===this.labelAlign?k+this.width:d.chartWidth);l.translateX<b&&(u=b-l.translateX);l.translateX+e.width>=c&&(u=-(l.translateX+e.width-c));l.attr({x:y+
u,y:q,anchorX:f?y:this.opposite?0:d.chartWidth,anchorY:f?this.opposite?d.chartHeight:0:q+e.height/2})}});n.init=function(){y.apply(this,arguments);this.setCompare(this.options.compare)};n.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&(this.isDirty=
!0)};n.processData=function(a){var b,c=-1,d=!0===this.options.compareStart?0:1;B.apply(this,arguments);if(this.xAxis&&this.processedYData){var e=this.processedXData;var f=this.processedYData;var k=f.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<k-d;b++){var l=f[b]&&-1<c?f[b][c]:f[b];if(g(l)&&e[b+d]>=this.xAxis.min&&0!==l){this.compareValue=l;break}}}};p(I,"afterGetExtremes",function(){if(this.modifyValue){var a=[this.modifyValue(this.dataMin),
this.modifyValue(this.dataMax)];this.dataMin=D(a);this.dataMax=C(a)}});d.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),x(b,!0)&&this.chart.redraw())};e.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,x(this.series.tooltipOptions.changeDecimals,2)));return E.apply(this,[a])};p(I,"render",function(){var a=this.chart;if(!(a.is3d&&a.is3d()||a.polar)&&this.xAxis&&
!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}!this.clipBox&&this.animate?(this.clipBox=u(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});p(a,"update",
function(a){a=a.options;"scrollbar"in a&&this.navigator&&(u(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)});p(d,"afterSetScale",function(){var a=this,b=a.chart.options.chart&&a.chart.options.chart.panning;if(b&&("y"===b.type||"xy"===b.type)&&!a.isXAxis&&!G(a.panningState)){var c=Number.MAX_VALUE,d=Number.MIN_VALUE;a.series.forEach(function(b){c=Math.min(r.arrayMin(b.yData),c)-(a.min&&a.dataMin?a.dataMin-a.min:0);d=Math.max(r.arrayMax(b.yData),d)+(a.max&&a.dataMax?
a.max-a.dataMax:0)});a.panningState={startMin:c,startMax:d}}})});F(p,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map