/*
 Highcharts JS v8.0.0 (2020-02-16)

 (c) 2016-2019 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/sunburst",["highcharts"],function(z){c(z);c.Highcharts=z;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function z(c,b,I,g){c.hasOwnProperty(b)||(c[b]=g.apply(null,I))}c=c?c._modules:{};z(c,"mixins/draw-point.js",[],function(){var c=function(b){var c=this,g=c.graphic,k=b.animatableAttribs,n=b.onComplete,C=b.css,r=b.renderer;
if(c.shouldDraw())g||(c.graphic=g=r[b.shapeType](b.shapeArgs).add(b.group)),g.css(C).attr(b.attribs).animate(k,b.isNew?!1:void 0,n);else if(g){var l=function(){c.graphic=g=g.destroy();"function"===typeof n&&n()};Object.keys(k).length?g.animate(k,void 0,function(){l()}):l()}};return function(b){(b.attribs=b.attribs||{})["class"]=this.getClassName();c.call(this,b)}});z(c,"mixins/tree-series.js",[c["parts/Color.js"],c["parts/Utilities.js"]],function(c,b){var C=b.extend,g=b.isArray,k=b.isNumber,n=b.isObject,
L=b.merge,r=b.pick;return{getColor:function(l,b){var u=b.index,A=b.mapOptionsToLevel,k=b.parentColor,C=b.parentColorIndex,g=b.series,E=b.colors,F=b.siblings,v=g.points,x=g.chart.options.chart,w;if(l){v=v[l.i];l=A[l.level]||{};if(A=v&&l.colorByPoint){var n=v.index%(E?E.length:x.colorCount);var L=E&&E[n]}if(!g.chart.styledMode){E=v&&v.options.color;x=l&&l.color;if(w=k)w=(w=l&&l.colorVariation)&&"brightness"===w.key?c.parse(k).brighten(u/F*w.to).get():k;w=r(E,x,L,w,g.color)}var z=r(v&&v.options.colorIndex,
l&&l.colorIndex,n,C,b.colorIndex)}return{color:w,colorIndex:z}},getLevelOptions:function(b){var c=null;if(n(b)){c={};var u=k(b.from)?b.from:1;var l=b.levels;var r={};var B=n(b.defaults)?b.defaults:{};g(l)&&(r=l.reduce(function(b,c){if(n(c)&&k(c.level)){var l=L({},c);var A="boolean"===typeof l.levelIsConstant?l.levelIsConstant:B.levelIsConstant;delete l.levelIsConstant;delete l.level;c=c.level+(A?0:u-1);n(b[c])?C(b[c],l):b[c]=l}return b},{}));l=k(b.to)?b.to:1;for(b=0;b<=l;b++)c[b]=L({},B,n(r[b])?r[b]:
{})}return c},setTreeValues:function J(b,c){var k=c.before,g=c.idRoot,n=c.mapIdToNode[g],u=c.points[b.i],A=u&&u.options||{},v=0,x=[];C(b,{levelDynamic:b.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:n.level),name:r(u&&u.name,""),visible:g===b.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof k&&(b=k(b,c));b.children.forEach(function(k,g){var u=C({},c);C(u,{index:g,siblings:b.children.length,visible:b.visible});k=J(k,u);x.push(k);k.visible&&(v+=k.val)});b.visible=
0<v||b.visible;k=r(A.value,v);C(b,{children:x,childrenTotal:v,isLeaf:b.visible&&!v,val:k});return b},updateRootId:function(b){if(n(b)){var c=n(b.options)?b.options:{};c=r(b.rootNode,c.rootId,"");n(b.userOptions)&&(b.userOptions.rootId=c);b.rootNode=c}return c}}});z(c,"modules/treemap.src.js",[c["parts/Globals.js"],c["mixins/tree-series.js"],c["mixins/draw-point.js"],c["parts/Color.js"],c["parts/Utilities.js"]],function(c,b,z,g,k){var n=g.parse,C=k.addEvent,r=k.correctFloat,l=k.defined,A=k.error,u=
k.extend,J=k.fireEvent,M=k.isArray,B=k.isNumber,I=k.isObject,E=k.isString,F=k.merge,v=k.objectEach,x=k.pick;g=k.seriesType;var w=k.stableSort,K=c.seriesTypes;k=c.noop;var Q=b.getColor,N=b.getLevelOptions,G=c.Series,O=function(a,d,e){e=e||this;v(a,function(q,h){d.call(e,q,h,a)})},H=function(a,d,e){e=e||this;a=d.call(e,a);!1!==a&&H(a,d,e)},f=b.updateRootId,m=!1;g("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,
formatter:function(){var a=this&&this.point?this.point:{};return E(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",
opacity:.15,states:{hover:{borderColor:"#999999",brightness:K.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:k,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,d){a=M(a)?a:[];var e=M(d)?d:[];d=a.reduce(function(a,d,e){d=x(d.parent,"");"undefined"===typeof a[d]&&(a[d]=[]);a[d].push(e);return a},{"":[]});O(d,function(a,d,f){""!==d&&-1===e.indexOf(d)&&
(a.forEach(function(a){f[""].push(a)}),delete f[d])});return d},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,d){var e=c.colorMapSeriesMixin;e&&(this.colorAttribs=e.colorAttribs);this.eventsToUnbind.push(C(this,"setOptions",function(a){a=a.userOptions;l(a.allowDrillToNode)&&!l(a.allowTraversingTree)&&(a.allowTraversingTree=
a.allowDrillToNode,delete a.allowDrillToNode);l(a.drillUpButton)&&!l(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)}));G.prototype.init.call(this,a,d);this.options.allowTraversingTree&&this.eventsToUnbind.push(C(this,"click",this.onClickDrillToNode))},buildNode:function(a,d,e,q,h){var f=this,b=[],c=f.points[d],D=0,m;(q[a]||[]).forEach(function(d){m=f.buildNode(f.points[d].id,d,e+1,q,a);D=Math.max(m.height+1,D);b.push(m)});d={id:a,i:d,children:b,height:D,level:e,parent:h,
visible:!1};f.nodeMap[d.id]=d;c&&(c.node=d);return d},setTreeValues:function(a){var d=this,e=d.options,f=d.nodeMap[d.rootNode];e="boolean"===typeof e.levelIsConstant?e.levelIsConstant:!0;var h=0,b=[],t=d.points[a.i];a.children.forEach(function(a){a=d.setTreeValues(a);b.push(a);a.ignore||(h+=a.val)});w(b,function(a,d){return a.sortIndex-d.sortIndex});var c=x(t&&t.options.value,h);t&&(t.value=c);u(a,{children:b,childrenTotal:h,ignore:!(x(t&&t.visible,!0)&&0<c),isLeaf:a.visible&&!h,levelDynamic:a.level-
(e?0:f.level),name:x(t&&t.name,""),sortIndex:x(t&&t.sortIndex,-c),val:c});return a},calculateChildrenAreas:function(a,d){var e=this,f=e.options,h=e.mapOptionsToLevel[a.level+1],b=x(e[h&&h.layoutAlgorithm]&&h.layoutAlgorithm,f.layoutAlgorithm),c=f.alternateStartingDirection,m=[];a=a.children.filter(function(a){return!a.ignore});h&&h.layoutStartingDirection&&(d.direction="vertical"===h.layoutStartingDirection?0:1);m=e[b](d,a);a.forEach(function(a,h){h=m[h];a.values=F(h,{val:a.childrenTotal,direction:c?
1-d.direction:d.direction});a.pointValues=F(h,{x:h.x/e.axisRatio,y:100-h.y-h.height,width:h.width/e.axisRatio});a.children.length&&e.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,d=a.xAxis,e=a.yAxis,f=a.chart.styledMode;a.points.forEach(function(h){var b=h.node,q=b.pointValues;b=b.visible;if(q&&b){b=q.height;var c=q.width,m=q.x,k=q.y,p=f?0:(a.pointAttribs(h)["stroke-width"]||0)%2/2;q=Math.round(d.toPixels(m,!0))-p;c=Math.round(d.toPixels(m+c,!0))-p;m=Math.round(e.toPixels(k,
!0))-p;b=Math.round(e.toPixels(k+b,!0))-p;h.shapeArgs={x:Math.min(q,c),y:Math.min(m,b),width:Math.abs(c-q),height:Math.abs(b-m)};h.plotX=h.shapeArgs.x+h.shapeArgs.width/2;h.plotY=h.shapeArgs.y+h.shapeArgs.height/2}else delete h.plotX,delete h.plotY})},setColorRecursive:function(a,d,e,b,h){var f=this,q=f&&f.chart;q=q&&q.options&&q.options.colors;if(a){var c=Q(a,{colors:q,index:b,mapOptionsToLevel:f.mapOptionsToLevel,parentColor:d,parentColorIndex:e,series:f,siblings:h});if(d=f.points[a.i])d.color=
c.color,d.colorIndex=c.colorIndex;(a.children||[]).forEach(function(d,e){f.setColorRecursive(d,c.color,c.colorIndex,e,a.children.length)})}},algorithmGroup:function(a,d,e,f){this.height=a;this.width=d;this.plot=f;this.startDirection=this.direction=e;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,d){return Math.max(a/d,d/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===
this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=
0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,d,e,f){var h,b,q,c,m=e.lW,k=e.lH,p=e.plot,l=0,g=e.elArr.length-1;if(d)m=e.nW,k=e.nH;else var n=e.elArr[e.elArr.length-1];e.elArr.forEach(function(a){if(d||l<g)0===e.direction?(h=p.x,b=p.y,q=m,c=a/q):(h=p.x,b=p.y,c=k,q=a/c),f.push({x:h,y:b,width:q,height:r(c)}),0===e.direction?p.y+=c:p.x+=q;l+=1});e.reset();0===e.direction?e.width-=m:e.height-=k;p.y=p.parent.y+(p.parent.height-e.height);p.x=p.parent.x+(p.parent.width-e.width);a&&(e.direction=
1-e.direction);d||e.addElement(n)},algorithmLowAspectRatio:function(a,d,e){var f=[],h=this,b,c={x:d.x,y:d.y,parent:d},m=0,k=e.length-1,l=new this.algorithmGroup(d.height,d.width,d.direction,c);e.forEach(function(e){b=e.val/d.val*d.height*d.width;l.addElement(b);l.lP.nR>l.lP.lR&&h.algorithmCalcPoints(a,!1,l,f,c);m===k&&h.algorithmCalcPoints(a,!0,l,f,c);m+=1});return f},algorithmFill:function(a,d,e){var f=[],h,b=d.direction,c=d.x,m=d.y,k=d.width,l=d.height,p,g,n,r;e.forEach(function(e){h=e.val/d.val*
d.height*d.width;p=c;g=m;0===b?(r=l,n=h/r,k-=n,c+=n):(n=k,r=h/n,l-=r,m+=r);f.push({x:p,y:g,width:n,height:r});a&&(b=1-b)});return f},strip:function(a,d){return this.algorithmLowAspectRatio(!1,a,d)},squarified:function(a,d){return this.algorithmLowAspectRatio(!0,a,d)},sliceAndDice:function(a,d){return this.algorithmFill(!0,a,d)},stripes:function(a,d){return this.algorithmFill(!1,a,d)},translate:function(){var a=this,d=a.options,e=f(a);G.prototype.translate.call(a);var b=a.tree=a.getTree();var h=a.nodeMap[e];
a.renderTraverseUpButton(e);a.mapOptionsToLevel=N({from:h.level+1,levels:d.levels,to:b.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:d.colorByPoint}});""===e||h&&h.children.length||(a.setRootNode("",!1),e=a.rootNode,h=a.nodeMap[e]);H(a.nodeMap[a.rootNode],function(d){var e=!1,b=d.parent;d.visible=!0;if(b||""===b)e=a.nodeMap[b];return e});H(a.nodeMap[a.rootNode].children,function(a){var d=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(d=(d||[]).concat(a.children))});
return d});a.setTreeValues(b);a.axisRatio=a.xAxis.len/a.yAxis.len;a.nodeMap[""].pointValues=e={x:0,y:0,width:100,height:100};a.nodeMap[""].values=e=F(e,{width:e.width*a.axisRatio,direction:"vertical"===d.layoutStartingDirection?0:1,val:b.val});a.calculateChildrenAreas(b,e);a.colorAxis||d.colorByPoint||a.setColorRecursive(a.tree);d.allowTraversingTree&&(d=h.pointValues,a.xAxis.setExtremes(d.x,d.x+d.width,!1),a.yAxis.setExtremes(d.y,d.y+d.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},
drawDataLabels:function(){var a=this,d=a.mapOptionsToLevel,e,b;a.points.filter(function(a){return a.node.visible}).forEach(function(f){b=d[f.node.level];e={style:{}};f.node.isLeaf||(e.enabled=!1);b&&b.dataLabels&&(e=F(e,b.dataLabels),a._hasPointLabels=!0);f.shapeArgs&&(e.style.width=f.shapeArgs.width,f.dataLabel&&f.dataLabel.css({width:f.shapeArgs.width+"px"}));f.dlOptions=F(e,f.options.dataLabels)});G.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,d,e){var b=e.style;!l(b.textOverflow)&&
d.text&&d.getBBox().width>d.text.textWidth&&d.css({textOverflow:"ellipsis",width:b.width+="px"});K.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,d){var e=I(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},b=a&&e[a.node.level]||{};e=this.options;var f=d&&e.states[d]||{},c=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||b.borderColor||f.borderColor||e.borderColor,"stroke-width":x(a&&a.borderWidth,b.borderWidth,
f.borderWidth,e.borderWidth),dashstyle:a&&a.borderDashStyle||b.borderDashStyle||f.borderDashStyle||e.borderDashStyle,fill:a&&a.color||this.color};-1!==c.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==c.indexOf("highcharts-internal-node-interactive")?(d=x(f.opacity,e.opacity),a.fill=n(a.fill).setOpacity(d).get(),a.cursor="pointer"):-1!==c.indexOf("highcharts-internal-node")?a.fill="none":d&&(a.fill=n(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=
this,d=a.chart,e=d.renderer,b=d.styledMode,f=a.options,c=b?{}:f.shadow,m=f.borderRadius,k=d.pointCount<f.animationLimit,l=f.allowTraversingTree;a.points.forEach(function(d){var h=d.node.levelDynamic,q={},t={},g={},n="level-group-"+h,r=!!d.graphic,D=k&&r,S=d.shapeArgs;d.shouldDraw()&&(m&&(t.r=m),F(!0,D?q:t,r?S:{},b?{}:a.pointAttribs(d,d.selected&&"select")),a.colorAttribs&&b&&u(g,a.colorAttribs(d)),a[n]||(a[n]=e.g(n).attr({zIndex:1E3-h}).add(a.group),a[n].survive=!0));d.draw({animatableAttribs:q,attribs:t,
css:g,group:a[n],renderer:e,shadow:c,shapeArgs:S,shapeType:"rect"});l&&d.graphic&&(d.drillId=f.interactByLeaf?a.drillToByLeaf(d):a.drillToByGroup(d))})},onClickDrillToNode:function(a){var d=(a=a.point)&&a.drillId;E(d)&&(a.setState(""),this.setRootNode(d,!0,{trigger:"click"}))},drillToByGroup:function(a){var d=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(d=a.id);return d},drillToByLeaf:function(a){var d=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!d;)a=
this.nodeMap[a.parent],a.parent===this.rootNode&&(d=a.id);return d},drillUp:function(){var a=this.nodeMap[this.rootNode];a&&E(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,d){A("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,d)},setRootNode:function(a,d,b){a=u({newRootId:a,previousRootId:this.rootNode,redraw:x(d,!0),series:this},b);J(this,"setRootNode",a,function(a){var d=
a.series;d.idPreviousRoot=a.previousRootId;d.rootNode=a.newRootId;d.isDirty=!0;a.redraw&&d.chart.redraw()})},renderTraverseUpButton:function(a){var d=this,b=d.options.traverseUpButton,f=x(b.text,d.nodeMap[a].name,"< Back");if(""===a)d.drillUpButton&&(d.drillUpButton=d.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:f}).align();else{var c=(a=b.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(f,null,null,function(){d.drillUp()},
a,c&&c.hover,c&&c.select).addClass("highcharts-drillup-button").attr({align:b.position.align,zIndex:7}).add().align(b.position,!1,b.relativeTo||"plotBox")}},buildKDTree:k,drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,getExtremes:function(){G.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;G.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;G.prototype.setState.call(this,a,
!1);this.options.inactiveOtherPoints=!1},utils:{recursive:H}},{draw:z,setVisible:K.pie.prototype.pointClass.prototype.setVisible,getClassName:function(){var a=c.Point.prototype.getClassName.call(this),d=this.series,b=d.options;this.node.level<=d.nodeMap[d.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||x(b.interactByLeaf,!b.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||
B(this.value)},setState:function(a){c.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:0})},shouldDraw:function(){return B(this.plotY)&&null!==this.y}});C(c.Series,"afterBindAxes",function(){var a=this.xAxis,d=this.yAxis;if(a&&d)if(this.is("treemap")){var b={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};u(d.options,b);u(a.options,b);m=!0}else m&&(d.setOptions(d.userOptions),
a.setOptions(a.userOptions),m=!1)});""});z(c,"modules/sunburst.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["mixins/draw-point.js"],c["mixins/tree-series.js"]],function(c,b,z,g){var k=b.correctFloat,n=b.error,C=b.extend,r=b.isNumber,l=b.isObject,A=b.isString,u=b.merge,J=b.seriesType,M=b.splat;b=c.CenteredSeriesMixin;var B=c.Series,I=b.getCenter,E=g.getColor,F=g.getLevelOptions,v=b.getStartAndEndRadians,x=180/Math.PI,w=c.seriesTypes,K=g.setTreeValues,Q=g.updateRootId,N=function(b,c){var a=
[];if(r(b)&&r(c)&&b<=c)for(;b<=c;b++)a.push(b);return a},G=function(b,c){c=l(c)?c:{};var a=0,d;if(l(b)){var f=u({},b);b=r(c.from)?c.from:0;var q=r(c.to)?c.to:0;var h=N(b,q);b=Object.keys(f).filter(function(a){return-1===h.indexOf(+a)});var m=d=r(c.diffRadius)?c.diffRadius:0;h.forEach(function(b){b=f[b];var c=b.levelSize.unit,e=b.levelSize.value;"weight"===c?a+=e:"percentage"===c?(b.levelSize={unit:"pixels",value:e/100*m},d-=b.levelSize.value):"pixels"===c&&(d-=e)});h.forEach(function(b){var c=f[b];
"weight"===c.levelSize.unit&&(c=c.levelSize.value,f[b].levelSize={unit:"pixels",value:c/a*d})});b.forEach(function(a){f[a].levelSize={value:0,unit:"pixels"}})}return f},O=function(b){var c=b.level;return{from:0<c?c:1,to:c+b.height}},H=function(b,c){var a=c.mapIdToNode[b.parent],d=c.series,e=d.chart,f=d.points[b.i];a=E(b,{colors:d.options.colors||e&&e.options.colors,colorIndex:d.colorIndex,index:c.index,mapOptionsToLevel:c.mapOptionsToLevel,parentColor:a&&a.color,parentColorIndex:a&&a.colorIndex,series:c.series,
siblings:c.siblings});b.color=a.color;b.colorIndex=a.colorIndex;f&&(f.color=b.color,f.colorIndex=b.colorIndex,b.sliced=b.id!==c.idRoot?f.sliced:!1);return b};J("sunburst","treemap",{center:["50%","50%"],colorByPoint:!1,opacity:1,dataLabels:{allowOverlap:!0,defer:!0,rotationMode:"auto",style:{textOverflow:"ellipsis"}},rootId:void 0,levelIsConstant:!0,levelSize:{value:1,unit:"weight"},slicedOffset:10},{drawDataLabels:c.noop,drawPoints:function(){var b=this,c=b.mapOptionsToLevel,a=b.shapeRoot,d=b.group,
e=b.hasRendered,q=b.rootNode,h=b.idPreviousRoot,k=b.nodeMap,g=k[h],n=g&&g.shapeArgs;g=b.points;var D=b.startAndEndRadians,v=b.chart,p=v&&v.options&&v.options.chart||{},z="boolean"===typeof p.animation?p.animation:!0,w=b.center[3]/2,E=b.chart.renderer,A=!1,F=!1;if(p=!!(z&&e&&q!==h&&b.dataLabelsGroup)){b.dataLabelsGroup.attr({opacity:0});var G=function(){A=!0;b.dataLabelsGroup&&b.dataLabelsGroup.animate({opacity:1,visibility:"visible"})}}g.forEach(function(f){var m=f.node,g=c[m.level];var p=f.shapeExisting||
{};var t=m.shapeArgs||{},R=!(!m.visible||!m.shapeArgs);if(e&&z){var A={};var P={end:t.end,start:t.start,innerR:t.innerR,r:t.r,x:t.x,y:t.y};R?!f.graphic&&n&&(A=q===f.id?{start:D.start,end:D.end}:n.end<=t.start?{start:D.end,end:D.end}:{start:D.start,end:D.start},A.innerR=A.r=w):f.graphic&&(h===f.id?P={innerR:w,r:w}:a&&(P=a.end<=p.start?{innerR:w,r:w,start:D.end,end:D.end}:{innerR:w,r:w,start:D.start,end:D.start}));p=A}else P=t,p={};A=[t.plotX,t.plotY];if(!f.node.isLeaf)if(q===f.id){var y=k[q];y=y.parent}else y=
f.id;C(f,{shapeExisting:t,tooltipPos:A,drillId:y,name:""+(f.name||f.id||f.index),plotX:t.plotX,plotY:t.plotY,value:m.val,isNull:!R});y=f.options;m=l(t)?t:{};y=l(y)?y.dataLabels:{};g=M(l(g)?g.dataLabels:{})[0];g=u({style:{}},g,y);y=g.rotationMode;if(!r(g.rotation)){if("auto"===y||"circular"===y)if(1>f.innerArcLength&&f.outerArcLength>m.radius){var B=0;f.dataLabelPath&&"circular"===y&&(g.textPath={enabled:!0})}else 1<f.innerArcLength&&f.outerArcLength>1.5*m.radius?"circular"===y?g.textPath={enabled:!0,
attributes:{dy:5}}:y="parallel":(f.dataLabel&&f.dataLabel.textPathWrapper&&"circular"===y&&(g.textPath={enabled:!1}),y="perpendicular");"auto"!==y&&"circular"!==y&&(B=m.end-(m.end-m.start)/2);g.style.width="parallel"===y?Math.min(2.5*m.radius,(f.outerArcLength+f.innerArcLength)/2):m.radius;"perpendicular"===y&&f.series.chart.renderer.fontMetrics(g.style.fontSize).h>f.outerArcLength&&(g.style.width=1);g.style.width=Math.max(g.style.width-2*(g.padding||0),1);B=B*x%180;"parallel"===y&&(B-=90);90<B?B-=
180:-90>B&&(B+=180);g.rotation=B}g.textPath&&(0===f.shapeExisting.innerR&&g.textPath.enabled?(g.rotation=0,g.textPath.enabled=!1,g.style.width=Math.max(2*f.shapeExisting.r-2*(g.padding||0),1)):f.dlOptions&&f.dlOptions.textPath&&!f.dlOptions.textPath.enabled&&"circular"===y&&(g.textPath.enabled=!0),g.textPath.enabled&&(g.rotation=0,g.style.width=Math.max((f.outerArcLength+f.innerArcLength)/2-2*(g.padding||0),1)));0===g.rotation&&(g.rotation=.001);f.dlOptions=g;if(!F&&R){F=!0;var T=G}f.draw({animatableAttribs:P,
attribs:C(p,!v.styledMode&&b.pointAttribs(f,f.selected&&"select")),onComplete:T,group:d,renderer:E,shapeType:"arc",shapeArgs:t})});p&&F?(b.hasRendered=!1,b.options.dataLabels.defer=!0,B.prototype.drawDataLabels.call(b),b.hasRendered=!0,A&&G()):B.prototype.drawDataLabels.call(b)},pointAttribs:w.column.prototype.pointAttribs,layoutAlgorithm:function(b,c,a){var d=b.start,f=b.end-d,g=b.val,h=b.x,m=b.y,k=a&&l(a.levelSize)&&r(a.levelSize.value)?a.levelSize.value:0,n=b.r,v=n+k,u=a&&r(a.slicedOffset)?a.slicedOffset:
0;return(c||[]).reduce(function(a,b){var c=1/g*b.val*f,e=d+c/2,q=h+Math.cos(e)*u;e=m+Math.sin(e)*u;b={x:b.sliced?q:h,y:b.sliced?e:m,innerR:n,r:v,radius:k,start:d,end:d+c};a.push(b);d=b.end;return a},[])},setShapeArgs:function(b,c,a){var d=[],f=a[b.level+1];b=b.children.filter(function(a){return a.visible});d=this.layoutAlgorithm(c,b,f);b.forEach(function(b,c){c=d[c];var f=c.start+(c.end-c.start)/2,e=c.innerR+(c.r-c.innerR)/2,g=c.end-c.start;e=0===c.innerR&&6.28<g?{x:c.x,y:c.y}:{x:c.x+Math.cos(f)*
e,y:c.y+Math.sin(f)*e};var h=b.val?b.childrenTotal>b.val?b.childrenTotal:b.val:b.childrenTotal;this.points[b.i]&&(this.points[b.i].innerArcLength=g*c.innerR,this.points[b.i].outerArcLength=g*c.r);b.shapeArgs=u(c,{plotX:e.x,plotY:e.y+4*Math.abs(Math.cos(f))});b.values=u(c,{val:h});b.children.length&&this.setShapeArgs(b,b.values,a)},this)},translate:function(){var b=this,c=b.options,a=b.center=I.call(b),d=b.startAndEndRadians=v(c.startAngle,c.endAngle),e=a[3]/2,g=a[2]/2-e,h=Q(b),k=b.nodeMap,l=k&&k[h],
r={};b.shapeRoot=l&&l.shapeArgs;B.prototype.translate.call(b);var u=b.tree=b.getTree();b.renderTraverseUpButton(h);k=b.nodeMap;l=k[h];var w=A(l.parent)?l.parent:"";w=k[w];var p=O(l);var x=p.from,z=p.to;p=F({from:x,levels:b.options.levels,to:z,defaults:{colorByPoint:c.colorByPoint,dataLabels:c.dataLabels,levelIsConstant:c.levelIsConstant,levelSize:c.levelSize,slicedOffset:c.slicedOffset}});p=G(p,{diffRadius:g,from:x,to:z});K(u,{before:H,idRoot:h,levelIsConstant:c.levelIsConstant,mapOptionsToLevel:p,
mapIdToNode:k,points:b.points,series:b});c=k[""].shapeArgs={end:d.end,r:e,start:d.start,val:l.val,x:a[0],y:a[1]};this.setShapeArgs(w,c,p);b.mapOptionsToLevel=p;b.data.forEach(function(a){r[a.id]&&n(31,!1,b.chart);r[a.id]=!0});r={}},alignDataLabel:function(b,c,a){if(!a.textPath||!a.textPath.enabled)return w.treemap.prototype.alignDataLabel.apply(this,arguments)},animate:function(b){var c=this.chart,a=[c.plotWidth/2,c.plotHeight/2],d=c.plotLeft,e=c.plotTop;c=this.group;b?(b={translateX:a[0]+d,translateY:a[1]+
e,scaleX:.001,scaleY:.001,rotation:10,opacity:.01},c.attr(b)):(b={translateX:d,translateY:e,scaleX:1,scaleY:1,rotation:0,opacity:1},c.animate(b,this.options.animation),this.animate=null)},utils:{calculateLevelSizes:G,getLevelFromAndTo:O,range:N}},{draw:z,shouldDraw:function(){return!this.isNull},isValid:function(){return!0},getDataLabelPath:function(b){var c=this.series.chart.renderer,a=this.shapeExisting,d=a.start,e=a.end,f=d+(e-d)/2;f=0>f&&f>-Math.PI||f>Math.PI;var g=a.r+(b.options.distance||0);
d===-Math.PI/2&&k(e)===k(1.5*Math.PI)&&(d=-Math.PI+Math.PI/360,e=-Math.PI/360,f=!0);if(e-d>Math.PI){f=!1;var l=!0}this.dataLabelPath&&(this.dataLabelPath=this.dataLabelPath.destroy());this.dataLabelPath=c.arc({open:!0,longArc:l?1:0}).add(b);this.dataLabelPath.attr({start:f?d:e,end:f?e:d,clockwise:+f,x:a.x,y:a.y,r:(g+a.innerR)/2});return this.dataLabelPath}})});z(c,"masters/modules/sunburst.src.js",[],function(){})});
//# sourceMappingURL=sunburst.js.map