/*
 Highcharts JS v8.0.0 (2020-02-16)

 (c) 2014-2019 Highsoft AS
 Authors: Jon Arild Nygard / Oystein Moseng

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/treemap",["highcharts"],function(q){c(q);c.Highcharts=q;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function q(c,f,n,p){c.hasOwnProperty(f)||(c[f]=p.apply(null,n))}c=c?c._modules:{};q(c,"mixins/tree-series.js",[c["parts/Color.js"],c["parts/Utilities.js"]],function(c,f){var n=f.extend,p=f.isArray,k=f.isNumber,h=f.isObject,
v=f.merge,D=f.pick;return{getColor:function(e,g){var f=g.index,k=g.mapOptionsToLevel,p=g.parentColor,h=g.parentColorIndex,n=g.series,w=g.colors,y=g.siblings,t=n.points,r=n.chart.options.chart,x;if(e){t=t[e.i];e=k[e.level]||{};if(k=t&&e.colorByPoint){var v=t.index%(w?w.length:r.colorCount);var q=w&&w[v]}if(!n.chart.styledMode){w=t&&t.options.color;r=e&&e.color;if(x=p)x=(x=e&&e.colorVariation)&&"brightness"===x.key?c.parse(p).brighten(f/y*x.to).get():p;x=D(w,r,q,x,n.color)}var K=D(t&&t.options.colorIndex,
e&&e.colorIndex,v,h,g.colorIndex)}return{color:x,colorIndex:K}},getLevelOptions:function(e){var g=null;if(h(e)){g={};var f=k(e.from)?e.from:1;var c=e.levels;var B={};var q=h(e.defaults)?e.defaults:{};p(c)&&(B=c.reduce(function(g,e){if(h(e)&&k(e.level)){var c=v({},e);var A="boolean"===typeof c.levelIsConstant?c.levelIsConstant:q.levelIsConstant;delete c.levelIsConstant;delete c.level;e=e.level+(A?0:f-1);h(g[e])?n(g[e],c):g[e]=c}return g},{}));c=k(e.to)?e.to:1;for(e=0;e<=c;e++)g[e]=v({},q,h(B[e])?B[e]:
{})}return g},setTreeValues:function F(g,c){var f=c.before,k=c.idRoot,p=c.mapIdToNode[k],h=c.points[g.i],v=h&&h.options||{},t=0,r=[];n(g,{levelDynamic:g.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:p.level),name:D(h&&h.name,""),visible:k===g.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof f&&(g=f(g,c));g.children.forEach(function(f,k){var h=n({},c);n(h,{index:k,siblings:g.children.length,visible:g.visible});f=F(f,h);r.push(f);f.visible&&(t+=f.val)});g.visible=
0<t||g.visible;f=D(v.value,t);n(g,{children:r,childrenTotal:t,isLeaf:g.visible&&!t,val:f});return g},updateRootId:function(c){if(h(c)){var f=h(c.options)?c.options:{};f=D(c.rootNode,f.rootId,"");h(c.userOptions)&&(c.userOptions.rootId=f);c.rootNode=f}return f}}});q(c,"mixins/draw-point.js",[],function(){var c=function(c){var f=this,p=f.graphic,k=c.animatableAttribs,h=c.onComplete,v=c.css,q=c.renderer;if(f.shouldDraw())p||(f.graphic=p=q[c.shapeType](c.shapeArgs).add(c.group)),p.css(v).attr(c.attribs).animate(k,
c.isNew?!1:void 0,h);else if(p){var e=function(){f.graphic=p=p.destroy();"function"===typeof h&&h()};Object.keys(k).length?p.animate(k,void 0,function(){e()}):e()}};return function(f){(f.attribs=f.attribs||{})["class"]=this.getClassName();c.call(this,f)}});q(c,"modules/treemap.src.js",[c["parts/Globals.js"],c["mixins/tree-series.js"],c["mixins/draw-point.js"],c["parts/Color.js"],c["parts/Utilities.js"]],function(c,f,q,p,k){var h=p.parse,n=k.addEvent,v=k.correctFloat,e=k.defined,g=k.error,A=k.extend,
F=k.fireEvent,B=k.isArray,J=k.isNumber,L=k.isObject,w=k.isString,y=k.merge,t=k.objectEach,r=k.pick;p=k.seriesType;var x=k.stableSort,G=c.seriesTypes;k=c.noop;var M=f.getColor,N=f.getLevelOptions,C=c.Series,O=function(a,b,d){d=d||this;t(a,function(c,l){b.call(d,c,l,a)})},E=function(a,b,d){d=d||this;a=b.call(d,a);!1!==a&&E(a,b,d)},P=f.updateRootId,H=!1;p("treemap","scatter",{allowTraversingTree:!1,animationLimit:250,showInLegend:!1,marker:!1,colorByPoint:!1,dataLabels:{defer:!1,enabled:!0,formatter:function(){var a=
this&&this.point?this.point:{};return w(a.name)?a.name:""},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:"",pointFormat:"<b>{point.name}</b>: {point.value}<br/>"},ignoreHiddenPoint:!0,layoutAlgorithm:"sliceAndDice",layoutStartingDirection:"vertical",alternateStartingDirection:!1,levelIsConstant:!0,drillUpButton:{position:{align:"right",x:-10,y:10}},traverseUpButton:{position:{align:"right",x:-10,y:10}},borderColor:"#e6e6e6",borderWidth:1,colorKey:"colorValue",opacity:.15,states:{hover:{borderColor:"#999999",
brightness:G.heatmap?0:.1,halo:!1,opacity:.75,shadow:!1}}},{pointArrayMap:["value"],directTouch:!0,optionalAxis:"colorAxis",getSymbol:k,parallelArrays:["x","y","value","colorValue"],colorKey:"colorValue",trackerGroups:["group","dataLabelsGroup"],getListOfParents:function(a,b){a=B(a)?a:[];var d=B(b)?b:[];b=a.reduce(function(a,b,d){b=r(b.parent,"");"undefined"===typeof a[b]&&(a[b]=[]);a[b].push(d);return a},{"":[]});O(b,function(a,b,c){""!==b&&-1===d.indexOf(b)&&(a.forEach(function(a){c[""].push(a)}),
delete c[b])});return b},getTree:function(){var a=this.data.map(function(a){return a.id});a=this.getListOfParents(this.data,a);this.nodeMap=[];return this.buildNode("",-1,0,a,null)},hasData:function(){return!!this.processedXData.length},init:function(a,b){var d=c.colorMapSeriesMixin;d&&(this.colorAttribs=d.colorAttribs);this.eventsToUnbind.push(n(this,"setOptions",function(a){a=a.userOptions;e(a.allowDrillToNode)&&!e(a.allowTraversingTree)&&(a.allowTraversingTree=a.allowDrillToNode,delete a.allowDrillToNode);
e(a.drillUpButton)&&!e(a.traverseUpButton)&&(a.traverseUpButton=a.drillUpButton,delete a.drillUpButton)}));C.prototype.init.call(this,a,b);this.options.allowTraversingTree&&this.eventsToUnbind.push(n(this,"click",this.onClickDrillToNode))},buildNode:function(a,b,d,c,l){var z=this,m=[],u=z.points[b],e=0,I;(c[a]||[]).forEach(function(b){I=z.buildNode(z.points[b].id,b,d+1,c,a);e=Math.max(I.height+1,e);m.push(I)});b={id:a,i:b,children:m,height:e,level:d,parent:l,visible:!1};z.nodeMap[b.id]=b;u&&(u.node=
b);return b},setTreeValues:function(a){var b=this,d=b.options,c=b.nodeMap[b.rootNode];d="boolean"===typeof d.levelIsConstant?d.levelIsConstant:!0;var l=0,z=[],m=b.points[a.i];a.children.forEach(function(a){a=b.setTreeValues(a);z.push(a);a.ignore||(l+=a.val)});x(z,function(a,b){return a.sortIndex-b.sortIndex});var e=r(m&&m.options.value,l);m&&(m.value=e);A(a,{children:z,childrenTotal:l,ignore:!(r(m&&m.visible,!0)&&0<e),isLeaf:a.visible&&!l,levelDynamic:a.level-(d?0:c.level),name:r(m&&m.name,""),sortIndex:r(m&&
m.sortIndex,-e),val:e});return a},calculateChildrenAreas:function(a,b){var d=this,c=d.options,l=d.mapOptionsToLevel[a.level+1],e=r(d[l&&l.layoutAlgorithm]&&l.layoutAlgorithm,c.layoutAlgorithm),m=c.alternateStartingDirection,f=[];a=a.children.filter(function(a){return!a.ignore});l&&l.layoutStartingDirection&&(b.direction="vertical"===l.layoutStartingDirection?0:1);f=d[e](b,a);a.forEach(function(a,c){c=f[c];a.values=y(c,{val:a.childrenTotal,direction:m?1-b.direction:b.direction});a.pointValues=y(c,
{x:c.x/d.axisRatio,y:100-c.y-c.height,width:c.width/d.axisRatio});a.children.length&&d.calculateChildrenAreas(a,a.values)})},setPointValues:function(){var a=this,b=a.xAxis,d=a.yAxis,c=a.chart.styledMode;a.points.forEach(function(l){var e=l.node,m=e.pointValues;e=e.visible;if(m&&e){e=m.height;var f=m.width,u=m.x,k=m.y,g=c?0:(a.pointAttribs(l)["stroke-width"]||0)%2/2;m=Math.round(b.toPixels(u,!0))-g;f=Math.round(b.toPixels(u+f,!0))-g;u=Math.round(d.toPixels(k,!0))-g;e=Math.round(d.toPixels(k+e,!0))-
g;l.shapeArgs={x:Math.min(m,f),y:Math.min(u,e),width:Math.abs(f-m),height:Math.abs(e-u)};l.plotX=l.shapeArgs.x+l.shapeArgs.width/2;l.plotY=l.shapeArgs.y+l.shapeArgs.height/2}else delete l.plotX,delete l.plotY})},setColorRecursive:function(a,b,d,c,l){var e=this,m=e&&e.chart;m=m&&m.options&&m.options.colors;if(a){var f=M(a,{colors:m,index:c,mapOptionsToLevel:e.mapOptionsToLevel,parentColor:b,parentColorIndex:d,series:e,siblings:l});if(b=e.points[a.i])b.color=f.color,b.colorIndex=f.colorIndex;(a.children||
[]).forEach(function(b,d){e.setColorRecursive(b,f.color,f.colorIndex,d,a.children.length)})}},algorithmGroup:function(a,b,d,c){this.height=a;this.width=b;this.plot=c;this.startDirection=this.direction=d;this.lH=this.nH=this.lW=this.nW=this.total=0;this.elArr=[];this.lP={total:0,lH:0,nH:0,lW:0,nW:0,nR:0,lR:0,aspectRatio:function(a,b){return Math.max(a/b,b/a)}};this.addElement=function(a){this.lP.total=this.elArr[this.elArr.length-1];this.total+=a;0===this.direction?(this.lW=this.nW,this.lP.lH=this.lP.total/
this.lW,this.lP.lR=this.lP.aspectRatio(this.lW,this.lP.lH),this.nW=this.total/this.height,this.lP.nH=this.lP.total/this.nW,this.lP.nR=this.lP.aspectRatio(this.nW,this.lP.nH)):(this.lH=this.nH,this.lP.lW=this.lP.total/this.lH,this.lP.lR=this.lP.aspectRatio(this.lP.lW,this.lH),this.nH=this.total/this.width,this.lP.nW=this.lP.total/this.nH,this.lP.nR=this.lP.aspectRatio(this.lP.nW,this.nH));this.elArr.push(a)};this.reset=function(){this.lW=this.nW=0;this.elArr=[];this.total=0}},algorithmCalcPoints:function(a,
b,d,c){var l,e,f,u,g=d.lW,k=d.lH,h=d.plot,p=0,r=d.elArr.length-1;if(b)g=d.nW,k=d.nH;else var q=d.elArr[d.elArr.length-1];d.elArr.forEach(function(a){if(b||p<r)0===d.direction?(l=h.x,e=h.y,f=g,u=a/f):(l=h.x,e=h.y,u=k,f=a/u),c.push({x:l,y:e,width:f,height:v(u)}),0===d.direction?h.y+=u:h.x+=f;p+=1});d.reset();0===d.direction?d.width-=g:d.height-=k;h.y=h.parent.y+(h.parent.height-d.height);h.x=h.parent.x+(h.parent.width-d.width);a&&(d.direction=1-d.direction);b||d.addElement(q)},algorithmLowAspectRatio:function(a,
b,d){var c=[],l=this,e,f={x:b.x,y:b.y,parent:b},g=0,k=d.length-1,h=new this.algorithmGroup(b.height,b.width,b.direction,f);d.forEach(function(d){e=d.val/b.val*b.height*b.width;h.addElement(e);h.lP.nR>h.lP.lR&&l.algorithmCalcPoints(a,!1,h,c,f);g===k&&l.algorithmCalcPoints(a,!0,h,c,f);g+=1});return c},algorithmFill:function(a,b,d){var c=[],l,e=b.direction,f=b.x,h=b.y,g=b.width,k=b.height,p,r,q,n;d.forEach(function(d){l=d.val/b.val*b.height*b.width;p=f;r=h;0===e?(n=k,q=l/n,g-=q,f+=q):(q=g,n=l/q,k-=n,
h+=n);c.push({x:p,y:r,width:q,height:n});a&&(e=1-e)});return c},strip:function(a,b){return this.algorithmLowAspectRatio(!1,a,b)},squarified:function(a,b){return this.algorithmLowAspectRatio(!0,a,b)},sliceAndDice:function(a,b){return this.algorithmFill(!0,a,b)},stripes:function(a,b){return this.algorithmFill(!1,a,b)},translate:function(){var a=this,b=a.options,d=P(a);C.prototype.translate.call(a);var c=a.tree=a.getTree();var e=a.nodeMap[d];a.renderTraverseUpButton(d);a.mapOptionsToLevel=N({from:e.level+
1,levels:b.levels,to:c.height,defaults:{levelIsConstant:a.options.levelIsConstant,colorByPoint:b.colorByPoint}});""===d||e&&e.children.length||(a.setRootNode("",!1),d=a.rootNode,e=a.nodeMap[d]);E(a.nodeMap[a.rootNode],function(b){var c=!1,d=b.parent;b.visible=!0;if(d||""===d)c=a.nodeMap[d];return c});E(a.nodeMap[a.rootNode].children,function(a){var b=!1;a.forEach(function(a){a.visible=!0;a.children.length&&(b=(b||[]).concat(a.children))});return b});a.setTreeValues(c);a.axisRatio=a.xAxis.len/a.yAxis.len;
a.nodeMap[""].pointValues=d={x:0,y:0,width:100,height:100};a.nodeMap[""].values=d=y(d,{width:d.width*a.axisRatio,direction:"vertical"===b.layoutStartingDirection?0:1,val:c.val});a.calculateChildrenAreas(c,d);a.colorAxis||b.colorByPoint||a.setColorRecursive(a.tree);b.allowTraversingTree&&(b=e.pointValues,a.xAxis.setExtremes(b.x,b.x+b.width,!1),a.yAxis.setExtremes(b.y,b.y+b.height,!1),a.xAxis.setScale(),a.yAxis.setScale());a.setPointValues()},drawDataLabels:function(){var a=this,b=a.mapOptionsToLevel,
c,e;a.points.filter(function(a){return a.node.visible}).forEach(function(d){e=b[d.node.level];c={style:{}};d.node.isLeaf||(c.enabled=!1);e&&e.dataLabels&&(c=y(c,e.dataLabels),a._hasPointLabels=!0);d.shapeArgs&&(c.style.width=d.shapeArgs.width,d.dataLabel&&d.dataLabel.css({width:d.shapeArgs.width+"px"}));d.dlOptions=y(c,d.options.dataLabels)});C.prototype.drawDataLabels.call(this)},alignDataLabel:function(a,b,c){var d=c.style;!e(d.textOverflow)&&b.text&&b.getBBox().width>b.text.textWidth&&b.css({textOverflow:"ellipsis",
width:d.width+="px"});G.column.prototype.alignDataLabel.apply(this,arguments);a.dataLabel&&a.dataLabel.attr({zIndex:(a.node.zIndex||0)+1})},pointAttribs:function(a,b){var c=L(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},e=a&&c[a.node.level]||{};c=this.options;var f=b&&c.states[b]||{},g=a&&a.getClassName()||"";a={stroke:a&&a.borderColor||e.borderColor||f.borderColor||c.borderColor,"stroke-width":r(a&&a.borderWidth,e.borderWidth,f.borderWidth,c.borderWidth),dashstyle:a&&a.borderDashStyle||e.borderDashStyle||
f.borderDashStyle||c.borderDashStyle,fill:a&&a.color||this.color};-1!==g.indexOf("highcharts-above-level")?(a.fill="none",a["stroke-width"]=0):-1!==g.indexOf("highcharts-internal-node-interactive")?(b=r(f.opacity,c.opacity),a.fill=h(a.fill).setOpacity(b).get(),a.cursor="pointer"):-1!==g.indexOf("highcharts-internal-node")?a.fill="none":b&&(a.fill=h(a.fill).brighten(f.brightness).get());return a},drawPoints:function(){var a=this,b=a.chart,c=b.renderer,e=b.styledMode,f=a.options,g=e?{}:f.shadow,h=f.borderRadius,
k=b.pointCount<f.animationLimit,p=f.allowTraversingTree;a.points.forEach(function(b){var d=b.node.levelDynamic,l={},m={},q={},n="level-group-"+d,r=!!b.graphic,u=k&&r,t=b.shapeArgs;b.shouldDraw()&&(h&&(m.r=h),y(!0,u?l:m,r?t:{},e?{}:a.pointAttribs(b,b.selected&&"select")),a.colorAttribs&&e&&A(q,a.colorAttribs(b)),a[n]||(a[n]=c.g(n).attr({zIndex:1E3-d}).add(a.group),a[n].survive=!0));b.draw({animatableAttribs:l,attribs:m,css:q,group:a[n],renderer:c,shadow:g,shapeArgs:t,shapeType:"rect"});p&&b.graphic&&
(b.drillId=f.interactByLeaf?a.drillToByLeaf(b):a.drillToByGroup(b))})},onClickDrillToNode:function(a){var b=(a=a.point)&&a.drillId;w(b)&&(a.setState(""),this.setRootNode(b,!0,{trigger:"click"}))},drillToByGroup:function(a){var b=!1;1!==a.node.level-this.nodeMap[this.rootNode].level||a.node.isLeaf||(b=a.id);return b},drillToByLeaf:function(a){var b=!1;if(a.node.parent!==this.rootNode&&a.node.isLeaf)for(a=a.node;!b;)a=this.nodeMap[a.parent],a.parent===this.rootNode&&(b=a.id);return b},drillUp:function(){var a=
this.nodeMap[this.rootNode];a&&w(a.parent)&&this.setRootNode(a.parent,!0,{trigger:"traverseUpButton"})},drillToNode:function(a,b){g("WARNING: treemap.drillToNode has been renamed to treemap.setRootNode, and will be removed in the next major version.");this.setRootNode(a,b)},setRootNode:function(a,b,c){a=A({newRootId:a,previousRootId:this.rootNode,redraw:r(b,!0),series:this},c);F(this,"setRootNode",a,function(a){var b=a.series;b.idPreviousRoot=a.previousRootId;b.rootNode=a.newRootId;b.isDirty=!0;a.redraw&&
b.chart.redraw()})},renderTraverseUpButton:function(a){var b=this,c=b.options.traverseUpButton,e=r(c.text,b.nodeMap[a].name,"< Back");if(""===a)b.drillUpButton&&(b.drillUpButton=b.drillUpButton.destroy());else if(this.drillUpButton)this.drillUpButton.placed=!1,this.drillUpButton.attr({text:e}).align();else{var f=(a=c.theme)&&a.states;this.drillUpButton=this.chart.renderer.button(e,null,null,function(){b.drillUp()},a,f&&f.hover,f&&f.select).addClass("highcharts-drillup-button").attr({align:c.position.align,
zIndex:7}).add().align(c.position,!1,c.relativeTo||"plotBox")}},buildKDTree:k,drawLegendSymbol:c.LegendSymbolMixin.drawRectangle,getExtremes:function(){C.prototype.getExtremes.call(this,this.colorValueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;C.prototype.getExtremes.call(this)},getExtremesFromAll:!0,setState:function(a){this.options.inactiveOtherPoints=!0;C.prototype.setState.call(this,a,!1);this.options.inactiveOtherPoints=!1},utils:{recursive:E}},{draw:q,setVisible:G.pie.prototype.pointClass.prototype.setVisible,
getClassName:function(){var a=c.Point.prototype.getClassName.call(this),b=this.series,d=b.options;this.node.level<=b.nodeMap[b.rootNode].level?a+=" highcharts-above-level":this.node.isLeaf||r(d.interactByLeaf,!d.allowTraversingTree)?this.node.isLeaf||(a+=" highcharts-internal-node"):a+=" highcharts-internal-node-interactive";return a},isValid:function(){return this.id||J(this.value)},setState:function(a){c.Point.prototype.setState.call(this,a);this.graphic&&this.graphic.attr({zIndex:"hover"===a?1:
0})},shouldDraw:function(){return J(this.plotY)&&null!==this.y}});n(c.Series,"afterBindAxes",function(){var a=this.xAxis,b=this.yAxis;if(a&&b)if(this.is("treemap")){var c={endOnTick:!1,gridLineWidth:0,lineWidth:0,min:0,dataMin:0,minPadding:0,max:100,dataMax:100,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};A(b.options,c);A(a.options,c);H=!0}else H&&(b.setOptions(b.userOptions),a.setOptions(a.userOptions),H=!1)});""});q(c,"masters/modules/treemap.src.js",[],function(){})});
//# sourceMappingURL=treemap.js.map