/*
 Highcharts JS v8.0.0 (2020-02-16)

 (c) 2009-2018 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(r){"object"===typeof module&&module.exports?(r["default"]=r,module.exports=r):"function"===typeof define&&define.amd?define("highcharts/highcharts-more",["highcharts"],function(E){r(E);r.Highcharts=E;return r}):r("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(r){function E(h,a,c,e){h.hasOwnProperty(a)||(h[a]=e.apply(null,c))}r=r?r._modules:{};E(r,"parts-more/Pane.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){function c(k,a){this.init(k,a)}function e(k,
a,l){return Math.sqrt(Math.pow(k-l[0],2)+Math.pow(a-l[1],2))<l[2]/2}var v=a.addEvent,q=a.extend,z=a.merge,y=a.pick,w=a.splat,g=h.CenteredSeriesMixin;h.Chart.prototype.collectionsWithUpdate.push("pane");q(c.prototype,{coll:"pane",init:function(k,a){this.chart=a;this.background=[];a.pane.push(this);this.setOptions(k)},setOptions:function(k){this.options=z(this.defaultOptions,this.chart.angular?{background:{}}:void 0,k)},render:function(){var k=this.options,a=this.options.background,l=this.chart.renderer;
this.group||(this.group=l.g("pane-group").attr({zIndex:k.zIndex||0}).add());this.updateCenter();if(a)for(a=w(a),k=Math.max(a.length,this.background.length||0),l=0;l<k;l++)a[l]&&this.axis?this.renderBackground(z(this.defaultBackgroundOptions,a[l]),l):this.background[l]&&(this.background[l]=this.background[l].destroy(),this.background.splice(l,1))},renderBackground:function(k,a){var l="animate",g={"class":"highcharts-pane "+(k.className||"")};this.chart.styledMode||q(g,{fill:k.backgroundColor,stroke:k.borderColor,
"stroke-width":k.borderWidth});this.background[a]||(this.background[a]=this.chart.renderer.path().add(this.group),l="attr");this.background[a][l]({d:this.axis.getPlotBandPath(k.from,k.to,k)}).attr(g)},defaultOptions:{center:["50%","50%"],size:"85%",innerSize:"0%",startAngle:0},defaultBackgroundOptions:{shape:"circle",borderWidth:1,borderColor:"#cccccc",backgroundColor:{linearGradient:{x1:0,y1:0,x2:0,y2:1},stops:[[0,"#ffffff"],[1,"#e6e6e6"]]},from:-Number.MAX_VALUE,innerRadius:0,to:Number.MAX_VALUE,
outerRadius:"105%"},updateCenter:function(a){this.center=(a||this.axis||{}).center=g.getCenter.call(this)},update:function(a,g){z(!0,this.options,a);z(!0,this.chart.options.pane,a);this.setOptions(this.options);this.render();this.chart.axes.forEach(function(a){a.pane===this&&(a.pane=null,a.update({},g))},this)}});h.Pane=c;h.Chart.prototype.getHoverPane=function(a){var k=this,g;a&&k.pane.forEach(function(l){var n=a.chartX-k.plotLeft,m=a.chartY-k.plotTop;e(k.inverted?m:n,k.inverted?n:m,l.center)&&(g=
l)});return g};v(h.Chart,"afterIsInsidePlot",function(a){this.polar&&(a.isInsidePlot=this.pane.some(function(k){return e(a.x,a.y,k.center)}))});v(h.Pointer,"beforeGetHoverData",function(a){var k=this.chart;k.polar&&(k.hoverPane=k.getHoverPane(a),a.filter=function(g){return g.visible&&!(!a.shared&&g.directTouch)&&y(g.options.enableMouseTracking,!0)&&(!k.hoverPane||g.xAxis.pane===k.hoverPane)})});v(h.Pointer,"afterGetHoverData",function(a){var k=this.chart;a.hoverPoint&&a.hoverPoint.plotX&&a.hoverPoint.plotY&&
k.hoverPane&&!e(a.hoverPoint.plotX,a.hoverPoint.plotY,k.hoverPane.center)&&(a.hoverPoint=void 0)})});E(r,"parts-more/RadialAxis.js",[r["parts/Globals.js"],r["parts/Tick.js"],r["parts/Utilities.js"]],function(h,a,c){var e=c.addEvent,v=c.correctFloat,q=c.defined,z=c.extend,y=c.merge,w=c.pick,g=c.pInt,k=c.relativeLength;c=c.wrap;var t=h.Axis,l=h.noop,B=t.prototype,n=a.prototype;var m={getOffset:l,redraw:function(){this.isDirty=!1},render:function(){this.isDirty=!1},createLabelCollector:function(){return!1},
setScale:l,setCategories:l,setTitle:l};var C={defaultRadialGaugeOptions:{labels:{align:"center",x:0,y:null},minorGridLineWidth:0,minorTickInterval:"auto",minorTickLength:10,minorTickPosition:"inside",minorTickWidth:1,tickLength:10,tickPosition:"inside",tickWidth:2,title:{rotation:0},zIndex:2},defaultCircularOptions:{gridLineWidth:1,labels:{align:null,distance:15,x:0,y:null,style:{textOverflow:"none"}},maxPadding:0,minPadding:0,showLastLabel:!1,tickLength:0},defaultRadialOptions:{gridLineInterpolation:"circle",
gridLineWidth:1,labels:{align:"right",x:-3,y:-2},showLastLabel:!1,title:{x:4,text:null,rotation:90}},setOptions:function(b){b=this.options=y(this.defaultOptions,this.defaultPolarOptions,b);b.plotBands||(b.plotBands=[]);h.fireEvent(this,"afterSetOptions")},getOffset:function(){B.getOffset.call(this);this.chart.axisOffset[this.side]=0},getLinePath:function(b,d,f){b=this.center;var p=this.chart,m=w(d,b[2]/2-this.offset);"undefined"===typeof f&&(f=this.horiz?0:this.center&&-this.center[3]/2);f&&(m+=f);
this.isCircular||"undefined"!==typeof d?(d=this.chart.renderer.symbols.arc(this.left+b[0],this.top+b[1]+(f||0),m,m,{start:this.startAngleRad,end:this.endAngleRad,open:!0,innerR:0}),d.xBounds=[this.left+b[0]],d.yBounds=[this.top+b[1]-m]):(d=this.postTranslate(this.angleRad,m),d=["M",b[0]+p.plotLeft,b[1]+p.plotTop,"L",d.x,d.y]);return d},setAxisTranslation:function(){B.setAxisTranslation.call(this);this.center&&(this.transA=this.isCircular?(this.endAngleRad-this.startAngleRad)/(this.max-this.min||1):
(this.center[2]-this.center[3])/2/(this.max-this.min||1),this.minPixelPadding=this.isXAxis?this.transA*this.minPointOffset:0)},beforeSetTickPositions:function(){this.autoConnect=this.isCircular&&"undefined"===typeof w(this.userMax,this.options.max)&&v(this.endAngleRad-this.startAngleRad)===v(2*Math.PI);!this.isCircular&&this.chart.inverted&&this.max++;this.autoConnect&&(this.max+=this.categories&&1||this.pointRange||this.closestPointRange||0)},setAxisSize:function(){B.setAxisSize.call(this);this.isRadial&&
(this.pane.updateCenter(this),this.isCircular?this.sector=this.endAngleRad-this.startAngleRad:this.center[1]-=this.center[3]/2,this.len=this.width=this.height=(this.center[2]-this.center[3])*w(this.sector,1)/2)},getPosition:function(b,d){b=this.translate(b);return this.postTranslate(this.isCircular?b:this.angleRad,w(this.isCircular?d:0>b?0:b,this.center[2]/2)-this.offset)},postTranslate:function(b,d){var f=this.chart,p=this.center;b=this.startAngleRad+b;return{x:f.plotLeft+p[0]+Math.cos(b)*d,y:f.plotTop+
p[1]+Math.sin(b)*d}},getPlotBandPath:function(b,d,f){var p=this.center,m=this.startAngleRad,a=p[2]/2,u=[w(f.outerRadius,"100%"),f.innerRadius,w(f.thickness,10)],k=Math.min(this.offset,0),l=/%$/;var n=this.isCircular;if("polygon"===this.options.gridLineInterpolation)u=this.getPlotLinePath({value:b}).concat(this.getPlotLinePath({value:d,reverse:!0}));else{b=Math.max(b,this.min);d=Math.min(d,this.max);n||(u[0]=this.translate(b),u[1]=this.translate(d));u=u.map(function(f){l.test(f)&&(f=g(f,10)*a/100);
return f});if("circle"!==f.shape&&n)b=m+this.translate(b),d=m+this.translate(d);else{b=-Math.PI/2;d=1.5*Math.PI;var e=!0}u[0]-=k;u[2]-=k;u=this.chart.renderer.symbols.arc(this.left+p[0],this.top+p[1],u[0],u[0],{start:Math.min(b,d),end:Math.max(b,d),innerR:w(u[1],u[0]-u[2]),open:e});n&&(n=(d+b)/2,k=this.left+p[0]+p[2]/2*Math.cos(n),u.xBounds=n>-Math.PI/2&&n<Math.PI/2?[k,this.chart.plotWidth]:[0,k],u.yBounds=[this.top+p[1]+p[2]/2*Math.sin(n)],u.yBounds[0]+=n>-Math.PI&&0>n||n>Math.PI?-10:10)}return u},
getCrosshairPosition:function(b,d,f){var p=b.value,m=this.pane.center;if(this.isCircular){if(q(p))b.point&&(a=b.point.shapeArgs||{},a.start&&(p=this.chart.inverted?this.translate(b.point.rectPlotY,!0):b.point.x));else{var a=b.chartX||0;var u=b.chartY||0;p=this.translate(Math.atan2(u-f,a-d)-this.startAngleRad,!0)}b=this.getPosition(p);a=b.x;u=b.y}else q(p)||(a=b.chartX,u=b.chartY),q(a)&&q(u)&&(f=m[1]+this.chart.plotTop,p=this.translate(Math.min(Math.sqrt(Math.pow(a-d,2)+Math.pow(u-f,2)),m[2]/2)-m[3]/
2,!0));return[p,a||0,u||0]},getPlotLinePath:function(b){var d=this,f=d.center,p=d.chart,m=p.inverted,a=b.value,u=b.reverse,g=d.getPosition(a),n=d.pane.options.background?d.pane.options.background[0]||d.pane.options.background:{},l=n.innerRadius||"0%",e=n.outerRadius||"100%";n=f[0]+p.plotLeft;var c=f[1]+p.plotTop,C=g.x,t=g.y,v=d.height;g=f[3]/2;var q,h;b.isCrosshair&&(t=this.getCrosshairPosition(b,n,c),a=t[0],C=t[1],t=t[2]);if(d.isCircular){u=Math.sqrt(Math.pow(C-n,2)+Math.pow(t-c,2));l="string"===
typeof l?k(l,1):l/u;e="string"===typeof e?k(e,1):e/u;f&&g&&(f=g/u,l<f&&(l=f),e<f&&(e=f));var B=["M",n+l*(C-n),c-l*(c-t),"L",C-(1-e)*(C-n),t+(1-e)*(c-t)]}else(a=d.translate(a))&&(0>a||a>v)&&(a=0),"circle"===d.options.gridLineInterpolation?B=d.getLinePath(0,a,g):(p[m?"yAxis":"xAxis"].forEach(function(f){f.pane===d.pane&&(q=f)}),B=[],f=q.tickPositions,q.autoConnect&&(f=f.concat([f[0]])),u&&(f=[].concat(f).reverse()),a&&(a+=g),f.forEach(function(f,b){h=q.getPosition(f,a);B.push(b?"L":"M",h.x,h.y)}));
return B},getTitlePosition:function(){var b=this.center,d=this.chart,f=this.options.title;return{x:d.plotLeft+b[0]+(f.x||0),y:d.plotTop+b[1]-{high:.5,middle:.25,low:0}[f.align]*b[2]+(f.y||0)}},createLabelCollector:function(){var b=this;return function(){if(b.isRadial&&b.tickPositions&&!0!==b.options.labels.allowOverlap)return b.tickPositions.map(function(d){return b.ticks[d]&&b.ticks[d].label}).filter(function(b){return!!b})}}};e(t,"init",function(b){var d=this.chart,f=d.inverted,p=d.angular,a=d.polar,
k=this.isXAxis,u=this.coll,g=p&&k,n,l=d.options;b=b.userOptions.pane||0;b=this.pane=d.pane&&d.pane[b];if("colorAxis"===u)this.isRadial=!1;else{if(p){if(z(this,g?m:C),n=!k)this.defaultPolarOptions=this.defaultRadialGaugeOptions}else a&&(z(this,C),this.defaultPolarOptions=(n=this.horiz)?this.defaultCircularOptions:y("xAxis"===u?this.defaultOptions:this.defaultYAxisOptions,this.defaultRadialOptions),f&&"yAxis"===u&&(this.defaultPolarOptions.stackLabels=this.defaultYAxisOptions.stackLabels));p||a?(this.isRadial=
!0,l.chart.zoomType=null,this.labelCollector||(this.labelCollector=this.createLabelCollector()),this.labelCollector&&d.labelCollectors.push(this.labelCollector)):this.isRadial=!1;b&&n&&(b.axis=this);this.isCircular=n}});e(t,"afterInit",function(){var b=this.chart,d=this.options,f=this.pane,p=f&&f.options;b.angular&&this.isXAxis||!f||!b.angular&&!b.polar||(this.angleRad=(d.angle||0)*Math.PI/180,this.startAngleRad=(p.startAngle-90)*Math.PI/180,this.endAngleRad=(w(p.endAngle,p.startAngle+360)-90)*Math.PI/
180,this.offset=d.offset||0)});e(t,"autoLabelAlign",function(b){this.isRadial&&(b.align=void 0,b.preventDefault())});e(t,"destroy",function(){if(this.chart&&this.chart.labelCollectors){var b=this.chart.labelCollectors.indexOf(this.labelCollector);0<=b&&this.chart.labelCollectors.splice(b,1)}});e(a,"afterGetPosition",function(b){this.axis.getPosition&&z(b.pos,this.axis.getPosition(this.pos))});e(a,"afterGetLabelPosition",function(b){var d=this.axis,f=this.label,p=f.getBBox(),m=d.options.labels,a=m.y,
u=20,g=m.align,n=(d.translate(this.pos)+d.startAngleRad+Math.PI/2)/Math.PI*180%360,l=Math.round(n),e="end",c=0>l?l+360:l,C=c,t=0,v=0,q=null===m.y?.3*-p.height:0;if(d.isRadial){var h=d.getPosition(this.pos,d.center[2]/2+k(w(m.distance,-25),d.center[2]/2,-d.center[2]/2));"auto"===m.rotation?f.attr({rotation:n}):null===a&&(a=d.chart.renderer.fontMetrics(f.styles&&f.styles.fontSize).b-p.height/2);null===g&&(d.isCircular?(p.width>d.len*d.tickInterval/(d.max-d.min)&&(u=0),g=n>u&&n<180-u?"left":n>180+u&&
n<360-u?"right":"center"):g="center",f.attr({align:g}));if("auto"===g&&2===d.tickPositions.length&&d.isCircular){90<c&&180>c?c=180-c:270<c&&360>=c&&(c=540-c);180<C&&360>=C&&(C=360-C);if(d.pane.options.startAngle===l||d.pane.options.startAngle===l+360||d.pane.options.startAngle===l-360)e="start";g=-90<=l&&90>=l||-360<=l&&-270>=l||270<=l&&360>=l?"start"===e?"right":"left":"start"===e?"left":"right";70<C&&110>C&&(g="center");15>c||180<=c&&195>c?t=.3*p.height:15<=c&&35>=c?t="start"===e?0:.75*p.height:
195<=c&&215>=c?t="start"===e?.75*p.height:0:35<c&&90>=c?t="start"===e?.25*-p.height:p.height:215<c&&270>=c&&(t="start"===e?p.height:.25*-p.height);15>C?v="start"===e?.15*-p.height:.15*p.height:165<C&&180>=C&&(v="start"===e?.15*p.height:.15*-p.height);f.attr({align:g});f.translate(v,t+q)}b.pos.x=h.x+m.x;b.pos.y=h.y+a}});c(n,"getMarkPath",function(b,d,f,p,m,a,u){var k=this.axis;k.isRadial?(b=k.getPosition(this.pos,k.center[2]/2+p),d=["M",d,f,"L",b.x,b.y]):d=b.call(this,d,f,p,m,a,u);return d})});E(r,
"parts-more/AreaRangeSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.defined,e=a.extend,v=a.isArray,q=a.isNumber,z=a.pick;a=a.seriesType;var y=h.seriesTypes,w=h.Series.prototype,g=h.Point.prototype;a("arearange","area",{lineWidth:1,threshold:null,tooltip:{pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},trackByArea:!0,dataLabels:{align:null,verticalAlign:null,xLow:0,xHigh:0,yLow:0,yHigh:0}},
{pointArrayMap:["low","high"],pointValKey:"low",deferTranslatePolar:!0,toYData:function(a){return[a.low,a.high]},highToXY:function(a){var g=this.chart,k=this.xAxis.postTranslate(a.rectPlotX,this.yAxis.len-a.plotHigh);a.plotHighX=k.x-g.plotLeft;a.plotHigh=k.y-g.plotTop;a.plotLowX=a.plotX},translate:function(){var a=this,g=a.yAxis,l=!!a.modifyValue;y.area.prototype.translate.apply(a);a.points.forEach(function(k){var n=k.high,m=k.plotY;k.isNull?k.plotY=null:(k.plotLow=m,k.plotHigh=g.translate(l?a.modifyValue(n,
k):n,0,1,0,1),l&&(k.yBottom=k.plotHigh))});this.chart.polar&&this.points.forEach(function(g){a.highToXY(g);g.tooltipPos=[(g.plotHighX+g.plotLowX)/2,(g.plotHigh+g.plotLow)/2]})},getGraphPath:function(a){var g=[],k=[],c,n=y.area.prototype.getGraphPath;var m=this.options;var e=this.chart.polar&&!1!==m.connectEnds,b=m.connectNulls,d=m.step;a=a||this.points;for(c=a.length;c--;){var f=a[c];f.isNull||e||b||a[c+1]&&!a[c+1].isNull||k.push({plotX:f.plotX,plotY:f.plotY,doCurve:!1});var p={polarPlotY:f.polarPlotY,
rectPlotX:f.rectPlotX,yBottom:f.yBottom,plotX:z(f.plotHighX,f.plotX),plotY:f.plotHigh,isNull:f.isNull};k.push(p);g.push(p);f.isNull||e||b||a[c-1]&&!a[c-1].isNull||k.push({plotX:f.plotX,plotY:f.plotY,doCurve:!1})}a=n.call(this,a);d&&(!0===d&&(d="left"),m.step={left:"right",center:"center",right:"left"}[d]);g=n.call(this,g);k=n.call(this,k);m.step=d;m=[].concat(a,g);this.chart.polar||"M"!==k[0]||(k[0]="L");this.graphPath=m;this.areaPath=a.concat(k);m.isArea=!0;m.xMap=a.xMap;this.areaPath.xMap=a.xMap;
return m},drawDataLabels:function(){var a=this.points,g=a.length,l,c=[],n=this.options.dataLabels,m,C=this.chart.inverted;if(v(n))if(1<n.length){var b=n[0];var d=n[1]}else b=n[0],d={enabled:!1};else b=e({},n),b.x=n.xHigh,b.y=n.yHigh,d=e({},n),d.x=n.xLow,d.y=n.yLow;if(b.enabled||this._hasPointLabels){for(l=g;l--;)if(m=a[l]){var f=b.inside?m.plotHigh<m.plotLow:m.plotHigh>m.plotLow;m.y=m.high;m._plotY=m.plotY;m.plotY=m.plotHigh;c[l]=m.dataLabel;m.dataLabel=m.dataLabelUpper;m.below=f;C?b.align||(b.align=
f?"right":"left"):b.verticalAlign||(b.verticalAlign=f?"top":"bottom")}this.options.dataLabels=b;w.drawDataLabels&&w.drawDataLabels.apply(this,arguments);for(l=g;l--;)if(m=a[l])m.dataLabelUpper=m.dataLabel,m.dataLabel=c[l],delete m.dataLabels,m.y=m.low,m.plotY=m._plotY}if(d.enabled||this._hasPointLabels){for(l=g;l--;)if(m=a[l])f=d.inside?m.plotHigh<m.plotLow:m.plotHigh>m.plotLow,m.below=!f,C?d.align||(d.align=f?"left":"right"):d.verticalAlign||(d.verticalAlign=f?"bottom":"top");this.options.dataLabels=
d;w.drawDataLabels&&w.drawDataLabels.apply(this,arguments)}if(b.enabled)for(l=g;l--;)if(m=a[l])m.dataLabels=[m.dataLabelUpper,m.dataLabel].filter(function(f){return!!f});this.options.dataLabels=n},alignDataLabel:function(){y.column.prototype.alignDataLabel.apply(this,arguments)},drawPoints:function(){var a=this.points.length,g;w.drawPoints.apply(this,arguments);for(g=0;g<a;){var l=this.points[g];l.origProps={plotY:l.plotY,plotX:l.plotX,isInside:l.isInside,negative:l.negative,zone:l.zone,y:l.y};l.lowerGraphic=
l.graphic;l.graphic=l.upperGraphic;l.plotY=l.plotHigh;c(l.plotHighX)&&(l.plotX=l.plotHighX);l.y=l.high;l.negative=l.high<(this.options.threshold||0);l.zone=this.zones.length&&l.getZone();this.chart.polar||(l.isInside=l.isTopInside="undefined"!==typeof l.plotY&&0<=l.plotY&&l.plotY<=this.yAxis.len&&0<=l.plotX&&l.plotX<=this.xAxis.len);g++}w.drawPoints.apply(this,arguments);for(g=0;g<a;)l=this.points[g],l.upperGraphic=l.graphic,l.graphic=l.lowerGraphic,e(l,l.origProps),delete l.origProps,g++},setStackedPoints:h.noop},
{setState:function(){var a=this.state,e=this.series,l=e.chart.polar;c(this.plotHigh)||(this.plotHigh=e.yAxis.toPixels(this.high,!0));c(this.plotLow)||(this.plotLow=this.plotY=e.yAxis.toPixels(this.low,!0));e.stateMarkerGraphic&&(e.lowerStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.upperStateMarkerGraphic);this.graphic=this.upperGraphic;this.plotY=this.plotHigh;l&&(this.plotX=this.plotHighX);g.setState.apply(this,arguments);this.state=a;this.plotY=this.plotLow;this.graphic=this.lowerGraphic;
l&&(this.plotX=this.plotLowX);e.stateMarkerGraphic&&(e.upperStateMarkerGraphic=e.stateMarkerGraphic,e.stateMarkerGraphic=e.lowerStateMarkerGraphic,e.lowerStateMarkerGraphic=void 0);g.setState.apply(this,arguments)},haloPath:function(){var a=this.series.chart.polar,e=[];this.plotY=this.plotLow;a&&(this.plotX=this.plotLowX);this.isInside&&(e=g.haloPath.apply(this,arguments));this.plotY=this.plotHigh;a&&(this.plotX=this.plotHighX);this.isTopInside&&(e=e.concat(g.haloPath.apply(this,arguments)));return e},
destroyElements:function(){["lowerGraphic","upperGraphic"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this);this.graphic=null;return g.destroyElements.apply(this,arguments)},isValid:function(){return q(this.low)&&q(this.high)}});""});E(r,"parts-more/AreaSplineRangeSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){a=a.seriesType;a("areasplinerange","arearange",null,{getPointSpline:h.seriesTypes.spline.prototype.getPointSpline});""});E(r,"parts-more/ColumnRangeSeries.js",
[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.clamp,e=a.merge,v=a.pick;a=a.seriesType;var q=h.defaultPlotOptions,z=h.noop,y=h.seriesTypes.column.prototype;a("columnrange","arearange",e(q.column,q.arearange,{pointRange:null,marker:null,states:{hover:{halo:!1}}}),{translate:function(){var a=this,g=a.yAxis,k=a.xAxis,e=k.startAngleRad,l,q=a.chart,n=a.xAxis.isRadial,m=Math.max(q.chartWidth,q.chartHeight)+999,C;y.translate.apply(a);a.points.forEach(function(b){var d=b.shapeArgs,
f=a.options.minPointLength;b.plotHigh=C=c(g.translate(b.high,0,1,0,1),-m,m);b.plotLow=c(b.plotY,-m,m);var p=C;var D=v(b.rectPlotY,b.plotY)-C;Math.abs(D)<f?(f-=D,D+=f,p-=f/2):0>D&&(D*=-1,p-=D);n?(l=b.barX+e,b.shapeType="arc",b.shapeArgs=a.polarArc(p+D,p,l,l+b.pointWidth)):(d.height=D,d.y=p,b.tooltipPos=q.inverted?[g.len+g.pos-q.plotLeft-p-D/2,k.len+k.pos-q.plotTop-d.x-d.width/2,D]:[k.left-q.plotLeft+d.x+d.width/2,g.pos-q.plotTop+p+D/2,D])})},directTouch:!0,trackerGroups:["group","dataLabelsGroup"],
drawGraph:z,getSymbol:z,crispCol:function(){return y.crispCol.apply(this,arguments)},drawPoints:function(){return y.drawPoints.apply(this,arguments)},drawTracker:function(){return y.drawTracker.apply(this,arguments)},getColumnMetrics:function(){return y.getColumnMetrics.apply(this,arguments)},pointAttribs:function(){return y.pointAttribs.apply(this,arguments)},animate:function(){return y.animate.apply(this,arguments)},polarArc:function(){return y.polarArc.apply(this,arguments)},translate3dPoints:function(){return y.translate3dPoints.apply(this,
arguments)},translate3dShapes:function(){return y.translate3dShapes.apply(this,arguments)}},{setState:y.pointClass.prototype.setState});""});E(r,"parts-more/ColumnPyramidSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.clamp,e=a.pick;a=a.seriesType;var v=h.seriesTypes.column.prototype;a("columnpyramid","column",{},{translate:function(){var a=this,h=a.chart,y=a.options,w=a.dense=2>a.closestPointRange*a.xAxis.transA;w=a.borderWidth=e(y.borderWidth,w?0:1);var g=a.yAxis,
k=y.threshold,t=a.translatedThreshold=g.getThreshold(k),l=e(y.minPointLength,5),B=a.getColumnMetrics(),n=B.width,m=a.barW=Math.max(n,1+2*w),C=a.pointXOffset=B.offset;h.inverted&&(t-=.5);y.pointPadding&&(m=Math.ceil(m));v.translate.apply(a);a.points.forEach(function(b){var d=e(b.yBottom,t),f=999+Math.abs(d),p=c(b.plotY,-f,g.len+f);f=b.plotX+C;var D=m/2,F=Math.min(p,d);d=Math.max(p,d)-F;var u;b.barX=f;b.pointWidth=n;b.tooltipPos=h.inverted?[g.len+g.pos-h.plotLeft-p,a.xAxis.len-f-D,d]:[f+D,p+g.pos-h.plotTop,
d];p=k+(b.total||b.y);"percent"===y.stacking&&(p=k+(0>b.y)?-100:100);p=g.toPixels(p,!0);var G=(u=h.plotHeight-p-(h.plotHeight-t))?D*(F-p)/u:0;var v=u?D*(F+d-p)/u:0;u=f-G+D;G=f+G+D;var q=f+v+D;v=f-v+D;var z=F-l;var H=F+d;0>b.y&&(z=F,H=F+d+l);h.inverted&&(q=h.plotWidth-F,u=p-(h.plotWidth-t),G=D*(p-q)/u,v=D*(p-(q-d))/u,u=f+D+G,G=u-2*G,q=f-v+D,v=f+v+D,z=F,H=F+d-l,0>b.y&&(H=F+d+l));b.shapeType="path";b.shapeArgs={x:u,y:z,width:G-u,height:d,d:["M",u,z,"L",G,z,q,H,v,H,"Z"]}})}});""});E(r,"parts-more/GaugeSeries.js",
[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.clamp,e=a.isNumber,v=a.merge,q=a.pick,z=a.pInt;a=a.seriesType;var y=h.Series,w=h.TrackerMixin;a("gauge","line",{dataLabels:{borderColor:"#cccccc",borderRadius:3,borderWidth:1,crop:!1,defer:!1,enabled:!0,verticalAlign:"top",y:15,zIndex:2},dial:{},pivot:{},tooltip:{headerFormat:""},showInLegend:!1},{angular:!0,directTouch:!0,drawGraph:h.noop,fixedBox:!0,forceDL:!0,noSharedTooltip:!0,trackerGroups:["group","dataLabelsGroup"],translate:function(){var a=
this.yAxis,k=this.options,h=a.center;this.generatePoints();this.points.forEach(function(g){var l=v(k.dial,g.dial),n=z(q(l.radius,"80%"))*h[2]/200,m=z(q(l.baseLength,"70%"))*n/100,C=z(q(l.rearLength,"10%"))*n/100,b=l.baseWidth||3,d=l.topWidth||1,f=k.overshoot,p=a.startAngleRad+a.translate(g.y,null,null,null,!0);if(e(f)||!1===k.wrap)f=e(f)?f/180*Math.PI:0,p=c(p,a.startAngleRad-f,a.endAngleRad+f);p=180*p/Math.PI;g.shapeType="path";g.shapeArgs={d:l.path||["M",-C,-b/2,"L",m,-b/2,n,-d/2,n,d/2,m,b/2,-C,
b/2,"z"],translateX:h[0],translateY:h[1],rotation:p};g.plotX=h[0];g.plotY=h[1]})},drawPoints:function(){var a=this,k=a.chart,e=a.yAxis.center,l=a.pivot,c=a.options,n=c.pivot,m=k.renderer;a.points.forEach(function(g){var b=g.graphic,d=g.shapeArgs,f=d.d,p=v(c.dial,g.dial);b?(b.animate(d),d.d=f):g.graphic=m[g.shapeType](d).attr({rotation:d.rotation,zIndex:1}).addClass("highcharts-dial").add(a.group);if(!k.styledMode)g.graphic[b?"animate":"attr"]({stroke:p.borderColor||"none","stroke-width":p.borderWidth||
0,fill:p.backgroundColor||"#000000"})});l?l.animate({translateX:e[0],translateY:e[1]}):(a.pivot=m.circle(0,0,q(n.radius,5)).attr({zIndex:2}).addClass("highcharts-pivot").translate(e[0],e[1]).add(a.group),k.styledMode||a.pivot.attr({"stroke-width":n.borderWidth||0,stroke:n.borderColor||"#cccccc",fill:n.backgroundColor||"#000000"}))},animate:function(a){var g=this;a||(g.points.forEach(function(a){var e=a.graphic;e&&(e.attr({rotation:180*g.yAxis.startAngleRad/Math.PI}),e.animate({rotation:a.shapeArgs.rotation},
g.options.animation))}),g.animate=null)},render:function(){this.group=this.plotGroup("group","series",this.visible?"visible":"hidden",this.options.zIndex,this.chart.seriesGroup);y.prototype.render.call(this);this.group.clip(this.chart.clipRect)},setData:function(a,e){y.prototype.setData.call(this,a,!1);this.processData();this.generatePoints();q(e,!0)&&this.chart.redraw()},hasData:function(){return!!this.points.length},drawTracker:w&&w.drawTrackerPoint},{setState:function(a){this.state=a}});""});E(r,
"parts-more/BoxPlotSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.pick;a=a.seriesType;var e=h.noop,v=h.seriesTypes;a("boxplot","column",{threshold:null,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Maximum: {point.high}<br/>Upper quartile: {point.q3}<br/>Median: {point.median}<br/>Lower quartile: {point.q1}<br/>Minimum: {point.low}<br/>'},whiskerLength:"50%",fillColor:"#ffffff",lineWidth:1,medianWidth:2,whiskerWidth:2},
{pointArrayMap:["low","q1","median","q3","high"],toYData:function(a){return[a.low,a.q1,a.median,a.q3,a.high]},pointValKey:"high",pointAttribs:function(){return{}},drawDataLabels:e,translate:function(){var a=this.yAxis,e=this.pointArrayMap;v.column.prototype.translate.apply(this);this.points.forEach(function(c){e.forEach(function(e){null!==c[e]&&(c[e+"Plot"]=a.translate(c[e],0,1,0,1))})})},drawPoints:function(){var a=this,e=a.options,v=a.chart,h=v.renderer,g,k,t,l,r,n,m=0,C,b,d,f,p=!1!==a.doQuartiles,
D,F=a.options.whiskerLength;a.points.forEach(function(u){var G=u.graphic,I=G?"animate":"attr",q=u.shapeArgs,J={},H={},K={},A={},x=u.color||a.color;"undefined"!==typeof u.plotY&&(C=q.width,b=Math.floor(q.x),d=b+C,f=Math.round(C/2),g=Math.floor(p?u.q1Plot:u.lowPlot),k=Math.floor(p?u.q3Plot:u.lowPlot),t=Math.floor(u.highPlot),l=Math.floor(u.lowPlot),G||(u.graphic=G=h.g("point").add(a.group),u.stem=h.path().addClass("highcharts-boxplot-stem").add(G),F&&(u.whiskers=h.path().addClass("highcharts-boxplot-whisker").add(G)),
p&&(u.box=h.path(void 0).addClass("highcharts-boxplot-box").add(G)),u.medianShape=h.path(void 0).addClass("highcharts-boxplot-median").add(G)),v.styledMode||(H.stroke=u.stemColor||e.stemColor||x,H["stroke-width"]=c(u.stemWidth,e.stemWidth,e.lineWidth),H.dashstyle=u.stemDashStyle||e.stemDashStyle,u.stem.attr(H),F&&(K.stroke=u.whiskerColor||e.whiskerColor||x,K["stroke-width"]=c(u.whiskerWidth,e.whiskerWidth,e.lineWidth),u.whiskers.attr(K)),p&&(J.fill=u.fillColor||e.fillColor||x,J.stroke=e.lineColor||
x,J["stroke-width"]=e.lineWidth||0,u.box.attr(J)),A.stroke=u.medianColor||e.medianColor||x,A["stroke-width"]=c(u.medianWidth,e.medianWidth,e.lineWidth),u.medianShape.attr(A)),n=u.stem.strokeWidth()%2/2,m=b+f+n,u.stem[I]({d:["M",m,k,"L",m,t,"M",m,g,"L",m,l]}),p&&(n=u.box.strokeWidth()%2/2,g=Math.floor(g)+n,k=Math.floor(k)+n,b+=n,d+=n,u.box[I]({d:["M",b,k,"L",b,g,"L",d,g,"L",d,k,"L",b,k,"z"]})),F&&(n=u.whiskers.strokeWidth()%2/2,t+=n,l+=n,D=/%$/.test(F)?f*parseFloat(F)/100:F/2,u.whiskers[I]({d:["M",
m-D,t,"L",m+D,t,"M",m-D,l,"L",m+D,l]})),r=Math.round(u.medianPlot),n=u.medianShape.strokeWidth()%2/2,r+=n,u.medianShape[I]({d:["M",b,r,"L",d,r]}))})},setStackedPoints:e});""});E(r,"parts-more/ErrorBarSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){a=a.seriesType;var c=h.noop,e=h.seriesTypes;a("errorbar","boxplot",{color:"#000000",grouping:!1,linkedTo:":previous",tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.low}</b> - <b>{point.high}</b><br/>'},
whiskerWidth:null},{type:"errorbar",pointArrayMap:["low","high"],toYData:function(a){return[a.low,a.high]},pointValKey:"high",doQuartiles:!1,drawDataLabels:e.arearange?function(){var a=this.pointValKey;e.arearange.prototype.drawDataLabels.call(this);this.data.forEach(function(e){e.y=e[a]})}:c,getColumnMetrics:function(){return this.linkedParent&&this.linkedParent.columnMetrics||e.column.prototype.getColumnMetrics.call(this)}});""});E(r,"parts-more/WaterfallSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],
function(h,a){var c=a.addEvent,e=a.arrayMax,v=a.arrayMin,q=a.correctFloat,z=a.isNumber,r=a.objectEach,w=a.pick;a=a.seriesType;var g=h.Axis,k=h.Chart,t=h.Point,l=h.Series,B=h.StackItem,n=h.seriesTypes;c(g,"afterInit",function(){this.isXAxis||(this.waterfallStacks={changed:!1})});c(g,"afterBuildStacks",function(){this.waterfallStacks.changed=!1;delete this.waterfallStacks.alreadyChanged});c(k,"beforeRedraw",function(){for(var a=this.axes,g=this.series,b=g.length;b--;)g[b].options.stacking&&(a.forEach(function(b){b.isXAxis||
(b.waterfallStacks.changed=!0)}),b=0)});c(g,"afterRender",function(){var a=this.options.stackLabels;a&&a.enabled&&this.waterfallStacks&&this.renderWaterfallStackTotals()});g.prototype.renderWaterfallStackTotals=function(){var a=this.waterfallStacks,g=this.stackTotalGroup,b=new B(this,this.options.stackLabels,!1,0,void 0);this.dummyStackItem=b;r(a,function(a){r(a,function(f){b.total=f.stackTotal;f.label&&(b.label=f.label);B.prototype.render.call(b,g);f.label=b.label;delete b.label})});b.total=null};
a("waterfall","column",{dataLabels:{inside:!0},lineWidth:1,lineColor:"#333333",dashStyle:"Dot",borderColor:"#333333",states:{hover:{lineWidthPlus:0}}},{pointValKey:"y",showLine:!0,generatePoints:function(){var a;n.column.prototype.generatePoints.apply(this);var g=0;for(a=this.points.length;g<a;g++){var b=this.points[g];var d=this.processedYData[g];if(b.isIntermediateSum||b.isSum)b.y=q(d)}},translate:function(){var a=this.options,g=this.yAxis,b,d=w(a.minPointLength,5),f=d/2,p=a.threshold,e=a.stacking,
c=g.waterfallStacks[this.stackKey];n.column.prototype.translate.apply(this);var u=b=p;var l=this.points;var k=0;for(a=l.length;k<a;k++){var h=l[k];var v=this.processedYData[k];var q=h.shapeArgs;var t=[0,v];var A=h.y;if(e){if(c){t=c[k];if("overlap"===e){var x=t.stackState[t.stateIndex--];x=0<=A?x:x-A;Object.hasOwnProperty.call(t,"absolutePos")&&delete t.absolutePos;Object.hasOwnProperty.call(t,"absoluteNeg")&&delete t.absoluteNeg}else 0<=A?(x=t.threshold+t.posTotal,t.posTotal-=A):(x=t.threshold+t.negTotal,
t.negTotal-=A,x-=A),!t.posTotal&&Object.hasOwnProperty.call(t,"absolutePos")&&(t.posTotal=t.absolutePos,delete t.absolutePos),!t.negTotal&&Object.hasOwnProperty.call(t,"absoluteNeg")&&(t.negTotal=t.absoluteNeg,delete t.absoluteNeg);h.isSum||(t.connectorThreshold=t.threshold+t.stackTotal);g.reversed?(v=0<=A?x-A:x+A,A=x):(v=x,A=x-A);h.below=v<=w(p,0);q.y=g.translate(v,0,1,0,1);q.height=Math.abs(q.y-g.translate(A,0,1,0,1))}if(A=g.dummyStackItem)A.x=k,A.label=c[k].label,A.setOffset(this.pointXOffset||
0,this.barW||0,this.stackedYNeg[k],this.stackedYPos[k])}else x=Math.max(u,u+A)+t[0],q.y=g.translate(x,0,1,0,1),h.isSum?(q.y=g.translate(t[1],0,1,0,1),q.height=Math.min(g.translate(t[0],0,1,0,1),g.len)-q.y):h.isIntermediateSum?(0<=A?(v=t[1]+b,A=b):(v=b,A=t[1]+b),g.reversed&&(v^=A,A^=v,v^=A),q.y=g.translate(v,0,1,0,1),q.height=Math.abs(q.y-Math.min(g.translate(A,0,1,0,1),g.len)),b+=t[1]):(q.height=0<v?g.translate(u,0,1,0,1)-q.y:g.translate(u,0,1,0,1)-g.translate(u-v,0,1,0,1),u+=v,h.below=u<w(p,0)),
0>q.height&&(q.y+=q.height,q.height*=-1);h.plotY=q.y=Math.round(q.y)-this.borderWidth%2/2;q.height=Math.max(Math.round(q.height),.001);h.yBottom=q.y+q.height;q.height<=d&&!h.isNull?(q.height=d,q.y-=f,h.plotY=q.y,h.minPointLengthOffset=0>h.y?-f:f):(h.isNull&&(q.width=0),h.minPointLengthOffset=0);q=h.plotY+(h.negative?q.height:0);this.chart.inverted?h.tooltipPos[0]=g.len-q:h.tooltipPos[1]=q}},processData:function(a){var g=this.options,b=this.yData,d=g.data,f=b.length,p=g.threshold||0,m,e,u,n,k;for(k=
e=m=u=n=0;k<f;k++){var c=b[k];var h=d&&d[k]?d[k]:{};"sum"===c||h.isSum?b[k]=q(e):"intermediateSum"===c||h.isIntermediateSum?(b[k]=q(m),m=0):(e+=c,m+=c);u=Math.min(e,u);n=Math.max(e,n)}l.prototype.processData.call(this,a);g.stacking||(this.dataMin=u+p,this.dataMax=n)},toYData:function(a){return a.isSum?"sum":a.isIntermediateSum?"intermediateSum":a.y},updateParallelArrays:function(a,g){l.prototype.updateParallelArrays.call(this,a,g);if("sum"===this.yData[0]||"intermediateSum"===this.yData[0])this.yData[0]=
null},pointAttribs:function(a,g){var b=this.options.upColor;b&&!a.options.color&&(a.color=0<a.y?b:null);a=n.column.prototype.pointAttribs.call(this,a,g);delete a.dashstyle;return a},getGraphPath:function(){return["M",0,0]},getCrispPath:function(){var a=this.data,g=this.yAxis,b=a.length,d=Math.round(this.graph.strokeWidth())%2/2,f=Math.round(this.borderWidth)%2/2,p=this.xAxis.reversed,e=this.yAxis.reversed,n=this.options.stacking,u=[],k;for(k=1;k<b;k++){var c=a[k].shapeArgs;var l=a[k-1];var h=a[k-
1].shapeArgs;var v=g.waterfallStacks[this.stackKey];var q=0<l.y?-h.height:0;if(v){v=v[k-1];n?(v=v.connectorThreshold,q=Math.round(g.translate(v,0,1,0,1)+(e?q:0))-d):q=h.y+l.minPointLengthOffset+f-d;var t=["M",h.x+(p?0:h.width),q,"L",c.x+(p?c.width:0),q]}if(!n&&t&&0>l.y&&!e||0<l.y&&e)t[2]+=h.height,t[5]+=h.height;u=u.concat(t)}return u},drawGraph:function(){l.prototype.drawGraph.call(this);this.graph.attr({d:this.getCrispPath()})},setStackedPoints:function(){function a(f,a,b,d){if(y)for(b;b<y;b++)x.stackState[b]+=
d;else x.stackState[0]=f,y=x.stackState.length;x.stackState.push(x.stackState[y-1]+a)}var g=this.options,b=this.yAxis.waterfallStacks,d=g.threshold,f=d||0,p=f,e=this.stackKey,k=this.xData,u=k.length,n,c,l;this.yAxis.usePercentage=!1;var h=c=l=f;if(this.visible||!this.chart.options.chart.ignoreHiddenSeries){var v=b.changed;(n=b.alreadyChanged)&&0>n.indexOf(e)&&(v=!0);b[e]||(b[e]={});n=b[e];for(var q=0;q<u;q++){var t=k[q];if(!n[t]||v)n[t]={negTotal:0,posTotal:0,stackTotal:0,threshold:0,stateIndex:0,
stackState:[],label:v&&n[t]?n[t].label:void 0};var x=n[t];var z=this.yData[q];0<=z?x.posTotal+=z:x.negTotal+=z;var r=g.data[q];t=x.absolutePos=x.posTotal;var w=x.absoluteNeg=x.negTotal;x.stackTotal=t+w;var y=x.stackState.length;r&&r.isIntermediateSum?(a(l,c,0,l),l=c,c=d,f^=p,p^=f,f^=p):r&&r.isSum?(a(d,h,y),f=d):(a(f,z,0,h),r&&(h+=z,c+=z));x.stateIndex++;x.threshold=f;f+=x.stackTotal}b.changed=!1;b.alreadyChanged||(b.alreadyChanged=[]);b.alreadyChanged.push(e)}},getExtremes:function(){var a=this.options.stacking;
if(a){var g=this.yAxis;g=g.waterfallStacks;var b=this.stackedYNeg=[];var d=this.stackedYPos=[];"overlap"===a?r(g[this.stackKey],function(f){b.push(v(f.stackState));d.push(e(f.stackState))}):r(g[this.stackKey],function(f){b.push(f.negTotal+f.threshold);d.push(f.posTotal+f.threshold)});this.dataMin=v(b);this.dataMax=e(d)}}},{getClassName:function(){var a=t.prototype.getClassName.call(this);this.isSum?a+=" highcharts-sum":this.isIntermediateSum&&(a+=" highcharts-intermediate-sum");return a},isValid:function(){return z(this.y)||
this.isSum||this.isIntermediateSum}});""});E(r,"parts-more/PolygonSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){a=a.seriesType;var c=h.Series,e=h.seriesTypes;a("polygon","scatter",{marker:{enabled:!1,states:{hover:{enabled:!1}}},stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:""},trackByArea:!0},{type:"polygon",getGraphPath:function(){for(var a=c.prototype.getGraphPath.call(this),e=a.length+1;e--;)(e===a.length||"M"===a[e])&&0<e&&a.splice(e,0,"z");return this.areaPath=
a},drawGraph:function(){this.options.fillColor=this.color;e.area.prototype.drawGraph.call(this)},drawLegendSymbol:h.LegendSymbolMixin.drawRectangle,drawTracker:c.prototype.drawTracker,setStackedPoints:h.noop});""});E(r,"parts-more/BubbleLegend.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.addEvent,e=a.arrayMax,v=a.arrayMin,q=a.isNumber,z=a.merge,r=a.objectEach,w=a.pick,g=a.stableSort,k=a.wrap,t=h.Series,l=h.Legend,B=h.Chart,n=h.color,m=h.noop,C=h.setOptions;C({legend:{bubbleLegend:{borderColor:void 0,
borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});h.BubbleLegend=function(a,d){this.init(a,d)};h.BubbleLegend.prototype=
{init:function(a,d){this.options=a;this.visible=!0;this.chart=d.chart;this.legend=d},setState:m,addToLegend:function(a){a.splice(this.options.legendIndex,0,this)},drawLegendSymbol:function(a){var b=this.chart,f=this.options,p=w(a.options.itemDistance,20),e=f.ranges;var m=f.connectorDistance;this.fontMetrics=b.renderer.fontMetrics(f.labels.style.fontSize.toString()+"px");e&&e.length&&q(e[0].value)?(g(e,function(f,a){return a.value-f.value}),this.ranges=e,this.setOptions(),this.render(),b=this.getMaxLabelSize(),
e=this.ranges[0].radius,a=2*e,m=m-e+b.width,m=0<m?m:0,this.maxLabel=b,this.movementX="left"===f.labels.align?m:0,this.legendItemWidth=a+m+p,this.legendItemHeight=a+this.fontMetrics.h/2):a.options.bubbleLegend.autoRanges=!0},setOptions:function(){var a=this.ranges,d=this.options,f=this.chart.series[d.seriesIndex],p=this.legend.baseline,g={"z-index":d.zIndex,"stroke-width":d.borderWidth},e={"z-index":d.zIndex,"stroke-width":d.connectorWidth},u=this.getLabelStyles(),m=f.options.marker.fillOpacity,k=
this.chart.styledMode;a.forEach(function(b,c){k||(g.stroke=w(b.borderColor,d.borderColor,f.color),g.fill=w(b.color,d.color,1!==m?n(f.color).setOpacity(m).get("rgba"):f.color),e.stroke=w(b.connectorColor,d.connectorColor,f.color));a[c].radius=this.getRangeRadius(b.value);a[c]=z(a[c],{center:a[0].radius-a[c].radius+p});k||z(!0,a[c],{bubbleStyle:z(!1,g),connectorStyle:z(!1,e),labelStyle:u})},this)},getLabelStyles:function(){var a=this.options,d={},f="left"===a.labels.align,p=this.legend.options.rtl;
r(a.labels.style,function(f,a){"color"!==a&&"fontSize"!==a&&"z-index"!==a&&(d[a]=f)});return z(!1,d,{"font-size":a.labels.style.fontSize,fill:w(a.labels.style.color,"#000000"),"z-index":a.zIndex,align:p||f?"right":"left"})},getRangeRadius:function(a){var b=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,b.ranges[b.ranges.length-1].value,b.ranges[0].value,b.minSize,b.maxSize,a)},render:function(){var a=this.chart.renderer,d=this.options.zThreshold;this.symbols||
(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=a.g("bubble-legend");this.legendItem=a.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(f){f.value>=d&&this.renderRange(f)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()},renderRange:function(a){var b=this.options,f=b.labels,p=this.chart.renderer,g=this.symbols,e=g.labels,u=a.center,m=Math.abs(a.radius),
k=b.connectorDistance,n=f.align,c=f.style.fontSize;k=this.legend.options.rtl||"left"===n?-k:k;f=b.connectorWidth;var l=this.ranges[0].radius,h=u-m-b.borderWidth/2+f/2;c=c/2-(this.fontMetrics.h-c)/2;var v=p.styledMode;"center"===n&&(k=0,b.connectorDistance=0,a.labelStyle.align="center");n=h+b.labels.y;var t=l+k+b.labels.x;g.bubbleItems.push(p.circle(l,u+((h%1?1:.5)-(f%2?0:.5)),m).attr(v?{}:a.bubbleStyle).addClass((v?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+
(b.className||"")).add(this.legendSymbol));g.connectors.push(p.path(p.crispLine(["M",l,h,"L",l+k,h],b.connectorWidth)).attr(v?{}:a.connectorStyle).addClass((v?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(b.connectorClassName||"")).add(this.legendSymbol));a=p.text(this.formatLabel(a),t,n+c).attr(v?{}:a.labelStyle).addClass("highcharts-bubble-legend-labels "+(b.labels.className||"")).add(this.legendSymbol);e.push(a);a.placed=!0;a.alignAttr={x:t,y:n+c}},
getMaxLabelSize:function(){var a,d;this.symbols.labels.forEach(function(f){d=f.getBBox(!0);a=a?d.width>a.width?d:a:d});return a||{}},formatLabel:function(b){var d=this.options,f=d.labels.formatter;d=d.labels.format;var p=this.chart.numberFormatter;return d?a.format(d,b):f?f.call(b):p(b.value,1)},hideOverlappingLabels:function(){var a=this.chart,d=this.symbols;!this.options.labels.allowOverlap&&d&&(a.hideOverlappingLabels(d.labels),d.labels.forEach(function(a,b){a.newOpacity?a.newOpacity!==a.oldOpacity&&
d.connectors[b].show():d.connectors[b].hide()}))},getRanges:function(){var a=this.legend.bubbleLegend,d=a.options.ranges,f,p=Number.MAX_VALUE,g=-Number.MAX_VALUE;a.chart.series.forEach(function(a){a.isBubble&&!a.ignoreSeries&&(f=a.zData.filter(q),f.length&&(p=w(a.options.zMin,Math.min(p,Math.max(v(f),!1===a.options.displayNegative?a.options.zThreshold:-Number.MAX_VALUE))),g=w(a.options.zMax,Math.max(g,e(f)))))});var m=p===g?[{value:g}]:[{value:p},{value:(p+g)/2},{value:g,autoRanges:!0}];d.length&&
d[0].radius&&m.reverse();m.forEach(function(a,f){d&&d[f]&&(m[f]=z(!1,d[f],a))});return m},predictBubbleSizes:function(){var a=this.chart,d=this.fontMetrics,f=a.legend.options,p="horizontal"===f.layout,g=p?a.legend.lastLineHeight:0,m=a.plotSizeX,e=a.plotSizeY,k=a.series[this.options.seriesIndex];a=Math.ceil(k.minPxSize);var n=Math.ceil(k.maxPxSize);k=k.options.maxSize;var c=Math.min(e,m);if(f.floating||!/%$/.test(k))d=n;else if(k=parseFloat(k),d=(c+g-d.h/2)*k/100/(k/100+1),p&&e-d>=m||!p&&m-d>=e)d=
n;return[a,Math.ceil(d)]},updateRanges:function(a,d){var f=this.legend.options.bubbleLegend;f.minSize=a;f.maxSize=d;f.ranges=this.getRanges()},correctSizes:function(){var a=this.legend,d=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(d.maxPxSize)-this.options.maxSize)&&(this.updateRanges(this.options.minSize,d.maxPxSize),a.render())}};c(h.Legend,"afterGetAllItems",function(a){var b=this.bubbleLegend,f=this.options,p=f.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&
b.ranges.length&&(p.ranges.length&&(p.autoRanges=!!p.ranges[0].autoRanges),this.destroyItem(b));0<=g&&f.enabled&&p.enabled&&(p.seriesIndex=g,this.bubbleLegend=new h.BubbleLegend(p,this),this.bubbleLegend.addToLegend(a.allItems))});B.prototype.getVisibleBubbleSeriesIndex=function(){for(var a=this.series,d=0;d<a.length;){if(a[d]&&a[d].isBubble&&a[d].visible&&a[d].zData.length)return d;d++}return-1};l.prototype.getLinesHeights=function(){var a=this.allItems,d=[],f=a.length,p,g=0;for(p=0;p<f;p++)if(a[p].legendItemHeight&&
(a[p].itemHeight=a[p].legendItemHeight),a[p]===a[f-1]||a[p+1]&&a[p]._legendItemPos[1]!==a[p+1]._legendItemPos[1]){d.push({height:0});var m=d[d.length-1];for(g;g<=p;g++)a[g].itemHeight>m.height&&(m.height=a[g].itemHeight);m.step=p}return d};l.prototype.retranslateItems=function(a){var b,f,g,m=this.options.rtl,e=0;this.allItems.forEach(function(d,p){b=d.legendGroup.translateX;f=d._legendItemPos[1];if((g=d.movementX)||m&&d.ranges)g=m?b-d.options.maxSize/2:b+g,d.legendGroup.attr({translateX:g});p>a[e].step&&
e++;d.legendGroup.attr({translateY:Math.round(f+a[e].height/2)});d._legendItemPos[1]=f+a[e].height/2})};c(t,"legendItemClick",function(){var a=this.chart,d=this.visible,f=this.chart.legend;f&&f.bubbleLegend&&(this.visible=!d,this.ignoreSeries=d,a=0<=a.getVisibleBubbleSeriesIndex(),f.bubbleLegend.visible!==a&&(f.update({bubbleLegend:{enabled:a}}),f.bubbleLegend.visible=a),this.visible=d)});k(B.prototype,"drawChartBox",function(a,d,f){var b=this.legend,g=0<=this.getVisibleBubbleSeriesIndex();if(b&&
b.options.enabled&&b.bubbleLegend&&b.options.bubbleLegend.autoRanges&&g){var m=b.bubbleLegend.options;g=b.bubbleLegend.predictBubbleSizes();b.bubbleLegend.updateRanges(g[0],g[1]);m.placed||(b.group.placed=!1,b.allItems.forEach(function(a){a.legendGroup.translateY=null}));b.render();this.getMargins();this.axes.forEach(function(a){a.visible&&a.render();m.placed||(a.setScale(),a.updateNames(),r(a.ticks,function(a){a.isNew=!0;a.isNewLabel=!0}))});m.placed=!0;this.getMargins();a.call(this,d,f);b.bubbleLegend.correctSizes();
b.retranslateItems(b.getLinesHeights())}else a.call(this,d,f),b&&b.options.enabled&&b.bubbleLegend&&(b.render(),b.retranslateItems(b.getLinesHeights()))})});E(r,"parts-more/BubbleSeries.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.arrayMax,e=a.arrayMin,v=a.clamp,q=a.extend,r=a.isNumber,y=a.pick,w=a.pInt;a=a.seriesType;var g=h.Axis,k=h.color,t=h.noop,l=h.Point,B=h.Series,n=h.seriesTypes;a("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,
verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,
pointAttribs:function(a,g){var b=this.options.marker.fillOpacity;a=B.prototype.pointAttribs.call(this,a,g);1!==b&&(a.fill=k(a.fill).setOpacity(b).get("rgba"));return a},getRadii:function(a,g,b){var d=this.zData,f=this.yData,p=b.minPxSize,e=b.maxPxSize,m=[];var k=0;for(b=d.length;k<b;k++){var n=d[k];m.push(this.getRadius(a,g,p,e,n,f[k]))}this.radii=m},getRadius:function(a,g,b,d,f,p){var e=this.options,m="width"!==e.sizeBy,k=e.zThreshold,n=g-a,c=.5;if(null===p||null===f)return null;if(r(f)){e.sizeByAbsoluteValue&&
(f=Math.abs(f-k),n=Math.max(g-k,Math.abs(a-k)),a=0);if(f<a)return b/2-1;0<n&&(c=(f-a)/n)}m&&0<=c&&(c=Math.sqrt(c));return Math.ceil(b+c*(d-b))/2},animate:function(a){!a&&this.points.length<this.options.animationLimit&&(this.points.forEach(function(a){var b=a.graphic;if(b&&b.width){var g={x:b.x,y:b.y,width:b.width,height:b.height};b.attr({x:a.plotX,y:a.plotY,width:1,height:1});b.animate(g,this.options.animation)}},this),this.animate=null)},hasData:function(){return!!this.processedXData.length},translate:function(){var a,
g=this.data,b=this.radii;n.scatter.prototype.translate.call(this);for(a=g.length;a--;){var d=g[a];var f=b?b[a]:0;r(f)&&f>=this.minPxSize/2?(d.marker=q(d.marker,{radius:f,width:2*f,height:2*f}),d.dlBox={x:d.plotX-f,y:d.plotY-f,width:2*f,height:2*f}):d.shapeArgs=d.plotY=d.dlBox=void 0}},alignDataLabel:n.column.prototype.alignDataLabel,buildKDTree:t,applyZones:t},{haloPath:function(a){return l.prototype.haloPath.call(this,0===a?0:(this.marker?this.marker.radius||0:0)+a)},ttBelow:!1});g.prototype.beforePadding=
function(){var a=this,g=this.len,b=this.chart,d=0,f=g,p=this.isXAxis,k=p?"xData":"yData",n=this.min,u={},l=Math.min(b.plotWidth,b.plotHeight),h=Number.MAX_VALUE,t=-Number.MAX_VALUE,q=this.max-n,z=g/q,B=[];this.series.forEach(function(f){var g=f.options;!f.bubblePadding||!f.visible&&b.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,B.push(f),p&&(["minSize","maxSize"].forEach(function(a){var f=g[a],b=/%$/.test(f);f=w(f);u[a]=b?l*f/100:f}),f.minPxSize=u.minSize,f.maxPxSize=Math.max(u.maxSize,
u.minSize),f=f.zData.filter(r),f.length&&(h=y(g.zMin,v(e(f),!1===g.displayNegative?g.zThreshold:-Number.MAX_VALUE,h)),t=y(g.zMax,Math.max(t,c(f))))))});B.forEach(function(b){var g=b[k],e=g.length;p&&b.getRadii(h,t,b);if(0<q)for(;e--;)if(r(g[e])&&a.dataMin<=g[e]&&g[e]<=a.max){var m=b.radii?b.radii[e]:0;d=Math.min((g[e]-n)*z-m,d);f=Math.max((g[e]-n)*z+m,f)}});B.length&&0<q&&!this.isLog&&(f-=g,z*=(g+Math.max(0,d)-Math.min(f,g))/g,[["min","userMin",d],["max","userMax",f]].forEach(function(f){"undefined"===
typeof y(a.options[f[0]],a[f[1]])&&(a[f[0]]+=f[2]/z)}))};""});E(r,"modules/networkgraph/integrations.js",[r["parts/Globals.js"]],function(h){h.networkgraphIntegrations={verlet:{attractiveForceFunction:function(a,c){return(c-a)/a},repulsiveForceFunction:function(a,c){return(c-a)/a*(c>a?1:0)},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,e=this.barycenter.yFactor;c=(c-(this.box.left+this.box.width)/2)*a;e=(e-(this.box.top+this.box.height)/2)*a;this.nodes.forEach(function(a){a.fixedPosition||
(a.plotX-=c/a.mass/a.degree,a.plotY-=e/a.mass/a.degree)})},repulsive:function(a,c,e){c=c*this.diffTemperature/a.mass/a.degree;a.fixedPosition||(a.plotX+=e.x*c,a.plotY+=e.y*c)},attractive:function(a,c,e){var h=a.getMass(),q=-e.x*c*this.diffTemperature;c=-e.y*c*this.diffTemperature;a.fromNode.fixedPosition||(a.fromNode.plotX-=q*h.fromNode/a.fromNode.degree,a.fromNode.plotY-=c*h.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.plotX+=q*h.toNode/a.toNode.degree,a.toNode.plotY+=c*h.toNode/
a.toNode.degree)},integrate:function(a,c){var e=-a.options.friction,h=a.options.maxSpeed,q=(c.plotX+c.dispX-c.prevX)*e;e*=c.plotY+c.dispY-c.prevY;var r=Math.abs,y=r(q)/(q||1);r=r(e)/(e||1);q=y*Math.min(h,Math.abs(q));e=r*Math.min(h,Math.abs(e));c.prevX=c.plotX+c.dispX;c.prevY=c.plotY+c.dispY;c.plotX+=q;c.plotY+=e;c.temperature=a.vectorLength({x:q,y:e})},getK:function(a){return Math.pow(a.box.width*a.box.height/a.nodes.length,.5)}},euler:{attractiveForceFunction:function(a,c){return a*a/c},repulsiveForceFunction:function(a,
c){return c*c/a},barycenter:function(){var a=this.options.gravitationalConstant,c=this.barycenter.xFactor,e=this.barycenter.yFactor;this.nodes.forEach(function(h){if(!h.fixedPosition){var q=h.getDegree();q*=1+q/2;h.dispX+=(c-h.plotX)*a*q/h.degree;h.dispY+=(e-h.plotY)*a*q/h.degree}})},repulsive:function(a,c,e,h){a.dispX+=e.x/h*c/a.degree;a.dispY+=e.y/h*c/a.degree},attractive:function(a,c,e,h){var q=a.getMass(),v=e.x/h*c;c*=e.y/h;a.fromNode.fixedPosition||(a.fromNode.dispX-=v*q.fromNode/a.fromNode.degree,
a.fromNode.dispY-=c*q.fromNode/a.fromNode.degree);a.toNode.fixedPosition||(a.toNode.dispX+=v*q.toNode/a.toNode.degree,a.toNode.dispY+=c*q.toNode/a.toNode.degree)},integrate:function(a,c){c.dispX+=c.dispX*a.options.friction;c.dispY+=c.dispY*a.options.friction;var e=c.temperature=a.vectorLength({x:c.dispX,y:c.dispY});0!==e&&(c.plotX+=c.dispX/e*Math.min(Math.abs(c.dispX),a.temperature),c.plotY+=c.dispY/e*Math.min(Math.abs(c.dispY),a.temperature))},getK:function(a){return Math.pow(a.box.width*a.box.height/
a.nodes.length,.3)}}}});E(r,"modules/networkgraph/QuadTree.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){a=a.extend;var c=h.QuadTreeNode=function(a){this.box=a;this.boxSize=Math.min(a.width,a.height);this.nodes=[];this.body=this.isInternal=!1;this.isEmpty=!0};a(c.prototype,{insert:function(a,h){this.isInternal?this.nodes[this.getBoxPosition(a)].insert(a,h-1):(this.isEmpty=!1,this.body?h?(this.isInternal=!0,this.divideBox(),!0!==this.body&&(this.nodes[this.getBoxPosition(this.body)].insert(this.body,
h-1),this.body=!0),this.nodes[this.getBoxPosition(a)].insert(a,h-1)):(h=new c({top:a.plotX,left:a.plotY,width:.1,height:.1}),h.body=a,h.isInternal=!1,this.nodes.push(h)):(this.isInternal=!1,this.body=a))},updateMassAndCenter:function(){var a=0,c=0,h=0;this.isInternal?(this.nodes.forEach(function(e){e.isEmpty||(a+=e.mass,c+=e.plotX*e.mass,h+=e.plotY*e.mass)}),c/=a,h/=a):this.body&&(a=this.body.mass,c=this.body.plotX,h=this.body.plotY);this.mass=a;this.plotX=c;this.plotY=h},divideBox:function(){var a=
this.box.width/2,h=this.box.height/2;this.nodes[0]=new c({left:this.box.left,top:this.box.top,width:a,height:h});this.nodes[1]=new c({left:this.box.left+a,top:this.box.top,width:a,height:h});this.nodes[2]=new c({left:this.box.left+a,top:this.box.top+h,width:a,height:h});this.nodes[3]=new c({left:this.box.left,top:this.box.top+h,width:a,height:h})},getBoxPosition:function(a){var e=a.plotY<this.box.top+this.box.height/2;return a.plotX<this.box.left+this.box.width/2?e?0:3:e?1:2}});h=h.QuadTree=function(a,
h,q,r){this.box={left:a,top:h,width:q,height:r};this.maxDepth=25;this.root=new c(this.box,"0");this.root.isInternal=!0;this.root.isRoot=!0;this.root.divideBox()};a(h.prototype,{insertNodes:function(a){a.forEach(function(a){this.root.insert(a,this.maxDepth)},this)},visitNodeRecursive:function(a,c,h){var e;a||(a=this.root);a===this.root&&c&&(e=c(a));!1!==e&&(a.nodes.forEach(function(a){if(a.isInternal){c&&(e=c(a));if(!1===e)return;this.visitNodeRecursive(a,c,h)}else a.body&&c&&c(a.body);h&&h(a)},this),
a===this.root&&h&&h(a))},calculateMassAndCenter:function(){this.visitNodeRecursive(null,null,function(a){a.updateMassAndCenter()})}})});E(r,"modules/networkgraph/layouts.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,a){var c=a.addEvent,e=a.clamp,v=a.defined,q=a.extend,r=a.isFunction,y=a.pick,w=a.setAnimation;a=h.Chart;h.layouts={"reingold-fruchterman":function(){}};q(h.layouts["reingold-fruchterman"].prototype,{init:function(a){this.options=a;this.nodes=[];this.links=[];this.series=
[];this.box={x:0,y:0,width:0,height:0};this.setInitialRendering(!0);this.integration=h.networkgraphIntegrations[a.integration];this.attractiveForce=y(a.attractiveForce,this.integration.attractiveForceFunction);this.repulsiveForce=y(a.repulsiveForce,this.integration.repulsiveForceFunction);this.approximation=a.approximation},start:function(){var a=this.series,e=this.options;this.currentStep=0;this.forces=a[0]&&a[0].forces||[];this.initialRendering&&(this.initPositions(),a.forEach(function(a){a.render()}));
this.setK();this.resetSimulation(e);e.enableSimulation&&this.step()},step:function(){var a=this,e=this.series,c=this.options;a.currentStep++;"barnes-hut"===a.approximation&&(a.createQuadTree(),a.quadTree.calculateMassAndCenter());a.forces.forEach(function(g){a[g+"Forces"](a.temperature)});a.applyLimits(a.temperature);a.temperature=a.coolDown(a.startTemperature,a.diffTemperature,a.currentStep);a.prevSystemTemperature=a.systemTemperature;a.systemTemperature=a.getSystemTemperature();c.enableSimulation&&
(e.forEach(function(a){a.chart&&a.render()}),a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()?(a.simulation&&h.win.cancelAnimationFrame(a.simulation),a.simulation=h.win.requestAnimationFrame(function(){a.step()})):a.simulation=!1)},stop:function(){this.simulation&&h.win.cancelAnimationFrame(this.simulation)},setArea:function(a,e,c,h){this.box={left:a,top:e,width:c,height:h}},setK:function(){this.k=this.options.linkLength||this.integration.getK(this)},addElementsToCollection:function(a,e){a.forEach(function(a){-1===
e.indexOf(a)&&e.push(a)})},removeElementFromCollection:function(a,e){a=e.indexOf(a);-1!==a&&e.splice(a,1)},clear:function(){this.nodes.length=0;this.links.length=0;this.series.length=0;this.resetSimulation()},resetSimulation:function(){this.forcedStop=!1;this.systemTemperature=0;this.setMaxIterations();this.setTemperature();this.setDiffTemperature()},setMaxIterations:function(a){this.maxIterations=y(a,this.options.maxIterations)},setTemperature:function(){this.temperature=this.startTemperature=Math.sqrt(this.nodes.length)},
setDiffTemperature:function(){this.diffTemperature=this.startTemperature/(this.options.maxIterations+1)},setInitialRendering:function(a){this.initialRendering=a},createQuadTree:function(){this.quadTree=new h.QuadTree(this.box.left,this.box.top,this.box.width,this.box.height);this.quadTree.insertNodes(this.nodes)},initPositions:function(){var a=this.options.initialPositions;r(a)?(a.call(this),this.nodes.forEach(function(a){v(a.prevX)||(a.prevX=a.plotX);v(a.prevY)||(a.prevY=a.plotY);a.dispX=0;a.dispY=
0})):"circle"===a?this.setCircularPositions():this.setRandomPositions()},setCircularPositions:function(){function a(b){b.linksFrom.forEach(function(b){m[b.toNode.id]||(m[b.toNode.id]=!0,n.push(b.toNode),a(b.toNode))})}var e=this.box,c=this.nodes,h=2*Math.PI/(c.length+1),q=c.filter(function(a){return 0===a.linksTo.length}),n=[],m={},r=this.options.initialPositionRadius;q.forEach(function(b){n.push(b);a(b)});n.length?c.forEach(function(a){-1===n.indexOf(a)&&n.push(a)}):n=c;n.forEach(function(a,d){a.plotX=
a.prevX=y(a.plotX,e.width/2+r*Math.cos(d*h));a.plotY=a.prevY=y(a.plotY,e.height/2+r*Math.sin(d*h));a.dispX=0;a.dispY=0})},setRandomPositions:function(){function a(a){a=a*a/Math.PI;return a-=Math.floor(a)}var e=this.box,c=this.nodes,h=c.length+1;c.forEach(function(g,c){g.plotX=g.prevX=y(g.plotX,e.width*a(c));g.plotY=g.prevY=y(g.plotY,e.height*a(h+c));g.dispX=0;g.dispY=0})},force:function(a){this.integration[a].apply(this,Array.prototype.slice.call(arguments,1))},barycenterForces:function(){this.getBarycenter();
this.force("barycenter")},getBarycenter:function(){var a=0,e=0,c=0;this.nodes.forEach(function(g){e+=g.plotX*g.mass;c+=g.plotY*g.mass;a+=g.mass});return this.barycenter={x:e,y:c,xFactor:e/a,yFactor:c/a}},barnesHutApproximation:function(a,e){var g=this.getDistXY(a,e),c=this.vectorLength(g);if(a!==e&&0!==c)if(e.isInternal)if(e.boxSize/c<this.options.theta&&0!==c){var h=this.repulsiveForce(c,this.k);this.force("repulsive",a,h*e.mass,g,c);var n=!1}else n=!0;else h=this.repulsiveForce(c,this.k),this.force("repulsive",
a,h*e.mass,g,c);return n},repulsiveForces:function(){var a=this;"barnes-hut"===a.approximation?a.nodes.forEach(function(g){a.quadTree.visitNodeRecursive(null,function(e){return a.barnesHutApproximation(g,e)})}):a.nodes.forEach(function(g){a.nodes.forEach(function(e){if(g!==e&&!g.fixedPosition){var c=a.getDistXY(g,e);var h=a.vectorLength(c);if(0!==h){var n=a.repulsiveForce(h,a.k);a.force("repulsive",g,n*e.mass,c,h)}}})})},attractiveForces:function(){var a=this,e,c,h;a.links.forEach(function(g){g.fromNode&&
g.toNode&&(e=a.getDistXY(g.fromNode,g.toNode),c=a.vectorLength(e),0!==c&&(h=a.attractiveForce(c,a.k),a.force("attractive",g,h,e,c)))})},applyLimits:function(){var a=this;a.nodes.forEach(function(e){e.fixedPosition||(a.integration.integrate(a,e),a.applyLimitBox(e,a.box),e.dispX=0,e.dispY=0)})},applyLimitBox:function(a,c){var g=a.radius;a.plotX=e(a.plotX,c.left+g,c.width-g);a.plotY=e(a.plotY,c.top+g,c.height-g)},coolDown:function(a,e,c){return a-e*c},isStable:function(){return.00001>Math.abs(this.systemTemperature-
this.prevSystemTemperature)||0>=this.temperature},getSystemTemperature:function(){return this.nodes.reduce(function(a,e){return a+e.temperature},0)},vectorLength:function(a){return Math.sqrt(a.x*a.x+a.y*a.y)},getDistR:function(a,e){a=this.getDistXY(a,e);return this.vectorLength(a)},getDistXY:function(a,e){var c=a.plotX-e.plotX;a=a.plotY-e.plotY;return{x:c,y:a,absX:Math.abs(c),absY:Math.abs(a)}}});c(a,"predraw",function(){this.graphLayoutsLookup&&this.graphLayoutsLookup.forEach(function(a){a.stop()})});
c(a,"render",function(){function a(a){a.maxIterations--&&isFinite(a.temperature)&&!a.isStable()&&!a.options.enableSimulation&&(a.beforeStep&&a.beforeStep(),a.step(),c=!1,e=!0)}var e=!1;if(this.graphLayoutsLookup){w(!1,this);for(this.graphLayoutsLookup.forEach(function(a){a.start()});!c;){var c=!0;this.graphLayoutsLookup.forEach(a)}e&&this.series.forEach(function(a){a&&a.layout&&a.render()})}})});E(r,"modules/networkgraph/draggable-nodes.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,
a){var c=a.addEvent;a=h.Chart;h.dragNodesMixin={onMouseDown:function(a,c){c=this.chart.pointer.normalize(c);a.fixedPosition={chartX:c.chartX,chartY:c.chartY,plotX:a.plotX,plotY:a.plotY};a.inDragMode=!0},onMouseMove:function(a,c){if(a.fixedPosition&&a.inDragMode){var e=this.chart,h=e.pointer.normalize(c);c=a.fixedPosition.chartX-h.chartX;h=a.fixedPosition.chartY-h.chartY;if(5<Math.abs(c)||5<Math.abs(h))c=a.fixedPosition.plotX-c,h=a.fixedPosition.plotY-h,e.isInsidePlot(c,h)&&(a.plotX=c,a.plotY=h,a.hasDragged=
!0,this.redrawHalo(a),this.layout.simulation?this.layout.resetSimulation():(this.layout.setInitialRendering(!1),this.layout.enableSimulation?this.layout.start():this.layout.setMaxIterations(1),this.chart.redraw(),this.layout.setInitialRendering(!0)))}},onMouseUp:function(a,c){a.fixedPosition&&a.hasDragged&&(this.layout.enableSimulation?this.layout.start():this.chart.redraw(),a.inDragMode=a.hasDragged=!1,this.options.fixedDraggable||delete a.fixedPosition)},redrawHalo:function(a){a&&this.halo&&this.halo.attr({d:a.haloPath(this.options.states.hover.halo.size)})}};
c(a,"load",function(){var a=this,h,q,r;a.container&&(h=c(a.container,"mousedown",function(e){var h=a.hoverPoint;h&&h.series&&h.series.hasDraggableNodes&&h.series.options.draggable&&(h.series.onMouseDown(h,e),q=c(a.container,"mousemove",function(a){return h&&h.series&&h.series.onMouseMove(h,a)}),r=c(a.container.ownerDocument,"mouseup",function(a){q();r();return h&&h.series&&h.series.onMouseUp(h,a)}))}));c(a,"destroy",function(){h()})})});E(r,"parts-more/PackedBubbleSeries.js",[r["parts/Globals.js"],
r["parts/Color.js"],r["parts/Utilities.js"]],function(h,a,c){var e=a.parse,r=c.addEvent,q=c.clamp,z=c.defined,y=c.extend;a=c.extendClass;var w=c.fireEvent,g=c.isArray,k=c.isNumber,t=c.merge,l=c.pick;c=c.seriesType;var B=h.Series,n=h.Point,m=h.Chart,C=h.layouts["reingold-fruchterman"],b=h.seriesTypes.bubble.prototype.pointClass,d=h.dragNodesMixin;h.networkgraphIntegrations.packedbubble={repulsiveForceFunction:function(a,b,d,c){return Math.min(a,(d.marker.radius+c.marker.radius)/2)},barycenter:function(){var a=
this,b=a.options.gravitationalConstant,d=a.box,c=a.nodes,e,h;c.forEach(function(f){a.options.splitSeries&&!f.isParentNode?(e=f.series.parentNode.plotX,h=f.series.parentNode.plotY):(e=d.width/2,h=d.height/2);f.fixedPosition||(f.plotX-=(f.plotX-e)*b/(f.mass*Math.sqrt(c.length)),f.plotY-=(f.plotY-h)*b/(f.mass*Math.sqrt(c.length)))})},repulsive:function(a,b,d,c){var f=b*this.diffTemperature/a.mass/a.degree;b=d.x*f;d=d.y*f;a.fixedPosition||(a.plotX+=b,a.plotY+=d);c.fixedPosition||(c.plotX-=b,c.plotY-=
d)},integrate:h.networkgraphIntegrations.verlet.integrate,getK:h.noop};h.layouts.packedbubble=a(C,{beforeStep:function(){this.options.marker&&this.series.forEach(function(a){a&&a.calculateParentRadius()})},setCircularPositions:function(){var a=this,b=a.box,d=a.nodes,c=2*Math.PI/(d.length+1),e,h,g=a.options.initialPositionRadius;d.forEach(function(f,d){a.options.splitSeries&&!f.isParentNode?(e=f.series.parentNode.plotX,h=f.series.parentNode.plotY):(e=b.width/2,h=b.height/2);f.plotX=f.prevX=l(f.plotX,
e+g*Math.cos(f.index||d*c));f.plotY=f.prevY=l(f.plotY,h+g*Math.sin(f.index||d*c));f.dispX=0;f.dispY=0})},repulsiveForces:function(){var a=this,b,d,c,e=a.options.bubblePadding;a.nodes.forEach(function(f){f.degree=f.mass;f.neighbours=0;a.nodes.forEach(function(h){b=0;f===h||f.fixedPosition||!a.options.seriesInteraction&&f.series!==h.series||(c=a.getDistXY(f,h),d=a.vectorLength(c)-(f.marker.radius+h.marker.radius+e),0>d&&(f.degree+=.01,f.neighbours++,b=a.repulsiveForce(-d/Math.sqrt(f.neighbours),a.k,
f,h)),a.force("repulsive",f,b*h.mass,c,h,d))})})},applyLimitBox:function(a){if(this.options.splitSeries&&!a.isParentNode&&this.options.parentNodeLimit){var f=this.getDistXY(a,a.series.parentNode);var b=a.series.parentNodeRadius-a.marker.radius-this.vectorLength(f);0>b&&b>-2*a.marker.radius&&(a.plotX-=.01*f.x,a.plotY-=.01*f.y)}C.prototype.applyLimitBox.apply(this,arguments)},isStable:function(){return.00001>Math.abs(this.systemTemperature-this.prevSystemTemperature)||0>=this.temperature||0<this.systemTemperature&&
.02>this.systemTemperature/this.nodes.length&&this.enableSimulation}});c("packedbubble","bubble",{minSize:"10%",maxSize:"50%",sizeBy:"area",zoneAxis:"y",tooltip:{pointFormat:"Value: {point.value}"},draggable:!0,useSimulation:!0,dataLabels:{formatter:function(){return this.point.value},parentNodeFormatter:function(){return this.name},parentNodeTextPath:{enabled:!0},padding:0},layoutAlgorithm:{initialPositions:"circle",initialPositionRadius:20,bubblePadding:5,parentNodeLimit:!1,seriesInteraction:!0,
dragBetweenSeries:!1,parentNodeOptions:{maxIterations:400,gravitationalConstant:.03,maxSpeed:50,initialPositionRadius:100,seriesInteraction:!0,marker:{fillColor:null,fillOpacity:1,lineWidth:1,lineColor:null,symbol:"circle"}},enableSimulation:!0,type:"packedbubble",integration:"packedbubble",maxIterations:1E3,splitSeries:!1,maxSpeed:5,gravitationalConstant:.01,friction:-.981}},{hasDraggableNodes:!0,forces:["barycenter","repulsive"],pointArrayMap:["value"],pointValKey:"value",isCartesian:!1,requireSorting:!1,
directTouch:!0,axisTypes:[],noSharedTooltip:!0,searchPoint:h.noop,accumulateAllPoints:function(a){var f=a.chart,b=[],d,c;for(d=0;d<f.series.length;d++)if(a=f.series[d],a.visible||!f.options.chart.ignoreHiddenSeries)for(c=0;c<a.yData.length;c++)b.push([null,null,a.yData[c],a.index,c,{id:c,marker:{radius:0}}]);return b},init:function(){B.prototype.init.apply(this,arguments);r(this,"updatedData",function(){this.chart.series.forEach(function(a){a.type===this.type&&(a.isDirty=!0)},this)});return this},
render:function(){var a=[];B.prototype.render.apply(this,arguments);this.options.dataLabels.allowOverlap||(this.data.forEach(function(f){g(f.dataLabels)&&f.dataLabels.forEach(function(f){a.push(f)})}),this.chart.hideOverlappingLabels(a))},setVisible:function(){var a=this;B.prototype.setVisible.apply(a,arguments);a.parentNodeLayout&&a.graph?a.visible?(a.graph.show(),a.parentNode.dataLabel&&a.parentNode.dataLabel.show()):(a.graph.hide(),a.parentNodeLayout.removeElementFromCollection(a.parentNode,a.parentNodeLayout.nodes),
a.parentNode.dataLabel&&a.parentNode.dataLabel.hide()):a.layout&&(a.visible?a.layout.addElementsToCollection(a.points,a.layout.nodes):a.points.forEach(function(f){a.layout.removeElementFromCollection(f,a.layout.nodes)}))},drawDataLabels:function(){var a=this.options.dataLabels.textPath,b=this.points;B.prototype.drawDataLabels.apply(this,arguments);this.parentNode&&(this.parentNode.formatPrefix="parentNode",this.points=[this.parentNode],this.options.dataLabels.textPath=this.options.dataLabels.parentNodeTextPath,
B.prototype.drawDataLabels.apply(this,arguments),this.points=b,this.options.dataLabels.textPath=a)},seriesBox:function(){var a=this.chart,b=Math.max,d=Math.min,c,e=[a.plotLeft,a.plotLeft+a.plotWidth,a.plotTop,a.plotTop+a.plotHeight];this.data.forEach(function(a){z(a.plotX)&&z(a.plotY)&&a.marker.radius&&(c=a.marker.radius,e[0]=d(e[0],a.plotX-c),e[1]=b(e[1],a.plotX+c),e[2]=d(e[2],a.plotY-c),e[3]=b(e[3],a.plotY+c))});return k(e.width/e.height)?e:null},calculateParentRadius:function(){var a=this.seriesBox();
this.parentNodeRadius=q(Math.sqrt(2*this.parentNodeMass/Math.PI)+20,20,a?Math.max(Math.sqrt(Math.pow(a.width,2)+Math.pow(a.height,2))/2+20,20):Math.sqrt(2*this.parentNodeMass/Math.PI)+20);this.parentNode&&(this.parentNode.marker.radius=this.parentNode.radius=this.parentNodeRadius)},drawGraph:function(){if(this.layout&&this.layout.options.splitSeries){var a=this.chart,b=this.layout.options.parentNodeOptions.marker;b={fill:b.fillColor||e(this.color).brighten(.4).get(),opacity:b.fillOpacity,stroke:b.lineColor||
this.color,"stroke-width":b.lineWidth};var d=this.visible?"inherit":"hidden";this.parentNodesGroup||(this.parentNodesGroup=this.plotGroup("parentNodesGroup","parentNode",d,.1,a.seriesGroup),this.group.attr({zIndex:2}));this.calculateParentRadius();d=t({x:this.parentNode.plotX-this.parentNodeRadius,y:this.parentNode.plotY-this.parentNodeRadius,width:2*this.parentNodeRadius,height:2*this.parentNodeRadius},b);this.parentNode.graphic||(this.graph=this.parentNode.graphic=a.renderer.symbol(b.symbol).add(this.parentNodesGroup));
this.parentNode.graphic.attr(d)}},createParentNodes:function(){var a=this,d=a.chart,c=a.parentNodeLayout,e,h=a.parentNode;a.parentNodeMass=0;a.points.forEach(function(f){a.parentNodeMass+=Math.PI*Math.pow(f.marker.radius,2)});a.calculateParentRadius();c.nodes.forEach(function(f){f.seriesIndex===a.index&&(e=!0)});c.setArea(0,0,d.plotWidth,d.plotHeight);e||(h||(h=(new b).init(this,{mass:a.parentNodeRadius/2,marker:{radius:a.parentNodeRadius},dataLabels:{inside:!1},dataLabelOnNull:!0,degree:a.parentNodeRadius,
isParentNode:!0,seriesIndex:a.index})),a.parentNode&&(h.plotX=a.parentNode.plotX,h.plotY=a.parentNode.plotY),a.parentNode=h,c.addElementsToCollection([a],c.series),c.addElementsToCollection([h],c.nodes))},addSeriesLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,c=t(a,a.parentNodeOptions,{enableSimulation:this.layout.options.enableSimulation});var e=b[a.type+"-series"];e||(b[a.type+"-series"]=e=new h.layouts[a.type],e.init(c),d.splice(e.index,
0,e));this.parentNodeLayout=e;this.createParentNodes()},addLayout:function(){var a=this.options.layoutAlgorithm,b=this.chart.graphLayoutsStorage,d=this.chart.graphLayoutsLookup,c=this.chart.options.chart;b||(this.chart.graphLayoutsStorage=b={},this.chart.graphLayoutsLookup=d=[]);var e=b[a.type];e||(a.enableSimulation=z(c.forExport)?!c.forExport:a.enableSimulation,b[a.type]=e=new h.layouts[a.type],e.init(a),d.splice(e.index,0,e));this.layout=e;this.points.forEach(function(a){a.mass=2;a.degree=1;a.collisionNmb=
1});e.setArea(0,0,this.chart.plotWidth,this.chart.plotHeight);e.addElementsToCollection([this],e.series);e.addElementsToCollection(this.points,e.nodes)},deferLayout:function(){var a=this.options.layoutAlgorithm;this.visible&&(this.addLayout(),a.splitSeries&&this.addSeriesLayout())},translate:function(){var a=this.chart,b=this.data,d=this.index,c,e=this.options.useSimulation;this.processedXData=this.xData;this.generatePoints();z(a.allDataPoints)||(a.allDataPoints=this.accumulateAllPoints(this),this.getPointRadius());
if(e)var h=a.allDataPoints;else h=this.placeBubbles(a.allDataPoints),this.options.draggable=!1;for(c=0;c<h.length;c++)if(h[c][3]===d){var g=b[h[c][4]];var m=h[c][2];e||(g.plotX=h[c][0]-a.plotLeft+a.diffX,g.plotY=h[c][1]-a.plotTop+a.diffY);g.marker=y(g.marker,{radius:m,width:2*m,height:2*m});g.radius=m}e&&this.deferLayout();w(this,"afterTranslate")},checkOverlap:function(a,b){var f=a[0]-b[0],d=a[1]-b[1];return-.001>Math.sqrt(f*f+d*d)-Math.abs(a[2]+b[2])},positionBubble:function(a,b,d){var f=Math.sqrt,
c=Math.asin,e=Math.acos,h=Math.pow,g=Math.abs;f=f(h(a[0]-b[0],2)+h(a[1]-b[1],2));e=e((h(f,2)+h(d[2]+b[2],2)-h(d[2]+a[2],2))/(2*(d[2]+b[2])*f));c=c(g(a[0]-b[0])/f);a=(0>a[1]-b[1]?0:Math.PI)+e+c*(0>(a[0]-b[0])*(a[1]-b[1])?1:-1);return[b[0]+(b[2]+d[2])*Math.sin(a),b[1]-(b[2]+d[2])*Math.cos(a),d[2],d[3],d[4]]},placeBubbles:function(a){var b=this.checkOverlap,f=this.positionBubble,d=[],c=1,e=0,h=0;var g=[];var m;a=a.sort(function(a,b){return b[2]-a[2]});if(a.length){d.push([[0,0,a[0][2],a[0][3],a[0][4]]]);
if(1<a.length)for(d.push([[0,0-a[1][2]-a[0][2],a[1][2],a[1][3],a[1][4]]]),m=2;m<a.length;m++)a[m][2]=a[m][2]||1,g=f(d[c][e],d[c-1][h],a[m]),b(g,d[c][0])?(d.push([]),h=0,d[c+1].push(f(d[c][e],d[c][0],a[m])),c++,e=0):1<c&&d[c-1][h+1]&&b(g,d[c-1][h+1])?(h++,d[c].push(f(d[c][e],d[c-1][h],a[m])),e++):(e++,d[c].push(g));this.chart.stages=d;this.chart.rawPositions=[].concat.apply([],d);this.resizeRadius();g=this.chart.rawPositions}return g},resizeRadius:function(){var a=this.chart,b=a.rawPositions,d=Math.min,
c=Math.max,e=a.plotLeft,h=a.plotTop,g=a.plotHeight,m=a.plotWidth,n,k,l;var q=n=Number.POSITIVE_INFINITY;var r=k=Number.NEGATIVE_INFINITY;for(l=0;l<b.length;l++){var t=b[l][2];q=d(q,b[l][0]-t);r=c(r,b[l][0]+t);n=d(n,b[l][1]-t);k=c(k,b[l][1]+t)}l=[r-q,k-n];d=d.apply([],[(m-e)/l[0],(g-h)/l[1]]);if(1e-10<Math.abs(d-1)){for(l=0;l<b.length;l++)b[l][2]*=d;this.placeBubbles(b)}else a.diffY=g/2+h-n-(k-n)/2,a.diffX=m/2+e-q-(r-q)/2},calculateZExtremes:function(){var a=this.options.zMin,b=this.options.zMax,d=
Infinity,c=-Infinity;if(a&&b)return[a,b];this.chart.series.forEach(function(a){a.yData.forEach(function(a){z(a)&&(a>c&&(c=a),a<d&&(d=a))})});a=l(a,d);b=l(b,c);return[a,b]},getPointRadius:function(){var a=this,b=a.chart,d=a.options,c=d.useSimulation,e=Math.min(b.plotWidth,b.plotHeight),h={},g=[],m=b.allDataPoints,n,k,l,r;["minSize","maxSize"].forEach(function(a){var b=parseInt(d[a],10),f=/%$/.test(d[a]);h[a]=f?e*b/100:b*Math.sqrt(m.length)});b.minRadius=n=h.minSize/Math.sqrt(m.length);b.maxRadius=
k=h.maxSize/Math.sqrt(m.length);var t=c?a.calculateZExtremes():[n,k];(m||[]).forEach(function(b,d){l=c?q(b[2],t[0],t[1]):b[2];r=a.getRadius(t[0],t[1],n,k,l);0===r&&(r=null);m[d][2]=r;g.push(r)});a.radii=g},redrawHalo:d.redrawHalo,onMouseDown:d.onMouseDown,onMouseMove:d.onMouseMove,onMouseUp:function(a){if(a.fixedPosition&&!a.removed){var b,f,c=this.layout,e=this.parentNodeLayout;e&&c.options.dragBetweenSeries&&e.nodes.forEach(function(d){a&&a.marker&&d!==a.series.parentNode&&(b=c.getDistXY(a,d),f=
c.vectorLength(b)-d.marker.radius-a.marker.radius,0>f&&(d.series.addPoint(t(a.options,{plotX:a.plotX,plotY:a.plotY}),!1),c.removeElementFromCollection(a,c.nodes),a.remove()))});d.onMouseUp.apply(this,arguments)}},destroy:function(){this.chart.graphLayoutsLookup&&this.chart.graphLayoutsLookup.forEach(function(a){a.removeElementFromCollection(this,a.series)},this);this.parentNode&&(this.parentNodeLayout.removeElementFromCollection(this.parentNode,this.parentNodeLayout.nodes),this.parentNode.dataLabel&&
(this.parentNode.dataLabel=this.parentNode.dataLabel.destroy()));h.Series.prototype.destroy.apply(this,arguments)},alignDataLabel:h.Series.prototype.alignDataLabel},{destroy:function(){this.series.layout&&this.series.layout.removeElementFromCollection(this,this.series.layout.nodes);return n.prototype.destroy.apply(this,arguments)}});r(m,"beforeRedraw",function(){this.allDataPoints&&delete this.allDataPoints});""});E(r,"parts-more/Polar.js",[r["parts/Globals.js"],r["parts/Utilities.js"]],function(h,
a){var c=a.addEvent,e=a.defined,r=a.find,q=a.pick,z=a.splat,y=a.uniqueKey,w=a.wrap,g=h.Series,k=h.seriesTypes,t=g.prototype,l=h.Pointer.prototype;t.searchPointByAngle=function(a){var c=this.chart,e=this.xAxis.pane.center;return this.searchKDTree({clientX:180+-180/Math.PI*Math.atan2(a.chartX-e[0]-c.plotLeft,a.chartY-e[1]-c.plotTop)})};t.getConnectors=function(a,c,e,b){var d=b?1:0;var f=0<=c&&c<=a.length-1?c:0>c?a.length-1+c:0;c=0>f-1?a.length-(1+d):f-1;d=f+1>a.length-1?d:f+1;var h=a[c];d=a[d];var g=
h.plotX;h=h.plotY;var m=d.plotX;var n=d.plotY;d=a[f].plotX;f=a[f].plotY;g=(1.5*d+g)/2.5;h=(1.5*f+h)/2.5;m=(1.5*d+m)/2.5;var k=(1.5*f+n)/2.5;n=Math.sqrt(Math.pow(g-d,2)+Math.pow(h-f,2));var l=Math.sqrt(Math.pow(m-d,2)+Math.pow(k-f,2));g=Math.atan2(h-f,g-d);k=Math.PI/2+(g+Math.atan2(k-f,m-d))/2;Math.abs(g-k)>Math.PI/2&&(k-=Math.PI);g=d+Math.cos(k)*n;h=f+Math.sin(k)*n;m=d+Math.cos(Math.PI+k)*l;k=f+Math.sin(Math.PI+k)*l;d={rightContX:m,rightContY:k,leftContX:g,leftContY:h,plotX:d,plotY:f};e&&(d.prevPointCont=
this.getConnectors(a,c,!1,b));return d};t.toXY=function(a){var c=this.chart,e=this.xAxis;var b=this.yAxis;var d=a.plotX,f=a.plotY,h=a.series,g=c.inverted,n=a.y,k=g?d:b.len-f;g&&h&&!h.isRadialBar&&(a.plotY=f="number"===typeof n?b.translate(n)||0:0);a.rectPlotX=d;a.rectPlotY=f;b.center&&(k+=b.center[3]/2);b=g?b.postTranslate(f,k):e.postTranslate(d,k);a.plotX=a.polarPlotX=b.x-c.plotLeft;a.plotY=a.polarPlotY=b.y-c.plotTop;this.kdByAngle?(c=(d/Math.PI*180+e.pane.options.startAngle)%360,0>c&&(c+=360),a.clientX=
c):a.clientX=a.plotX};k.spline&&(w(k.spline.prototype,"getPointSpline",function(a,c,e,b){this.chart.polar?b?(a=this.getConnectors(c,b,!0,this.connectEnds),a=["C",a.prevPointCont.rightContX,a.prevPointCont.rightContY,a.leftContX,a.leftContY,a.plotX,a.plotY]):a=["M",e.plotX,e.plotY]:a=a.call(this,c,e,b);return a}),k.areasplinerange&&(k.areasplinerange.prototype.getPointSpline=k.spline.prototype.getPointSpline));c(g,"afterTranslate",function(){var a=this.chart;if(a.polar&&this.xAxis){(this.kdByAngle=
a.tooltip&&a.tooltip.shared)?this.searchPoint=this.searchPointByAngle:this.options.findNearestPointBy="xy";if(!this.preventPostTranslate)for(var e=this.points,g=e.length;g--;)this.toXY(e[g]),!a.hasParallelCoordinates&&!this.yAxis.reversed&&e[g].y<this.yAxis.min&&(e[g].isNull=!0);this.hasClipCircleSetter||(this.hasClipCircleSetter=!!this.eventsToUnbind.push(c(this,"afterRender",function(){if(a.polar){var b=this.yAxis.pane.center;this.clipCircle?this.clipCircle.animate({x:b[0],y:b[1],r:b[2]/2,innerR:b[3]/
2}):this.clipCircle=a.renderer.clipCircle(b[0],b[1],b[2]/2,b[3]/2);this.group.clip(this.clipCircle);this.setClip=h.noop}})))}},{order:2});w(t,"getGraphPath",function(a,c){var e=this,b;if(this.chart.polar){c=c||this.points;for(b=0;b<c.length;b++)if(!c[b].isNull){var d=b;break}if(!1!==this.options.connectEnds&&"undefined"!==typeof d){this.connectEnds=!0;c.splice(c.length,0,c[d]);var f=!0}c.forEach(function(a){"undefined"===typeof a.polarPlotY&&e.toXY(a)})}b=a.apply(this,[].slice.call(arguments,1));
f&&c.pop();return b});var B=function(a,c){var e=this,b=this.chart,d=this.options.animation,f=this.group,g=this.markerGroup,m=this.xAxis.center,k=b.plotLeft,n=b.plotTop,l,r,t,v;if(b.polar)if(e.isRadialBar)c||(e.startAngleRad=q(e.translatedThreshold,e.xAxis.startAngleRad),h.seriesTypes.pie.prototype.animate.call(e,c));else{if(b.renderer.isSVG)if(d=h.animObject(d),e.is("column")){if(!c){var w=m[3]/2;e.points.forEach(function(a){l=a.graphic;t=(r=a.shapeArgs)&&r.r;v=r&&r.innerR;l&&r&&(l.attr({r:w,innerR:w}),
l.animate({r:t,innerR:v},e.options.animation))});e.animate=null}}else c?(a={translateX:m[0]+k,translateY:m[1]+n,scaleX:.001,scaleY:.001},f.attr(a),g&&g.attr(a)):(a={translateX:k,translateY:n,scaleX:1,scaleY:1},f.animate(a,d),g&&g.animate(a,d),e.animate=null)}else a.call(this,c)};w(t,"animate",B);k.column&&(g=k.arearange.prototype,k=k.column.prototype,k.polarArc=function(a,c,e,b){var d=this.xAxis.center,f=this.yAxis.len,h=d[3]/2;c=f-c+h;a=f-q(a,f)+h;this.yAxis.reversed&&(0>c&&(c=h),0>a&&(a=h));return{x:d[0],
y:d[1],r:c,innerR:a,start:e,end:b}},w(k,"animate",B),w(k,"translate",function(c){var g=this.options,k=g.stacking,b=this.chart,d=this.xAxis,f=this.yAxis,l=f.reversed,n=f.center,q=d.startAngleRad,r=d.endAngleRad-q;this.preventPostTranslate=!0;c.call(this);if(d.isRadial){c=this.points;d=c.length;var t=f.translate(f.min);var v=f.translate(f.max);g=g.threshold||0;if(b.inverted&&h.isNumber(g)){var w=f.translate(g);e(w)&&(0>w?w=0:w>r&&(w=r),this.translatedThreshold=w+q)}for(;d--;){g=c[d];var y=g.barX;var z=
g.x;var B=g.y;g.shapeType="arc";if(b.inverted){g.plotY=f.translate(B);if(k){if(B=f.stacks[(0>B?"-":"")+this.stackKey],this.visible&&B&&B[z]&&!g.isNull){var A=B[z].points[this.getStackIndicator(void 0,z,this.index).key];var x=f.translate(A[0]);A=f.translate(A[1]);e(x)&&(x=a.clamp(x,0,r))}}else x=w,A=g.plotY;x>A&&(A=[x,x=A][0]);if(!l)if(x<t)x=t;else if(A>v)A=v;else{if(A<t||x>v)x=A=0}else if(A>t)A=t;else if(x<v)x=v;else if(x>t||A<v)x=A=r;f.min>f.max&&(x=A=l?r:0);x+=q;A+=q;n&&(g.barX=y+=n[3]/2);z=Math.max(y,
0);B=Math.max(y+g.pointWidth,0);g.shapeArgs={x:n&&n[0],y:n&&n[1],r:B,innerR:z,start:x,end:A};g.opacity=x===A?0:void 0;g.plotY=(e(this.translatedThreshold)&&(x<this.translatedThreshold?x:A))-q}else x=y+q,g.shapeArgs=this.polarArc(g.yBottom,g.plotY,x,x+g.pointWidth);this.toXY(g);b.inverted?(y=f.postTranslate(g.rectPlotY,y+g.pointWidth/2),g.tooltipPos=[y.x-b.plotLeft,y.y-b.plotTop]):g.tooltipPos=[g.plotX,g.plotY];n&&(g.ttBelow=g.plotY>n[1])}}}),k.findAlignments=function(a,c){null===c.align&&(c.align=
20<a&&160>a?"left":200<a&&340>a?"right":"center");null===c.verticalAlign&&(c.verticalAlign=45>a||315<a?"bottom":135<a&&225>a?"top":"middle");return c},g&&(g.findAlignments=k.findAlignments),w(k,"alignDataLabel",function(a,c,e,b,d,f){var g=this.chart,h=q(b.inside,!!this.options.stacking);g.polar?(a=c.rectPlotX/Math.PI*180,g.inverted?(this.forceDL=g.isInsidePlot(c.plotX,Math.round(c.plotY),!1),h&&c.shapeArgs?(d=c.shapeArgs,d=this.yAxis.postTranslate((d.start+d.end)/2-this.xAxis.startAngleRad,c.barX+
c.pointWidth/2),d={x:d.x-g.plotLeft,y:d.y-g.plotTop}):c.tooltipPos&&(d={x:c.tooltipPos[0],y:c.tooltipPos[1]}),b.align=q(b.align,"center"),b.verticalAlign=q(b.verticalAlign,"middle")):this.findAlignments&&(b=this.findAlignments(a,b)),t.alignDataLabel.call(this,c,e,b,d,f),this.isRadialBar&&c.shapeArgs&&c.shapeArgs.start===c.shapeArgs.end&&e.hide(!0)):a.call(this,c,e,b,d,f)}));w(l,"getCoordinates",function(a,c){var e=this.chart,b={xAxis:[],yAxis:[]};e.polar?e.axes.forEach(function(a){var d=a.isXAxis,
g=a.center;if("colorAxis"!==a.coll){var h=c.chartX-g[0]-e.plotLeft;g=c.chartY-g[1]-e.plotTop;b[d?"xAxis":"yAxis"].push({axis:a,value:a.translate(d?Math.PI-Math.atan2(h,g):Math.sqrt(Math.pow(h,2)+Math.pow(g,2)),!0)})}}):b=a.call(this,c);return b});h.SVGRenderer.prototype.clipCircle=function(a,c,e,b){var d=y(),f=this.createElement("clipPath").attr({id:d}).add(this.defs);a=b?this.arc(a,c,e,b,0,2*Math.PI).add(f):this.circle(a,c,e).add(f);a.id=d;a.clipPath=f;return a};c(h.Chart,"getAxes",function(){this.pane||
(this.pane=[]);z(this.options.pane).forEach(function(a){new h.Pane(a,this)},this)});c(h.Chart,"afterDrawChartBox",function(){this.pane.forEach(function(a){a.render()})});c(h.Series,"afterInit",function(){var a=this.chart;a.inverted&&a.polar&&(this.isRadialSeries=!0,this.is("column")&&(this.isRadialBar=!0))});w(h.Chart.prototype,"get",function(a,c){return r(this.pane,function(a){return a.options.id===c})||a.call(this,c)})});E(r,"masters/highcharts-more.src.js",[],function(){})});
//# sourceMappingURL=highcharts-more.js.map