/*
 Highstock JS v8.0.0 (2020-02-16)

 All technical indicators for Highstock

 (c) 2010-2019 Pawel Fus

 License: www.highcharts.com/license
*/
(function(k){"object"===typeof module&&module.exports?(k["default"]=k,module.exports=k):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators-all",["highcharts","highcharts/modules/stock"],function(t){k(t);k.Highcharts=t;return k}):k("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(k){function t(g,f,l,h){g.hasOwnProperty(f)||(g[f]=h.apply(null,l))}k=k?k._modules:{};t(k,"mixins/indicator-required.js",[k["parts/Utilities.js"]],function(g){var f=g.error;return{isParentLoaded:function(l,
h,e,d,c){if(l)return d?d(l):!0;f(c||this.generateMessage(e,h));return!1},generateMessage:function(f,h){return'Error: "'+f+'" indicator type requires "'+h+'" indicator loaded before. Please read docs: https://api.highcharts.com/highstock/plotOptions.'+f}}});t(k,"indicators/indicators.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.addEvent,e=f.error,d=f.extend,c=f.isArray,a=f.pick,b=f.seriesType,r=f.splat,v=g.Series,q=g.seriesTypes,
p=g.seriesTypes.ohlc.prototype,m=l.generateMessage;h(g.Series,"init",function(a){a=a.options;a.useOhlcData&&"highcharts-navigator-series"!==a.id&&d(this,{pointValKey:p.pointValKey,keys:p.keys,pointArrayMap:p.pointArrayMap,toYData:p.toYData})});h(v,"afterSetOptions",function(a){a=a.options;var c=a.dataGrouping;c&&a.useOhlcData&&"highcharts-navigator-series"!==a.id&&(c.approximation="ohlc")});b("sma","line",{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:0,period:14}},
{processData:function(){var a=this.options.compareToMain,c=this.linkedParent;v.prototype.processData.apply(this,arguments);c&&c.compareValue&&a&&(this.compareValue=c.compareValue)},bindTo:{series:!0,eventName:"updatedData"},hasDerivedData:!0,useCommonDataGrouping:!0,nameComponents:["period"],nameSuffixes:[],calculateOn:"init",requiredIndicators:[],requireIndicators:function(){var a={allLoaded:!0};this.requiredIndicators.forEach(function(c){q[c]?q[c].prototype.requireIndicators():(a.allLoaded=!1,a.needed=
c)});return a},init:function(a,c){function d(){var a=b.points||[],c=(b.xData||[]).length,d=b.getValues(b.linkedParent,b.options.params)||{values:[],xData:[],yData:[]},e=[],n=!0;if(c&&!b.hasGroupedData&&b.visible&&b.points)if(b.cropped){if(b.xAxis){var m=b.xAxis.min;var q=b.xAxis.max}c=b.cropData(d.xData,d.yData,m,q);for(m=0;m<c.xData.length;m++)e.push([c.xData[m]].concat(r(c.yData[m])));c=d.xData.indexOf(b.xData[0]);m=d.xData.indexOf(b.xData[b.xData.length-1]);-1===c&&m===d.xData.length-2&&e[0][0]===
a[0].x&&e.shift();b.updateData(e)}else d.xData.length!==c-1&&d.xData.length!==c+1&&(n=!1,b.updateData(d.values));n&&(b.xData=d.xData,b.yData=d.yData,b.options.data=d.values);!1===b.bindTo.series&&(delete b.processedXData,b.isDirty=!0,b.redraw());b.isDirtyData=!1}var b=this,n=b.requireIndicators();if(!n.allLoaded)return e(m(b.type,n.needed));v.prototype.init.call(b,a,c);a.linkSeries();b.dataEventsToUnbind=[];if(!b.linkedParent)return e("Series "+b.options.linkedTo+" not found! Check `linkedTo`.",!1,
a);b.dataEventsToUnbind.push(h(b.bindTo.series?b.linkedParent:b.linkedParent.xAxis,b.bindTo.eventName,d));if("init"===b.calculateOn)d();else var q=h(b.chart,b.calculateOn,function(){d();q()});return b},getName:function(){var b=this.name,c=[];b||((this.nameComponents||[]).forEach(function(b,d){c.push(this.options.params[b]+a(this.nameSuffixes[d],""))},this),b=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+c.join(", ")+")":""));return b},getValues:function(a,b){var d=b.period,e=
a.xData;a=a.yData;var r=a.length,m=0,q=0,n=[],v=[],p=[],h=-1;if(!(e.length<d)){for(c(a[0])&&(h=b.index?b.index:0);m<d-1;)q+=0>h?a[m]:a[m][h],m++;for(b=m;b<r;b++){q+=0>h?a[b]:a[b][h];var f=[e[b],q/d];n.push(f);v.push(f[0]);p.push(f[1]);q-=0>h?a[b-m]:a[b-m][h]}return{values:n,xData:v,yData:p}}},destroy:function(){this.dataEventsToUnbind.forEach(function(a){a()});v.prototype.destroy.apply(this,arguments)}});""});t(k,"indicators/accumulation-distribution.src.js",[k["parts/Utilities.js"]],function(g){var f=
g.error;g=g.seriesType;g("ad","sma",{params:{volumeSeriesID:"volume"}},{nameComponents:!1,nameBase:"Accumulation/Distribution",getValues:function(l,h){var e=h.period,d=l.xData,c=l.yData,a=h.volumeSeriesID,b=l.chart.get(a);h=b&&b.yData;var r=c?c.length:0,v=[],q=[],p=[];if(!(d.length<=e&&r&&4!==c[0].length)){if(b){for(;e<r;e++){l=v.length;a=c[e][1];b=c[e][2];var m=c[e][3],n=h[e];a=[d[e],m===a&&m===b||a===b?0:(2*m-b-a)/(a-b)*n];0<l&&(a[1]+=v[l-1][1]);v.push(a);q.push(a[0]);p.push(a[1])}return{values:v,
xData:q,yData:p}}f("Series "+a+" not found! Check `volumeSeriesID`.",!0,l.chart)}}});""});t(k,"indicators/ao.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){var l=f.correctFloat,h=f.isArray;f=f.seriesType;f("ao","sma",{greaterBarColor:"#06B535",lowerBarColor:"#F21313",threshold:0,groupPadding:.2,pointPadding:.2,states:{hover:{halo:{size:0}}}},{nameBase:"AO",nameComponents:!1,markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,crispCol:g.seriesTypes.column.prototype.crispCol,
translate:g.seriesTypes.column.prototype.translate,drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){var e=this.options,d=this.points,c=e.greaterBarColor;e=e.lowerBarColor;var a=d[0];if(!this.userOptions.color&&a)for(a.color=c,a=1;a<d.length;a++)d[a].color=d[a].y>d[a-1].y?c:d[a].y<d[a-1].y?e:d[a-1].color},getValues:function(e){var d=e.xData||[];e=e.yData||[];var c=e.length,a=[],b=[],r=[],v=0,q=0,p;if(!(34>=d.length)&&h(e[0])&&4===e[0].length){for(p=0;33>p;p++){var m=(e[p][1]+
e[p][2])/2;29<=p&&(v=l(v+m));q=l(q+m)}for(p=33;p<c;p++){m=(e[p][1]+e[p][2])/2;v=l(v+m);q=l(q+m);m=v/5;var n=q/34;m=l(m-n);a.push([d[p],m]);b.push(d[p]);r.push(m);m=p+1-5;n=p+1-34;v=l(v-(e[m][1]+e[m][2])/2);q=l(q-(e[n][1]+e[n][2])/2)}return{values:a,xData:b,yData:r}}}});""});t(k,"mixins/multipe-lines.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){var l=f.defined,h=f.error,e=f.merge,d=g.each,c=g.seriesTypes.sma;return{pointArrayMap:["top","bottom"],pointValKey:"top",linesApiNames:["bottomLine"],
getTranslatedLinesNames:function(a){var b=[];d(this.pointArrayMap,function(c){c!==a&&b.push("plot"+c.charAt(0).toUpperCase()+c.slice(1))});return b},toYData:function(a){var b=[];d(this.pointArrayMap,function(c){b.push(a[c])});return b},translate:function(){var a=this,b=a.pointArrayMap,e=[],v;e=a.getTranslatedLinesNames();c.prototype.translate.apply(a,arguments);d(a.points,function(c){d(b,function(b,d){v=c[b];null!==v&&(c[e[d]]=a.yAxis.toPixels(v,!0))})})},drawGraph:function(){var a=this,b=a.linesApiNames,
r=a.points,v=r.length,q=a.options,p=a.graph,m={options:{gapSize:q.gapSize}},n=[],f=a.getTranslatedLinesNames(a.pointValKey),x;d(f,function(a,b){for(n[b]=[];v--;)x=r[v],n[b].push({x:x.x,plotX:x.plotX,plotY:x[a],isNull:!l(x[a])});v=r.length});d(b,function(b,d){n[d]?(a.points=n[d],q[b]?a.options=e(q[b].styles,m):h('Error: "There is no '+b+' in DOCS options declared. Check if linesApiNames are consistent with your DOCS line names." at mixin/multiple-line.js:34'),a.graph=a["graph"+b],c.prototype.drawGraph.call(a),
a["graph"+b]=a.graph):h('Error: "'+b+" doesn't have equivalent in pointArrayMap. To many elements in linesApiNames relative to pointArrayMap.\"")});a.points=r;a.options=q;a.graph=p;c.prototype.drawGraph.call(a)}}});t(k,"indicators/aroon.src.js",[k["parts/Utilities.js"],k["mixins/multipe-lines.js"]],function(g,f){function l(d,c){var a=d[0],b=0,e;for(e=1;e<d.length;e++)if("max"===c&&d[e]>=a||"min"===c&&d[e]<=a)a=d[e],b=e;return b}var h=g.merge,e=g.pick;g=g.seriesType;g("aroon","sma",{params:{period:25},
marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Aroon Up: {point.y}<br/>Aroon Down: {point.aroonDown}<br/>'},aroonDown:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},h(f,{nameBase:"Aroon",pointArrayMap:["y","aroonDown"],pointValKey:"y",linesApiNames:["aroonDown"],getValues:function(d,c){c=c.period;var a=d.xData,b=(d=d.yData)?d.length:0,r=[],v=[],q=[],h;for(h=c-1;h<b;h++){var m=d.slice(h-c+1,h+2);var n=
l(m.map(function(a){return e(a[2],a)}),"min");m=l(m.map(function(a){return e(a[1],a)}),"max");m=m/c*100;n=n/c*100;a[h+1]&&(r.push([a[h+1],m,n]),v.push(a[h+1]),q.push([m,n]))}return{values:r,xData:v,yData:q}}}));""});t(k,"indicators/aroon-oscillator.src.js",[k["parts/Globals.js"],k["mixins/multipe-lines.js"],k["mixins/indicator-required.js"],k["parts/Utilities.js"]],function(g,f,l,h){var e=h.merge;h=h.seriesType;var d=g.seriesTypes.aroon;h("aroonoscillator","aroon",{params:{period:25},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b>: {point.y}'}},
e(f,{nameBase:"Aroon Oscillator",pointArrayMap:["y"],pointValKey:"y",linesApiNames:[],init:function(){var c=arguments,a=this;l.isParentLoaded(d,"aroon",a.type,function(b){b.prototype.init.apply(a,c)})},getValues:function(c,a){var b=[],e=[],h=[];c=d.prototype.getValues.call(this,c,a);for(a=0;a<c.yData.length;a++){var q=c.yData[a][0];var p=c.yData[a][1];q-=p;b.push([c.xData[a],q]);e.push(c.xData[a]);h.push(q)}return{values:b,xData:e,yData:h}}}));""});t(k,"indicators/atr.src.js",[k["parts/Utilities.js"]],
function(g){function f(e,d){return Math.max(e[1]-e[2],d===h?0:Math.abs(e[1]-d[3]),d===h?0:Math.abs(e[2]-d[3]))}var l=g.isArray;g=g.seriesType;var h;g("atr","sma",{params:{period:14}},{getValues:function(e,d){d=d.period;var c=e.xData,a=(e=e.yData)?e.length:0,b=1,h=0,v=0,q=[],p=[],m=[],n;var g=[[c[0],e[0]]];if(!(c.length<=d)&&l(e[0])&&4===e[0].length){for(n=1;n<=a;n++)if(g.push([c[n],e[n]]),d<b){var x=d;var u=c[n-1],A=f(e[n-1],e[n-2]);x=[u,(h*(x-1)+A)/x];h=x[1];q.push(x);p.push(x[0]);m.push(x[1])}else d===
b?(h=v/(n-1),q.push([c[n-1],h]),p.push(c[n-1]),m.push(h)):v+=f(e[n-1],e[n-2]),b++;return{values:q,xData:p,yData:m}}}});""});t(k,"indicators/bollinger-bands.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/multipe-lines.js"]],function(g,f,l){var h=f.isArray,e=f.merge;f=f.seriesType;var d=g.seriesTypes.sma;f("bb","sma",{params:{period:20,standardDeviation:2,index:3},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},
marker:{enabled:!1},dataGrouping:{approximation:"averages"}},e(l,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameComponents:["period","standardDeviation"],linesApiNames:["topLine","bottomLine"],init:function(){d.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(c,a){var b=a.period,e=a.standardDeviation,v=c.xData,q=(c=c.yData)?c.length:0,p=[],m=[],n=[],f;if(!(v.length<
b)){var x=h(c[0]);for(f=b;f<=q;f++){var l=v.slice(f-b,f);var g=c.slice(f-b,f);var y=d.prototype.getValues.call(this,{xData:l,yData:g},a);l=y.xData[0];y=y.yData[0];for(var k=0,w=g.length,z=0;z<w;z++){var D=(x?g[z][a.index]:g[z])-y;k+=D*D}D=Math.sqrt(k/(w-1));g=y+e*D;D=y-e*D;p.push([l,g,y,D]);m.push(l);n.push([g,y,D])}return{values:p,xData:m,yData:n}}}}));""});t(k,"indicators/cci.src.js",[k["parts/Utilities.js"]],function(g){function f(h){return h.reduce(function(e,d){return e+d},0)}var l=g.isArray;
g=g.seriesType;g("cci","sma",{params:{period:14}},{getValues:function(h,e){e=e.period;var d=h.xData,c=(h=h.yData)?h.length:0,a=[],b=1,r=[],v=[],q=[];if(!(d.length<=e)&&l(h[0])&&4===h[0].length){for(;b<e;){var p=h[b-1];a.push((p[1]+p[2]+p[3])/3);b++}for(b=e;b<=c;b++){p=h[b-1];p=(p[1]+p[2]+p[3])/3;var m=a.push(p);var n=a.slice(m-e);m=f(n)/e;var g,x=n.length,u=0;for(g=0;g<x;g++)u+=Math.abs(m-n[g]);n=u/e;p=(p-m)/(.015*n);r.push([d[b-1],p]);v.push(d[b-1]);q.push(p)}return{values:r,xData:v,yData:q}}}});
""});t(k,"indicators/cmf.src.js",[k["parts/Utilities.js"]],function(g){g=g.seriesType;g("cmf","sma",{params:{period:14,volumeSeriesID:"volume"}},{nameBase:"Chaikin Money Flow",isValid:function(){var f=this.chart,l=this.options,h=this.linkedParent;f=this.volumeSeries||(this.volumeSeries=f.get(l.params.volumeSeriesID));var e=h&&h.yData&&4===h.yData[0].length;return!!(h&&f&&h.xData&&h.xData.length>=l.params.period&&f.xData&&f.xData.length>=l.params.period&&e)},getValues:function(f,l){if(this.isValid())return this.getMoneyFlow(f.xData,
f.yData,this.volumeSeries.yData,l.period)},getMoneyFlow:function(f,l,h,e){function d(a,b){var c=a[1],d=a[2];a=a[3];return null!==b&&null!==c&&null!==d&&null!==a&&c!==d?(a-d-(c-a))/(c-d)*b:(n=m,null)}var c=l.length,a=[],b=0,r=0,v=[],q=[],p=[],m,n=-1;if(0<e&&e<=c){for(m=0;m<e;m++)a[m]=d(l[m],h[m]),b+=h[m],r+=a[m];v.push(f[m-1]);q.push(m-n>=e&&0!==b?r/b:null);for(p.push([v[0],q[0]]);m<c;m++){a[m]=d(l[m],h[m]);b-=h[m-e];b+=h[m];r-=a[m-e];r+=a[m];var g=[f[m],m-n>=e?r/b:null];v.push(g[0]);q.push(g[1]);
p.push([g[0],g[1]])}}return{values:p,xData:v,yData:q}}});""});t(k,"indicators/dpo.src.js",[k["parts/Utilities.js"]],function(g){function f(e,d,c,a,b){d=h(d[c][a],d[c]);return b?l(e-d):l(e+d)}var l=g.correctFloat,h=g.pick;g=g.seriesType;g("dpo","sma",{params:{period:21}},{nameBase:"DPO",getValues:function(e,d){var c=d.period;d=d.index;var a=c+Math.floor(c/2+1),b=e.xData||[];e=e.yData||[];var r=e.length,v=[],q=[],p=[],m=0,n,l;if(!(b.length<=a)){for(n=0;n<c-1;n++)m=f(m,e,n,d);for(l=0;l<=r-a;l++){var x=
l+c-1;n=l+a-1;m=f(m,e,x,d);x=h(e[n][d],e[n]);x-=m/c;m=f(m,e,l,d,!0);v.push([b[n],x]);q.push(b[n]);p.push(x)}return{values:v,xData:q,yData:p}}}});""});t(k,"indicators/ema.src.js",[k["parts/Utilities.js"]],function(g){var f=g.correctFloat,l=g.isArray;g=g.seriesType;g("ema","sma",{params:{index:3,period:9}},{accumulatePeriodPoints:function(h,e,d){for(var c=0,a=0,b;a<h;)b=0>e?d[a]:d[a][e],c+=b,a++;return c},calculateEma:function(h,e,d,c,a,b,r){h=h[d-1];e=0>b?e[d-1]:e[d-1][b];c="undefined"===typeof a?
r:f(e*c+a*(1-c));return[h,c]},getValues:function(h,e){var d=e.period,c=h.xData,a=(h=h.yData)?h.length:0,b=2/(d+1),r=[],v=[],q=[],f=-1;if(!(a<d)){l(h[0])&&(f=e.index?e.index:0);e=this.accumulatePeriodPoints(d,f,h);for(e/=d;d<a+1;d++){var m=this.calculateEma(c,h,d,b,m,f,e);r.push(m);v.push(m[0]);q.push(m[1]);m=m[1]}return{values:r,xData:v,yData:q}}}});""});t(k,"indicators/chaikin.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.correctFloat,
e=f.error;f=f.seriesType;var d=g.seriesTypes.ema,c=g.seriesTypes.ad;f("chaikin","ema",{params:{volumeSeriesID:"volume",periods:[3,10]}},{nameBase:"Chaikin Osc",nameComponents:["periods"],init:function(){var a=arguments,b=this;l.isParentLoaded(d,"ema",b.type,function(c){c.prototype.init.apply(b,a)})},getValues:function(a,b){var f=b.periods,v=b.period,q=[],p=[],m=[],n;if(2!==f.length||f[1]<=f[0])e('Error: "Chaikin requires two periods. Notice, first period should be lower than the second one."');else if(b=
c.prototype.getValues.call(this,a,{volumeSeriesID:b.volumeSeriesID,period:v}))if(a=d.prototype.getValues.call(this,b,{period:f[0]}),b=d.prototype.getValues.call(this,b,{period:f[1]}),a&&b){f=f[1]-f[0];for(n=0;n<b.yData.length;n++)v=h(a.yData[n+f]-b.yData[n]),q.push([b.xData[n],v]),p.push(b.xData[n]),m.push(v);return{values:q,xData:p,yData:m}}}});""});t(k,"indicators/dema.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.correctFloat,
e=f.isArray;f=f.seriesType;var d=g.seriesTypes.ema;f("dema","ema",{},{init:function(){var c=arguments,a=this;l.isParentLoaded(d,"ema",a.type,function(b){b.prototype.init.apply(a,c)})},getEMA:function(c,a,b,e,h,q){return d.prototype.calculateEma(q||[],c,"undefined"===typeof h?1:h,this.chart.series[0].EMApercent,a,"undefined"===typeof e?-1:e,b)},getValues:function(c,a){var b=a.period,f=2*b,v=c.xData,q=c.yData,p=q?q.length:0,m=-1,n=[],l=[],x=[],g=0,A=[],y;c.EMApercent=2/(b+1);if(!(p<2*b-1)){e(q[0])&&
(m=a.index?a.index:0);c=d.prototype.accumulatePeriodPoints(b,m,q);a=c/b;c=0;for(y=b;y<p+2;y++){y<p+1&&(g=this.getEMA(q,k,a,m,y)[1],A.push(g));var k=g;if(y<f)c+=g;else{y===f&&(a=c/b);g=A[y-b-1];var w=this.getEMA([g],w,a)[1];var z=[v[y-2],h(2*g-w)];n.push(z);l.push(z[0]);x.push(z[1])}}return{values:n,xData:l,yData:x}}}});""});t(k,"indicators/tema.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.correctFloat,e=f.isArray;f=f.seriesType;
var d=g.seriesTypes.ema;f("tema","ema",{},{init:function(){var c=arguments,a=this;l.isParentLoaded(d,"ema",a.type,function(b){b.prototype.init.apply(a,c)})},getEMA:function(c,a,b,e,h,q){return d.prototype.calculateEma(q||[],c,"undefined"===typeof h?1:h,this.chart.series[0].EMApercent,a,"undefined"===typeof e?-1:e,b)},getTemaPoint:function(c,a,b,d){return[c[d-3],h(3*b.level1-3*b.level2+b.level3)]},getValues:function(c,a){var b=a.period,h=2*b,f=3*b,q=c.xData,p=c.yData,m=p?p.length:0,n=-1,l=[],x=[],
g=[],A=[],k=[],B,w,z={};c.EMApercent=2/(b+1);if(!(m<3*b-2)){e(p[0])&&(n=a.index?a.index:0);c=d.prototype.accumulatePeriodPoints(b,n,p);a=c/b;c=0;for(B=b;B<m+3;B++){B<m+1&&(z.level1=this.getEMA(p,D,a,n,B)[1],A.push(z.level1));var D=z.level1;if(B<h)c+=z.level1;else{B===h&&(a=c/b,c=0);z.level1=A[B-b-1];z.level2=this.getEMA([z.level1],J,a)[1];k.push(z.level2);var J=z.level2;if(B<f)c+=z.level2;else{B===f&&(a=c/b);B===m+1&&(z.level1=A[B-b-1],z.level2=this.getEMA([z.level1],J,a)[1],k.push(z.level2));z.level1=
A[B-b-2];z.level2=k[B-2*b-1];z.level3=this.getEMA([z.level2],z.prevLevel3,a)[1];if(w=this.getTemaPoint(q,f,z,B))l.push(w),x.push(w[0]),g.push(w[1]);z.prevLevel3=z.level3}}}return{values:l,xData:x,yData:g}}}});""});t(k,"indicators/trix.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.correctFloat;f=f.seriesType;var e=g.seriesTypes.tema;f("trix","tema",{},{init:function(){var d=arguments,c=this;l.isParentLoaded(e,"tema",c.type,function(a){a.prototype.init.apply(c,
d)})},getTemaPoint:function(d,c,a,b){if(b>c)var e=[d[b-3],0!==a.prevLevel3?h(a.level3-a.prevLevel3)/a.prevLevel3*100:null];return e}});""});t(k,"indicators/apo.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.error;f=f.seriesType;var e=g.seriesTypes.ema;f("apo","ema",{params:{periods:[10,20]}},{nameBase:"APO",nameComponents:["periods"],init:function(){var d=arguments,c=this;l.isParentLoaded(e,"ema",c.type,function(a){a.prototype.init.apply(c,
d)})},getValues:function(d,c){var a=c.periods,b=c.index;c=[];var f=[],v=[],q;if(2!==a.length||a[1]<=a[0])h('Error: "APO requires two periods. Notice, first period should be lower than the second one."');else{var p=e.prototype.getValues.call(this,d,{index:b,period:a[0]});d=e.prototype.getValues.call(this,d,{index:b,period:a[1]});if(p&&d){a=a[1]-a[0];for(q=0;q<d.yData.length;q++)b=p.yData[q+a]-d.yData[q],c.push([d.xData[q],b]),f.push(d.xData[q]),v.push(b);return{values:c,xData:f,yData:v}}}}});""});
t(k,"indicators/ichimoku-kinko-hyo.src.js",[k["parts/Globals.js"],k["parts/Color.js"],k["parts/Utilities.js"]],function(g,f,l){function h(a){return a.reduce(function(a,b){return Math.max(a,b[1])},-Infinity)}function e(a){return a.reduce(function(a,b){return Math.min(a,b[2])},Infinity)}function d(a){return{high:h(a),low:e(a)}}function c(a){var b,c,d,e,h;a.series.forEach(function(a){if(a.xData)for(e=a.xData,h=c=a.xIncrement?1:e.length-1;0<h;h--)if(d=e[h]-e[h-1],b===n||d<b)b=d});return b}function a(a,
b,c,d){if(a&&b&&c&&d){var e=b.plotX-a.plotX;b=b.plotY-a.plotY;var h=d.plotX-c.plotX;d=d.plotY-c.plotY;var m=a.plotX-c.plotX,f=a.plotY-c.plotY;c=(-b*m+e*f)/(-h*b+e*d);h=(h*f-d*m)/(-h*b+e*d);if(0<=c&&1>=c&&0<=h&&1>=h)return{plotX:a.plotX+h*e,plotY:a.plotY+h*b}}return!1}function b(a){var b=a.indicator;b.points=a.points;b.nextPoints=a.nextPoints;b.color=a.color;b.options=p(a.options.senkouSpan.styles,a.gap);b.graph=a.graph;b.fillGraph=!0;k.prototype.drawGraph.call(b)}var r=f.parse,v=l.defined,q=l.isArray,
p=l.merge,m=l.objectEach;f=l.seriesType;var n,k=g.seriesTypes.sma;g.approximations["ichimoku-averages"]=function(){var a=[],b;[].forEach.call(arguments,function(c,d){a.push(g.approximations.average(c));b=!b&&"undefined"===typeof a[d]});return b?void 0:a};f("ikh","sma",{params:{period:26,periodTenkan:9,periodSenkouSpanB:52},marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>TENKAN SEN: {point.tenkanSen:.3f}<br/>KIJUN SEN: {point.kijunSen:.3f}<br/>CHIKOU SPAN: {point.chikouSpan:.3f}<br/>SENKOU SPAN A: {point.senkouSpanA:.3f}<br/>SENKOU SPAN B: {point.senkouSpanB:.3f}<br/>'},
tenkanLine:{styles:{lineWidth:1,lineColor:void 0}},kijunLine:{styles:{lineWidth:1,lineColor:void 0}},chikouLine:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanA:{styles:{lineWidth:1,lineColor:void 0}},senkouSpanB:{styles:{lineWidth:1,lineColor:void 0}},senkouSpan:{styles:{fill:"rgba(255, 0, 0, 0.5)"}},dataGrouping:{approximation:"ichimoku-averages"}},{pointArrayMap:["tenkanSen","kijunSen","chikouSpan","senkouSpanA","senkouSpanB"],pointValKey:"tenkanSen",nameComponents:["periodSenkouSpanB","period",
"periodTenkan"],init:function(){k.prototype.init.apply(this,arguments);this.options=p({tenkanLine:{styles:{lineColor:this.color}},kijunLine:{styles:{lineColor:this.color}},chikouLine:{styles:{lineColor:this.color}},senkouSpanA:{styles:{lineColor:this.color,fill:r(this.color).setOpacity(.5).get()}},senkouSpanB:{styles:{lineColor:this.color,fill:r(this.color).setOpacity(.5).get()}},senkouSpan:{styles:{fill:r(this.color).setOpacity(.2).get()}}},this.options)},toYData:function(a){return[a.tenkanSen,a.kijunSen,
a.chikouSpan,a.senkouSpanA,a.senkouSpanB]},translate:function(){var a=this;k.prototype.translate.apply(a);a.points.forEach(function(b){a.pointArrayMap.forEach(function(c){v(b[c])&&(b["plot"+c]=a.yAxis.toPixels(b[c],!0),b.plotY=b["plot"+c],b.tooltipPos=[b.plotX,b["plot"+c]],b.isNull=!1)})})},drawGraph:function(){var c=this,d=c.points,e=d.length,h=c.options,f=c.graph,q=c.color,n={options:{gapSize:h.gapSize}},l=c.pointArrayMap.length,g=[[],[],[],[],[],[]],r={tenkanLine:g[0],kijunLine:g[1],chikouLine:g[2],
senkouSpanA:g[3],senkouSpanB:g[4],senkouSpan:g[5]},E=[],C=c.options.senkouSpan,t=C.color||C.styles.fill,L=C.negativeColor,M=[[],[]],O=[[],[]],P=0,K,Q,N;for(c.ikhMap=r;e--;){var G=d[e];for(K=0;K<l;K++)C=c.pointArrayMap[K],v(G[C])&&g[K].push({plotX:G.plotX,plotY:G["plot"+C],isNull:!1});L&&e!==d.length-1&&(C=r.senkouSpanB.length-1,G=a(r.senkouSpanA[C-1],r.senkouSpanA[C],r.senkouSpanB[C-1],r.senkouSpanB[C]),K={plotX:G.plotX,plotY:G.plotY,isNull:!1,intersectPoint:!0},G&&(r.senkouSpanA.splice(C,0,K),r.senkouSpanB.splice(C,
0,K),E.push(C)))}m(r,function(a,b){h[b]&&"senkouSpan"!==b&&(c.points=g[P],c.options=p(h[b].styles,n),c.graph=c["graph"+b],c.fillGraph=!1,c.color=q,k.prototype.drawGraph.call(c),c["graph"+b]=c.graph);P++});c.graphCollection&&c.graphCollection.forEach(function(a){c[a].destroy();delete c[a]});c.graphCollection=[];if(L&&r.senkouSpanA[0]&&r.senkouSpanB[0]){E.unshift(0);E.push(r.senkouSpanA.length-1);for(l=0;l<E.length-1;l++){C=E[l];G=E[l+1];e=r.senkouSpanB.slice(C,G+1);C=r.senkouSpanA.slice(C,G+1);if(1<=
Math.floor(e.length/2))if(G=Math.floor(e.length/2),e[G].plotY===C[G].plotY){for(N=K=G=0;N<e.length;N++)G+=e[N].plotY,K+=C[N].plotY;G=G>K?0:1}else G=e[G].plotY>C[G].plotY?0:1;else G=e[0].plotY>C[0].plotY?0:1;M[G]=M[G].concat(e);O[G]=O[G].concat(C)}["graphsenkouSpanColor","graphsenkouSpanNegativeColor"].forEach(function(a,d){M[d].length&&O[d].length&&(Q=0===d?t:L,b({indicator:c,points:M[d],nextPoints:O[d],color:Q,options:h,gap:n,graph:c[a]}),c[a]=c.graph,c.graphCollection.push(a))})}else b({indicator:c,
points:r.senkouSpanB,nextPoints:r.senkouSpanA,color:t,options:h,gap:n,graph:c.graphsenkouSpan}),c.graphsenkouSpan=c.graph;delete c.nextPoints;delete c.fillGraph;c.points=d;c.options=h;c.graph=f},getGraphPath:function(a){var b=[];a=a||this.points;if(this.fillGraph&&this.nextPoints){var c=k.prototype.getGraphPath.call(this,this.nextPoints);c[0]="L";var d=k.prototype.getGraphPath.call(this,a);c=c.slice(0,d.length);for(var e=c.length-1;0<e;e-=3)b.push(c[e-2],c[e-1],c[e]);d=d.concat(b)}else d=k.prototype.getGraphPath.apply(this,
arguments);return d},getValues:function(a,b){var e=b.period,h=b.periodTenkan;b=b.periodSenkouSpanB;var m=a.xData,f=a.yData,v=f&&f.length||0;a=c(a.xAxis);var l=[],p=[],r;if(!(m.length<=e)&&q(f[0])&&4===f[0].length){var g=m[0]-e*a;for(r=0;r<e;r++)p.push(g+r*a);for(r=0;r<v;r++){if(r>=h){var k=f.slice(r-h,r);k=d(k);k=(k.high+k.low)/2}if(r>=e){var x=f.slice(r-e,r);x=d(x);x=(x.high+x.low)/2;var E=(k+x)/2}if(r>=b){var u=f.slice(r-b,r);u=d(u);u=(u.high+u.low)/2}g=f[r][3];var t=m[r];l[r]===n&&(l[r]=[]);l[r+
e]===n&&(l[r+e]=[]);l[r+e][0]=k;l[r+e][1]=x;l[r+e][2]=n;l[r][2]=g;r<=e&&(l[r+e][3]=n,l[r+e][4]=n);l[r+2*e]===n&&(l[r+2*e]=[]);l[r+2*e][3]=E;l[r+2*e][4]=u;p.push(t)}for(r=1;r<=e;r++)p.push(t+r*a);return{values:l,xData:p,yData:l}}}});""});t(k,"indicators/keltner-channels.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/multipe-lines.js"]],function(g,f,l){var h=f.correctFloat,e=f.merge;f=f.seriesType;var d=g.seriesTypes.sma,c=g.seriesTypes.ema,a=g.seriesTypes.atr;f("keltnerchannels",
"sma",{params:{period:20,periodATR:10,multiplierATR:2},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1,lineColor:void 0}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Upper Channel: {point.top}<br/>EMA({series.options.params.period}): {point.middle}<br/>Lower Channel: {point.bottom}<br/>'},marker:{enabled:!1},dataGrouping:{approximation:"averages"},lineWidth:1},e(l,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",
nameBase:"Keltner Channels",nameComponents:["period","periodATR","multiplierATR"],linesApiNames:["topLine","bottomLine"],requiredIndicators:["ema","atr"],init:function(){d.prototype.init.apply(this,arguments);this.options=e({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},getValues:function(b,d){var e=d.period,f=d.periodATR,r=d.multiplierATR,m=b.yData;m=m?m.length:0;var n=[];d=c.prototype.getValues(b,{period:e,index:d.index});var l=a.prototype.getValues(b,
{period:f}),g=[],k=[],A;if(!(m<e)){for(A=e;A<=m;A++){var y=d.values[A-e];var B=l.values[A-f];var w=y[0];b=h(y[1]+r*B[1]);B=h(y[1]-r*B[1]);y=y[1];n.push([w,b,y,B]);g.push(w);k.push([b,y,B])}return{values:n,xData:g,yData:k}}}}));""});t(k,"indicators/macd.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){var l=f.correctFloat,h=f.defined,e=f.merge;f=f.seriesType;var d=g.seriesTypes.sma,c=g.seriesTypes.ema;f("macd","sma",{params:{shortPeriod:12,longPeriod:26,signalPeriod:9,period:26},
signalLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},macdLine:{zones:[],styles:{lineWidth:1,lineColor:void 0}},threshold:0,groupPadding:.1,pointPadding:.1,states:{hover:{halo:{size:0}}},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Value: {point.MACD}<br/>Signal: {point.signal}<br/>Histogram: {point.y}<br/>'},dataGrouping:{approximation:"averages"},minPointLength:0},{nameComponents:["longPeriod","shortPeriod","signalPeriod"],requiredIndicators:["ema"],
pointArrayMap:["y","signal","MACD"],parallelArrays:["x","y","signal","MACD"],pointValKey:"y",markerAttribs:g.noop,getColumnMetrics:g.seriesTypes.column.prototype.getColumnMetrics,crispCol:g.seriesTypes.column.prototype.crispCol,init:function(){d.prototype.init.apply(this,arguments);this.options&&(this.options=e({signalLine:{styles:{lineColor:this.color}},macdLine:{styles:{color:this.color}}},this.options),this.macdZones={zones:this.options.macdLine.zones,startIndex:0},this.signalZones={zones:this.macdZones.zones.concat(this.options.signalLine.zones),
startIndex:this.macdZones.zones.length},this.resetZones=!0)},toYData:function(a){return[a.y,a.signal,a.MACD]},translate:function(){var a=this,b=["plotSignal","plotMACD"];g.seriesTypes.column.prototype.translate.apply(a);a.points.forEach(function(c){[c.signal,c.MACD].forEach(function(d,e){null!==d&&(c[b[e]]=a.yAxis.toPixels(d,!0))})})},destroy:function(){this.graph=null;this.graphmacd=this.graphmacd&&this.graphmacd.destroy();this.graphsignal=this.graphsignal&&this.graphsignal.destroy();d.prototype.destroy.apply(this,
arguments)},drawPoints:g.seriesTypes.column.prototype.drawPoints,drawGraph:function(){for(var a=this,b=a.points,c=b.length,f=a.options,q=a.zones,l={options:{gapSize:f.gapSize}},m=[[],[]],n;c--;)n=b[c],h(n.plotMACD)&&m[0].push({plotX:n.plotX,plotY:n.plotMACD,isNull:!h(n.plotMACD)}),h(n.plotSignal)&&m[1].push({plotX:n.plotX,plotY:n.plotSignal,isNull:!h(n.plotMACD)});["macd","signal"].forEach(function(b,c){a.points=m[c];a.options=e(f[b+"Line"].styles,l);a.graph=a["graph"+b];a.currentLineZone=b+"Zones";
a.zones=a[a.currentLineZone].zones;d.prototype.drawGraph.call(a);a["graph"+b]=a.graph});a.points=b;a.options=f;a.zones=q;a.currentLineZone=null},getZonesGraphs:function(a){var b=d.prototype.getZonesGraphs.call(this,a),c=b;this.currentLineZone&&(c=b.splice(this[this.currentLineZone].startIndex+1),c.length?c.splice(0,0,a[0]):c=[a[0]]);return c},applyZones:function(){var a=this.zones;this.zones=this.signalZones.zones;d.prototype.applyZones.call(this);this.graphmacd&&this.options.macdLine.zones.length&&
this.graphmacd.hide();this.zones=a},getValues:function(a,b){var d=0,e=[],f=[],g=[];if(!(a.xData.length<b.longPeriod+b.signalPeriod)){var m=c.prototype.getValues(a,{period:b.shortPeriod});var n=c.prototype.getValues(a,{period:b.longPeriod});m=m.values;n=n.values;for(a=1;a<=m.length;a++)h(n[a-1])&&h(n[a-1][1])&&h(m[a+b.shortPeriod+1])&&h(m[a+b.shortPeriod+1][0])&&e.push([m[a+b.shortPeriod+1][0],0,null,m[a+b.shortPeriod+1][1]-n[a-1][1]]);for(a=0;a<e.length;a++)f.push(e[a][0]),g.push([0,null,e[a][3]]);
b=c.prototype.getValues({xData:f,yData:g},{period:b.signalPeriod,index:2});b=b.values;for(a=0;a<e.length;a++)e[a][0]>=b[0][0]&&(e[a][2]=b[d][1],g[a]=[0,b[d][1],e[a][3]],null===e[a][3]?(e[a][1]=0,g[a][0]=0):(e[a][1]=l(e[a][3]-b[d][1]),g[a][0]=l(e[a][3]-b[d][1])),d++);return{values:e,xData:f,yData:g}}}});""});t(k,"indicators/mfi.src.js",[k["parts/Utilities.js"]],function(g){function f(d){return d.reduce(function(c,a){return c+a})}function l(d){return(d[1]+d[2]+d[3])/3}var h=g.error,e=g.isArray;g=g.seriesType;
g("mfi","sma",{params:{period:14,volumeSeriesID:"volume",decimals:4}},{nameBase:"Money Flow Index",getValues:function(d,c){var a=c.period,b=d.xData,r=d.yData,g=r?r.length:0,q=c.decimals,p=1,m=d.chart.get(c.volumeSeriesID),n=m&&m.yData,k=[],x=[],u=[],A=[],y=[];if(!m)h("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,d.chart);else if(!(b.length<=a)&&e(r[0])&&4===r[0].length&&n){for(d=l(r[p]);p<a+1;)c=d,d=l(r[p]),c=d>=c,m=d*n[p],A.push(c?m:0),y.push(c?0:m),p++;for(a=p-1;a<g;a++)a>
p-1&&(A.shift(),y.shift(),c=d,d=l(r[a]),c=d>c,m=d*n[a],A.push(c?m:0),y.push(c?0:m)),c=f(y),m=f(A),c=m/c,c=parseFloat((100-100/(1+c)).toFixed(q)),k.push([b[a],c]),x.push(b[a]),u.push(c);return{values:k,xData:x,yData:u}}}});""});t(k,"indicators/momentum.src.js",[k["parts/Utilities.js"]],function(g){function f(h,e,d,c,a){d=d[c-1][3]-d[c-a-1][3];e=e[c-1];h.shift();return[e,d]}var l=g.isArray;g=g.seriesType;g("momentum","sma",{params:{period:14}},{nameBase:"Momentum",getValues:function(h,e){e=e.period;
var d=h.xData,c=(h=h.yData)?h.length:0,a=d[0],b=[],g=[],v=[];if(!(d.length<=e)&&l(h[0])){var q=h[0][3];q=[[a,q]];for(a=e+1;a<c;a++){var p=f(q,d,h,a,e,void 0);b.push(p);g.push(p[0]);v.push(p[1])}p=f(q,d,h,a,e,void 0);b.push(p);g.push(p[0]);v.push(p[1]);return{values:b,xData:g,yData:v}}}});""});t(k,"indicators/natr.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){f=f.seriesType;var l=g.seriesTypes.atr;f("natr","sma",{tooltip:{valueSuffix:"%"}},{requiredIndicators:["atr"],getValues:function(h,
e){var d=l.prototype.getValues.apply(this,arguments),c=d.values.length,a=e.period-1,b=h.yData,f=0;if(d){for(;f<c;f++)d.yData[f]=d.values[f][1]/b[a][3]*100,d.values[f][1]=d.yData[f],a++;return d}}});""});t(k,"indicators/pivot-points.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){function l(c,a){var b=c.series.pointArrayMap,e=b.length;for(d.prototype.pointClass.prototype[a].call(c);e--;)a="dataLabel"+b[e],c[a]&&c[a].element&&c[a].destroy(),c[a]=null}var h=f.defined,e=f.isArray;
f=f.seriesType;var d=g.seriesTypes.sma;f("pivotpoints","sma",{params:{period:28,algorithm:"standard"},marker:{enabled:!1},enableMouseTracking:!1,dataLabels:{enabled:!0,format:"{point.pivotLine}"},dataGrouping:{approximation:"averages"}},{nameBase:"Pivot Points",pointArrayMap:"R4 R3 R2 R1 P S1 S2 S3 S4".split(" "),pointValKey:"P",toYData:function(c){return[c.P]},translate:function(){var c=this;d.prototype.translate.apply(c);c.points.forEach(function(a){c.pointArrayMap.forEach(function(b){h(a[b])&&
(a["plot"+b]=c.yAxis.toPixels(a[b],!0))})});c.plotEndPoint=c.xAxis.toPixels(c.endPoint,!0)},getGraphPath:function(c){for(var a=this,b=c.length,e=[[],[],[],[],[],[],[],[],[]],f=[],l=a.plotEndPoint,g=a.pointArrayMap.length,m,n,k;b--;){n=c[b];for(k=0;k<g;k++)m=a.pointArrayMap[k],h(n[m])&&e[k].push({plotX:n.plotX,plotY:n["plot"+m],isNull:!1},{plotX:l,plotY:n["plot"+m],isNull:!1},{plotX:l,plotY:null,isNull:!0});l=n.plotX}e.forEach(function(c){f=f.concat(d.prototype.getGraphPath.call(a,c))});return f},
drawDataLabels:function(){var c=this,a=c.pointArrayMap,b,e,h;if(c.options.dataLabels.enabled){var f=c.points.length;a.concat([!1]).forEach(function(l,m){for(h=f;h--;)e=c.points[h],l?(e.y=e[l],e.pivotLine=l,e.plotY=e["plot"+l],b=e["dataLabel"+l],m&&(e["dataLabel"+a[m-1]]=e.dataLabel),e.dataLabels||(e.dataLabels=[]),e.dataLabels[0]=e.dataLabel=b=b&&b.element?b:null):e["dataLabel"+a[m-1]]=e.dataLabel;d.prototype.drawDataLabels.apply(c,arguments)})}},getValues:function(c,a){var b=a.period,d=c.xData,h=
(c=c.yData)?c.length:0;a=this[a.algorithm+"Placement"];var f=[],l=[],m=[],n;if(!(d.length<b)&&e(c[0])&&4===c[0].length){for(n=b+1;n<=h+b;n+=b){var g=d.slice(n-b-1,n);var k=c.slice(n-b-1,n);var u=g.length;var A=g[u-1];k=this.getPivotAndHLC(k);k=a(k);k=f.push([A].concat(k));l.push(A);m.push(f[k-1].slice(1))}this.endPoint=g[0]+(A-g[0])/u*b;return{values:f,xData:l,yData:m}}},getPivotAndHLC:function(c){var a=-Infinity,b=Infinity,d=c[c.length-1][3];c.forEach(function(c){a=Math.max(a,c[1]);b=Math.min(b,
c[2])});return[(a+b+d)/3,a,b,d]},standardPlacement:function(c){var a=c[1]-c[2];return[null,null,c[0]+a,2*c[0]-c[2],c[0],2*c[0]-c[1],c[0]-a,null,null]},camarillaPlacement:function(c){var a=c[1]-c[2];return[c[3]+1.5*a,c[3]+1.25*a,c[3]+1.1666*a,c[3]+1.0833*a,c[0],c[3]-1.0833*a,c[3]-1.1666*a,c[3]-1.25*a,c[3]-1.5*a]},fibonacciPlacement:function(c){var a=c[1]-c[2];return[null,c[0]+a,c[0]+.618*a,c[0]+.382*a,c[0],c[0]-.382*a,c[0]-.618*a,c[0]-a,null]}},{destroyElements:function(){l(this,"destroyElements")},
destroy:function(){l(this,"destroyElements")}});""});t(k,"indicators/ppo.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){var h=f.correctFloat,e=f.error;f=f.seriesType;var d=g.seriesTypes.ema;f("ppo","ema",{params:{periods:[12,26]}},{nameBase:"PPO",nameComponents:["periods"],init:function(){var c=arguments,a=this;l.isParentLoaded(d,"ema",a.type,function(b){b.prototype.init.apply(a,c)})},getValues:function(c,a){var b=a.periods,f=a.index;a=[];
var l=[],g=[],p;if(2!==b.length||b[1]<=b[0])e('Error: "PPO requires two periods. Notice, first period should be lower than the second one."');else{var m=d.prototype.getValues.call(this,c,{index:f,period:b[0]});c=d.prototype.getValues.call(this,c,{index:f,period:b[1]});if(m&&c){b=b[1]-b[0];for(p=0;p<c.yData.length;p++)f=h((m.yData[p+b]-c.yData[p])/c.yData[p]*100),a.push([c.xData[p],f]),l.push(c.xData[p]),g.push(f);return{values:a,xData:l,yData:g}}}}});""});t(k,"mixins/reduce-array.js",[k["parts/Globals.js"]],
function(g){var f=g.reduce;return{minInArray:function(l,h){return f(l,function(e,d){return Math.min(e,d[h])},Number.MAX_VALUE)},maxInArray:function(l,h){return f(l,function(e,d){return Math.max(e,d[h])},-Number.MAX_VALUE)},getArrayExtremes:function(l,h,e){return f(l,function(d,c){return[Math.min(d[0],c[h]),Math.max(d[1],c[e])]},[Number.MAX_VALUE,-Number.MAX_VALUE])}}});t(k,"indicators/price-channel.src.js",[k["parts/Utilities.js"],k["mixins/reduce-array.js"],k["mixins/multipe-lines.js"]],function(g,
f,l){var h=g.merge;g=g.seriesType;var e=f.getArrayExtremes;g("pc","sma",{params:{period:20},lineWidth:1,topLine:{styles:{lineColor:"#90ed7d",lineWidth:1}},bottomLine:{styles:{lineColor:"#f45b5b",lineWidth:1}},dataGrouping:{approximation:"averages"}},h(l,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Price Channel",nameComponents:["period"],linesApiNames:["topLine","bottomLine"],getValues:function(d,c){c=c.period;var a=d.xData,b=(d=d.yData)?d.length:0,f=[],h=[],l=[],g;if(!(b<
c)){for(g=c;g<=b;g++){var m=a[g-1];var n=d.slice(g-c,g);var k=e(n,2,1);n=k[1];var x=k[0];k=(n+x)/2;f.push([m,n,k,x]);h.push(m);l.push([n,k,x])}return{values:f,xData:h,yData:l}}}}));""});t(k,"indicators/price-envelopes.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){var l=f.isArray,h=f.merge;f=f.seriesType;var e=g.seriesTypes.sma;f("priceenvelopes","sma",{marker:{enabled:!1},tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>Top: {point.top}<br/>Middle: {point.middle}<br/>Bottom: {point.bottom}<br/>'},
params:{period:20,topBand:.1,bottomBand:.1},bottomLine:{styles:{lineWidth:1,lineColor:void 0}},topLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},{nameComponents:["period","topBand","bottomBand"],nameBase:"Price envelopes",pointArrayMap:["top","middle","bottom"],parallelArrays:["x","y","top","bottom"],pointValKey:"middle",init:function(){e.prototype.init.apply(this,arguments);this.options=h({topLine:{styles:{lineColor:this.color}},bottomLine:{styles:{lineColor:this.color}}},this.options)},
toYData:function(d){return[d.top,d.middle,d.bottom]},translate:function(){var d=this,c=["plotTop","plotMiddle","plotBottom"];e.prototype.translate.apply(d);d.points.forEach(function(a){[a.top,a.middle,a.bottom].forEach(function(b,e){null!==b&&(a[c[e]]=d.yAxis.toPixels(b,!0))})})},drawGraph:function(){for(var d=this,c=d.points,a=c.length,b=d.options,f=d.graph,l={options:{gapSize:b.gapSize}},g=[[],[]],p;a--;)p=c[a],g[0].push({plotX:p.plotX,plotY:p.plotTop,isNull:p.isNull}),g[1].push({plotX:p.plotX,
plotY:p.plotBottom,isNull:p.isNull});["topLine","bottomLine"].forEach(function(a,c){d.points=g[c];d.options=h(b[a].styles,l);d.graph=d["graph"+a];e.prototype.drawGraph.call(d);d["graph"+a]=d.graph});d.points=c;d.options=b;d.graph=f;e.prototype.drawGraph.call(d)},getValues:function(d,c){var a=c.period,b=c.topBand,f=c.bottomBand,h=d.xData,g=(d=d.yData)?d.length:0,p=[],m=[],n=[],k;if(!(h.length<a)&&l(d[0])&&4===d[0].length){for(k=a;k<=g;k++){var x=h.slice(k-a,k);var u=d.slice(k-a,k);u=e.prototype.getValues.call(this,
{xData:x,yData:u},c);x=u.xData[0];u=u.yData[0];var A=u*(1+b);var y=u*(1-f);p.push([x,A,u,y]);m.push(x);n.push([A,u,y])}return{values:p,xData:m,yData:n}}}});""});t(k,"indicators/psar.src.js",[k["parts/Utilities.js"]],function(g){g=g.seriesType;g("psar","sma",{lineWidth:0,marker:{enabled:!0},states:{hover:{lineWidthPlus:0}},params:{initialAccelerationFactor:.02,maxAccelerationFactor:.2,increment:.02,index:2,decimals:4}},{nameComponents:!1,getValues:function(f,l){var h=f.xData;f=f.yData;var e=f[0][1],
d=l.maxAccelerationFactor,c=l.increment,a=l.initialAccelerationFactor,b=f[0][2],g=l.decimals,k=l.index,q=[],p=[],m=[],n=1,E;if(!(k>=f.length)){for(E=0;E<k;E++)e=Math.max(f[E][1],e),b=Math.min(f[E][2],parseFloat(b.toFixed(g)));var x=f[E][1]>b?1:-1;l=l.initialAccelerationFactor;var u=l*(e-b);q.push([h[k],b]);p.push(h[k]);m.push(parseFloat(b.toFixed(g)));for(E=k+1;E<f.length;E++){k=f[E-1][2];var A=f[E-2][2];var y=f[E-1][1];var B=f[E-2][1];var w=f[E][1];var z=f[E][2];null!==A&&null!==B&&null!==k&&null!==
y&&null!==w&&null!==z&&(b=x===n?1===x?b+u<Math.min(A,k)?b+u:Math.min(A,k):b+u>Math.max(B,y)?b+u:Math.max(B,y):e,k=1===x?w>e?w:e:z<e?z:e,w=1===n&&z>b||-1===n&&w>b?1:-1,n=w,u=k,z=c,A=d,y=a,l=n===x?1===n&&u>e?l===A?A:parseFloat((l+z).toFixed(2)):-1===n&&u<e?l===A?A:parseFloat((l+z).toFixed(2)):l:y,e=k-b,u=l*e,q.push([h[E],parseFloat(b.toFixed(g))]),p.push(h[E]),m.push(parseFloat(b.toFixed(g))),n=x,x=w,e=k)}return{values:q,xData:p,yData:m}}}});""});t(k,"indicators/roc.src.js",[k["parts/Utilities.js"]],
function(g){var f=g.isArray;g=g.seriesType;g("roc","sma",{params:{index:3,period:9}},{nameBase:"Rate of Change",getValues:function(g,h){var e=h.period,d=g.xData,c=(g=g.yData)?g.length:0,a=[],b=[],l=[],k=-1;if(!(d.length<=e)){f(g[0])&&(k=h.index);for(h=e;h<c;h++){var q=0>k?(q=g[h-e])?(g[h]-q)/q*100:null:(q=g[h-e][k])?(g[h][k]-q)/q*100:null;q=[d[h],q];a.push(q);b.push(q[0]);l.push(q[1])}return{values:a,xData:b,yData:l}}}});""});t(k,"indicators/rsi.src.js",[k["parts/Utilities.js"]],function(g){var f=
g.isArray;g=g.seriesType;g("rsi","sma",{params:{period:14,decimals:4}},{getValues:function(g,h){var e=h.period,d=g.xData,c=(g=g.yData)?g.length:0;h=h.decimals;var a=1,b=[],l=[],k=[],q=0,p=0,m;if(!(d.length<e)&&f(g[0])&&4===g[0].length){for(;a<e;){var n=parseFloat((g[a][3]-g[a-1][3]).toFixed(h));0<n?q+=n:p+=Math.abs(n);a++}var E=parseFloat((q/(e-1)).toFixed(h));for(m=parseFloat((p/(e-1)).toFixed(h));a<c;a++)n=parseFloat((g[a][3]-g[a-1][3]).toFixed(h)),0<n?(q=n,p=0):(q=0,p=Math.abs(n)),E=parseFloat(((E*
(e-1)+q)/e).toFixed(h)),m=parseFloat(((m*(e-1)+p)/e).toFixed(h)),q=0===m?100:0===E?0:parseFloat((100-100/(1+E/m)).toFixed(h)),b.push([d[a],q]),l.push(d[a]),k.push(q);return{values:b,xData:l,yData:k}}}});""});t(k,"indicators/stochastic.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/reduce-array.js"],k["mixins/multipe-lines.js"]],function(g,f,l,h){var e=f.isArray,d=f.merge;f=f.seriesType;var c=g.seriesTypes.sma,a=l.getArrayExtremes;f("stochastic","sma",{params:{periods:[14,3]},marker:{enabled:!1},
tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span><b> {series.name}</b><br/>%K: {point.y}<br/>%D: {point.smoothed}<br/>'},smoothedLine:{styles:{lineWidth:1,lineColor:void 0}},dataGrouping:{approximation:"averages"}},d(h,{nameComponents:["periods"],nameBase:"Stochastic",pointArrayMap:["y","smoothed"],parallelArrays:["x","y","smoothed"],pointValKey:"y",linesApiNames:["smoothedLine"],init:function(){c.prototype.init.apply(this,arguments);this.options=d({smoothedLine:{styles:{lineColor:this.color}}},
this.options)},getValues:function(b,d){var f=d.periods[0];d=d.periods[1];var h=b.xData,g=(b=b.yData)?b.length:0,m=[],l=[],k=[],r=null,u;if(!(g<f)&&e(b[0])&&4===b[0].length){for(u=f-1;u<g;u++){var A=b.slice(u-f+1,u+1);var y=a(A,2,1);var B=y[0];A=b[u][3]-B;B=y[1]-B;A=A/B*100;l.push(h[u]);k.push([A,null]);u>=f-1+(d-1)&&(r=c.prototype.getValues.call(this,{xData:l.slice(-d),yData:k.slice(-d)},{period:d}),r=r.yData[0]);m.push([h[u],A,r]);k[k.length-1][1]=r}return{values:m,xData:l,yData:k}}}}));""});t(k,
"indicators/slow-stochastic.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/indicator-required.js"]],function(g,f,l){f=f.seriesType;var h=g.seriesTypes;f("slowstochastic","stochastic",{params:{periods:[14,3,3]}},{nameBase:"Slow Stochastic",init:function(){var e=arguments,d=this;l.isParentLoaded(g.seriesTypes.stochastic,"stochastic",d.type,function(c){c.prototype.init.apply(d,e)})},getValues:function(e,d){var c=d.periods,a=h.stochastic.prototype.getValues.call(this,e,d);e={values:[],
xData:[],yData:[]};d=0;if(a){e.xData=a.xData.slice(c[1]-1);a=a.yData.slice(c[1]-1);var b=h.sma.prototype.getValues.call(this,{xData:e.xData,yData:a},{index:1,period:c[2]});if(b){for(var f=e.xData.length;d<f;d++)e.yData[d]=[a[d][1],b.yData[d-c[2]+1]||null],e.values[d]=[e.xData[d],a[d][1],b.yData[d-c[2]+1]||null];return e}}}});""});t(k,"indicators/supertrend.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],function(g,f){function l(a,c,b){return{index:c,close:a.yData[c][b],x:a.xData[c]}}var h=
f.correctFloat,e=f.merge,d=f.seriesType,c=f.isArray,a=f.objectEach,b=g.seriesTypes.atr,k=g.seriesTypes.sma;d("supertrend","sma",{params:{multiplier:3,period:10},risingTrendColor:"#06B535",fallingTrendColor:"#F21313",changeTrendLine:{styles:{lineWidth:1,lineColor:"#333333",dashStyle:"LongDash"}}},{nameBase:"Supertrend",nameComponents:["multiplier","period"],requiredIndicators:["atr"],init:function(){k.prototype.init.apply(this,arguments);var a=this.options;a.cropThreshold=this.linkedParent.options.cropThreshold-
(a.params.period-1)},drawGraph:function(){var c=this,b=c.options,d=c.linkedParent,f=d?d.points:[],h=c.points,g=c.graph,r=h.length,u=f.length-r;u=0<u?u:0;for(var A={options:{gapSize:b.gapSize}},y={top:[],bottom:[],intersect:[]},B={top:{styles:{lineWidth:b.lineWidth,lineColor:b.fallingTrendColor||b.color,dashStyle:b.dashStyle}},bottom:{styles:{lineWidth:b.lineWidth,lineColor:b.risingTrendColor||b.color,dashStyle:b.dashStyle}},intersect:b.changeTrendLine},w,z,D,t,F,H,C,I;r--;)w=h[r],z=h[r-1],D=f[r-1+
u],t=f[r-2+u],F=f[r+u],H=f[r+u+1],C=w.options.color,I={x:w.x,plotX:w.plotX,plotY:w.plotY,isNull:!1},!t&&D&&d.yData[D.index-1]&&(t=l(d,D.index-1,3)),!H&&F&&d.yData[F.index+1]&&(H=l(d,F.index+1,3)),!D&&t&&d.yData[t.index+1]?D=l(d,t.index+1,3):!D&&F&&d.yData[F.index-1]&&(D=l(d,F.index-1,3)),w&&D&&F&&t&&w.x!==D.x&&(w.x===F.x?(t=D,D=F):w.x===t.x?(D=t,t={close:d.yData[D.index-1][3],x:d.xData[D.index-1]}):H&&w.x===H.x&&(D=H,t=F)),z&&t&&D?(F={x:z.x,plotX:z.plotX,plotY:z.plotY,isNull:!1},w.y>=D.close&&z.y>=
t.close?(w.color=C||b.fallingTrendColor||b.color,y.top.push(I)):w.y<D.close&&z.y<t.close?(w.color=C||b.risingTrendColor||b.color,y.bottom.push(I)):(y.intersect.push(I),y.intersect.push(F),y.intersect.push(e(F,{isNull:!0})),w.y>=D.close&&z.y<t.close?(w.color=C||b.fallingTrendColor||b.color,z.color=C||b.risingTrendColor||b.color,y.top.push(I),y.top.push(e(F,{isNull:!0}))):w.y<D.close&&z.y>=t.close&&(w.color=C||b.risingTrendColor||b.color,z.color=C||b.fallingTrendColor||b.color,y.bottom.push(I),y.bottom.push(e(F,
{isNull:!0}))))):D&&(w.y>=D.close?(w.color=C||b.fallingTrendColor||b.color,y.top.push(I)):(w.color=C||b.risingTrendColor||b.color,y.bottom.push(I)));a(y,function(a,b){c.points=a;c.options=e(B[b].styles,A);c.graph=c["graph"+b+"Line"];k.prototype.drawGraph.call(c);c["graph"+b+"Line"]=c.graph});c.points=h;c.options=b;c.graph=g},getValues:function(a,d){var e=d.period;d=d.multiplier;var f=a.xData,g=a.yData,l=[],k=[],q=[],r=0===e?0:e-1,v=[],B=[],w;if(!(f.length<=e||!c(g[0])||4!==g[0].length||0>e)){a=b.prototype.getValues.call(this,
a,{period:e}).yData;for(w=0;w<a.length;w++){var z=g[r+w];var t=g[r+w-1]||[];var J=v[w-1];var F=B[w-1];var H=q[w-1];0===w&&(J=F=H=0);e=h((z[1]+z[2])/2+d*a[w]);var C=h((z[1]+z[2])/2-d*a[w]);v[w]=e<J||t[3]>J?e:J;B[w]=C>F||t[3]<F?C:F;if(H===J&&z[3]<v[w]||H===F&&z[3]<B[w])var I=v[w];else if(H===J&&z[3]>v[w]||H===F&&z[3]>B[w])I=B[w];l.push([f[r+w],I]);k.push(f[r+w]);q.push(I)}return{values:l,xData:k,yData:q}}}});""});t(k,"indicators/volume-by-price.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"]],
function(g,f){var l=f.addEvent,h=f.animObject,e=f.arrayMax,d=f.arrayMin,c=f.correctFloat,a=f.error,b=f.extend,k=f.isArray;f=f.seriesType;var v=Math.abs,q=g.noop,p=g.seriesTypes.column.prototype;f("vbp","sma",{params:{ranges:12,volumeSeriesID:"volume"},zoneLines:{enabled:!0,styles:{color:"#0A9AC9",dashStyle:"LongDash",lineWidth:1}},volumeDivision:{enabled:!0,styles:{positiveColor:"rgba(144, 237, 125, 0.8)",negativeColor:"rgba(244, 91, 91, 0.8)"}},animationLimit:1E3,enableMouseTracking:!1,pointPadding:0,
zIndex:-1,crisp:!0,dataGrouping:{enabled:!1},dataLabels:{allowOverlap:!0,enabled:!0,format:"P: {point.volumePos:.2f} | N: {point.volumeNeg:.2f}",padding:0,style:{fontSize:"7px"},verticalAlign:"top"}},{nameBase:"Volume by Price",bindTo:{series:!1,eventName:"afterSetExtremes"},calculateOn:"render",markerAttribs:q,drawGraph:q,getColumnMetrics:p.getColumnMetrics,crispCol:p.crispCol,init:function(a){g.seriesTypes.sma.prototype.init.apply(this,arguments);var b=this.options.params;var c=this.linkedParent;
b=a.get(b.volumeSeriesID);this.addCustomEvents(c,b);return this},addCustomEvents:function(a,b){function c(){d.chart.redraw();d.setData([]);d.zoneStarts=[];d.zoneLinesSVG&&(d.zoneLinesSVG.destroy(),delete d.zoneLinesSVG)}var d=this;d.dataEventsToUnbind.push(l(a,"remove",function(){c()}));b&&d.dataEventsToUnbind.push(l(b,"remove",function(){c()}));return d},animate:function(a){var c=this,d={};g.svg&&!a&&(d.translateX=c.yAxis.pos,c.group.animate(d,b(h(c.options.animation),{step:function(a,b){c.group.attr({scaleX:Math.max(.001,
b.pos)})}})),c.animate=null)},drawPoints:function(){this.options.volumeDivision.enabled&&(this.posNegVolume(!0,!0),p.drawPoints.apply(this,arguments),this.posNegVolume(!1,!1));p.drawPoints.apply(this,arguments)},posNegVolume:function(a,b){var c=b?["positive","negative"]:["negative","positive"],d=this.options.volumeDivision,e=this.points.length,f=[],h=[],g=0,l;a?(this.posWidths=f,this.negWidths=h):(f=this.posWidths,h=this.negWidths);for(;g<e;g++){var m=this.points[g];m[c[0]+"Graphic"]=m.graphic;m.graphic=
m[c[1]+"Graphic"];if(a){var k=m.shapeArgs.width;var n=this.priceZones[g];(l=n.wholeVolumeData)?(f.push(k/l*n.positiveVolumeData),h.push(k/l*n.negativeVolumeData)):(f.push(0),h.push(0))}m.color=b?d.styles.positiveColor:d.styles.negativeColor;m.shapeArgs.width=b?this.posWidths[g]:this.negWidths[g];m.shapeArgs.x=b?m.shapeArgs.x:this.posWidths[g]}},translate:function(){var a=this,b=a.options,d=a.chart,f=a.yAxis,h=f.min,g=a.options.zoneLines,l=a.priceZones,k=0,q,r,t;p.translate.apply(a);var J=a.points;
if(J.length){var F=.5>b.pointPadding?b.pointPadding:.1;b=a.volumeDataArray;var H=e(b);var C=d.plotWidth/2;var I=d.plotTop;var L=v(f.toPixels(h)-f.toPixels(h+a.rangeStep));var M=v(f.toPixels(h)-f.toPixels(h+a.rangeStep));F&&(h=v(L*(1-2*F)),k=v((L-h)/2),L=v(h));J.forEach(function(b,d){r=b.barX=b.plotX=0;t=b.plotY=f.toPixels(l[d].start)-I-(f.reversed?L-M:L)-k;q=c(C*l[d].wholeVolumeData/H);b.pointWidth=q;b.shapeArgs=a.crispCol.apply(a,[r,t,q,L]);b.volumeNeg=l[d].negativeVolumeData;b.volumePos=l[d].positiveVolumeData;
b.volumeAll=l[d].wholeVolumeData});g.enabled&&a.drawZones(d,f,a.zoneStarts,g.styles)}},getValues:function(b,c){var d=b.processedXData,e=b.processedYData,f=this.chart,h=c.ranges,g=[],l=[],m=[],n;if(b.chart)if(n=f.get(c.volumeSeriesID))if((c=k(e[0]))&&4!==e[0].length)a("Type of "+b.name+" series is different than line, OHLC or candlestick.",!0,f);else return(this.priceZones=this.specifyZones(c,d,e,h,n)).forEach(function(a,b){g.push([a.x,a.end]);l.push(g[b][0]);m.push(g[b][1])}),{values:g,xData:l,yData:m};
else a("Series "+c.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,f);else a("Base series not found! In case it has been removed, add a new one.",!0,f)},specifyZones:function(a,b,f,h,g){if(a){var l=f.length;for(var k=f[0][3],m=k,n=1,q;n<l;n++)q=f[n][3],q<k&&(k=q),q>m&&(m=q);l={min:k,max:m}}else l=!1;l=(k=l)?k.min:d(f);q=k?k.max:e(f);k=this.zoneStarts=[];m=[];var r=0;n=1;if(!l||!q)return this.points.length&&(this.setData([]),this.zoneStarts=[],this.zoneLinesSVG.destroy()),[];var p=this.rangeStep=
c(q-l)/h;for(k.push(l);r<h-1;r++)k.push(c(k[r]+p));k.push(q);for(h=k.length;n<h;n++)m.push({index:n-1,x:b[0],start:k[n-1],end:k[n]});return this.volumePerZone(a,m,g,b,f)},volumePerZone:function(a,b,c,d,e){var f=this,h=c.processedXData,g=c.processedYData,l=b.length-1,k=e.length;c=g.length;var m,n,q,r,p;v(k-c)&&(d[0]!==h[0]&&g.unshift(0),d[k-1]!==h[c-1]&&g.push(0));f.volumeDataArray=[];b.forEach(function(b){b.wholeVolumeData=0;b.positiveVolumeData=0;for(p=b.negativeVolumeData=0;p<k;p++)q=n=!1,r=a?e[p][3]:
e[p],m=p?a?e[p-1][3]:e[p-1]:r,r<=b.start&&0===b.index&&(n=!0),r>=b.end&&b.index===l&&(q=!0),(r>b.start||n)&&(r<b.end||q)&&(b.wholeVolumeData+=g[p],m>r?b.negativeVolumeData+=g[p]:b.positiveVolumeData+=g[p]);f.volumeDataArray.push(b.wholeVolumeData)});return b},drawZones:function(a,b,c,d){var e=a.renderer,f=this.zoneLinesSVG,h=[],g=a.plotWidth,l=a.plotTop,k;c.forEach(function(c){k=b.toPixels(c)-l;h=h.concat(a.renderer.crispLine(["M",0,k,"L",g,k],d.lineWidth))});f?f.animate({d:h}):f=this.zoneLinesSVG=
e.path(h).attr({"stroke-width":d.lineWidth,stroke:d.color,dashstyle:d.dashStyle,zIndex:this.group.zIndex+.1}).add(this.group)}},{destroy:function(){this.negativeGraphic&&(this.negativeGraphic=this.negativeGraphic.destroy());return g.Point.prototype.destroy.apply(this,arguments)}});""});t(k,"indicators/vwap.src.js",[k["parts/Utilities.js"]],function(g){var f=g.error,l=g.isArray;g=g.seriesType;g("vwap","sma",{params:{period:30,volumeSeriesID:"volume"}},{getValues:function(h,e){var d=h.chart,c=h.xData;
h=h.yData;var a=e.period,b=!0,g;if(g=d.get(e.volumeSeriesID))return l(h[0])||(b=!1),this.calculateVWAPValues(b,c,h,g,a);f("Series "+e.volumeSeriesID+" not found! Check `volumeSeriesID`.",!0,d)},calculateVWAPValues:function(f,e,d,c,a){var b=c.yData,h=c.xData.length,g=e.length;c=[];var l=[],k=[],m=[],n=[],t;h=g<=h?g:h;for(t=g=0;g<h;g++){var x=f?(d[g][1]+d[g][2]+d[g][3])/3:d[g];x*=b[g];x=t?c[g-1]+x:x;var u=t?l[g-1]+b[g]:b[g];c.push(x);l.push(u);n.push([e[g],x/u]);k.push(n[g][0]);m.push(n[g][1]);t++;
t===a&&(t=0)}return{values:n,xData:k,yData:m}}});""});t(k,"indicators/williams-r.src.js",[k["parts/Utilities.js"],k["mixins/reduce-array.js"]],function(g,f){var l=g.isArray;g=g.seriesType;var h=f.getArrayExtremes;g("williamsr","sma",{params:{period:14}},{nameBase:"Williams %R",getValues:function(e,d){d=d.period;var c=e.xData,a=(e=e.yData)?e.length:0,b=[],f=[],g=[],k;if(!(c.length<d)&&l(e[0])&&4===e[0].length){for(k=d-1;k<a;k++){var p=e.slice(k-d+1,k+1);var m=h(p,2,1);p=m[0];m=m[1];var n=e[k][3];p=
(m-n)/(m-p)*-100;c[k]&&(b.push([c[k],p]),f.push(c[k]),g.push(p))}return{values:b,xData:f,yData:g}}}});""});t(k,"indicators/wma.src.js",[k["parts/Utilities.js"]],function(g){function f(e,d){d*=(d+1)/2;return e.reduce(function(c,a,b){return[null,c[1]+a[1]*(b+1)]})[1]/d}function l(e,d,c,a){c=f(e,e.length);d=d[a-1];e.shift();return[d,c]}var h=g.isArray;g=g.seriesType;g("wma","sma",{params:{index:3,period:9}},{getValues:function(e,d){var c=d.period,a=e.xData,b=(e=e.yData)?e.length:0,f=1,g=a[0],k=e[0],
p=[],m=[],n=[],t=-1;if(!(a.length<c)){h(e[0])&&(t=d.index,k=e[0][t]);for(d=[[g,k]];f!==c;)d.push([a[f],0>t?e[f]:e[f][t]]),f++;for(c=f;c<b;c++)f=l(d,a,e,c),p.push(f),m.push(f[0]),n.push(f[1]),d.push([a[c],0>t?e[c]:e[c][t]]);f=l(d,a,e,c);p.push(f);m.push(f[0]);n.push(f[1]);return{values:p,xData:m,yData:n}}}});""});t(k,"indicators/zigzag.src.js",[k["parts/Utilities.js"]],function(g){g=g.seriesType;g("zigzag","sma",{params:{lowIndex:2,highIndex:1,deviation:1}},{nameComponents:["deviation"],nameSuffixes:["%"],
nameBase:"Zig Zag",getValues:function(f,g){var h=g.lowIndex,e=g.highIndex,d=g.deviation/100;g=1+d;var c=1-d;d=f.xData;var a=f.yData;f=a?a.length:0;var b=[],k=[],l=[],q,p,m=!1,n=!1;if(!(!d||1>=d.length||f&&(void 0===a[0][h]||void 0===a[0][e]))){var t=a[0][h];var x=a[0][e];for(q=1;q<f;q++){if(a[q][h]<=x*c){b.push([d[0],x]);var u=[d[q],a[q][h]];m=p=!0}else a[q][e]>=t*g&&(b.push([d[0],t]),u=[d[q],a[q][e]],p=!1,m=!0);if(m){k.push(b[0][0]);l.push(b[0][1]);var A=q++;q=f}}for(q=A;q<f;q++)p?(a[q][h]<=u[1]&&
(u=[d[q],a[q][h]]),a[q][e]>=u[1]*g&&(n=e)):(a[q][e]>=u[1]&&(u=[d[q],a[q][e]]),a[q][h]<=u[1]*c&&(n=h)),!1!==n&&(b.push(u),k.push(u[0]),l.push(u[1]),u=[d[q],a[q][n]],p=!p,n=!1);h=b.length;0!==h&&b[h-1][0]<d[f-1]&&(b.push(u),k.push(u[0]),l.push(u[1]));return{values:b,xData:k,yData:l}}}});""});t(k,"indicators/regressions.src.js",[k["parts/Utilities.js"]],function(g){var f=g.isArray;g=g.seriesType;g("linearRegression","sma",{params:{xAxisUnit:void 0},tooltip:{valueDecimals:4}},{nameBase:"Linear Regression Indicator",
getRegressionLineParameters:function(g,h){var e=this.options.params.index,d=function(a,b){return f(a)?a[b]:a},c=g.reduce(function(a,b){return b+a},0),a=h.reduce(function(a,b){return d(b,e)+a},0);c/=g.length;a/=h.length;var b=0,k=0,l;for(l=0;l<g.length;l++){var q=g[l]-c;var p=d(h[l],e)-a;b+=q*p;k+=Math.pow(q,2)}g=k?b/k:0;return{slope:g,intercept:a-g*c}},getEndPointY:function(f,g){return f.slope*g+f.intercept},transformXData:function(f,g){var e=f[0];return f.map(function(d){return(d-e)/g})},findClosestDistance:function(f){var g,
e;for(e=1;e<f.length-1;e++){var d=f[e]-f[e-1];0<d&&("undefined"===typeof g||d<g)&&(g=d)}return g},getValues:function(f,g){var e=f.xData;f=f.yData;g=g.period;var d,c={xData:[],yData:[],values:[]},a=this.options.params.xAxisUnit||this.findClosestDistance(e);for(d=g-1;d<=e.length-1;d++){var b=d-g+1;var h=d+1;var k=e[d];var l=e.slice(b,h);b=f.slice(b,h);h=this.transformXData(l,a);l=this.getRegressionLineParameters(h,b);b=this.getEndPointY(l,h[h.length-1]);c.values.push({regressionLineParameters:l,x:k,
y:b});c.xData.push(k);c.yData.push(b)}return c}});g("linearRegressionSlope","linearRegression",{},{nameBase:"Linear Regression Slope Indicator",getEndPointY:function(f){return f.slope}});g("linearRegressionIntercept","linearRegression",{},{nameBase:"Linear Regression Intercept Indicator",getEndPointY:function(f){return f.intercept}});g("linearRegressionAngle","linearRegression",{tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span>{series.name}: <b>{point.y}\u00b0</b><br/>'}},{nameBase:"Linear Regression Angle Indicator",
slopeToAngle:function(f){return 180/Math.PI*Math.atan(f)},getEndPointY:function(f){return this.slopeToAngle(f.slope)}});""});t(k,"indicators/acceleration-bands.src.js",[k["parts/Globals.js"],k["parts/Utilities.js"],k["mixins/multipe-lines.js"]],function(g,f,k){var h=f.correctFloat,e=f.merge;f=f.seriesType;var d=g.seriesTypes.sma;f("abands","sma",{params:{period:20,factor:.001,index:3},lineWidth:1,topLine:{styles:{lineWidth:1}},bottomLine:{styles:{lineWidth:1}},dataGrouping:{approximation:"averages"}},
e(k,{pointArrayMap:["top","middle","bottom"],pointValKey:"middle",nameBase:"Acceleration Bands",nameComponents:["period","factor"],linesApiNames:["topLine","bottomLine"],getValues:function(c,a){var b=a.period,e=a.factor;a=a.index;var f=c.xData,g=(c=c.yData)?c.length:0,k=[],l=[],n=[],t=[],x=[],u;if(!(g<b)){for(u=0;u<=g;u++){if(u<g){var A=c[u][2];var y=c[u][1];var B=e;A=h(y-A)/(h(y+A)/2)*1E3*B;k.push(c[u][1]*h(1+2*A));l.push(c[u][2]*h(1-2*A))}if(u>=b){A=f.slice(u-b,u);var w=c.slice(u-b,u);B=d.prototype.getValues.call(this,
{xData:A,yData:k.slice(u-b,u)},{period:b});y=d.prototype.getValues.call(this,{xData:A,yData:l.slice(u-b,u)},{period:b});w=d.prototype.getValues.call(this,{xData:A,yData:w},{period:b,index:a});A=w.xData[0];B=B.yData[0];y=y.yData[0];w=w.yData[0];n.push([A,B,w,y]);t.push(A);x.push([B,w,y])}}return{values:n,xData:t,yData:x}}}}));""});t(k,"indicators/trendline.src.js",[k["parts/Utilities.js"]],function(g){var f=g.isArray;g=g.seriesType;g("trendline","sma",{params:{index:3}},{nameBase:"Trendline",nameComponents:!1,
getValues:function(g,h){var e=g.xData,d=g.yData;g=[];var c=[],a=[],b=0,k=0,l=0,q=0,p=e.length,m=h.index;for(h=0;h<p;h++){var n=e[h];var t=f(d[h])?d[h][m]:d[h];b+=n;k+=t;l+=n*t;q+=n*n}d=(p*l-b*k)/(p*q-b*b);isNaN(d)&&(d=0);b=(k-d*b)/p;for(h=0;h<p;h++)n=e[h],t=d*n+b,g[h]=[n,t],c[h]=n,a[h]=t;return{xData:c,yData:a,values:g}}});""});t(k,"masters/indicators/indicators-all.src.js",[],function(){})});
//# sourceMappingURL=indicators-all.js.map